### ISSUE TITLE
Improve Bitcoin Amount Units and Readability

### ISSUE THREAD

**Issue by praxeology-guy** [bitcoin/bitcoin#10243]
### Issue
Bitcoin uses a very large number of decimal places.  For anything less than 1 bitcoin, it is difficult for users to comprehend the amount they are looking at.  People are not good at thinking about numbers more than 2 decimal places smaller than a whole number.  Especially when commas or other group separators are not traditionally used for fraction digits.

### Proposed solution
A discussion on IRC #bitcoin about which units an exchange used triggered me into thinking... why not 
use a bitcoin format similar to what is used with Latitude and Longitude?

41°25'01.123"N and 120°58'57.456"W

### Comparison of current and suggested format
Instead of:
1.54321098 btc
Format as:
1.543m210u98s btc

The wonderful thing about this format is that you are always using units of "BTC", but at the same time you are also displaying units of mBTC, uBTC, and satoshis!

A small bitcoin amount like:
0.00001098 btc
Could instead  be formatted as:
10u98s btc

Cheers,
Praxeology Guy

**Comment by mariodian** [comment]
> People are not good at thinking about numbers more than 2 decimal places smaller than a whole number

Aren't people even worse when it comes to milli, micro, nano etc? Personally, when I look at the number **10u98s**, at first glance I have no idea what it represents because I've never seen it before. I may struggle with **0.00001098** too but at least I'm familiar with the concept of decimals.

If you want to display units of mBTC, uBTC and satoshi perhaps using a color representation makes a bit more sense:
![btc decimals](https://cloud.githubusercontent.com/assets/3636406/25263283/148e680e-2691-11e7-96ef-8f8654287f52.png)

This concept is similar to tones in Mandarin Chinese:

![chinese tones](https://i.stack.imgur.com/am6J0.png)

**Comment by lugrugzo** [comment]
Adapting geographic coordinate system would make things harder and weirder for all users. Also for readability, there are already mBTC and satoshi.

**Comment by laanwj** [comment]
This is more of a social issue and not a software issue. If a certain convention is widely used we'll happily add it to the software. I think sure developers of other wallets feel the same.

This isn't a good place to discuss it, though.
