### ISSUE TITLE
Man page is out of date

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#1040]
We have a manpage in ./contrib/debian/manpages/bitcoind.1 (surprise!), but it's very out of date.

**Comment by laanwj** [comment]
I still think the manpages should become a first-class part of the repository and also installed on 'make install', instead of inside the `contrib/debian/` 'ghetto'.

It is possible to generate part of it automatically from `--help` output.

Also it probably shouldn't aim to list all the RPC commands, as there are too many of them. Also as `bitcoind` doesn't work as a RPC client anymore in the first place...

**Comment by laanwj** [comment]
Closing this as #7274 bumped the man page.
