### ISSUE TITLE
Insufficient funds, but it's sufficient

### ISSUE THREAD

**Issue by kolesnevg** [bitcoin/bitcoin#10491]
Hi, sometimes i can not send coins from my wallet, it show error "code 6 Insufficient funds", but it's sufficient
how it's possible and what i can do

![dc65dd3d3b](https://cloud.githubusercontent.com/assets/1493518/26656370/6d644f66-4667-11e7-92ef-04642740523c.jpg)

if i will wait 30-60 minutes, i can send coins again, it's really strange, please help me

Thank you

**Comment by laanwj** [comment]
It is likely that the maximum mempool unconfirmed chain limit is exceeded at those time. At that point, no more transactions can be created (with those UTXOs) because the local mempool wouldn't accept them, let alone other nodes.

If you are creating long transaction chains it might be preferable to batch sends and send them at once with `sendmany`. This is more efficient in regard to block space as well.

**Comment by kolesnevg** [comment]
Thank you
