### ISSUE TITLE
run bitcoind without mining

### ISSUE THREAD

**Issue by muhammednagy** [bitcoin/bitcoin#10499]
is it possible to run bitcoind as a wallet only? i want to use it with bitcoin-cli 
it takes all the server specs

**Comment by MarcoFalke** [comment]
Which version of Bitcoin Core are you running? According to
https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.13.0.md#mining,
all versions after 0.13.0 have the internal miner removed. I.e. you should
not be able to call the RPC `getgenerate`

**Comment by jonasschnelli** [comment]
@muhammednagy: I guess you are looking to run without validation or with "simple verification / client mode". This is currently not possible.

Once you initially start Bitcoin-Core, it does download the complete blockchain ~100GB and verifies (almost) all transactions. This takes time... and can take up to serval days.

You can enable pruning (auto-cut off old blocks) with starting with `-prune=550` (or add `prune=550` to the `bitcoin.conf`). This will reduce the disk space to ~3-4GB (instead of 100GB+).

Running just the wallet is not possible.

**Comment by muhammednagy** [comment]
i'm running 0.14.1-xenial1

what I mean is that it downloads the full node and take most of my server
resources

**Comment by muhammednagy** [comment]
okay thanks, i will try this

**Comment by muhammednagy** [comment]
don't you intend to make client mode?
