### ISSUE TITLE
Upgrade depends/ build system to use Qt5.9

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#10505]
Qt5.9 has been [released](http://blog.qt.io/blog/2017/05/31/qt-5-9-released/).

Notable could be:

`
With Qt 5.9, we have had a strong focus on performance and stability. We’ve fixed a large number of bugs all across Qt[...]
`

`
Finally, we added support for compiling Qt in a size optimized mode (-Os on GCC), saving around 5-20% in binary size for the Qt libraries and your applications.
`

`
One major decision we have taken is to make Qt 5.9 another long-term supported (LTS) release. The previous LTS release, Qt 5.6, is starting to show it’s age, and many users have been asking for a more up to date version of Qt that they can use as a basis for long running projects.
`

**Comment by Benudek** [comment]
I see a potential root cause / solution path but not the error description - maybe I overlook it ?

**Comment by BlockMechanic** [comment]
This seems prudent , maybe not top priority but could be worth it. May be a while until 6.0 is released.

**Comment by thijstriemstra** [comment]
Opened #12316 to upgrade to 5.9.4. The 5.9.x release is an longterm support series, so 5.9 seems like the better choice over 5.10.x.

**Comment by TheCharlatan** [comment]
Ubuntu trusty does not ship a mingw version recent enough to be able to compile a Qt Version > 5.8 . So building with anything greater what is there currently will be problematic for both travis and gitian building. 
I have a 5.9.1 depends recipe and added a switch to the makefile and bitcoin_qt.m4 so I can choose between Qt versions (locally I use an up to date toolchain). It's not really useful though for bitcoin, since it adds no direct benefit or new feature set. I'd wait for this until theuni finishes his work on getting the entire toolchain on depends.

**Comment by MarcoFalke** [comment]
800dea88a6ad2d8b615c1cc486da5942f6e391c2
