### ISSUE TITLE
Bound memory usage when recovering from a crash during chainstate write

### ISSUE THREAD

**Issue by sdaftuar** [bitcoin/bitcoin#10693]
Now that #10148 is merged, it's possible to exceed configured memory limits for the utxo cache while recovering in `ReplayBlocks`.  We should fix this, perhaps by making the recovery itself use non-atomic writes:  https://github.com/bitcoin/bitcoin/pull/10148#issuecomment-310473040

**Comment by sipa** [comment]
So in general this problem is not solvable: LevelDB will use a large amount of memory when reading in a large number of changes that were just written before shutdown. In particular a flush with large -dbcache may result in a temporary spike at startup afterwards when LevelDB converts the log into a table.
