### ISSUE TITLE
Automated testing of mappings in RPC server registration and client arg conversion

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#10751]
#10747 fixed an issue where out client-side args type conversions got de-synced from our server-side named arguments -> arg position mappings. It would be super nice to have some kind of automated tester for that as I'm afraid simple typos will go entirely unnoticed.

**Comment by luke-jr** [comment]
I agree. But I wonder if it's possible to just use the main RPC arg list rather than having two mapping lists?

**Comment by TheBlueMatt** [comment]
I thought about that, might lead to having much too many deps for -cli, but we could maybe go the other way - have a separate table for name -> arg mappings and use that.

**Comment by laanwj** [comment]
I actually have a script for this, just need to hook it in.

> I agree. But I wonder if it's possible to just use the main RPC arg list rather than having two mapping lists?

The problem is indeed one of dependencies. There is no way the -cli can access the server implementation files (`rpc/misc.cpp` etc). which contain the dispatch tables.

An old idea is to remove all command-specific knowledge from the cli and instead request a JSON document from the server that describes the interface. This, in combination with smart caching to prevent extra roundtrips, could work.

**Comment by MarcoFalke** [comment]
@laanwj Fixed this. Thx!
