### ISSUE TITLE
bitcoin-qt core dumps when bitcoin(d/-qt) is already running

### ISSUE THREAD

**Issue by morcos** [bitcoin/bitcoin#10815]
On master at 7666250

It's expected to just exit cleanly with an error message that it can't obtain a lock on the data directory.
Instead it shows that error message and then when you click it away it core dumps.

This doesn't happen with bitcoind.  

This also results in losing RPC credentials to the running bitcoin(d/-qt)

**Comment by laanwj** [comment]
This problem happens because Shutdown() is called, even though the data directory was not locked.

Most easily reproducible in the GUI, though it's also possible to happen with `bitcoind` in a rare race condition (if the check in `AppInitSanityChecks` succeeds, but the lock can't actually be grabbed in `AppInitSanityChecks` and that exits with `false`, it will fall through and call `Shutdown`).
