### ISSUE TITLE
setAddress.clear() without a lock in CCryptoKeyStore::GetKeys and CBasicKeyStore::GetKeys

### ISSUE THREAD

**Issue by lyle-nel** [bitcoin/bitcoin#10905]
### Describe the issue
CCryptoKeyStore::GetKeys at line 173 of file src/wallet/crypter.h and
CBasicKeyStore::GetKeys at line 75 of file src/keystore.h call `setAddress.clear();` without a lock.
### What version of bitcoin-core are you using?
Master branch:0c173a15ca1bf20999f74987988985508c9de463

**Comment by benma** [comment]
If it needs to be locked, then at the callsite, not in the caller. 

However, it doesn't need to be locked. The only callsite is wallet.cpp:3664, where the variable is a local stack variable, so there is no thread-safety issue.

The `setAddress.clear();` line in that sense doesn't do anything meaningful either. We could think about returning the result (unique_ptr) instead of passing it by reference to avoid the `clear()` and also to make it more clear that locking isn't needed there.
