### ISSUE TITLE
Replace base58.h/cpp with base62x

### ISSUE THREAD

**Issue by wadelau** [bitcoin/bitcoin#11072]
Is it possible to replace token-generating method [base58](https://github.com/bitcoin/bitcoin/blob/master/src/base58.h) to [base62x](https://github.com/wadelau/Base62x) in the bitcoin repository?
As it stated in base58.h, 

>   Why base-58 instead of standard base-64 encoding?
>   - Don't want 0OIl characters that look the same in some fonts and
>      could be used to create visually identical looking data.
>  - A string with non-alphanumeric characters is not as easily accepted as input.
>  - E-mail usually won't line-break if there's no punctuation to break at.
>  - Double-clicking selects the whole string as one word if it's all alphanumeric.

[base62x](https://github.com/wadelau/Base62x) meets all of these reqirements and its has ***some shorter representation*** due to higher number base, i.e., 58 --> 64.

Except that there are 0OIl in the representation, however it is quite rare for users of bitcoin to write or read those token by human, instead all of tokens input and output by machine, i.e., copy and paste in most of cases and environments.

And one more plus for [base62x](https://github.com/wadelau/Base62x), it might ***calculate faster*** than base58 because its bitwise operations over that of base58 with arithmetic methods.

What others should be put under consideration for this switch?

**Comment by sipa** [comment]
Bitcoin uses base58 for the existing address format, and due to backward compatibility, we'll probably be required to support it forever. You can't suddenly stop supporting addresses created by other software.

Discussions about address formats belong on the bitcoin-dev mailinglist, as they affect multiple implementations.

I'm obviously biased as designer of Bech32, but I think that making addresses even harder to read/write is the wrong direction to go.

For SegWit addresses, it seems like that BIP173 (disclaimer: i'm the author) will be adopted.
