### ISSUE TITLE
getrawmempool verbose mode should return "size" and "disksize" for segwit transactions

### ISSUE THREAD

**Issue by junderw** [bitcoin/bitcoin#11218]
### Describe the issue

getrawmempool verbose mode only returns "size" rather than "size" and "disksize" (the size on disk for segwit transactions)

#### If so, please list the steps to reproduce below:
1. Run getrawmempool with verbose set to true
2. Notice it only gives size

### Expected behaviour
It should show:
1. effective feerate "size" (ceil(weight/4))
2. disk size "disksize" (total number of bytes in the serialized segwit transaction. (since "disksize" and "size" will be equal for non-segwit transactions, "disksize" should only appear for segwit transactions)

### Actual behaviour
It shows size only (effective size for fees ceil(weight/4))

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
0.14.2

**Comment by sipa** [comment]
The only thing that counts towards the block limit (and by extension, what matters for feerate) is vsize.

**Comment by junderw** [comment]
I guess I'll take that as an "out of scope" response.
The mempool only cares about vsize, so "size" is always vsize... makes sense.

However, this is a "verbose" mode which imo should "give as much information as possible so the user/coder can decide what's useful and what's not"...

In regards to segwit transactions, the only missing info regarding the possible effect on the blockchain (for sites looking to record or watch these statistics) is how much disk space it will take up.

Thinking it through. You would only really need 2 of the 3, and the other one can be calculated.

Perhaps segwit transactions can have an extra key which is "disksize"... since non-segwit disksize == size, it can be removed.

**Comment by sdaftuar** [comment]
I'm skeptical of `disksize` being a useful quantity, because that is implementation specific and not protocol-enforced; for instance if we implemented compression to store the transaction on disk, would we then return a smaller value for `disksize`?

Perhaps you mean "serialized size", which is well-defined because the serialization is part of the protocol, but we don't cache this in the mempool because we don't need it for anything.  I'd prefer not to cache this in the mempool to avoid wasting memory, and I'm not sure it's worth reserializing the mempool contents to calculate this value whenever a user calls getrawmempool, because that rpc is already slow enough, and I don't know what the use case here would be...  Note that users can always calculate the serialized size themselves by asking for the serialized transaction directly, eg with getrawtransaction.

**Comment by sipa** [comment]
Perhaps we should however rename the "size" field to "vsize" there, for consistency?

**Comment by FelixWeis** [comment]
+1 renaming it vsize

maybe +/-0.5 splitting it to `weigth` and adding `disksize`

**Comment by jnewbery** [comment]
Agree that we should rename `size` -> `vsize`.

There's a PR to expose transaction weight in `getrawtransaction` here: #12791. Perhaps we could do the same for `getrawmempool`

No need for disksize IMO.

Suggest tagging this as 'good first issue'

**Comment by hebasto** [comment]
Is this still an issue?

**Comment by junderw** [comment]
No. It's fine.
