### ISSUE TITLE
add* RPCs require backups

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#11243]
At a minimum, help text should note this. This is true for things like addwitnessaddress especially.

**Comment by TheBlueMatt** [comment]
This needs an 0.15.1 tag.

**Comment by sipa** [comment]
Also, importprivkey, importmulti, importaddress, importpubkey, addmultisigaddress, ... and perhaps more

**Comment by laanwj** [comment]
Also the watch-only ones?

**Comment by sipa** [comment]
> Also the watch-only ones?

Yes, I've included those in the list above.

**Comment by MarcoFalke** [comment]
From #11294:
The `dumpwallet` command currently writes out all keys, including the hd seed. In case there are keys in the wallet that are not derivable from that seed, a warning should be included to explain that that seed on itself is not enough to backup the wallet.

**Comment by PavelNiedoba** [comment]
From business perspective it's very important to have possibility to backup wallet using string, which can be stored on paper or hardware password manager. Files are much harder to handle safely. Think about people running business, storing tens of millions in this wallet.

**Comment by sipa** [comment]
@PavelNiedoba Yes, of course. But by definition, importing something in the wallet will always require a backup. That's why it's important to make this clear.

**Comment by JohnVonNeumann** [comment]
Excuse the noob question here, I saw this had the good first issue tag applied to it so just looking to get further clarification. This issue is in regards to help output surrounding the following RPC's:

- addwitnessaddress
- importprivkey
- importmulti 
- importaddress 
- importpubkey 
- addmultisigaddress

The basic premise of the issue to add extra help output for users to indicate that before performing any of these actions, they should be performing a backup of the item they intend to use as input? IE: non-segwit address, multikey wallets, addresses, etc

Let me know if I'm not on the right path here.

**Comment by MarcoFalke** [comment]
> EDIT: Apologies, I didn't see that MeshCollider had already written a fix via #11289.

@JohnVonNeumann You can still help by reviewing :)

**Comment by JohnVonNeumann** [comment]
I kinda assumed my review would be pointless being a noob? Wouldn't it require more experienced people to pass it? @MarcoFalke

**Comment by MarcoFalke** [comment]
Obviously, if you just run around and spam "ACK" or "Concept ACK", it will be ignored. However, if you go around and find issues with the code or can figure out a solution that is cleaner, it will be greatly appreciated.

**Comment by JohnVonNeumann** [comment]
That makes sense then, awesome, I left a small comment on something. Cheers for the advice!
