### ISSUE TITLE
multiwallet `validateaddress` tells me `ismine: false` without -rpcwallet arg

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#11324]
In `master` branch, 96ac26e56627f0c24213fcd3a1cce9fc95f1f661:

I have two wallets loaded. I have the same privkey in both of them, but when I check using `validateaddress` it tells me `"ismine": false,`:

    $ bitcoin-cli validateaddress $addr | grep ismine
      "ismine": false,
    $ bitcoin-cli -rpcwallet=wallet.dat validateaddress $addr | grep ismine
      "ismine": true,

Perhaps we shouldn't include `ismine` and `iswatchonly` in the output if we don't know which wallet we're talking about.

**Comment by achow101** [comment]
`validateaddress` requests which wallet to use, but with multiple wallets, when a wallet is not specified, a nullptr is returned. This then results in `validateaddress` return ISMINE_NO because it does not have a wallet to use. This may actually be an issue with some other RPC calls that are not dedicated wallet RPCs (e.g. signrawtransaction).

**Comment by promag** [comment]
@dooglus FYI https://github.com/bitcoin/bitcoin/pull/10849#issuecomment-315842820.

**Comment by jarolrod** [comment]
@fanquake can this be closed? [#10583](https://github.com/bitcoin/bitcoin/pull/10583) addresses this and was merged.
