### ISSUE TITLE
How does bitcoin core plan to survive the exodus of miners?

### ISSUE THREAD

**Issue by billkle1n** [bitcoin/bitcoin#11416]
As we all know, Bitcoin's security is predicated on no single miner possessing more than 51% of the hash rate. If Segwit2x is successful, this condition will stop being true. Is there any contingency plan for Bitcoin to survive this? Could Bitcoin switch to a merged mined algorithm where the S2X miners merge mine it (I think many of them would agree to since it wouldn't cost them anything and is not explicitly against the NYA)? Just a proposal.

**Comment by majorlegendx** [comment]
Sounds like if Segwit2x is successful, Greg will propose a change of POW:
https://coinjournal.net/greg-maxwell-prospects-segwit2x-bitcoin-developers-may-leave-project-succeeds/

Merging would be an interesting proposition, but unlikely to happen due to the current bitter divide over the issue. At this point October feels like the calm before the storm.
