### ISSUE TITLE
Windows build instructions do not create .exe files

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#11633]
Following the instructions in the latest master and V0.15.0.1 seem to work (with the PATH fix for v.0.15.0.1) but the resulting binaries are not .exe files - even after running make install.

When running the file from the command prompt, they core dump, and also give the error:-
QXcbConnection: Could not connect to display

Running "file" on the binaries displays:-
bitcoin-qt: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=15f46d424faaf60811625c0406df1a8b9c214b11, not stripped

I am following the instructions to the latter, as far as I can tell, but it may be that additional packages have been installed prior to following the build instructions. If this is the cause of the issue, perhaps the instructions could be amended to include instructions to cater for the possibility of additional packages existing (installed), e.g. Qt libraries.

**Comment by sipsorcery** [comment]
It does look like you've ended up doing a build targeting Linux rather than Windows. 

On my system after a successful Windows build:

> /usr/src/bitcoin$ file ./src/qt/bitcoin-qt.exe
./src/qt/bitcoin-qt.exe: PE32+ executable (GUI) x86-64, for MS Windows

What do you get if you run the command below?

> /usr/src/bitcoin$ make -p -f /dev/null | grep MAKE_HOST
make: *** No targets.  Stop.
MAKE_HOST := x86_64-pc-linux-gnu

And this is what you should see after configure:

`/usr/src/bitcoin$ CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/`

> Options used to compile and link:
  with wallet   = yes
  with gui / qt = yes
    qt version  = 5
    with qr     = yes
  with zmq      = yes
  with test     = yes
  with bench    = yes
  with upnp     = yes
  use asm       = yes
  debug enabled = no
  werror        = no
  target os     = windows
  build os      =
  CC            = /usr/src/bitcoin/depends/x86_64-w64-mingw32/share/../native/bin/ccache x86_64-w64-mingw32-gcc
  CFLAGS        = -pipe -O2
  CPPFLAGS      = -I/usr/src/bitcoin/depends/x86_64-w64-mingw32/share/../include/  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -D_MT -DWIN32 -D_WINDOWS -DBOOST_THREAD_USE_LIB -D_FILE_OFFSET_BITS=64
  CXX           = /usr/src/bitcoin/depends/x86_64-w64-mingw32/share/../native/bin/ccache x86_64-w64-mingw32-g++ -std=c++11
  CXXFLAGS      = -pipe -O2
  LDFLAGS       = -L/usr/src/bitcoin/depends/x86_64-w64-mingw32/share/../lib
  ARFLAGS       = cr

**Comment by rebroad** [comment]
Fixed by #11438. closing
