### ISSUE TITLE
config.status --recheck does not reuse previously configured environment

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#11657]
This is an issue for anyone currently developing on windows. i.e. when making (e.g. after a git checkout), make will reconfigure but for the linux environment, rather than the windows environment (even if this was what has only been done so far).

A fix would be to store the configuration of the relevant variables that influence the ./configure so that these are re-used each time.

**Comment by laanwj** [comment]
This is due to CONFIG_SITE:
```
CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
```
An alternative way to provide the config.site that is remembered would be welcome, not sure this exists at all.
(FWIW you can also do `./configure --prefix=$PWD/depends/x86_64-w64-mingw32`, I think that survives reconfigured, however then you can't usefully install the result with `make install`)

**Comment by rebroad** [comment]
How about adding to the build document an instruction to add CONFIG_SITE as an environment variable to the .bashrc file?

**Comment by laanwj** [comment]
Could do that, though I'd personally be wary of adding bitcoin build specific arguments to my `.bashrc` file. It might also cause conflicts: `CONFIG_SITE` is used by all programs that are configured using autotools.
