### ISSUE TITLE
Extreme slow sync speed MacBook Pro 2.7GHZ

### ISSUE THREAD

**Issue by borriej** [bitcoin/bitcoin#11725]
Hi,

- I'm on a MacBook Pro Retina 2.7Ghz I7, 8GB RAM.
- High Sierra OSX 10.13.1
- Internet speed is 84 Mbits..  so I download 10-11MB/s. 
- Downloaded Bitcoin Core (latest stable from the website) 0.15.1,
- Im on a mac, so limited HDD.. so I've set-up blockchain on external USB 3.0 2TB external disk with speeds up to 120 MB/s
- I expected Bitcoin Core to download + sync within 24 hours
- But it's taking ages, as in: Im just over 50% within 48 hours.. progress per hour is 0.10% 

- EDIT: another interesting fact.. CPU usage of Bitcoin-Qt was around 3-6%.. memory aroundd 200-400MB.

1) Im on a fast computer, with great internet.. so what is causing this?
2) How do you launch with other config settings to test? like dbcache=4000?
3) What should I do?
4) Is this a software thing?

**Comment by borriej** [comment]
And second problem, just now.. it hangs on start-up. I closed it an hour ago, it crashed. I opened it again, it says: 'checking block..4%... 100% etc.'... 'done loading' and then nothing: it freezes at the splash saying it ready loading. But I get the Mac infinite spinner.

**Comment by jonasschnelli** [comment]
Bitcoin Core and its database layer (leveldb) work best on internal disks. External hard dives cause often problems (data corruption, etc.).

I recommend you to use **pruning** (same security, complete full node, but you don't send old blocks to other peers).

The low CPU usage could be caused by disk write bottleneck.

You should definitively enable `-dbcache=4000`.
Either you create a `bitcoin.conf` file in `/Library/Application Support/Bitcoin/` and write into a text file `dbcache=4000` or you open the Bitcoin GUI settings and change the value there.

Pruning can't be set via the GUI settings.
So write `prune=550` into the `bitcoin.conf` file on a extra line.

Because you have changed your data directory to your external hard drive. You may want to "reset the settings" (via GUI setting) first.

Optionally you can also enable `debug=bench` (add this to your `bitcoin.conf`) to get more benchmark info. You can see them then in the file `debug.log`

**Comment by TheBlueMatt** [comment]
@jonasschnelli I believe the GUI settings dialog also allows you to modify the dbcache DB memory limit setting, no? Same with pruning? If it really is stuck (and not just stuck waiting for 30 minutes on I/O latency), share the debug.log.

**Comment by jonasschnelli** [comment]
@TheBlueMatt: Pruning can't be enabled/configured via the GUI. DBCache: yes, as I wrote.

**Comment by borriej** [comment]
Adding those 3 lines to my config file didn't speed up things..

prune=550
dbcache=5000
debug=bench

Im trying again now form my SSD.

Any other tips?

Is it usual to only see 1 active bitcoin connection to the network?

**Comment by TheBlueMatt** [comment]
Even with pruning the I/O latency of an external disk sync can make IBD painfully slow. I'm not sure that we couldn't avoid some fsync calls in block writing which may make things very significantly better.
