### ISSUE TITLE
bitcoin core as downloaded contains viruses

### ISSUE THREAD

**Issue by tomjan35** [bitcoin/bitcoin#11852]
Is this loading the system with viruses intentional or just a security laps that will be rectified?
![image](https://user-images.githubusercontent.com/34372922/33766661-405f434c-dc6a-11e7-81bf-fa8b677d547b.png)

**Comment by TheBlueMatt** [comment]
It even says in the screenshot "not-a-virus". It looks like the AV tool you're using considers it important to notify you that you've downloaded Bitcoin.

**Comment by RHavar** [comment]
I think it's warning you that it detected a possible bitcoin miner. This is probably because some software surreptitiously ships with cryptocoin miners which waste a persons computer resources without them being aware.

But anyway, that isn't the case with bitcoin itself. So you probably should report this to AV software as a false positive.
