### ISSUE TITLE
Multi-wallet RPC URI parsing invalid when ending with a slash

### ISSUE THREAD

**Issue by jackycjh** [bitcoin/bitcoin#11861]
Using the newer RPC access point for multi-wallet support as described https://bitcoincore.org/en/releases/0.15.0/#multi-wallet-support will __not__ work if the URI ends with a slash ( `/` ).
In other words, all RPCs for multi-wallet would only work if the URI does not end with a slash.

Expected behavior:
Any RPC command (or by using _curl_ ) __should work__ for URI like `http://username:password@127.0.0.1:8332/wallet/wallet.dat/` regardless of the ending slash.

Actual behavior:
An error will be return `{"result":null,"error":{"code":-18,"message":"Requested wallet does not exist or is not loaded"},"id":"curltext"}` even when the wallet name is valid.
- `http://username:password@127.0.0.1:8332/wallet/wallet.dat` will work.

Reproduction steps:
1. Run `curl --data-binary '{"jsonrpc":"1.1","id":"curltext","method":"listreceivedbyaddress","params":[]}' -H 'content-type:text/plain;' http://username:password@127.0.0.1:8332/wallet/wallet.dat/`

Found in Version: 0.15.1
OS: Windows 10 Pro with Ubuntu WSL _(if this info matters)_

**Comment by ryanofsky** [comment]
Current behaviour seems right to me. It seems better to treat slashes as significant, because silently ignoring slashes could break external code that constructs absolute URI's by joining relative URIs.

More generally, this is supposed to be a programmatic RPC interface, not a human interface, so it makes sense for it to be strict about not accepting invalid input. Though even some regular websites do treat trailing slashes as significant:

Valid: https://en.wikipedia.org/wiki/Zebra
Not found: https://en.wikipedia.org/wiki/Zebra/

Valid: https://www.nytimes.com/2017/12/11/world/middleeast/saudi-arabia-movie-theaters.html
Not found: https://www.nytimes.com/2017/12/11/world/middleeast/saudi-arabia-movie-theaters.html/

**Comment by jonasschnelli** [comment]
Agree with @ryanofsky

**Comment by promag** [comment]
+1 @ryanofsky. BTW see https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html?m=1.

**Comment by jackycjh** [comment]
I see, I guess I was confused by the documentation on bitcoincore.org, perhaps I should create an issue in https://github.com/bitcoin-core/bitcoincore.org to correct its documentation instead.
