### ISSUE TITLE
Add '--enable-mainnet' configure and bitcoind option

### ISSUE THREAD

**Issue by maaku** [bitcoin/bitcoin#11901]
Feature request: add a configuration option '--enable-mainnet' which defaults to false but is set to true by the gitian builds. When true, behavior is unaffected. When false (the default for someone cloning the repo and building with no configuration options), the resulting binary will require a new 'enablemainnet' option to be set in order to launch the daemon or Qt GUI with main net chain params.

This prevents developers or downstream system integrators from accidentally corrupting main net wallets or block chain data when developing new features. It has happened to me multiple times in the past that I've corrupted wallets while implementing and debugging new wallet features. Of course these were either testnet wallets, or I was careful to backup the wallet first. But we should strive to create a development environment without single-point failure potential to prevent fat-finger mistakes if nothing else.

**Comment by luke-jr** [comment]
Concept ACK. This also avoids (to an extent) the common mistake of end users running master. (We can maybe enable by default for stable branches)

**Comment by jeffrade** [comment]
I started working on this issue, but want to make sure I understand what is requested before submitting a PR:

 - Add `--enable-mainnet` option flag when running `./configure`
 - If above flag is present, define `ENABLE_MAINNET` for pre-processor in `src/chainparamsbase.cpp`.
 - `ChainNameFromCommandLine()` in `src/chainparamsbase.cpp` will now set new boolean `fMainNet` where it will look for `-enablemainnet` arg to run `mainnet` chain (but default to `true` if `ENABLE_MAINNET`).
 - If `ENABLE_MAINNET` config is not set and `-enablemainnet` flag is not passed to binary, `bitcoind` will run on `testnet` chain.
 - (TODO) Update any help docs/output/markup since `mainnet` was defaulted and had to explicitly set `-regtest` or `-testnet`.

[Here is a quick implementation](https://github.com/jeffrade/bitcoin/commit/3e86a97c4d41b30babb25f0c0ca48f14ae095e34) in my branch.  Am I on the right track (C++ noob here)?

**Comment by luke-jr** [comment]
I think you understood it backward. If the configure option is used, mainnet should be the default. Only if configured with `--disable-mainnet` (default) should a command-line option be required at runtime.

**Comment by jeffrade** [comment]
Thanks @luke-jr, will get a PR open for this soon.

**Comment by MarcoFalke** [comment]
There is a pull request for this feature. Please review/comment there

**Comment by MarcoFalke** [comment]
Note: The pull request was closed with the rationale "There is no agreement to do this"
