### ISSUE TITLE
OSX Uninstaller (which can also delete blockchain data)

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#11959]
Sister ticket for #993 Windows.

For reasons I can't wrap my around there's doesn't seem to be a way for OSX applications to clean up after themselves after a user drags them into the trash can.

One workaround could be for QT to check if `~/Application Support/Bitcoin` already exists. If not, it would store the blockchain and other non-wallet data _in the application package itself_ and put a symlink in `~/Application Support/Bitcoin` so Bitcoind can find it. This might be quite brittle though.

Another approach is to put an uninstall button inside QT, somewhere in the settings. This would work for Linux as well. In Windows it would just launch the standalone uninstaller. The uninstall button would have a check box:

"Do you want to delete the blockchain data? [x GB]", checked by default

In addition it would say: "your wallet will remain in [PATH]" and will be used again if you decide to reinstall in the future.

**Comment by jonasschnelli** [comment]
>  [...] in the application package itself [...] 

I wouldn't do that. Applications are stored in the non-user space while the library is in the user space.

> Another approach is to put an uninstall button inside QT, somewhere in the settings. This would work for Linux as well. In Windows it would just launch the standalone uninstaller. The uninstall button would have a check box.

Hmm.. pretty uncommon for macOS applications.

IIRC, OSX does now auto-detect related data files when you delete an application. Someone should look up the apple developer docs what recommendation are made there.

**Comment by Varunram** [comment]
I think the common Mac app practice is to leave the files in `Application Support /` as is, even when the user drags them into the trash can. This is because in case the user decides to put it back in (if they deleted by mistake) , stuff works "as expected". The uninstall button sounds like a nice option, and users can choose to keep the chain in case they decide to install again.

**Comment by jarolrod** [comment]
I think the OSX philosophy is to leave files as is so that if a user ever wants to reinstall, these important files are there again. In terms of Bitcoin Core as a GUI app, I'd rather not include such an option in settings; to prevent foot gunning, you leave your laptop open and someone quickly deletes your blockchain data pranks :).

I think this issue can be closed.

**Comment by joshuadbryant1985** [comment]
If someone steals off me I'm going to kick their ass
