### ISSUE TITLE
rewinding blocks dialogue stays with no progress indicator or further information after hours

### ISSUE THREAD

**Issue by woeisme** [bitcoin/bitcoin#12030]
Bitcoin-qt is stuck at rewinding blocks gui

progress after a few hours (ran overnight)
No relevant info in debug.log except that progress number seems to be increasing vs decreasing

never fully loaded gui or stopped rewinding blocks dialogue

start bitcoin-qt either from cli or ubuntu dialogue

15.0.1 
ubuntu launchpad ppa from matt corallo

acer ao722 AMD C-60 with 2Gb ram

**Comment by TheBlueMatt** [comment]
If you're on a slow spinning disk on a system with memory pressure (eg 2GB ram with a web browser or other stuff running) rewinding blocks can be incredibly slow, check memory/swap usage as well as iotop to see what else is eating I/O cycles, or, since your CPU is a bit on the slow side, check top to see if its a CPU bottleneck.
