### ISSUE TITLE
importprivkey not working with bech32 address private key generated from electrum

### ISSUE THREAD

**Issue by vachichuong** [bitcoin/bitcoin#12111]
Hi, I get error code -5 when trying to importprivkey with a private key from a bech32 address generated with electrum.
Any idea how to solve it?

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests for third party software are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

**Comment by Sjors** [comment]
This issue is pretty high in the Google rankings. There seems to be some confusion around the private key format used by Electrum. I don't think the private key itself is in bech32 format, but rather they changed the WIF format to specificy whether the private key should be converted to a legacy (1...) address or a bc1... address. See also https://github.com/spesmilo/electrum/issues/3620

**Comment by MarcoFalke** [comment]
See also https://github.com/spesmilo/electrum/issues/3667
