### ISSUE TITLE
RPC: savemempool: Don't write mempool.dat while not having the previous one in memory

### ISSUE THREAD

**Issue by jtimon** [bitcoin/bitcoin#12142]
Currently it is possible to stupidly lose mempool data by calling the rpc "savemempool" before the previous stored mempool has been read and processed to the memory mempool.

I haven't looked at the code yet, but at minimum one ugly solution would be to have a global g_is_mempool_read_finished (or something of the short) that starts false and gets sets to true once the reading is reading processing of mempool.dat is successfully finished. The rpc savemempool checks this global on the start and returns a an error while it remains false.

**Comment by sipa** [comment]
Good point, seems easy to fix.

**Comment by jtimon** [comment]
Created https://github.com/bitcoin/bitcoin/pull/12172

**Comment by Willtech** [comment]
Having a global g_is_mempool_read_finished (or something of the short) may be one ugly solution but, it is also useful for other purposes.

I haven't looked at your fix but presume that also the mempool is not again saved if exiting before the mempool is finished loading when persistmempool is true. Is that the expected behaviour?
