### ISSUE TITLE
Translate text to all languages

### ISSUE THREAD

**Issue by DATSEC** [bitcoin/bitcoin#12234]
Warning: Fee estimation is currently not possible.
https://github.com/bitcoin/bitcoin/blob/master/src/qt/forms/sendcoinsdialog.ui#L774

**Comment by MarcoFalke** [comment]
Awesome. Thanks for helping with translations!

Changes to translations as well as new translations can be submitted to
[Bitcoin Core's Transifex page](https://www.transifex.com/projects/p/bitcoin/).

Translations are periodically pulled from Transifex and merged into the git repository. See the
[translation process](https://github.com/bitcoin/bitcoin/blob/master/doc/translation_process.md) for details on how this works.

**Important**: We do not accept translation changes as GitHub pull requests because the next
pull from Transifex would automatically overwrite them again.
