### ISSUE TITLE
Bitcoin segwit address accepts litecoin segwit transaction

### ISSUE THREAD

**Issue by coinsmith** [bitcoin/bitcoin#12301]
Describe the issue

As a test, I withdrew litecoin to a Bitcoin core generated segwit address. I used a Yobit wallet for this test. The withdrawal went through and now sits in a litecoin address I have no private key of

What behavior did you expect?

I would expect the transaction to bounce, since it's generated from a Bitcoin address

What was the actual behavior?

The transferred litecoin now sits in what originally was a Bitcoin address

**Comment by WalterBoles** [comment]
What account did you pull from and when

**Comment by laanwj** [comment]
This is a problem with the sending wallet, it should check the address prefix against the litecoin one. Bitcoin core cannot "bounce" altcoin transactions as it has no access to that chain.

**Comment by coinsmith** [comment]
WalterBoles, I bought some litecoin on the exchange and withdrew it to a Bitcoin core segwit address. On chain.so, I can see the amount sitting in the same litecoin segwit address as the address I generated on the Bitcoin core wallet.

**Comment by MarcoFalke** [comment]
I assume you are using P2SH, in which case you should report the issue to the litecoin wallet developers and the exchange (i.e. sending wallet) that sent the coins to you.

Apparently they use the same "chain identifier" (i.e. version) for base58 p2sh addresses. See [ltc](https://github.com/litecoin-project/litecoin/blob/94adaf8468fad3607f0639b55e7b3cbd0758fd53/src/chainparams.cpp#L134) and [btc](https://github.com/bitcoin/bitcoin/blob/3448907a68e0f719be3bf82f4d321a30975d3539/src/chainparams.cpp#L140)

Litecoin wallets should not generate nor accept such addresses. The issue is clearly with their software.

**Comment by coinsmith** [comment]
Thanks for clarifying!
