### ISSUE TITLE
Implement bip69 (Lexicographical Indexing of Transaction Inputs and Outputs)

### ISSUE THREAD

**Issue by RHavar** [bitcoin/bitcoin#12457]
[BIP69](https://github.com/bitcoin/bips/blob/master/bip-0069.mediawiki) is a pretty under appreciated bip that defines a standard ordering for transactions inputs / outputs.

There's quite a few obvious advantages to the approach, like making it easy to verify correctness, or making it easier to write unit tests. But I think the most important aspect is it helps users verify their wallet isn't maliciously leaking information. Granted a malicious wallet could try leak information via the nonces, deterministic signing helps make that detectible with access to the private keys.

As some wallets have already moved to bip69 (and unlikely to consider moving back) it would be very beneficial if core moves in the same direction resulting in better transaction uniformity for everyone.

(And a bounty for fun: if this is merged in the next 3 months I'll offer 0.03 BTC to the author :D)

**Comment by jl2012** [comment]
@fanquake I think BIP69 is merely an informational BIP, not consensus. Making such kind of thing consensus will invalidate pre-signed txs and limit flexibility for future upgrade

**Comment by Sjors** [comment]
@jl2012 I don't think @RHavar is proposing to make this a consensus rule, merely to use this when creating transactions.

The standard is currently used by several wallets, e.g. blockchain.info, Electrum and probably everything that uses BitcoinJS, so it would help blending in.

According to the BIP `std::lexicographical_compare` should do the trick.

Do we know of any downside?

**Comment by Sjors** [comment]
@luke-jr pointed out elsewhere that there might be an issue with `SIGHASH_SINGLE`. From the BIP:

> While out of scope of this BIP, protocols that do require a specified order of inputs/outputs (e.g. due to use of SIGHASH_SINGLE) should consider the goals of this BIP and how best to adapt them to the specific needs of those protocols.

> the most important aspect is it helps users verify their wallet isn't maliciously leaking information

Compromised wallets can do all sorts of damage. I think a more important aspect is blending in with other wallets.

**Comment by RHavar** [comment]
> Compromised wallets can do all sorts of damage. I think a more important aspect is blending in with other wallets.

Well, not that it really matters what is more important but they go a bit hand-in-hand. Like in the context of how I use bitcoin core, I don't really care -- but there other wallets where bip69 is important to me (with my trezor) and I wouldn't want to give it up. But the best of both worlds is that every wallet uses bip69 for maximal transaction conformity (hence this issue)

**Comment by nopara73** [comment]
As long as most wallets don't comply with BIP69, (which will be the case for like forever,) input and output shuffling results in superior privacy.  

Of course testing it requires a bit more effort, but should you make your software worse so to save 10 lines of testing code?

**Comment by RHavar** [comment]
> As long as most wallets don't comply with BIP69, (which will be the case for like forever,) input and output shuffling results in superior privacy.

I'm not sure I can agree. I hope we can agree on two basic ideas:
* The status-quo is harmful -- it allowing for (messy) clustering of transaction origins
* Certain wallets require the determinism that bip69 offers, while for other wallets it doesn't matter

Which I think leads to the logical conclusion that moving to (something like) bip69 is the smart thing -- even for wallets (perhaps like core) that don't really care too much about it. 

If you are worried that core switching to bip69 could reduce privacy (which I don't think is a big concern, as several big wallets already are using bip69), there is an easy solution: it can slowly be phased in (e.g. seed a random number generator with the hash of the first priv key, then with a X% chance use bip69 or shuffle with inputs/outputs with the rng).

> Of course testing it requires a bit more effort, but should you make your software worse so to save 10 lines of testing code?

Testing improvements really is one of the smallest benefits of bip69, but you are really underselling it. For a wallet that uses bip69, if a transaction is ever created that doesn't conform -- then it's immediately obvious. You don't nearly have the same benefit with shuffled inputs/outputs -- where it would be very easy to have a wallet or code path that doesn't shuffle without anyone realizing.

**Comment by nopara73** [comment]
I assume if you take a look at the blockchain how many transactions are BIP69 compliant today you will find it's less than 5%. I think our differences come from that you assume otherwise.

If my assumption is correct, with BIP69, if blockchain analysis looks at a transaction it would know if the transaction can be from Core or not. If it's shuffled then it would not have that information.

I think this change requires some statistics: **"What percentage of blockchain transactions are BIP69 compliant today?"**  
And if the answer is "tiny", then BIP69 integration is just flagging the transaction as a Bitcoin Core transaction to make the job of Blockchain analysis easier.

**Comment by achow101** [comment]
> I think this change requires some statistics: "What percentage of blockchain transactions are BIP69 compliant today?"

According to https://p2sh.info/dashboard/db/bip-69-stats?orgId=1, approximately 55% of transactions comply with BIP69.

**Comment by nopara73** [comment]
> According to https://p2sh.info/dashboard/db/bip-69-stats?orgId=1, approximately 55% of transactions comply with BIP69.  

It was approximately 40% until 2015, so the creation of the BIP may resulted in 15% additional BIP compliance. A more accurate estimate would be `15*0.4 + 15 =` **21% of the network is actively BIP69 compliant today.**

**Comment by nopara73** [comment]
@RHavar That would only make sense if the Bitcoin Core would be close sourced.

**Comment by RHavar** [comment]
> @RHavar That would only make sense if the Bitcoin Core would be close sourced.

???

**Comment by nopara73** [comment]
@RHavar I misunderstood what you said:

> But if you generate a transaction that isn't bip69 compliant, then you know for sure they're using a non-bip69 wallet.

So your threat model is: a blockchain observer wants to know if a transaction was done with a BIP69 compliant wallet or not.  

My threat model was: a blockchain observer wants to know if a transaction was done with a specific wallet or not.  

The first threat model asks the wrong question, because blockchain analysis doesn't care if a wallet BIP69 compliant or not.

But we could even take a step back and consider all possible 2 output clustering combinations: you've done a transaction with your wallet and blockchain analysis wants to know which was your change.  

![](https://i.imgur.com/iTKXHWy.png)  

# A

|                      | BIP69    | Shuffling |
|----------------------|----------|-----------|
| Which is the change? | dontknow | dontknow  |

# B

|                      | BIP69    | Shuffling |
|----------------------|----------|-----------|
| Which is the change? | 1. | dontknow  |

# C

|                      | BIP69    | Shuffling |
|----------------------|----------|-----------|
| Which is the change? | canthappen | dontknow  |

# D

|                      | BIP69    | Shuffling |
|----------------------|----------|-----------|
| Which is the change? | canthappen | dontknow  |

# E

|                      | BIP69    | Shuffling |
|----------------------|----------|-----------|
| Which is the change? | canthappen | dontknow  |

# F

|                      | BIP69    | Shuffling |
|----------------------|----------|-----------|
| Which is the change? | canthappen | dontknow  |

# Question asked during clustering

Which one was the change?  

Blockchain observer deducted the answer to the question by examining if a specific transaction was done with a specific wallet or not, ergo applying the second threat model directly to every single transaction.  

Can you come up with a scenario where blockchain analysis is interested if the wallet is BIP69 or not?

**Comment by nopara73** [comment]
> @RHavar That would only make sense if the Bitcoin Core would be close sourced.
> > ???

If a wallet is closed sourced and BIP69 compliant, but blockchain analysis doesn't know that, then it could generate BIP69 compliant txs all day long, blockchain analysis would not be able to rule out on a non-BIP69 transaction that it wasn't done by the wallet.  

At least originally I thought that's what you meant.

**Comment by RHavar** [comment]
Your analysis of scenario B isn't correct,  it's not generally clear if the bip69 use is accidental or on purpose -- so it's not correct to assume output 1 is change.

And actually the exact same thing in reverse is happening scenario `D` which in practice is going to lead to more information leak.

---

But I really think you're overthinking it. The solution here is to get as many wallets and transactions using bip69 as possible, and suddenly there's no difference and everyone wins.

**Comment by nopara73** [comment]
> Your analysis of scenario B isn't correct, it's not generally clear if the bip69 use is accidental or on purpose  

Of course the assumption was Blockchain analysis knows the wallet the first transaction was taken with. That's  often the case, since there are a bunch of wallet identifier metadata left behind: 1. what fees are added, 2. rbf usage patterns, 3. types of scripts used, etc...

> but actually the exact same thing in reverse is happening scenario D which in practice is going to lead to more information leak.

???

> But I really think you're overthinking it.

A deterministic algorithm, until everyone uses it will leak more information than a nondeterministic one. The intuition is quite clear here.

> The solution here is to get as many wallets and transactions using bip69 as possible, and suddenly there's no difference and everyone wins.

Agreed, yet it's not happening since 2015. Good luck getting CoinBase/other banks getting into Bitcoin to use BIP69. You need an SF for that, not a BIP. Which by the way, if you would want to propose this SF, I would support.

**Comment by RHavar** [comment]
Yeah, I guess I'll just close this. It's clear that "Let's get everyone using bip69" is probably insurmountable, so probably the best approach is to come up with a new standard for deterministic sorting to replace bip69  (based on a "semi-secret") and see if the current bip69 users are amenable to. 

I don't really have the time for it, but if anyone want to pick up the mantle..

**Comment by benma** [comment]
For future reference: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-October/016457.html
