### ISSUE TITLE
walletdump generates WIF strings that contradict documentation

### ISSUE THREAD

**Issue by GSPP** [bitcoin/bitcoin#12660]
`walletdump` generated the following slightly redacted line:

KwntAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 2000-01-01T00:00:00Z label= # addr=1L...

This base58check string results in 34 bytes (checkable using http://gobittest.appspot.com/PrivateKey). The first byte is [documented ](https://en.bitcoin.it/wiki/Wallet_import_format) to be 0x80 so the rest is 33 bytes long. Private keys are always 32 bytes.

What does this mean? How to obtain the private key?

**Comment by MeshCollider** [comment]
Notice that the private key begins with a `K`. That means it is a key for a compressed public key, and as per the wiki documentation you linked, the key should have 0x80 prepended to it *and* 0x01 appended to it. That's an extra 2 bytes, not just 1. Please see [here](https://en.bitcoin.it/wiki/Wallet_import_format#WIF_to_private_key) for how to convert between the WIF format and the private key, and in future please use bitcoin.stackexchange.com for support/usage questions rather than GitHub

**Comment by GSPP** [comment]
I missed that 0x01 statement in the documentation. Thanks for clarifying. I was under the impression that this was a bug (at least a documentation but) which is why I filed it here.
