### ISSUE TITLE
Fatal Error while bitcoin core is downloading rest of the blocks after 70% done 

### ISSUE THREAD

**Issue by AbhinavJKJ** [bitcoin/bitcoin#12868]
![fatalerror](https://user-images.githubusercontent.com/21276445/38235421-c5eeacd0-373e-11e8-8043-769f9f9c8a21.PNG)

[debug.log](https://github.com/bitcoin/bitcoin/files/1870569/debug.log)

Please see the attached debug file

**Comment by fanquake** [comment]
Please provide more information, including the information asked for in the issue template..

#### Describe the issue:
#### What behavior did you expect?

#### What was the actual behavior (provide screenshots if the issue is GUI-related)?

#### How reliably can you reproduce the issue, what are the steps to do so?

#### What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?

#### What type of machine are you observing the error on (OS/CPU and disk type)?

#### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by jnewbery** [comment]
You problem is here:

`2018-04-03 06:54:20 ERROR: ReadBlockFromDisk: Errors in block header at CBlockDiskPos(nFile=72, nPos=131509702)`

There's corruption in one of the block headers stored to disk. This in turn causes ActivateBestChain to fail:

`2018-04-03 06:54:34 Failed to connect best block`
