### ISSUE TITLE
Make Deploy for Cross Compile Windows Fails 

### ISSUE THREAD

**Issue by buddilla** [bitcoin/bitcoin#12876]
When running make deploy during cross compile setup.exe fails to build

setup.exe is built

fails to be built

Follow ubuntu cross compile instructions for windows and run make deploy after make

bitcoin-core 0.16

ubuntu 14.04 VM (2 core 2G Ram Allocated) on
Macbook Pro (15-inch, mid 2012)
macOS 10.13.3
2.6 GHz Intel Core i7
16 GB 1600 MHz DDR3
NVIDIA GeForce GT 650M 1 GB
Intel HD Graphics 4000 1536 MB

ubuntu:~/Desktop/bitcoin-0.16$ make deploy
Making all in src
make[1]: Entering directory `/home/bitcoin/Desktop/bitcoin-0.16/src'
make[2]: Entering directory `/home/bitcoin/Desktop/bitcoin-0.16/src'
make[3]: Entering directory `/home/bitcoin/Desktop/bitcoin-0.16'
make[3]: Leaving directory `/home/bitcoin/Desktop/bitcoin-0.16'
make[2]: Leaving directory `/home/bitcoin/Desktop/bitcoin-0.16/src'
make[1]: Leaving directory `/home/bitcoin/Desktop/bitcoin-0.16/src'
Making all in doc/man
make[1]: Entering directory `/home/bitcoin/Desktop/bitcoin-0.16/doc/man'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/bitcoin/Desktop/bitcoin-0.16/doc/man'
make[1]: Entering directory `/home/bitcoin/Desktop/bitcoin-0.16'
make[1]: Nothing to be done for `all-am'.
make[1]: Leaving directory `/home/bitcoin/Desktop/bitcoin-0.16'
/bin/mkdir -p ./release
STRIPPROG="/usr/bin/x86_64-w64-mingw32-strip" /bin/bash /home/bitcoin/Desktop/bitcoin-0.16/build-aux/install-sh -c -s ./src/bitcoind.exe ./release
STRIPPROG="/usr/bin/x86_64-w64-mingw32-strip" /bin/bash /home/bitcoin/Desktop/bitcoin-0.16/build-aux/install-sh -c -s ./src/qt/bitcoin-qt.exe ./release
STRIPPROG="/usr/bin/x86_64-w64-mingw32-strip" /bin/bash /home/bitcoin/Desktop/bitcoin-0.16/build-aux/install-sh -c -s ./src/bitcoin-cli.exe ./release
error: could not build bitcoin-0.16.0-win64-setup.exe
built bitcoin-0.16.0-win64-setup.exe

[config.log](https://github.com/bitcoin/bitcoin/files/1874352/config.log)

**Comment by globaltoken** [comment]
Did you installed all dependencies?

**Comment by hanzou-x** [comment]
Pretty sure @buddilla must have installed/built everything in the `depends/` subfolder , as that's required in order to build `bitcoin-qt.exe`.

Some days ago I hit the same error on a Litecoin forked altcoin, so I went back to bitcoin master and the error is the same for me:
```
STRIPPROG="/usr/bin/x86_64-w64-mingw32-strip" /bin/bash /home/hanzou/bitcoin/build-aux/install-sh -c -s ./src/qt/bitcoin-qt.exe ./release
STRIPPROG="/usr/bin/x86_64-w64-mingw32-strip" /bin/bash /home/hanzou/bitcoin/build-aux/install-sh -c -s ./src/bitcoin-cli.exe ./release
error: could not build bitcoin-0.16.99-win64-setup.exe
built bitcoin-0.16.99-win64-setup.exe
```
(also evidently it doesn't propagate errors well, the last line thinking it was built successfully.)

There is zero mention of NSIS in https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md but this worked for me:
```
sudo apt install nsis
makensis share/setup.nsi
```
That successfully built a working `bitcoin-0.1.16.99-win64-setup.exe`, yet `make deploy` still can't find it so there's still something that needs to be fixed in documentation or the build flow.

**Comment by buddilla** [comment]
Yep that was it. thank you

**Comment by hanzou-x** [comment]
Ok, `make deploy` works for me if I install NSIS first. Still:
* Someone should update the docs to include the makensis dependency
* It should output something while running makensis, rather than having the silent point after the strip
* When it fails, shouldn't say "built bitcoin-0.16.99-win64-setup.exe"
