### ISSUE TITLE
Regtest generated coins from prev 0.16.0 version are "generated but not accepted mined"

### ISSUE THREAD

**Issue by macdasi** [bitcoin/bitcoin#12872]
I've upgraded bitcoin core from 0.15.1 to 0.16.0 and I run it with same args for regtest on same datadir, I get balance 0 although at the 0.15.1 I had X balance . I can see on the "Transactions" tab that the mined rows are with "?" mark and tooltip with  "Generated but not accepted mined" .

I expected to see the balance from the last version

To reproduce the issue:
1. run 0.15.1 with regtest
2. generate 200 in console 
3. upgrade to version 0.16
4. no balance

bitcoin core version upgraded from 0.15.1 to 0.16.0
on win10 64x

**Comment by jnewbery** [comment]
Strange. `TransactionStatus::NotAccepted` is set on transactions which are not in the main chain, so the blocks containing these coinbase transactions must have been re-orged out of the main chain.

As @achow101 says, this will be a lot easier to troubleshoot with the debug.log file. Are you able to upload it?

**Comment by sdaftuar** [comment]
In 0.16, we changed the consensus parameters for regtest so that segwit was always active.  This was mentioned briefly in the release notes https://github.com/bitcoin/bitcoin/blob/v0.16.0/doc/release-notes.md#testing-changes, along with a workaround to replicate the old behavior.

I am surprised that you're not seeing the assertion failure mentioned in the release notes, but I suspect this is the cause of what you're seeing.
