### ISSUE TITLE
RPC verifymessage throws -3 code, Address does not refer to key

### ISSUE THREAD

**Issue by matijalukic** [bitcoin/bitcoin#12875]
I expected from verify message to return true/false value, but no matter which address I put, I got 'error code -3, error message: **Address does not refer to key**'

I am simply trying to do _signmessage_/_verifymessage_ operation with address that I generated on a testnet locally, with bitcoin-cli RPC using PowerShell.

**Comment by sipa** [comment]
`signmessage` and `verifymessage` only work with P2PKH addresses. Since 0.16, P2SH-P2WPKH addresses are the default.

You can generate P2PKH addresses by running with `-addresstype=legacy`.

There is ongoing discussions on how to extend the message sign/verify logic to support other address types, but we're not there yet.
