### ISSUE TITLE
Redistribute Lost Bitcoins After 50 Years ! 

### ISSUE THREAD

**Issue by besoeasy** [bitcoin/bitcoin#13334]
Hello, Today while analysing the bitcoin blockchain, i suspect many addresses access may be lost by there users, or the user may be dead!

This limits down on bitcoin supply, and will affect the bitcoin in long-term!

We Can Redistribute Lost Coins by checking last transaction date, if it is some years ( can be 100 years = one human lifespan ) old, the coins should be distributed as block reward..

its necessary for now, but as per my calculation

457 Bitcoins are lost/each month (avg)

**Comment by fanquake** [comment]
This issue tracker is used for discussing technical issues with the Bitcoin Core client, this topic would be more suited to a post on the bitcoin dev mailing list.

**Comment by sipa** [comment]
1) This is a topic for the bitcoin-dev mailinglist, not the issue tracker for a protocol implementation. The protocol would need to change in order to permit this.

2) I expect this would wildly be considered theft by many Bitcoin users, and such a protocol change would need massive buy-in from the ecosystem.

**Comment by besoeasy** [comment]
agree @sipa, but it would not be a problem for active users!
