### ISSUE TITLE
-sysperms=false (default) doesn't appear to do anything

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#13371]
Despite -sysperms=false (default) docs saying files will be created with perms 077, none of my default-created datadirs appear to have any permissions aside from 0600. Maybe I'm misreading the docs but it appears umask(077) isnt doing anything.

**Comment by n2yen** [comment]
can work on this.

**Comment by hebasto** [comment]
@TheBlueMatt
> Despite -sysperms=false (default) docs saying files will be created with perms 077, none of my default-created datadirs appear to have any permissions aside from 0600. Maybe I'm misreading the docs but it appears umask(077) isnt doing anything.

`-sysperms=false` makes Bitcoin Core create files with `umask = 077` rather permissions `077`.
And this implies `0600` permissions for regular files and `0700` for directories.
See: [Debian Reference](https://www.debian.org/doc/manuals/debian-reference/ch01.en.html#_control_of_permissions_for_newly_created_files_umask)

So, Bitcoin Core creates files as expected ;)

**Comment by niVelion** [comment]
> Despite -sysperms=false (default) docs saying files will be created with perms 077

I assume you're referring to these docs:

```
$ bitcoind --help | grep --after-context 3 sysperms
  -sysperms
       Create new files with system default permissions, instead of umask 077
       (only effective with disabled wallet functionality)
```

I don't know where to find the default values, but you mention this setting is by default `false`, which makes sense given what it does.

Running `umask` on my Debian-based distro returns my system default umask `002`, meaning the system (that is, not my user) will create new files with permissions u=rwx g=rwx o=rx.

Perhaps the help text would be more readable if it said:

"Create new files with system default umask, instead of umask 077".

Link to help text: https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L430

**Comment by susanka068** [comment]
Hello, I'd like to tackle this issue. Is this issue still open ?

**Comment by willcl-ark** [comment]
> @TheBlueMatt
> 
> > Despite -sysperms=false (default) docs saying files will be created with perms 077, none of my default-created datadirs appear to have any permissions aside from 0600. Maybe I'm misreading the docs but it appears umask(077) isnt doing anything.
> 
> `-sysperms=false` makes Bitcoin Core create files with `umask = 077` rather permissions `077`. And this implies `0600` permissions for regular files and `0700` for directories. See: [Debian Reference](https://www.debian.org/doc/manuals/debian-reference/ch01.en.html#_control_of_permissions_for_newly_created_files_umask)
> 
> So, Bitcoin Core creates files as expected ;)

Just to check:

System: Ubuntu 22.04
umask: 002 (OS default)

I've tested creating a new datadir on master with default bitcoind settings (i.e. **without** setting `-sysperms` and **with** wallet enabled): `bitcoind -signet`. We expect bitcoin to use umask 077 by default.

For directories expect: 777 - 077 = 700 = `rwx------`
For files expect:      666 - 077 = 600 = `rw-------`

It created the following:

```
will@ubuntu in /tmp
❯ exa -alR .bitcoin
drwxrwxr-x - will 15 Nov 14:22 signet
drwxrwxr-x - will 15 Nov 14:22 wallets

.bitcoin/signet:
.rw-------    0 will 15 Nov 14:22 .lock
.rw-------   37 will 15 Nov 14:22 anchors.dat
.rw-------   31 will 15 Nov 14:22 banlist.json
drwx------    - will 15 Nov 14:22 blocks
drwx------    - will 15 Nov 14:22 chainstate
.rw------- 7.0k will 15 Nov 14:22 debug.log
.rw------- 248k will 15 Nov 14:22 fee_estimates.dat
.rw-------   18 will 15 Nov 14:22 mempool.dat
.rw-------   99 will 15 Nov 14:22 onion_v3_private_key
.rw-------  11k will 15 Nov 14:22 peers.dat
.rw-rw-r--    4 will 15 Nov 14:22 settings.json
drwxrwxr-x    - will 15 Nov 14:22 wallets
``` 


It seems to have used the system umask to create `.bitcoin/`, `signet/`, `signet/wallets/` and top level `wallets/` directories (777-002=775), but not `blocks/` and `chainstate/` directories. It has also used system umask to create the `settings.json` file.

This happens because `ReadConfigFiles()` is called [_before_](https://github.com/bitcoin/bitcoin/blob/v24.0rc4/src/bitcoind.cpp#L156-L183) `AppInitBasicSetup()` (which sets the umask) and `ReadConfigFiles` will internally call `GetConfigFile()` which in turn calls [`AbsPathForConfigVal()`](https://github.com/bitcoin/bitcoin/blob/dce93b2dd7a96398058cd7ef0044a3d48b608cba/src/util/system.cpp#L1424-L1430), where calling either of `GetDataDirNet()` or `GetDataDirBase()` will init the base file structure before the `-sysperms` flag has been parsed.

---

Starting with `bitcoind -signet -sysperms -disablewallet`:

For directories expect:  777 - 002 = 775 = `rwxrwxr-x`
For files expect:      666 - 002 = 664 = `rw-rw-r--`

Which creates the following:

```
will@ubuntu in /tmp
❯ exa -al -R .bitcoin_sysperms/
drwxrwxr-x - will 15 Nov 16:18 signet
drwxrwxr-x - will 15 Nov 16:17 wallets

.bitcoin_sysperms/signet:
.rw-rw-r--    0 will 15 Nov 16:18 .lock
.rw-rw-r--   37 will 15 Nov 16:18 anchors.dat
.rw-rw-r--   31 will 15 Nov 16:18 banlist.json
drwxrwxr-x    - will 15 Nov 16:18 blocks
drwxrwxr-x    - will 15 Nov 16:18 chainstate
.rw-rw-r-- 6.5k will 15 Nov 16:18 debug.log
.rw-rw-r-- 248k will 15 Nov 16:18 fee_estimates.dat
.rw-rw-r--   18 will 15 Nov 16:18 mempool.dat
.rw-rw-r--   99 will 15 Nov 16:18 onion_v3_private_key
.rw-rw-r--  12k will 15 Nov 16:18 peers.dat
.rw-rw-r--    4 will 15 Nov 16:18 settings.json
drwxrwxr-x    - will 15 Nov 16:17 wallets
```
---

I have made a [patch](https://github.com/bitcoin/bitcoin/compare/master...willcl-ark:bitcoin:2022_13371_sysperms) which results in the following (correct) filestructure when started **without** the `-sysperms` flag:

```
will@ubuntu in /tmp/13371
❯ exa -al -R
drwx------ - will 16 Nov 13:47 .bitcoin

./.bitcoin:
drwx------ - will 16 Nov 13:47 signet
drwx------ - will 16 Nov 13:47 wallets

./.bitcoin/signet:
.rw-------    0 will 16 Nov 13:47 .lock
.rw-------   37 will 16 Nov 13:47 anchors.dat
.rw-------   31 will 16 Nov 13:47 banlist.json
drwx------    - will 16 Nov 13:47 blocks
drwx------    - will 16 Nov 13:47 chainstate
.rw------- 7.1k will 16 Nov 13:47 debug.log
.rw------- 248k will 16 Nov 13:47 fee_estimates.dat
.rw-------   18 will 16 Nov 13:47 mempool.dat
.rw-------   99 will 16 Nov 13:47 onion_v3_private_key
.rw-------  16k will 16 Nov 13:47 peers.dat
.rw-------    4 will 16 Nov 13:47 settings.json
drwx------    - will 16 Nov 13:47 wallets
```

And with `-sysperms -disablewallet`:

```
will@ubuntu in /tmp/13371
❯ exa -al -R
drwxrwxr-x - will 16 Nov 13:54 .bitcoin_sysperms

./.bitcoin_sysperms:
drwxrwxr-x - will 16 Nov 13:55 signet
drwxrwxr-x - will 16 Nov 13:54 wallets

./.bitcoin_sysperms/signet:
.rw-rw-r--    0 will 16 Nov 13:55 .lock
.rw-rw-r--   37 will 16 Nov 13:55 anchors.dat
.rw-rw-r--   31 will 16 Nov 13:55 banlist.json
drwxrwxr-x    - will 16 Nov 13:55 blocks
drwxrwxr-x    - will 16 Nov 13:55 chainstate
.rw-rw-r-- 7.0k will 16 Nov 13:55 debug.log
.rw-rw-r-- 248k will 16 Nov 13:55 fee_estimates.dat
.rw-rw-r--   18 will 16 Nov 13:55 mempool.dat
.rw-rw-r--   99 will 16 Nov 13:55 onion_v3_private_key
.rw-rw-r--  14k will 16 Nov 13:55 peers.dat
.rw-rw-r--    4 will 16 Nov 13:55 settings.json
drwxrwxr-x    - will 16 Nov 13:54 wallets
```

I would be interested in more feedback on whether such a change is desirable because changing the **default** file permissions could possibly break things upstream for other projects?
