### ISSUE TITLE
[GUI]: Missing line breaks for Notifications

### ISSUE THREAD

**Issue by globaltoken** [bitcoin/bitcoin#13376]
Hey,

While testing in regtest I noticed a small issue.
I used the current Master branch and entered regtest, and generated blocks.

While receiving regtest rewards I noticed that the GUI Notification for receiving is missing line breaks.
A Screenshot has been attached.

Regards,
Pawel
![issue](https://user-images.githubusercontent.com/24831016/40885995-a3f7d7d8-6730-11e8-9dd2-b512360d0467.jpg)

**Comment by qmma70** [comment]
Just tried this out -- works fine on macOS. I suspect this is working on Unix/Linux as well.

A quick look at the file below shows we're already doing things correctly (i.e. using `\n` for plaintext message in `QSystemTrayIcon::showMessage`). 
https://github.com/bitcoin/bitcoin/blob/a315b79ad2b8f76b66f8c2b79bbe5da43cca8b4a/src/qt/bitcoingui.cpp#L1026

As a work around, maybe we can use some separator like ` , ` or ` . ` on Windows instead of relying on the OS's interpretation of `\n`?

**Comment by globaltoken** [comment]
@qmma70 I used the current master branch, not 0.16, I compiled a Wallet by myself, because I tried --enable-debug.
Earlier versions are not affected by this issue, it seems to be buggy after 0.16 (current Master branch.)

Regards

**Comment by qmma70** [comment]
I understand -- I was running from my build as well.

I noticed the code hasn't changed in a while now, so this looks more like an environmental issue.

**Comment by fanquake** [comment]
@globaltoken If this was self compiled, what version of Qt was used?

**Comment by globaltoken** [comment]
@fanquake I used QT 5.7.1

**Comment by fanquake** [comment]
I can't recreate this issue on Windows using the latest release binaries.

![notification_popup](https://user-images.githubusercontent.com/863730/73744134-20878500-478b-11ea-8e5c-99ad4c556ba4.png)

![notification_bar](https://user-images.githubusercontent.com/863730/73744138-22514880-478b-11ea-98f7-a73140353a17.png)
