### ISSUE TITLE
listtransactions and getbalance discrepancy

### ISSUE THREAD

**Issue by kallewoof** [bitcoin/bitcoin#13559]
Another user noted that `bitcoin-cli listtransactions "*" 99999` and `getbalance "*"` (these days simply `getbalance`) are not giving the same amounts when summed together.

I noticed the same behavior on a node I have access to, but could not reproduce this on regtest despite sending back and forth multiple times between two nodes.

To tally the `listtransactions` amounts:

```bash
bitcoin-cli listtransactions "*" 99999|jq -r ".[].amount, .[].fee" | grep -v null | perl -nle '$sum += $_ } END { print $sum'
```

Compare this to `bitcoin-cli getbalance`. It *differs* in my case, and in the case of the other user (both testnet and mainnet for him, mainnet for me; I don't have any testnet coins right now).

**Comment by marcoagner** [comment]
I'm probably missing something but couldn't this be happening because `getbalance` doesn't count 0 confs by default (and in the case of mining on regtest, immature coins are not counted too) while `listtransactions` lists everything (0 conf, immature...)?

**Comment by marcoagner** [comment]
Here's what I'm doing so you can tell if I'm reproducing the issue or not:
- run node1 on regtest
- generate 101 blocks to myself
- tests both commands and get `50` for `getbalance` and `5050` for the `listtransactions` sum (101 blocks * 50 reward)
- run node2 on regtest
- send between them and get different ammounts from the same commands because of 0 confs and immature coins

**Comment by kallewoof** [comment]
@marcoagner No, there were no unconfirmed transactions.

**Comment by kallewoof** [comment]
@jonasschnelli Yes, that seems to be the problem. Thanks!
