### ISSUE TITLE
Adding stop commands to bitcoind.service

### ISSUE THREAD

**Issue by McRemco** [bitcoin/bitcoin#13736]
When bitcoind (version 0.16.1)  is started via systemd with the supplied bitcoind.service file stopping the service results in an unclean shutdown if for some reason it takes too long to write the cache to hdd and subsequently will cause a rolling forward when it is started the next time.

So maybe it is a good idea to add something like this to the bitcoind.service file
```
# Commands to ensure a clean shutdown when stopping bitcoind
ExecStop=bitcoin-cli -conf=/etc/bitcoin/bitcoin.conf stop
TimeoutStopSec=600
# don't send kill signal
KillMode=none
```

**Comment by luke-jr** [comment]
RPC `stop` shouldn't be any faster than signal-based shutdown... I'd just do the timeout if needed.

**Comment by McRemco** [comment]
So if I understand it correct the kill signal grom systemd invokes the same routines the rpc command stop does, I was under the impression that that the kill signal was much more abrupt, hence the name.

**Comment by McRemco** [comment]
@sipa, Thank you for clearing that out, I'm stil fairly new in the world of Linux but learning every day a little more.

**Comment by greenaddress** [comment]
Perhaps is no longer the case but bitcoind in the past had instances where it was slow to shutdown, in the past using SIGTERM i remember i lost mempool/feeestimates and moved to call stop via rpc/cli to avoid the SIGKILL post SIGTERM timeout.

**Comment by jonasschnelli** [comment]
The shutdown can be "fast or slow" via RPC stop and via SIGTERM. It depends on caches being written and other tasks begin uncompleted. Example: if you sync the complete chain from the scratch with a dbcache of 6GB the shutdown (regardless wether you have use SIGTERM or RPC stop) will take a fairly long time since the the complete cache gets written during the shutdown procedure.

It would be possible to furthermore optimise for a quicker shutdown. See #12980 as an example.

**Comment by jonasschnelli** [comment]
It would probably be worth to figure out, what maximal execution time a process is given via systemd (or other application managers) before a SIGKILL happens. But in generally it might be complicated to never exceed this maximal timeout since it depends on disk speed, CPU, etc...
Ideally, every time consuming process would respect the shutdown trigger (if possible).

**Comment by setpill** [comment]
Simple fix would be to set `TimeoutStopSec=infinity` in the `bitcoind.service` file. Imho that has preference over setting a long timeout with `KillMode=none` since this can break systemd's restart logic.

Another idea by @Sjors as discussed on IRC would be to switch from `Type=forking` to `Type=notify` which would allow `bitcoind` to request timeout extensions via `EXTEND_TIMEOUT_USEC=`; however this would involve (non-trivial) changes to the codebase to use `sd_notify`.

**Comment by andrewtoth** [comment]
#15218 would mitigate this issue.

**Comment by setpill** [comment]
I don't believe it would; perhaps in specific cases but not all, if I understand the functioning correctly. It assumes an uninterrupted IBD.

**Comment by andrewtoth** [comment]
It would solve for the first 24 hours after IBD is finished. In cases where IBD doesn't finish, then you are correct.

**Comment by setpill** [comment]
Especially in the case where one tinkers with the config during IBD (e.g. to increase db cache in order to speed up IBD) and uses `systemctl restart bitcoind`, the current systemd service file causes unclean shutdowns, triggering a lengthy "Rolling forward" after the restart of the service (wasting much work that has been done and increasing how painful the IBD experience is). Imho both PRs do not conflict and complement each other :)

**Comment by adamjonas** [comment]
Closed by https://github.com/bitcoin/bitcoin/pull/16569.
