### ISSUE TITLE
Missing and unaccesible sync modal when using QT without wallet

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#13828]
Noticed this while reviewing #13529, but it's also in master @ 5ba77df15. On macOS 10.13.6:

```
bitcoin-qt -disablewallet
```

<img width="1354" alt="schermafbeelding 2018-08-01 om 16 03 41" src="https://user-images.githubusercontent.com/10217/43526506-b23264d8-95a4-11e8-81a0-5debcad838ae.png">

The usual progress modal doesn't appear when QT starts, and clicking on the progress bar has no effect. It works fine when there's a wallet present.

**Comment by MarcoFalke** [comment]
I guess that is because some of the text does only apply to a wallet node?

Still, I agree the estimated time left should somehow be communicated, since it seems useful. Maybe even just through rpc?

**Comment by fanquake** [comment]
At the moment we just have `verificationprogress` via getblockchaininfo.
`"verificationprogress": 0.002939916278266955,`

Would we add an `"estimatedsynctime"` or similar to the same RPC call?

**Comment by jonasschnelli** [comment]
@Sjors: indeed. The modal overlay (sync info) is somehow attached to the wallets view "out of sync/balance"-warning. This could be changed. The modal overlay itself contains no wallet relevant information.

Agree with @MarcoFalke / @fanquake to add the `estimatedsynctime` to the RPC call `getblockchaininfo`.

**Comment by benthecarman** [comment]
> Agree with @MarcoFalke / @fanquake to add the `estimatedsynctime` to the RPC call `getblockchaininfo`.

I don't think adding an `estimatedsynctime` to the RPC call `getblockchaininfo` is possible.  Currently how it is calculated is by refering to the previous calls of `tipUpdate` and calculating how much progress has been made since the last set of calls and then using that to calcuate the remaining time.  The RPC shouldn't be able to access this info unless the data is moved to somewhere not in the GUI.
