### ISSUE TITLE
0.17.2rc issue (standardness change for bare multisig)

### ISSUE THREAD

**Issue by preminem** [bitcoin/bitcoin#14104]
IN 0.16.2 some output type is multisig.But in 0.17.2rc this is nonstardard. Anyone know why？

**Comment by preminem** [comment]
e.g.
txid : fc200f9cef8faf8f76756b5d02081061a1fd22ec1d580f778c12373e12a56016

**Comment by jonasschnelli** [comment]
0.16 did allow [invalid pubkey as long as they had the right size](https://github.com/bitcoin/bitcoin/blob/0.16/src/script/standard.cpp#L135).

0.17 is more [strict about this](https://github.com/bitcoin/bitcoin/blob/0.17/src/script/standard.cpp#L81).

Your tx listed above uses invalid pubkeys (a pubkey starting with 0x20 is invalid) which are now non-standard.

This is caused by #13194

**Comment by mmortal03** [comment]
Was this fixed by 0.17.0?

**Comment by MarcoFalke** [comment]
I doubt it, it should have been added to the release notes.

**Comment by MarcoFalke** [comment]
Unfortunately we can't change the release notes after the fact
