### ISSUE TITLE
Add test vectors in BIP143 into tx_valid.json / sighash.json

### ISSUE THREAD

**Issue by Christewart** [bitcoin/bitcoin#14308]
AFAICT these test vectors aren't actually run bitcoin core, and other library developers use `tx_valid.json`/`tx_invalid.json` / `sighash.json` to test their implementations.

It looks like `sighash.json` hasn't been updated in 4 years (!) 

https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki#example

**Comment by pinheadmz** [comment]
This isn't a bad idea, and we could include the witnessV0 test vectors in the JSON file, but since `sighash_tests.cpp` only executes `SignatureHash()` and not `SignatureHashSchnorr()`, I don't think those test/data files should be considered complete anymore. 

To test [taproot validation on bcoin](https://github.com/bcoin-org/bcoin/pull/1063) for example I created a [fork of bitcoin](https://github.com/pinheadmz/bitcoin/tree/taproottest-0.21.1) that generated a taproot test vectors json file similar to the original files you are looking at (from https://github.com/bitcoin/bitcoin/pull/3975)
