### ISSUE TITLE
Failing to disconnect a block should result in node shutdown

### ISSUE THREAD

**Issue by sdaftuar** [bitcoin/bitcoin#14341]
I think that if a reorg fails due to an error while disconnecting blocks, the node should shut down.

My thought is that if we are trying to switch to a more work chain and something goes wrong before we can even try to validate that more-work chain, then we have a problem that is not related to the chain we're trying to switch to but instead related to our own hardware or software; shutting down and having the user deal with the issue is better than continuing on, when we know there's a more work chain that we're unable to try validating.

This has recently come up on testnet, where unpatched nodes are unable to reorg from the invalid chain containing the duplicate-input-in-a-transaction block, but rather than crash or shutdown they are continuing on the invalid chain, with messages like this in the debug log:

```
ERROR: DisconnectTip(): DisconnectBlock 00000000210004840364b52bc5e455d888f164e4264a4fec06a514b67e9d5722 failed
```

**Comment by HashUnlimited** [comment]
Alright, it has already been discovered, didn't stumble over this one earlier. Is the invalid chain still around anywhere on testnet? As we have seen on several chains out in the wild, this can cause a whole network to freeze because once we actually do have a longer chain, wrong nodes aren't banned and there for nothing even gets relayed anymore.
