### ISSUE TITLE
v0.17.0: symbolic link to wallet.dat re-enabled

### ISSUE THREAD

**Issue by isghe** [bitcoin/bitcoin#14429]
in version `v0.17.0` it's possible to have symbolic link to `wallet.dat` file. It's not clear if it's a mistake, or a new feature. The check against symbolic link, was introduced silently (not described in `release-notes.md`) in v0.15.0, and permitted again silently (not described in `release-notes.md` v0.17.0).
https://github.com/bitcoin/bitcoin/pull/11343
Thanks, Isidoro Ghezzi

**Comment by promag** [comment]
Considering:
```
$ ls -l
wallet_sym.dat -> wallet.dat
```
The following tests fail:

Test 1 :
```
bitcoind -regtest -wallet=wallet_sym.dat
Error: Invalid -wallet path ... -wallet path should point to ...
```
Test 2:
```
bitcoind -regtest -wallet=w1
bitcoin-cli -regtest loadwallet wallet_sym.dat
error code: -4
error message:
Wallet file verification failed: Invalid -wallet path 'wallet_sym.dat'. -wallet path should point to ...
```
Could you share your test?

Note that it is possible to have links if it's a directory (`where wallet.dat and database/log.?????????? files can be stored`).

**Comment by isghe** [comment]
it's the usual wallet.dat (a symbolic link) file in `~/Library/Application Support/Bitcoin/`. I will try the tests you suggested in the week end :-) thanks

**Comment by ryanofsky** [comment]
`-wallet=<path>` arguments can't be symbolic links to files, but if `<path>` is a directory and the directory contains a wallet.dat which is a symbolic link, that isn't currently treated like an error. It could be treated like an error, though, if we wanted to forbid it as a precaution.

But I would say this change in behavior in 0.17 is neither a mistake nor a new feature. Just a minor, backwards compatible change that wasn't mentioned in the release notes, because the only effect is to allow a particular configuration of symlinks which is probably fine, but not something we would go out of our way to document or recommend.
