### ISSUE TITLE
Bitcoin uploads found blocks to all peers simultaneously 

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#1467]
If you find a block (esp p2pool users who are often behind low-upload connections) you simultaneously announce it to all peers, resulting in increased upload time and in some cases, possibly even increased orphan rate.  Bitcoin should ideally stagger uploads so that it can start getting new blocks out to the network quickly.

**Comment by rebroad** [comment]
I think this is a great idea (and had the same idea myself before reading this). Perhaps some sort of ratio setting could be used so that we don't relay blocks to peers that are giving us very little in return - but still allow some resources for serving historical blocks (albeit as a lower priority to block relay).

**Comment by Leviathn** [comment]
Compact blocks should resolve this, yes?
