### ISSUE TITLE
bip 125 replaceable flag should require a change output

### ISSUE THREAD

**Issue by pstratem** [bitcoin/bitcoin#14724]
otherwise users think their transaction is replaceable, but bumpfee doesn't work

**Comment by mruddy** [comment]
Making a change output mandatory in order to get BIP125 functionality does not seem desirable to me. For example, what if you are just consolidating some outputs down to one (e.g.- sending to long term cold storage) and want to have the ability to adjust the fee later if it ends up taking longer than you want to wait? Is this really a bug report that the bumpfee feature in the GUI wallet does not work as expected?

**Comment by promag** [comment]
> The command will pay the additional fee by decreasing (or perhaps removing) its change output.
> If the change output is not big enough to cover the increased fee, the command will currently fail instead of adding new inputs to compensate. (A future implementation could improve this.)

Currently it requires exactly one change output. And `bumpfee` can remove it (when it's considered dust) which would prevent another `bumpfee`. `bumpfee` could fail if `replaceable=true` and new change output is dust.

**Comment by jnewbery** [comment]
I agree that the behaviour right now isn't great, but it'd be a shame to prevent users from being able to set the flag. As things stand a user could (in theory) create a replacement transaction with additional inputs outside Bitcoin Core, and then sign using `signrawtrasnactionwithwallet`.

The right fix here is to improve bumpfee so it can add additional inputs to a replacement transaction. And can we please start signaling opt-in RBF by default please? :)

I don't see any harm in adding a *warning* if opt-in RBF is signaled on a transaction with no change output.

**Comment by bitschmidty** [comment]
There might be a consideration to the UI if "coin control features" is enabled. 

Right now the context menu for increase a transaction in QT is simply "Increase transaction fee" since there is one or zero change outputs. 

However, with coin control enabled and the ability to add inputs to the transaction this might require an additional dialog for selecting the additional inputs required to bump.
