### ISSUE TITLE
settxfee should require wallet unlock

### ISSUE THREAD

**Issue by BeOleg** [bitcoin/bitcoin#14824]
Attack scenario:
The attacker gains access to the wallet but does not have a passphrase.
He then sets the transaction fee to the maximum (0.1 BTC per transaction) and waits until the wallet publishes transactions.

If enough transactions are published (for example an exchange wallet) he then invests his top buck in cloud mining and mines a new block and includes the transactions that were published with the inflated fee.

**Comment by WorkShop-Office** [comment]
Yes accept

Dian Jaka Widiawan

**Comment by promag** [comment]
If the attacker has access then it can retry sending until it succeeds meaning someone unlocked it.

**Comment by BeOleg** [comment]
The way exchange wallets work is that they unlock to publish transactions a
d then lock again.
Mainly programatically.

**Comment by promag** [comment]
Right, I was suggesting they could send right after the unlock.

Anyway, how would this work in multi wallet if the RPC endpoint is not wallet specific?

**Comment by BeOleg** [comment]
Multi wallet implement raw signing with custom keys as far as I know.
ty fee remains the same.

**Comment by MarcoFalke** [comment]
Is it not wallet-specific after #12909?

**Comment by willcl-ark** [comment]
It seems to me that the "attack" vector here is pretty slim, as it would likely rely on compromise of the host (at which point many other attacks are possible), before setting the per-wallet tx feerate (since #12909) using `settxfee`. Next the (exchange?) wallet user would have to initiate transactions **without** setting conf target or feerate manually, which also seems unlikely to me, in order to be taken advantage of.

The payoff (if the attack is not simply a grief) requires having significant-enough hashpower to then collect the fees from those transactions by winning the next block.

If the sender specifies either conf target or feerate as part of the call then these override the the value of `m_pay_tx_fee`. 

In addition to this, the `wallet.m_pay_tx_fee` member variable seems unlikely to ever be converted to a persistent wallet database entry which would end up being encrypted by the wallet passphrase, as OP suggests could protect against this.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
