### ISSUE TITLE
Error when running gmake check on NetBSD 8.0

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#14948]
After compiling Core on a fresh NetBSD 8.0 install (you can recreate using this [Vagrantfile](https://github.com/fanquake/core-review/blob/master/vagrant/Vagrantfile)). The 
[fsbridge_fstream](https://github.com/bitcoin/bitcoin/blob/master/src/test/fs_tests.cpp#L12) test is failing:
```
vagrant ssh netbsd8
...

src/test/test_bitcoin --log_level=all --run_test=fs_tests

Running 1 test case...
Entering test module "Bitcoin Test Suite"
test/fs_tests.cpp(10): Entering test suite "fs_tests"
test/fs_tests.cpp(12): Entering test case "fsbridge_fstream"
unknown location(0): fatal error: in "fs_tests/fsbridge_fstream": boost::system::system_error: boost::filesystem::path codecvt to string: error
test/fs_tests.cpp(12): last checkpoint: "fsbridge_fstream" test entry
test/fs_tests.cpp(12): Leaving test case "fsbridge_fstream"; testing time: 30ms
test/fs_tests.cpp(10): Leaving test suite "fs_tests"; testing time: 30ms
Leaving test module "Bitcoin Test Suite"; testing time: 30ms
```

**Comment by laanwj** [comment]
So as I see there's three options here:
- Force `LC_ALL=C.UTF-8` (or more specifically): this ignores filesystem locale encoding completely and forces passing of UTF-8 to the OS for filenames. This cause cause issues for OSes that truly don't support UTF-8 filenames, or problems interacting with other software that does use the environment locale.
- Remove the funny characters from the test; drawback is that UTF-8 will no longer be tested on say, Windows, or Linux with UTF locale
- Accept "codecvt to string: error" as a valid outcome in the test. Accept that the filesystem cannot support this character, there's nothing to be done

**Comment by ryanofsky** [comment]
I'm doubtful the codecvt errors come from accessing the filesystem. Unix filesystem APIs just take 8-byte character strings and then most filesystem implementations store them without additional translation.

I would guess the error is coming from the line:

https://github.com/bitcoin/bitcoin/blob/7a30e0f6c54443616fdc28b7080dcbc9b630ac77/src/test/fs_tests.cpp#L17

which is attempting to append a `wchar_t` string to an `char` string and failing in the conversion. This might be caused by runtime local settings like @laanwj  suggests, or it could be happening as a result of `input-charset` / `exec-charset` / `wide-exec-charset` [preprocessor settings](https://gcc.gnu.org/onlinedocs/cpp/Invocation.html). But assuming this is a runtime issue and not a compile time issue, in addition to three options above we could also:

4) Call `fs::path::imbue` like @ken2812221 did in #13877 so `char` <-> `wchar_t` conversions 
done by `fs::path` are always utf8 <-> utf16.

5) Drop the failing test line, and no longer check what happens when you try to append a `wchar_t` string to an `fs::path`. Since we don't actually use `wchar_t` strings in bitcoin code, this isn't something we need to care about, even on windows where the `fs::path` class uses `wchar_t` strings, but only internally.

I'd maybe lean to option 4, which could be implemented as easily as dropping the `#ifndef WIN32` condition from ken's #13877 fix. This is nice because it would be a simplification to current code, and it seems acceptable because on unix it is left to individual applications to decide what encodings they want to use for filenames. For example, while Qt applications [use the system locale](http://doc.qt.io/qt-5/qfile.html#encodeName), glib applications [use utf8 and ignore the system locale](https://developer.gnome.org/glib/stable/glib-running.html#G_BROKEN_FILENAMES) unless `G_BROKEN_FILENAMES` is set.

**Comment by itoffshore** [comment]
I receive this same error on Alpine Linux (which does not support `locale`) with `v0.18.0`.

Bitcoin under [Alpine forces a `locale` of `C`](https://github.com/bitcoin/bitcoin/commit/c26acfc308482bac901ab3c7368c951514f13429) so `export LC_ALL=C.UTF-8` & `LC_ALL=C` do not work:

```
Running tests: descriptor_tests from test/descriptor_tests.cpp
Running tests: fs_tests from test/fs_tests.cpp
Running tests: getarg_tests from test/getarg_tests.cpp
Running 1 test case...
Entering test module "Bitcoin Test Suite"
test/fs_tests.cpp(10): Entering test suite "fs_tests"
test/fs_tests.cpp(12): Entering test case "fsbridge_fstream"
unknown location(0): fatal error: in "fs_tests/fsbridge_fstream": boost::system::system_error: boost::filesystem::path codecvt to string: error
test/fs_tests.cpp(12): last checkpoint: "fsbridge_fstream" test entry
test/fs_tests.cpp(12): Leaving test case "fsbridge_fstream"; testing time: 48415us
test/fs_tests.cpp(10): Leaving test suite "fs_tests"; testing time: 48455us
Leaving test module "Bitcoin Test Suite"; testing time: 48585us

*** 1 failure is detected in the test module "Bitcoin Test Suite"
make[3]: *** [Makefile:14450: test/fs_tests.cpp.test] Error 1
make[3]: *** Waiting for unfinished jobs....
PASS: qt/test/test_bitcoin-qt
============================================================================
Testsuite summary for Bitcoin Core 0.18.0
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[4]: Leaving directory '/home/stuart/aports/community/bitcoin/src/bitcoin-0.18.0/src'
```

**Comment by practicalswift** [comment]
This seems to be causing some unnecessary confusion: perhaps we could handle this a bit more gracefully.

If the UTF-8 locale requirement is not fulfilled then we could provide less confusing guidance regarding the issue at hand.

**Comment by meeDamian** [comment]
In case someone else stumbles on it on Alpine as well:

```patch
diff --git src/test/fs_tests.cpp src/test/fs_tests.cpp
index 93aee10bb..4a01e2ed8 100644
--- src/test/fs_tests.cpp
+++ src/test/fs_tests.cpp
@@ -14,7 +14,7 @@ BOOST_AUTO_TEST_CASE(fsbridge_fstream)
     fs::path tmpfolder = SetDataDir("fsbridge_fstream");
     // tmpfile1 should be the same as tmpfile2
     fs::path tmpfile1 = tmpfolder / "fs_tests_₿_🏃";
-    fs::path tmpfile2 = tmpfolder / L"fs_tests_₿_🏃";
+    fs::path tmpfile2 = tmpfolder / "fs_tests_₿_🏃";
     {
         fsbridge::ofstream file(tmpfile1);
         file << "bitcoin";
```

Save ^this as `utf8-fs-test.patch`, and:

```
patch -p0 < utf8-fs-test.patch
```

Run `make check` again.

Above works for automated builds.  To make it pass manually, just delete that letter `L` from `src/test/fs_tests.cpp`.

**Comment by laanwj** [comment]
Huh, I don't think the L should be there at all. We don't use `wchar_t` at all in our code (except for some windows-specific API things), all internal strings in Bitcoin Core are 8-bit UTF-8, and we assume boost to handle that as UTF-8.

**Comment by carnhofdaki** [comment]
> Huh, I don't think the L should be there at all. We don't use `wchar_t` at all in our code (except for some windows-specific API things), all internal strings in Bitcoin Core are 8-bit UTF-8, and we assume boost to handle that as UTF-8. If removing it fixes the test, let's do that.

Yes, removing the `L` really fixes it.

**Comment by carnhofdaki** [comment]
@fanquake I guess this can be closed now.

Thank you all.
