### ISSUE TITLE
Bitcoin Core should not have a fork of univalue

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#15009]
There is no justification for forking UniValue. The subtree should be restored to the official upstream and the fork deleted.

**Comment by jnewbery** [comment]
This is a complete waste of time. You've NACK'ed a bunch of useful PRs (https://github.com/bitcoin-core/univalue/pull/11#issuecomment-419453702, https://github.com/bitcoin/bitcoin/pull/14164#pullrequestreview-153596070, etc) because you believe the upstream should be jgarzik/univalue without once giving a justification of why that should be.

jgarzik/univalue appears to be very infrequently maintained. There haven't been any code changes since August, and a request to add a 1.0.4 release (prompted by you here: https://github.com/bitcoin/bitcoin/pull/12666) has been [unacknowledged since August 21st](https://github.com/jgarzik/univalue/issues/54).

Switching to having our own repo was a pragmatic decision to avoid relying on a spottily-maintained single-maintainer repo, as Wladimir rightly points out here: https://github.com/bitcoin/bitcoin/pull/14882#issuecomment-449001484.

jgarzik does not appear to be interested in actively maintaining his repo. Why should we add that dependency and demand that he maintain it for us?

**Comment by luke-jr** [comment]
Not-forking should be the *default*; only forking should require justification.

It hasn't *needed* any code changes since August AFAICT.

Despite the stale open issue, v1.0.4 was released Sep 1: https://github.com/jgarzik/univalue/releases/tag/v1.0.4

cc @jgarzik

**Comment by MarcoFalke** [comment]
Note that the repo is missing a test fix, that we needed: https://github.com/jgarzik/univalue/compare/master...MarcoFalke:test_fix

Also our copy has the deprecated pair wrappers removed to avoid introducing them in future code changes and to avoid having to constantly fix them up again. I think I explained that earlier. Are we running in circles here?

**Comment by luke-jr** [comment]
Where is the test fix PR upstream? That is an example of why we *shouldn't* have a fork...

**Comment by jgarzik** [comment]
* univalue is actively maintained upstream (jgarzik/univalue)
* To the specific issue of deprecated pair wrappers, upstream has had - for a long time now - a method of compiling those out, to provide a certainty that future Bitcoin code cannot use them.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
