### ISSUE TITLE
Unexplained 1 million block height in mempool code

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#15080]
Where is this magic number from?

https://github.com/bitcoin/bitcoin/blob/fb52d0684e0f03bca5d7ddcf3fc5b0657859ac2c/src/txmempool.cpp#L603

**Comment by fanquake** [comment]
Looks like it was introduced by @TheBlueMatt in #5267.

**Comment by promag** [comment]
A block far far away?

**Comment by instagibbs** [comment]
It's not for testnet.

**Comment by instagibbs** [comment]
I'm having a really difficult time convincing myself this behavior could not lead to incorrect results. But this can only be hit when `-checkmempool` is non-0, aka `-regtest` by default so it's not used in production.

I think here the `spendheight` is the correct height since that is where this duplicate mempool is actually at.

I'll think a little more how a false assertion or validation failure could hit if unchanged.

**Comment by instagibbs** [comment]
If we're at block 1,000,001, a tx A spending something in mempool(tx B) that has an output CLTV of 1,000,001(tx B), then this check may fail.

**Comment by mzumsande** [comment]
I think that the height currently specified as a magic number is never accessed:

In `check()`, the ancestor tx of the mempool are "spent" in the `UpdateCoins()` function (adding new UTXOs to the local cache mempoolDuplicate), providing the inputs for subsequent spending of the dependent tx, and thereby allowing to check that all tx in the mempool can be mined in some order (no orphans). 

While all ancestors need to be added to mempoolDuplicate, the height at which they are added is not checked in `mempoolDuplicate.HaveInputs()`, just their `COutPoint`.  

I did some testing with a height of 0 instead of 1E6 and didn't see any effect.
So I don't see how the current implementation could lead to a bug, though I agree that using `spendheight` would make more sense and might prevent future bugs.

**Comment by instagibbs** [comment]
Lines up with my current thinking.
