### ISSUE TITLE
Unable use replace-by-fee if i use my own address for change

### ISSUE THREAD

**Issue by bekman1** [bitcoin/bitcoin#15331]

**Comment by bekman1** [comment]
I try to increase a transaction fee for transaction wich was made with flag replace-by-fee
and cant do it. For this transaction i have set explicit address for change.
Bitcoin Core ver. 0.17
Mac OS High Siera 10.13.6

**Comment by promag** [comment]
Do you get this error?
```
Transaction does not have a change output (code -4)
```

**Comment by bekman1** [comment]
> Do you get this error?
> 
> ```
> Transaction does not have a change output (code -4)
> ```

yes

**Comment by jonasschnelli** [comment]
If you have set a manual change address (with `fundrawtransaction`, etc.) unknown to your wallet as change, the `bumpfee` call has no clue which output to reduce in order to increase the fee.

`bumpfee` currently isn't very clever. I think it won't work with transaction without a change output.

Try to manually create a replacement-transaction with `createrawtransaction`.

**Comment by MarcoFalke** [comment]
I think you'll have to use an address from `getrawchangeaddress`
