### ISSUE TITLE
Interrupting CWallet::AddToWallet requires rescan

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#1535]
If I interrupt CWallet::AddToWallet at the start, while it is adding a new coinbase transaction (or probably any first-seen-in-block) - for example with "quit" in GDB or SIGKILL - after restarting, Bitcoin-Qt (and bitcoind?) will not pick up on this transaction even after completely catching up. -rescan is then needed to see it.

**Comment by TheBlueMatt** [comment]
This may be because SetBestChain is called when the block state is flushed, irregardless of whether the wallet is currently doing ScanForWalletTransactions. eg if a user starts Bitcoin Core, it is running wallet scan, they try to stop the node, and it takes too long so they kill it (because wallet rescan is uninterruptible, I believe), the wallet best tip pointer may be set based on blocks which were flushed to disk (eg via FlushStateToDisk() in Shutdown()).

**Comment by promag** [comment]
Bump. What could be done here?

**Comment by TheBlueMatt** [comment]
I'd bet this is no longer a bug, and given it was never reported to be reproduceible, I'd suggest close.
