### ISSUE TITLE
getaddressesbylabel API spends much time

### ISSUE THREAD

**Issue by nekonenene** [bitcoin/bitcoin#15447]
The `getaddressesbylabel` API spends a lot more time than the `getaddressesbyaccount` API.

I generated addresses by the `getnewaddress` API, then, I measured time that the `getaddressesby*` API spends. It seems the algorithm of the `getaddressesbylabel` API takes **O(N ^ 2)** time! The results of my survey are as follows.

### getaddressesbylabel

bitcoind v0.17.1 on Ubuntu 16.04 (AWS EC2 t3.large)

#### 11,001 addresses

```sh
time sudo /usr/local/bin/bitcoin-cli -conf=/etc/bitcoin/bitcoin.conf getaddressesbylabel ""
# (omitted)
real    0m1.230s # 1.2s
user    0m0.044s
sys 0m0.048s
```

#### 111,001 addresses

```sh
time sudo /usr/local/bin/bitcoin-cli -conf=/etc/bitcoin/bitcoin.conf getaddressesbylabel ""
# (omitted)
real    1m37.027s # 97.0s
user    0m0.408s
sys 0m0.544s
```

#### 211,001 addresses

```sh
time sudo /usr/local/bin/bitcoin-cli -conf=/etc/bitcoin/bitcoin.conf getaddressesbylabel ""
# (omitted)
real    6m3.727s # 363.7s
user    0m0.800s
sys 0m0.900s
```

### getaddressesbyaccount

bitcoind v0.16.3 on Ubuntu 16.04 (AWS EC2 t3.large)

#### 11,001 addresses

```sh
time sudo /usr/local/bin/bitcoin-cli -conf=/etc/bitcoin/bitcoin.conf getaddressesbyaccount ""
# (omitted)
real    0m0.500s # 0.5s
user    0m0.092s
sys 0m0.160s
```

#### 111,001 addresses

```sh
time sudo /usr/local/bin/bitcoin-cli -conf=/etc/bitcoin/bitcoin.conf getaddressesbyaccount ""
# (omitted)
real    0m1.361s # 1.4s
user    0m0.168s
sys 0m0.348s
```

#### 211,001 addresses

```sh
time sudo /usr/local/bin/bitcoin-cli -conf=/etc/bitcoin/bitcoin.conf getaddressesbyaccount ""
# (omitted)
real    0m2.220s # 2.2s
user    0m0.384s
sys 0m0.532s
```

**Comment by ryanofsky** [comment]
It might be useful to test `getaddressesbyaccount` in 0.17.1 with `-deprecatedrpc=accounts`, to see if that is slow as well. 

Just comparing [`getaddressesbyaccount` in 0.16.3](https://github.com/bitcoin/bitcoin/blob/v0.16.3/src/wallet/rpcwallet.cpp#L393-L401) and [`getaddressesbylabel` in 0.17.1](https://github.com/bitcoin/bitcoin/blob/v0.17.1/src/wallet/rpcwallet.cpp#L4299-L4305), I don't see what would make the new version O(N^2), although it is returning more data so I would expect it to be somewhat slower.

If I were going to try to optimize this code, I think I might start by adding a UniValue move constructor, and pushKV overload that can move from std::string and UniValue arguments instead of copying. It looks like all this code is doing is iterating over a map and building a giant UniValue.

**Comment by MarcoFalke** [comment]
Related #14765?

**Comment by ryanofsky** [comment]
> Related #14765?

Good find, #14765 completely explains this issue. The switch from `push_back` to `pushKV` makes `getaddressesbylabel` O(N^2). Using `__pushKV` instead would fix it.

**Comment by laanwj** [comment]
This is annoying but not a blocker for 0.18.0 release imo, moving the milestone.
