### ISSUE TITLE
When to make bech32 the default -addresstype?

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#15560]
From `gmaxwell` on [IRC (line 435)](http://www.erisian.com.au/bitcoin-core-dev/log-2019-03-08.html).
> We've been able to send to bc1 addresses since 0.16.0 which was released feb 2018.
Should it be a goal for 0.19? 0.20?
Bitcoin core makes it pretty easy to get other addresses when you need them for compatiblity, fortunately.

> when satoshi completely broke compatiblity with the p2p protocol, he gave two years time for people to upgrade. On one hand, that was a much harder break, on the other hand, it as a much smaller ecosystem at that time.

> I'm somewhat disappointed to see that some parties that I've past identified as tech leaders still don't have sending support... which is an argument against rushing.
But maybe announcing a plan to default by version X might help some parties prioritize.

**Comment by instagibbs** [comment]
Might be worth figuring out which larger services/wallets cannot decode them and figuring out what the blocker there is.

**Comment by NicolasDorier** [comment]
Ledger Live https://github.com/LedgerHQ/ledger-live-desktop/issues/1842

**Comment by fanquake** [comment]
https://twitter.com/Ledger/status/1095971576229580800

> It's on our roadmap but we can't provide an ETA unfortunately. The on-device apps support bech32 but there's still back-end and front-end engineering to be done. For now you can use Electrum to enjoy bech32 on your Ledger Nano S.

**Comment by Sjors** [comment]
I think we can make it the default in 0.19, if we make it super obvious in the GUI how to get a p2sh address. Something like "Looking for an address starting with 1... or 3...? Click here. [but blah blah, most wallets can handle bech32... blah blah save fees]"

**Comment by fanquake** [comment]
Maybe something for @bitcoinops? cc @moneyball, @jamesob.

**Comment by moneyball** [comment]
I worked pretty closely with the folks at BRD, who developed the whensegwit initiative, and I know they are keen on pushing the ecosystem toward widespread adoption of bech32 addresses. The first step for any service is quite clear - supporting sending to bech32 addresses, which is relatively easy to implement and does not introduce any complications for users. As noted by @gmaxwell, Core wallet has been able to do this since v0.16, and many other wallets support this too (whensegwit.com has a list).

Nevertheless, it is still far from 100% adoption and thus any service supporting bech32 receive addresses creates a risk of user confusion if the user attempts to send funds to a Core bech32 address from a wallet that doesn't support sending to bech32 (and thus would fail for the user). Optech is planning to research this further (similar to the RBF in the Wild research) to ensure the list is as comprehensive as possible. This will give services an idea of potentially how much user confusion might be created by generated bech32 receive addresses. Optech also does proactive outreach to services that don't yet support sending to bech32 addresses.

There are several UI options a wallet can consider for bech32 receiving addresses, depending on a number of factors such as how the wallet is marketed/positioned, how sophisticated its userbase is, its ability to handle customer service requests, and its attitude toward pushing for ecosystem wide adoption.

UI options:
1. Show only backwards compatible addresses. Wait to support receiving bech32 until broader adoption. [most conservative position]
2. Show backwards compatible addresses by default. Separately show an "advanced user" option that provides sophisticated users the ability to generate a bech32 receiving address. As the user has to go out of their way to do it, the odds of them being confused if it fails and generated a customer support ticket is reduced. [fairly conservative position]
3. Show bech32 addresses by default. Separately show a "backwards compatible" option that provides an escape valve in case a user is trying to send funds from a wallet that does not yet support sending to bech32 addresses. [more aggressive position]

What is being proposed in this PR is option #3.

The team at Optech has a number of other ideas we're considering to help with adoption, and we will follow up here within a week proposing additional steps we can take to help with this. It is likely that some of our work will aid in determining which version of Core should adopt the more aggressive stance on receiving bech32 addresses.

**Comment by bitschmidty** [comment]
For testing Bech32 support across Bitcoin services, Optech's initial tests are to include:

- Does wallet allow sending to Bech32
- Which receive address types are supported 
- What is the default receive address type
- UX of each via screenshots and screen recordings 

If there is another aspect of a Bitcoin service's handling of Bech32 that would be useful, I am happy to test that as well.

**Comment by MarcoFalke** [comment]
https://whensegwit.com/ does not include wallets/exchanges that do not support sending to a bech32 address, so it seems not too useful in the context of the brainstorming in this issue.

Last time I checked, at least Gemini (exchange) would not support sending to bech32 addresses. Not sure if this changed in the meantime.

**Comment by moneyball** [comment]
@MarcoFalke See @bitschmidty's post above - we plan to do research that will identify services that do and do not support bech32. This should help with Core's decision.

**Comment by moneyball** [comment]
Also, Optech started a 24 week(!) bech32 educational campaign in this week's newsletter. https://bitcoinops.org/en/newsletters/2019/03/19/

I suspect there is a good chance that by August we'll have more information to inform the decision whether v0.19 should make bech32 the default address type.

**Comment by gmaxwell** [comment]
https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/193 < recent events

**Comment by MarcoFalke** [comment]
Many exchanges don't support it yet :(

See https://en.bitcoin.it/wiki/Bech32_adoption

**Comment by Sjors** [comment]
@gmaxwell that PR is from a year ago, but could be a useful code example.

**Comment by harding** [comment]
This was [discussed](http://www.erisian.com.au/meetbot/bitcoin-core-dev/2019/bitcoin-core-dev.2019-03-28-19.01.log.html#l-83) in the most recently weekly meeting.  My reading of the conclusion was that the project commits to switch to bech32 receiving addresses by default for the 0.20 release but will optionally switch at the 0.19 release if project members believe there is enough bech32 sending support in other programs and services at that time that the change won't be needlessly disruptive to inexperienced Bitcoin Core users.

Specifically mentioned in this PR's OP is the project announcing this planned change, but I didn't see anything in the discussion about how the project planned to make that announcement.  Maybe a sentence in the 0.18 release notes or a post to the rarely-used [bitcoin-core-dev mailing list](https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-core-dev)?

**Comment by gmaxwell** [comment]
0.18 release notes ACK from me,  likewise mailing list sounds fine.  We should mention that we'll send more announcements once we've decided on 0.19.

Should probably use language that makes 0.19 sound likely:  my expectation is that we'll do 0.19 too unless someone shows up with arguments not to, and if it sounds too much like we won't, maybe the person with the golden argument won't make it. :)

**Comment by moneyball** [comment]
FYI here is the draft Optech newsletter coverage of this issue in case anyone would like to provide feedback by end of day Monday prior to Tuesday's publication. https://github.com/bitcoinops/bitcoinops.github.io/pull/127/files#diff-6ade689824ee4c2e6d315bb25d14851aR56

**Comment by MarcoFalke** [comment]
As a low-risk first step:

* gui: Generate bech32 addresses by default #15711

**Comment by MarcoFalke** [comment]
A user in the GUI will see the tooltip right away and can choose a different address type on each occasion for each service.

Changing the default for the RPC is a bit more involved, since changing the address type is potentially no longer offered to the user on a case-by-case basis. (I think Gemini does it, but others might not or oversee it). So it needs to update the documentation, release notes, and optionally education through some optech newsletters.

**Comment by MarcoFalke** [comment]
There is a well-written section in the optech news: https://bitcoinops.org/en/newsletters/2019/04/02/#news

Would be nice if someone could copy-paste this to our `./doc/release-notes.md`.

**Comment by nopara73** [comment]
> Might be worth figuring out which larger services/wallets cannot decode them and figuring out what the blocker there is.

> Last time I checked, at least Gemini (exchange) would not support sending to bech32 addresses. Not sure if this changed in the meantime.

Recent Bech32 sendability statuses:

- February: BitcoinJ Added full segwit support (and gave out a new release in March) - https://github.com/bitcoinj/bitcoinj/pull/1563
- March: "Bitcoin Wallet" for android upgraded bitcoinj and now able to send to bech32.
- March: Gemini added bech32 support about 6 days ago: https://www.reddit.com/r/Bitcoin/comments/b66n0v/psa_gemini_is_full_on_with_native_segwit_and_uses/
- March: Blockchain.info added bech32 sendability - https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/193
- Bisq: Depends on bitcoinj, so bech32 sendability is imminent: https://github.com/bisq-network/bisq/issues/1139
- Ledger: There's an issue with a 0.1BTC bounty for bech32 sendability, someone may wants to take it: https://github.com/LedgerHQ/ledger-live-desktop/issues/1842

**Comment by harding** [comment]
I've added the note suggested by @MarcoFalke to the release notes draft: https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.18.0-Release-Notes-Draft#planned-changes

**Comment by gmaxwell** [comment]
https://github.com/LedgerHQ/ledger-live-desktop/pull/2026

**Comment by fanquake** [comment]
Native Segwit support recently became available to end users in Ledger Live Desktop as part of the [1.11.0 release](https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v1.11.0):
> 🎊 Native SegWit is now available!

> Native SegWit, also known as bech32, is a new address format for Bitcoin that is more efficient and thus reduces the requires network fees. Native SegWit addresses for Bitcoin start with bc1.

> To start using native SegWit in Ledger Live, please create a new account and transfer your Bitcoin to it.

> Not all exchanges or wallet providers support sending to bc1 addresses, therefore Ledger Live still allows you to create compatibility SegWit (3 addresses).

**Comment by bitschmidty** [comment]
Some data to help with this decision from the just launched Optech Compatibility Matrix:
https://bitcoinops.org/en/compatibility/

Most wallets/services, of the ones we tested, support bech32 sending.

**Comment by MarcoFalke** [comment]
This has missed the deadline in #15940. 

I think we can move forward with this in 0.20.0

**Comment by instagibbs** [comment]
to be clear, I think that was the intention:

> Starting with Bitcoin Core 0.20 (expected about a year after 0.18), Bitcoin Core will default to native segwit addresses

in release notes

**Comment by instagibbs** [comment]
What do we want to do about change type? Right now we do bech32 change if the wallet selected it, or if the recipient is using bech32. It might also be time to simple default to bech32, or whatever the user chooses in their conf.

**Comment by instagibbs** [comment]
Either way I think it's time, so I made a proposal PR to do so: https://github.com/bitcoin/bitcoin/pull/16884
