### ISSUE TITLE
0.18.0 rc2 Italian translation error

### ISSUE THREAD

**Issue by Amiga500** [bitcoin/bitcoin#15679]
--------------------------------------------------------------------------------------------------------

into file bitcoin/src/qt/locale/bitcoin_it.ts

word wrote wrongpriecedenza
priecedenza -> precedenza

<source>Options set in this dialog are overridden by the command line or in the configuration file:</source>
<translation>Le impostazioni sulla riga di comando o nell'archivio di configurazione hanno priecedenza su quelle impostate in questo pannello:</translation>

--------------------------------------------------------------------------------------------------------

**Comment by MarcoFalke** [comment]
Thanks for helping with translations! However, changes to translations as well as new translations are submitted to [Bitcoin Core's Transifex page](https://www.transifex.com/projects/p/bitcoin/).

Translations are periodically pulled from Transifex and merged into the git repository. See the [translation process](https://github.com/bitcoin/bitcoin/blob/master/doc/translation_process.md) for details on how this works. So we do not accept translation changes as GitHub pull requests because the next pull from Transifex would automatically overwrite them again.

**Comment by lucayepa** [comment]
Fixed on Transifex. Thanks @Amiga500 . This issue can be closed.
