### ISSUE TITLE
0 confirmations, 3 days, missing block?

### ISSUE THREAD

**Issue by wazzzup9** [bitcoin/bitcoin#15723]
So I sent 0.28btc two days ago and still 0 confirmations, what could be the issue? The transaction is the last one made at 
04-01 11:45:15
https://www.blockchain.com/fi/btc/address/3JWdqN1VRQN2SFNhoeQpgvmp4VDGXnTtJK

**Comment by lucayepa** [comment]
The transaction be004aed1f0f1754e9fdd02ea672e5db93b2a69eca429cfa5f35a701e5937b28 pays a fee of 53010 satoshis and has a size of 5349 bytes. Thus, it pays 53010/5349 = 9.91 satoshi/byte. This seems on the low side. [Here](https://bitcoinfees.earn.com/) you can see the transactions in the mempool, aggregated by fee per byte.

**Comment by MarcoFalke** [comment]
https://blockstream.info/tx/be004aed1f0f1754e9fdd02ea672e5db93b2a69eca429cfa5f35a701e5937b28 gives an eta of "Currently unavailable".

**Comment by auscash** [comment]
See also: https://blockstream.info/tx/0cd392cd6d651213872b39f0d996884e68639312ca860abee46b24d539f2f658

This is my transaction, made at night using Coinomi which has no native support for Replace-by-Fee (RBF), and neither am I going to use any ridiculous overpriced tx-boosting feature that costs more than the satoshis I wanted to move.

This is a problem in Bitcoin, an aggravating one and not necessarily the user's fault.  Bitcoin should have some type of fixed-fee DROP_TRANSACTION tx that can be sent out from any other wallet or key, something that miners would be likely to accept.  This should cause the DROP_TRANSACTION to be mined in a block, which could perhaps purge the limbo tx from the mempool.  If that happens, the new script could be read by other miners accepting the confirmed block to also purge the tx, with the desired outcome being the funds are reverted back as if it never happened in the first place.

I'd like to try and implement this feature, but there's almost always no help available and a lot of missing documentation for developers who want to contribute to Bitcoin Core or other similar projects like forks.

A brief example:

Good script and other documentation should outline the rough steps on adding a new script opcode and exactly how Bitcoin interprets scripts with a broad overview of the stack-based language.

It should contain a few concrete, simple examples, along with testing information (e.g. implement, get on regnet, write test cases and document).  It should contain information on why some opcodes are disabled and pointers to code comments on why some are now renamed and re-implemented, for example an EQUAL op now being a specific numeric EQUAL opcode, and how to think about new scripts and opcodes and whether they may pose a DoS attack risk or an unintended behavior risk.

I would contribute documentation and get on with pull requests, but there's very little to go on to get a start with.  It doesn't matter whether the pull request is rejected for any reason or the code is just rubbish; at least it would help developers get a bit of a jump start making contributions.

I hope this is interpreted as constructive criticism rather than a rant!

**Comment by MarcoFalke** [comment]
@auscash  Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or bitcoin-dev mailing list.

@wazzzup9 The transaction is now confirmed, but in the future you might use rbf to bump the tx fee if confirmation is needed in a shorter time.
