### ISSUE TITLE
wallet: Remove AvailableCoins nMinDepth argument

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#15823]
`AvailableCoins()` could be refactored to not take an `nMinDepth` argument now that coin control has a `m_min_depth` member

**Comment by MarcoFalke** [comment]
Having two ways to set this is a nice footgun

**Comment by fanquake** [comment]
How would you like to handle `listunspent` passing the `minconf` argument (as `nMinDepth`) straight into `AvailableCoins`:

https://github.com/bitcoin/bitcoin/blob/598323911e930d67e678e464353eb570ad3bf2b7/src/wallet/rpcwallet.cpp#L2797

With `nMinDepth` removed, I assume we'll need to create a `CCoinControl` object, just to set `m_min_depth`, and pass that into `AvailableCoins` rather than a `nullptr`.

**Comment by promag** [comment]
> create a `CCoinControl` object, just to set `m_min_depth`, and pass that into `AvailableCoins`

@fanquake I guess.

**Comment by amitiuttarwar** [comment]
I started looking into this & have a question about desired default behavior. Right now, `AvailableCoins` can be invoked without passing in a `CCoinControl` object, as done in `ListCoins` here: https://github.com/bitcoin/bitcoin/blob/master/src/wallet/wallet.cpp#L2348.  The function declaration in the header handles this behavior by defaulting `CCoinControl` to a `nullptr`. Having that null pointer obviously creates an issue when trying to access `m_min_depth` on coin control. 

The two options I see: 
1. Have `AvailableCoins` default to creating a new coin control. 
2. Remove the default & require the caller to create a new coin control.  
The second option seems preferable because the caller can manage memory cleanup.  There could also be other ways to handle. 

Thoughts?

**Comment by amitiuttarwar** [comment]
I started looking into this & have a question about desired default behavior. Right now, `AvailableCoins` can be invoked without passing in a `CCoinControl` object, as done in `ListCoins` here: https://github.com/bitcoin/bitcoin/blob/master/src/wallet/wallet.cpp#L2348.  The function declaration in the header handles this behavior by defaulting `CCoinControl` to a `nullptr`. Having that null pointer obviously creates an issue when trying to access `m_min_depth` on coin control. 

The two options I see: 
1. Have `AvailableCoins` default to creating a new coin control. 
2. Remove the default & require the caller to create a new coin control.  
The second option seems preferable because the caller can manage memory cleanup.  There could also be other ways to handle. 

Thoughts?

**Comment by MarcoFalke** [comment]
I wouldn't mind explicitly passing through a `const CCoinControl&` instead of a pointer (that can be null). That way coin control is exposed to all callers and they can choose to use the default values or overwrite them.

**Comment by promag** [comment]
@amitiuttarwar are you going to work on this?

**Comment by amitiuttarwar** [comment]
I would like to, but I'm off the grid until Thursday.

**Comment by jnewbery** [comment]
Concept ACK. See https://github.com/bitcoin/bitcoin/pull/15557#discussion_r271411570 for a bit more discussion/background.

**Comment by ryanofsky** [comment]
Reason for closing this?

**Comment by MarcoFalke** [comment]
Has been fixed in 00922b8720278f07a0f6e0e22b6b38356f9ee384

**Comment by jnewbery** [comment]
> Has been fixed in 00922b8

(which is PR #15906)
