### ISSUE TITLE
Bitcoin node sync only block header (not wallet)

### ISSUE THREAD

**Issue by lukehungngo** [bitcoin/bitcoin#16274]
I found out bitcoin core allow me to prune old block data, that's wonder full but not exactly what i want.

I expect a running mode that allow node to get only block header. Because, in prune mode, old data block will be deleted. Our project need all block headers data.

Do we have any running mode like that? Many thanks

**Comment by sipa** [comment]
Bitcoin Core in pruning mode will download and store all headers, and also download and verify but not store the full blocks.

If you just want the headers, this mode is overkill, but will work.

If this is not what you need, you should consider other software.

**Comment by lukehungngo** [comment]
Many thanks, i will check this again
May I ask, how much GB will this mode consumed, for current bitcoin blockchain?

**Comment by gertjaap** [comment]
In order to verify blocks, the client must keep track of the unspent coins (to ensure that a transaction is spending coins that exist, and that the transaction satisfies the conditions given to the coin). So it doesn't _just_ store blocks that you can prune - it also keeps a database of unspent coins which is a few gigabyte at present.

If you're not fully verifying data, you're essentially relying on other people (such as miners) to have done that for you.

If you want to download and verify headers only, you are essentially building on a similar foundation as SPV. You should probably look at implementations such as Electrum or Neutrino, and see if they are a fit to what you're trying to achieve.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
