### ISSUE TITLE
Bitcoin Core 0.18.0 requests access to Contacts.app and Calendar.app on macOS Mojave from a new installation on a formatted machine.

### ISSUE THREAD

**Issue by einelefantle** [bitcoin/bitcoin#16403]
Bitcoin Core 0.18.0 requests access to Contacts.app and Calendar.app on macOS Mojave from a new installation on a formatted machine.

 I am certain I've never seen this happen before.

![Screen Shot 2019 07 16](https://user-images.githubusercontent.com/52983118/61341016-1caa0a80-a81b-11e9-8f22-6757e0b4cbe2.png)
![Screen Shot 2019-07-16](https://user-images.githubusercontent.com/52983118/61341017-1caa0a80-a81b-11e9-9a26-6ba50973aab4.png)

 Format macOS, install Mojave, install Bitcoin Core 0.18.0

 Bitcoin Core 0.18.0 from https://bitcoincore.org/en/download/ **verified** with SHA256.

 macOS Mojave on MacBook Air.

**Comment by MarcoFalke** [comment]
Can anyone reproduce this?

**Comment by fanquake** [comment]
I did some experimenting. It looks like if an application requests access to the users home directory, there's a potential for these popups to (sporadically?) appear. Note that this is definitely not something that we're doing, it's triggered by macOS.

I've been able to recreate the behavior using the v0.18.0 dmg from bitcoincore, and a macOS 10.14.5 system. On startup if you choose to use a custom data directory, you may get the following popups:

![calendar](https://user-images.githubusercontent.com/863730/61423027-c8994600-a940-11e9-968a-81b653c67cf2.png)
![contacts](https://user-images.githubusercontent.com/863730/61423034-cafba000-a940-11e9-9add-9b891275bb53.png)

and see Bitcoin Core listed under the apps that have requested access to either of those things in `Privacy`:
![privacy](https://user-images.githubusercontent.com/863730/61423050-df3f9d00-a940-11e9-97a9-0674dc9ffdb7.png)

I've found reports of similar behavior from other (non-Qt) apps as well, so not sure if this is something we can "fix".

Atom - [macOS Mojave: Atom requests access to Contacts and Calendars ](https://github.com/atom/atom/issues/17687)
VsCode - [macOS Mojave: VSCode requests access to Contacts and Calendars](https://github.com/Microsoft/vscode/issues/55236)
IntelliJ WebStorm - [WebStorm requests access to contacts from particular user on macOs Mojave ](https://youtrack.jetbrains.com/issue/IDEA-194789)

**Comment by MarcoFalke** [comment]
There are some explanations and workarounds:

https://discuss.atom.io/t/why-does-macos-say-that-atom-wants-to-access-my-calendar-contacts-photos-etc/59291

**Comment by fjahr** [comment]
Since this seems to only be an issue when the home directory is chosen as the custom data-dir I think the easiest "catch-all" solution is to add some kind of hint along with the custom data-dir option. Something like "This may require additional permissions depending on the location you choose and your operating system." Given that users could choose any kind of obscure location for their data dir (like the actual contacts folder) I think there will always be a chance that users are prompted for additional permissions. On the other hand, Contacts/Calendars will still be confusing to some people because they don't think of them as folders in their file system. But for those users, the only further help I can think of is adding install notes or an faq entry somewhere easy to find, something along the lines of the atom forum post.

I am not a macOS developer but since the IDE developers have not brought up this solution I suspect there is no way to generally exclude access to specific subfolders on the system, which would be the cleanest solution, of course.

**Comment by MarcoFalke** [comment]
Not sure what to do here. Can this be closed?

**Comment by fanquake** [comment]
I think so. There's not really anything for us to solve here, and this is well outside an actual being an actual bitcoin issue.
