### ISSUE TITLE
build: configure using depends by default if config.site exists 

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#16692]
Mentioned by ryanofsky in #16691:

> Also, I think it would be a good idea that if a depends/${host}/share/config.site file exists, bitcoin configure script would just use depends/$(host) as the default --prefix value instead of /usr/local.

> This way using depends would just require running 'make -C depends; ./configure; make` without needing to figure out the host triple or look at depends output.

**Comment by hebasto** [comment]
#14959 could be related:
> Why can't `./configure` without any options find out self-compiled dependencies in the `depends/` directory?

**Comment by practicalswift** [comment]
Concept ACK

**Comment by ryanofsky** [comment]
> If this feature will be implemented what could be the way to force build against system packages?

Maybe an `--enable-depends`/`--disable-depends` configure option where `no` would disable use of depends config.site settings, `yes` would require them, and `auto` would use them if they exist for the current build/host pair

**Comment by willcl-ark** [comment]
@fanquake @hebasto mentions [here](https://github.com/hebasto/bitcoin/pull/10#issuecomment-1530100470) that:

> I no longer consider this feature as a useful one due to the case, which is actually an everyday workflow for me, when the user has depends built for many hosts simultaneously.

Intuitively I would estimate the number of users building depends for multiple hosts to be significantly less than the number building for their own host (especially since we have https://github.com/bitcoin/bitcoin/pull/26834). 

IMO ideally the easiest option should be geared towards new users who should only have to run `make -C depends; ./configure; make` to get a working version of Bitcoin Core with all the dependencies, rather than requiring them to modify the build options on the command line or export variables etc.

@hebasto might it not make sense to detect your host triplet and build with depends automatically only if that host triplet is found? In any other case you are cross-compiling and will be setting `CONFIG_SITE` anyway. ISTM that this would still work with @ryanofsky's suggestion of an `auto` default mode for a `--en/disable-depends` flag
