### ISSUE TITLE
feature_block and p2p_permissions time out

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#16794]
Current master, on travis:

https://travis-ci.org/bitcoin/bitcoin/builds/578612449
https://travis-ci.org/bitcoin/bitcoin/builds/578444718
https://travis-ci.org/bitcoin/bitcoin/builds/577975853

Reported by @mzumsande in https://github.com/bitcoin/bitcoin/pull/16756#issuecomment-526748925

**Comment by ryanofsky** [comment]
I had to bump the feature_block.py timeouts and also add a syncwithvalidationinterfacequeue call in
https://github.com/bitcoin/bitcoin/commit/33b642725c69e198779e6f910986f4d7776648dd#diff-3c4697a632e54ae2c6e68e0159ec2234 from #10102 because the BlockConnected notifications are a lot slower in that PR.
