### ISSUE TITLE
OSX: Bad kerning in disk image background

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#16836]
The background image generated by `make deploy` for our OSX disk image has bad kerning at least for the OSX version I tested.

![Screen Shot 2019-09-09 at 12 57 33 PM](https://user-images.githubusercontent.com/3445290/64551081-d2796d00-d323-11e9-8b42-2ccb8d4238b7.png)

Software specs:
```
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G87
```

**Comment by MarcoFalke** [comment]
Is this with gitian or a native build?

**Comment by dongcarl** [comment]
> Is this with gitian or a native build?

Native build, perhaps we don't care that much about the disk image for native builds?

**Comment by fanquake** [comment]
@dongcarl Do you have any more info? I have never seen this issue locally.

**Comment by jonasschnelli** [comment]
Looks like the @2x image is fine (retina/HiDPI). Can you confirm @dongcarl ?

**Comment by za-kk** [comment]
> Looks like the @2x image is fine (retina/HiDPI). Can you confirm @dongcarl ?

Tested this issue using a retina display Macbook Pro running the same software specs, no kerning on my side which suggests the @2x image works as intended.

<img width="542" alt="bitcoin core" src="https://user-images.githubusercontent.com/31032215/65371043-6833c700-dc57-11e9-8c18-2e7a2f6cb452.png">

I also get the kerning if i convert manually using
`rsvg-convert contrib/macdeploy/background.svg -f png -d 36 -p 36 -o test.png
`

but not if i convert @2x manually using 
`rsvg-convert contrib/macdeploy/background.svg -f png -d 72 -p 72 -o test.png
`


Software specs:

```
ProductName:    macOS Mojave
ProductVersion: 10.14.6
BuildVersion:   18G87
```

**Comment by za-kk** [comment]
> Looks like its related to the `width="1000pt" height="640pt"` part in the `<svg>` tag (changing from `pt` to `px` makes the kerning looks good, but unsure about the output image size).

@jonasschnelli I've been playing around with this issue and as you mentioned changing from `pt` to `px` seems to solve the kerning issue. 

However when using `px` instead of `pt`, the png outputs from the `rsvg-convert` seem to create the exact same file (regardless of the change in dpi) and therefor having the two different image output files (`background.tiff.png` and `background.tiff@2x.png`) would be pointless.

A potential solution would be to have two different `background.svg` files for each image resolution, however a solution that keeps it confined to one `background.svg` would seem more appropriate.

I'm willing to take on fixing this issue if nobody else already has, not sure of the best solution yet and your thoughts on this would be appreciated. 

Also I'm fairly new around here so apologies if i haven't followed correct procedure or have put this in the wrong place (working my way through the contributing guide)

**Comment by dongcarl** [comment]
I've looked into this issue some more and provided upstream with a minimal reproducer: https://gitlab.gnome.org/GNOME/librsvg/issues/520

It appears to be an issue that only occurs on OSX.

**Comment by dongcarl** [comment]
Small update: seems to be a pango issue https://gitlab.gnome.org/GNOME/pango/issues/422

**Comment by fanquake** [comment]
I've removed "Good first issue" and added upstream. I don't think fixing this a high priority.

**Comment by hebasto** [comment]
Is this still an issue?
