### ISSUE TITLE
Better FreeBSD documentation

### ISSUE THREAD

**Issue by emilengler** [bitcoin/bitcoin#16846]
**Is your feature request related to a problem? Please describe.**
The current FreeBSD documentation is very poor and only helps to compile a minimal version

**Describe the solution you'd like**
Could someone with a good understanding of FreeBSD update it?

**Describe alternatives you've considered**
Ports

**Comment by steverusso** [comment]
> The current FreeBSD documentation is very poor ...

@emilengler can you elaborate on how so?

> ...  and only helps to compile a minimal version

Bitcoin Core can be built in different ways to fulfill different purposes, so the documentation for a minimal version should probably _remain_ in this repository, while the FreeBSD community assumes responsibility for more in-depth guides maintained _outside_ of this repository. For example, as I've tried to do with [this](https://freebsd.sh/bitcoin/bitcoin-core/).

**Comment by emilengler** [comment]
@stevenroose It doesn't show how to compile Bitcoin Core with a wallet and the GUI.
Also build guides should cover who to build it with no extra configure arguments needed in my opinion

**Comment by steverusso** [comment]
> It doesn't show how to compile Bitcoin Core with a wallet ...

I might be missing something here, but the current FreeBSD [build guide in this repo](https://github.com/bitcoin/bitcoin/blob/master/doc/build-freebsd.md) **does in fact provide the instructions for building with a wallet.** It shows [how to build BerkleyDB](https://github.com/bitcoin/bitcoin/blob/master/doc/build-freebsd.md#building-berkeleydb) and it shows [how to configure with wallet functionality](https://github.com/bitcoin/bitcoin/blob/master/doc/build-freebsd.md#building-bitcoin-core) under the section titled "With Wallet:".

> It doesn't show how to compile Bitcoin Core with ... the GUI.

Official FreeBSD does not come with a desktop. Users of course have the option to install one, such as XFCE, but it is primarily (and officially) a server oriented OS, so it wouldn't make much sense to include GUI build instructions because you'd have to include instructions on how to install a desktop first.

**Comment by emilengler** [comment]
Oh forget this with the wallet...
Debian also doesn't come with a GUI, why is it included there?
Also isn't a pure server OS.
According to freebsd.org:
> FreeBSD is an operating system used to power modern servers, **desktops**, and embedded platforms.
There are also people who run X apps over SSH on a server

**Comment by steverusso** [comment]
Ok, so would it be fair to re-summarize your issue as follows?
* include GUI build instructions for FreeBSD

---

> Debian also doesn't come with a GUI, why is it included there?

Are you referring to [this](https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#ubuntu--debian), the _**Ubuntu**_ and Debian build instructions, Ubuntu being an OS that is shipped with a desktop environment? If so, then I'd guess that that is the reason why GUI build instructions are "included there."
