### ISSUE TITLE
CBloomFilter: Missing updateemptyfull?

### ISSUE THREAD

**Issue by alexzk1** [bitcoin/bitcoin#16886]
On processing command filteradd (if (strCommand == NetMsgType::FILTERADD)) in net_processing.cpp  it does not call pfilter->UpdateEmptyFull() while command filterload do that. Is it bug?

**Comment by theStack** [comment]
It's not a bug, but rather a missed performance improvement: the purpose of `CBloomFilter::UpdateEmptyFull()` is to set the flags `isEmpty` (filter is all zero-bits) and `isFull` (filter is all one-bits) which in turn are checked in the in-set function `CBloomFilter::contains()` to avoid unnecessarily wasting time for those two corner-cases.
Since the `CBloomFilter::insert()` operation could lead to a full bloom filter, it makes in my opinion perfect sense to update the `isFull` flag after via calling `UpdateEmptyFull()`.

**Comment by alexzk1** [comment]
Guess, UpdateEmptyFull must be private method and called from insert/add/copy filter from inside class CBloomFilter. That could make impossible such "forgot".

**Comment by promag** [comment]
@alexzk1 note that `insert()` is called in a loop so `UpdateEmptyFull` would be called unnecessarily.

**Comment by alexzk1** [comment]
> @alexzk1 note that `insert()` is called in a loop so `UpdateEmptyFull` would be called unnecessarily.

Shouldn't it be for each insert ? As I recall inserting into full filter is invalid, so any way must check if full prior next insert. But I can be wrong about.

**Comment by theStack** [comment]
> > @alexzk1 note that `insert()` is called in a loop so `UpdateEmptyFull` would be called unnecessarily.
> 
> Shouldn't it be for each insert ? As I recall inserting into full filter is invalid, so any way must check if full prior next insert. But I can be wrong about.

Note that explicitely keeping track of whether a filter is full or empty is not necessary for correctness, but is only an optimization ("to avoid wasting cpu", as the comment for the update function in `bloom.h` puts it), introduced with commit 37c6389c5a0ca63ae3573440ecdfe95d28ad8f07. Inserting into a full filter is not invalid, but rather a waste of time -- since all bits are already set, setting any bit again doesn't change the state.

**Comment by theStack** [comment]
Considering that the primary point of introducing those empty/full-flags was not optimization, but a covert fix for CVE-2013-5700 (see gmaxwells comments about commit 37c6389: https://github.com/bitcoin/bitcoin/issues/18483#issuecomment-608224095 and https://github.com/bitcoin/bitcoin/pull/9060#issuecomment-257749165), I think this issue can be closed.
