### ISSUE TITLE
Misleading description of useLegacyAddress checkbox

### ISSUE THREAD

**Issue by andronoob** [bitcoin/bitcoin#16924]
I see that `legacy` means `P2PKH` in both command line options and RPC help info:
```
-addresstype
What type of addresses to use ("legacy", "p2sh-segwit", or "bech32", default: "p2sh-segwit") 
```
```
getnewaddress ( "label" "address_type" )
...
2. address_type    (string, optional, default=set by -addresstype) The address type to use. Options are "legacy", "p2sh-segwit", and "bech32".
...
```

The useLegacyAddress checkbox describes itself as “Generate legacy address” - however, it actually makes the wallet GUI generate “p2sh-segwit” address for the user if it's checked.

**Comment by emilengler** [comment]
The p2sh segwit addresses are legacy. They exist since 2012(?) so you probably mean the `1` addresses. I see no point why this should be supported.

**Comment by sipa** [comment]
@emilengler "legacy" in the context of address types means p2pkh, nothing else.

Your opinion on whether they should be supported is a distinct issue (about that: since p2sh-p2wpkh is more efficient than p2pkh, it should probably be preferred if we'd ever decide to stop distinguishing between the two).
