### ISSUE TITLE
macOs: "test_bitcoin-qt -platform cocoa" no longer works

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#17013]
As of v0.18.1 I can use `test_bitcoin-qt -platform cocoa` to run GUI tests; this opens and closes a regtest GUI a bunch of times.

As of master (6e4f6553913978fcdddba30e0bb6f97edcb12e80) it seems to ignore the `-platform cocoa` and just run the test as with `minimal`.

As seen on macOS 10.14.6. Git bisect blames a2714a5c69f0b0506689af04c3e785f71ee0915d in #16578 `Do not pass in command line arguments to QApplication` (@achow101, @ryanofsky)

**Comment by achow101** [comment]
You can use the `QT_QPA_PLATFORM` environment variable to set that instead.

**Comment by MarcoFalke** [comment]
I use `QT_QPA_PLATFORM=wayland` and it still works just like before

**Comment by MarcoFalke** [comment]
Should this workaround be mentioned in the release notes?

**Comment by ryanofsky** [comment]
For reference my earlier comment is: https://github.com/bitcoin/bitcoin/pull/16578#issuecomment-530562989.

I think the easiest fix would be to update the [instructions](https://github.com/bitcoin/bitcoin/blob/2324aa1dc409e9496b7083aaef5fcb20849f33c0/src/qt/test/wallettests.cpp#L126-L128) to use environment variables instead of command line arguments.

```sh
QT_QPA_PLATFORM=xcb src/qt/test/test_bitcoin-qt
QT_QPA_PLATFORM=windows src/qt/test/test_bitcoin-qt
QT_QPA_PLATFORM=cocoa src/qt/test/test_bitcoin-qt
```

I think this will just require replacing [`setenv`](https://github.com/bitcoin/bitcoin/blob/2324aa1dc409e9496b7083aaef5fcb20849f33c0/src/qt/test/test_main.cpp#L66) with:

```c++
if (getenv("QT_QPA_PLATFORM") != nullptr) setenv("QT_QPA_PLATFORM", "minimal", 0);
```

**Comment by Sjors** [comment]
Using `QT_QPA_PLATFORM=cocoa` works for me as well. Changing the instructions (also those printed by the `test_bitcoin-qt` command) seems like a good solution.

**Comment by ryanofsky** [comment]
Oh, I guess checking `getenv("QT_QPA_PLATFORM") == nullptr` is not necessary because the [`setenv`](https://github.com/bitcoin/bitcoin/blob/2324aa1dc409e9496b7083aaef5fcb20849f33c0/src/qt/test/test_main.cpp#L66) override argument is 0. This might be needed for the windows [`_putenv_s`](https://github.com/bitcoin/bitcoin/blob/2324aa1dc409e9496b7083aaef5fcb20849f33c0/src/qt/test/test_main.cpp#L64) call above, though
