### ISSUE TITLE
Unit test logs should be written to build path, not source path

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#17224]
When doing out-of-tree builds it's not expected that the build (or tests) clutter the source path. All build output should be written to the build path (the current directory when `configure` is run) and subdirectories of that.
(*theoretically* it should even be possible to have the source on a read-only mount, but that's not really important imo, the point is to not clutter the git repository with build output)

However, after running `make check` there will be a while slew of *.log files in the source directory:
```bash
bitcoin$ ./autogen.sh
bitcoin$ make build
bitcoin$ cd build
bitcoin/build$ ../configure ...
bitcoin/build$ make check
bitcoin/build$ cd ..
bitcoin$ ls src/test/*.log
src/test/addrman_tests.cpp.log            src/test/compress_tests.cpp.log         src/test/netbase_tests.cpp.log          src/test/sigopcount_tests.cpp.log
src/test/allocator_tests.cpp.log          src/test/crypto_tests.cpp.log           src/test/net_tests.cpp.log              src/test/skiplist_tests.cpp.log
src/test/amount_tests.cpp.log             src/test/cuckoocache_tests.cpp.log      src/test/pmt_tests.cpp.log              src/test/streams_tests.cpp.log
src/test/arith_uint256_tests.cpp.log      src/test/dbwrapper_tests.cpp.log        src/test/policyestimator_tests.cpp.log  src/test/sync_tests.cpp.log
...
```
Either these files should be written to a temporary path (like the other test output), or to the build directory.

**Comment by sadrasabouri** [comment]
@laanwj Hi.
I searched the code for this issue and i wonder if i should take this actions:

1. In [Make.test.include](https://github.com/bitcoin/bitcoin/blob/master/src/Makefile.test.include#L87) changing all `test/...` to `../build/test/...` which seems not to be efficient :(.
OR

2. In Makefile:line 2241
`if test -f "./$$f"; then dir=./;			\
elif test -f "$$f"; then dir=;				\
else dir="$(srcdir)/"; fi;				\
tst=$$dir$$f; log='$@';`
I think we should change `$(srcdir)` here to build directory so that test logs will save in build sub directories which seems much better.

**Comment by laanwj** [comment]
> In Make.test.include changing all test/... to ../build/test/... which seems not to be an efficient solution :(.

I think that would be incorrect. The source should stay in the source path.

> I think we should change $(srcdir) here to build directory so that test logs will save in build sub directory which seems much better.

Yes, I think that would be better. The idea is to get the `.log` files to be written somewhere else, but keep everything else the same.

**Comment by sadrasabouri** [comment]
Where can i change this?
It seems this file (`Makefile` in `src/`) is created after `make` and does not exist before making process.

**Comment by brakmic** [comment]
Hi,

After some investigation and reading and trying out [various](https://www.gnu.org/software/automake/manual/html_node/Scripts_002dbased-Testsuites.html#Scripts_002dbased-Testsuites) [Makefile](https://www.gnu.org/software/automake/manual/html_node/Parallel-Test-Harness.html) [settings](https://www.gnu.org/software/automake/manual/html_node/Overview-of-Custom-Test-Drivers-Support.html), I think I've found the reason why the logs always land in tests directory.

It has to do with the fact that *autogen.sh* is automatically generating *test-driver* in build/aux. 

test-driver itself has an option, **--log-file**, but because there is currently no way to access it before the compilation is kicked off, the settings fall back to their default: generate log files in current dir.

Here's the snippet of test-driver's params:

```shell
while test $# -gt 0; do
  case $1 in
  --help) print_usage; exit $?;;
  --version) echo "test-driver $scriptversion"; exit $?;;
  --test-name) test_name=$2; shift;;
  --log-file) log_file=../src/logs/$2; shift;;
  --trs-file) trs_file=$2; shift;;
  --color-tests) color_tests=$2; shift;;
  --expect-failure) expect_failure=$2; shift;;
  --enable-hard-errors) enable_hard_errors=$2; shift;;
  --) shift; break;;
  -*) usage_error "invalid option: '$1'";;
   *) break;;
  esac
  shift
done
```

Further down in its code there is also a line where the logs get written.

```shell
# Test script is run here.
"$@" >$log_file 2>&1
```

I've seen some projects [keeping the test-driver under revision control](https://salsa.debian.org/debian/libpqxx/commit/bdb2443f8b5a1f624965cceede0e64c28277aab7), because they prefer to build & configure it without autogen.sh. Maybe this strategy could be applied here as well? Just in case it's fitting to the overall architecture, of course.

Regards,

**Comment by laanwj** [comment]
@brakmic thanks for the thorough investigation!

**Comment by glaksmono** [comment]
Anyone is working on this? Otherwise, I would like to take a stab on it

**Comment by fanquake** [comment]
> Anyone is working on this? Otherwise, I would like to take a stab on it

@glaksmono Feel free to work on it.

**Comment by glaksmono** [comment]
hey @fanquake, @laanwj,

Should we make a temp folder under `./tests/temp` or `./src/tests/temp` for all of the log files?

Thoughts?

**Comment by MarcoFalke** [comment]
Just putting them in $build_patch/src/test/ should be enough, no?

**Comment by yancyribbens** [comment]
This issue looks likes it's been around for a while so I thought i'd take a stab at it.  Created a PR here: https://github.com/bitcoin/bitcoin/pull/19385.  @MarcoFalke I didn't see a simple way to use $build_path.  Any idea where $build_path is defined?

**Comment by MarcoFalke** [comment]
Not sure how automake works, but there should be a symbol `abs_top_builddir` somewhere, which is the build path

**Comment by yancyribbens** [comment]
This issue has been around for a while so I thought I'd take a stab at it.   @MarcoFalke thanks for the suggestion about using `abs_top_builddir`.

**Comment by yancyribbens** [comment]
@MarcoFalke Sorry for the confusion with the comments.  I deleted my comment and in the 10 seconds it took me to write a new comment you replied xD

**Comment by yancyribbens** [comment]
@MarcoFalke could we move the discussion to the PR?

**Comment by Psycho-Pirate** [comment]
Is this issue fixed by @yancyribbens PR? I would like to work on this if something else needs to be done.

**Comment by MarcoFalke** [comment]
I think this can be closed now?
