### ISSUE TITLE
~1sec latency on received/send transactions

### ISSUE THREAD

**Issue by Devicore** [bitcoin/bitcoin#17222]
Hello,

I am on Ubuntu 16.04, with the latest version of Bitcoin Core, synced and working.

I would like to know why is there a little delay of approximately 1 sec, sometimes more, before a received transaction appear on the console when we run for instance `bitcoind -printoconsole`, if I check the tx on blockchain.com for instance, I can see that the transaction were received 1 or 2 sec before I even see it on my node, why is there a delay ? I have try on another ubuntu server with a super fast connection and it's the same thing. By the way, it's the same thing when I send a Tx, it's submitted and appear on the network 1-2 secs after.

So my question is why is there such a delay even on a node ? Is it possible to reduce it ? 

Thanks in advance !

**Comment by sipa** [comment]
No, transactions are relayed with an intentional delay to reduce the ability for attackers to spy the network for transaction origin. You cannot fix this on your side, as it depends on others giving you transactions quickly, which the network is simply intentionally not doing.

General questions about Bitcoin's protocol are best asked on https://bitcoin.stackexchange.com.
