### ISSUE TITLE
meta: Good first issue boilerplate

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#17317]
Good first issues seem to attract new contributors, but often the contributors lack the motivation to think about the changes and put effort into their contribution. Also, the most common reply to a good first issue is "Can I work on this?".

So I suggest that every good first issue has a "Requirement", e.g.

* "Strong background in C++11 std::thread"
* "Experienced Qt5 GUI developer and async GUI design"
* "Basic understanding of Bitcoin mining and the Bitcoin Core rpc interface"

And finally a section like this:

### Want to work on this issue?

Go ahead, there is no need to ask for permission. Anyone is free to contribute, and you are welcome to ask for help. ... (Maybe a link to contributing.md)

**Comment by MarcoFalke** [comment]
It could be done as an issue template: https://github.com/bitcoin/bitcoin/tree/master/.github/ISSUE_TEMPLATE

**Comment by fjahr** [comment]
I think the "Can I work on this?" is also about "reserving" the issue. As a new contributor who is doing this after hours, it could take several days to do something that a seasoned contributor could do in <1h. But everyone has to start somewhere so this is ok. I would actually encourage first-timers to indicate they are working on something and report more on their progress if they are stuck, so I like encouraging them to ask for help. I can imagine that sometimes it seems like a lack of effort when they are actually just overwhelmed.

I also like the "Requirement" as a hint of what skills could be useful so that newcomers don't dive into something that turns out to be too complicated for them. However, I would frame it a little softer as something like: "It would be very helpful if you have experience with...".

Actually, the main skill lacking in new contributors that I have seen (in my short time) was using Git properly. Since there are sections on that in contributing.md I would include it as well.

**Comment by michaelfolkson** [comment]
Ok, I will and I'll run it pass @fjahr before opening a PR.

**Comment by amitiuttarwar** [comment]
agree with @fjahr & @michaelfolkson about
- encouraging first timers to communicate starting / progress / being stuck 
- listing skills required to solve the problem is helpful, framing it as a requirement can unnecessarily discourage

@michaelfolkson I'm also interested in providing feedback. feel free to tag me on the PR

**Comment by emilengler** [comment]
"Requirement" looks a bit to "strict" for me.
I believe that something like "Useful skills" is a better term.
