### ISSUE TITLE
Uninitialized secp256k1 context in fuzzer

### ISSUE THREAD

**Issue by JeremyRubin** [bitcoin/bitcoin#17334]
I'm working on a branch that is pretty far away from the pubkey stuff, but now the fuzzer tests produce the following errors:

https://gist.github.com/JeremyRubin/68897819c3dc047e1da15fbb54dd7a1c

I'm *pretty sure* my code isn't causing it.

@practicalswift

**Comment by fanquake** [comment]
This might have been fixed in #17274.

**Comment by JeremyRubin** [comment]
Should be it! Closing for now

**Comment by practicalswift** [comment]
@JeremyRubin Yes, this is fixed by #17274. I was actually very glad to see this bug report: that means that I'm not the only one fuzzing. You're the first one noticing AFAIK :)

Some day I hope that fuzz testing will be a first-class citizen in Bitcoin Core testing: on par with the unit tests or functional tests. I'll work towards that goal :)
