### ISSUE TITLE
Verification progress tests

### ISSUE THREAD

**Issue by darosior** [bitcoin/bitcoin#17352]
While trying to test #17328, I noticed that:
1) We don't test the verification progress (`verificationprogress` field in `getblockchaininfo`)
2) The verification progress would always be `1` on regtest (even during IBD), both in the `verificationprogress` field of `getblockchaininfo`, or in the "new best" log message. *(I tested this with 3 nodes, node 1 being the transaction spammer, node 2 the miner, node 3 the logger in both normal and blocksonly modes)*

Is 2) due to some regtest special behavior I don't know about ?
 .1) is not that bad since it seems to work well in main and test networks, but might be a good first issue ?

**Comment by laanwj** [comment]
I think I'm starting to understand why, historically, there are no tests for this. The "verification progress" was added as at most a heuristic, and the tests should not set one particular way of estimating progress in stone as it might be improved or changed.

A sanity check couldn't hurt, I guess.

**Comment by sipa** [comment]
It doesn't work for regtest because no statistics on transaction rate are known for regtest. It is not possible for the current approach to work on regtest.

Just to clarify: progress is computed as the ratio between the total number of processed transactions and an estimate of the total number of transactions in the chain. The latter relies on statistics.

**Comment by darosior** [comment]
Ok thank you for the clarification ! I think I can close this then.
