### ISSUE TITLE
Improve Running CI Locally

### ISSUE THREAD

**Issue by JeremyRubin** [bitcoin/bitcoin#17372]
One issue that can come up when running CI locally is that docker links directly to the current working directory. This has two unsavory side effects:

1) When docker writes the files, it writes them as root, preventing local building 
2) It blows away your current build

**Comment by MarcoFalke** [comment]
Please use the ci system locally only at your own risk, it might eat your laptop. ;)

Running the ci completely in a docker, without leaving any traces on the host system is not possible right now because the ccache and depends dir needs to be propagated back and picked up by the host for caching.

See #17423

**Comment by JeremyRubin** [comment]
> Please use the ci system locally only at your own risk, it might eat your laptop. ;)

If that's actually the standard of code we have in there right now.... yikes! Maybe we should have some stronger warnings or something...

**Comment by MarcoFalke** [comment]
The code was initially written for travis (in the `.travis.yml`), and travis machines have no concerns. Then it was gradually moved into separate shell scripts and finally into the `ci` folder. 

I will try to document the expectations a bit better.
