### ISSUE TITLE
build: Create test utility library from src/test/util/

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#17401]
The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

### Useful skills

 * Experience with autotools build systems

### Task

The test utility library in https://github.com/bitcoin/bitcoin/tree/master/src/test/util is currently only a folder and each module in there is compiled for each target that uses it. For example, `setup_common` is compiled 27 times (for the fuzz suite) and another 3 times for the other tests (bench, unit test, gui). To speed up the compilation and clarify build dependencies, this folder should be transformed into an actual library.

Because our test binaries should test as much as possible, this library may depend on any Bitcoin Core library or third party library (except boost-unit-test). It should be built when at least one target that requires it is built, skipped otherwise.

### Want to work on this issue?

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by brakmic** [comment]
Hi,

I've started working on this. Not sure if I understood the goals correctly (*and if I should write anything here*), but I can at least generate a static lib based on src/test/util sources. I've also removed the many src/util/test headers from *Makefile.test.include*, because I don't need them anymore to compile individual tests. 
Instead, I've put into each test's LDADD the libtest_util.a, that is *$(LIBTEST_UTIL)*.  However, I'm not quite sure if this is the correct way to do it.

There's also a new [Makefile.test_util.include](https://github.com/brakmic/bitcoin/blob/test-util-lib/src/Makefile.test_util.include). 

Not sure if another Makefile would be allowed, but before I expand the already existing (and complex) ones, I think a small, separate Makefile is better.

Here the link to the commit in my forked repo: https://github.com/brakmic/bitcoin/commit/3f4b5e3a0b93c6b528bf707fd38eb63c0e29efa9

I'm working on macOS Catalina 10.15.1 with clang 9.0.0. 

Regards,

**Comment by MarcoFalke** [comment]
Overall looks good, but the bench and gui tests are not using it?

**Comment by brakmic** [comment]
Thanks!
I've included the missing references in bench & qttest.

Here's the commit: https://github.com/brakmic/bitcoin/commit/03002e3683c05dbd769efc7b2df206e0798bab3a

I've compiled bench/qttest and could execute them.

**Comment by brakmic** [comment]
Oops, have forgotten to remove TEST_BITCOIN_H. Will do it now.

**Comment by brakmic** [comment]
Done. 

https://github.com/brakmic/bitcoin/commit/10c270bf5b0d5f444f6178592330320710b27261

**Comment by MarcoFalke** [comment]
Ok, looks like you can open a pull request to get more review on it :+1:

**Comment by brakmic** [comment]
Many thanks. Will look in contribution guide first. ;)
