### ISSUE TITLE
Run tests in memory sanitizer

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#17460]
We run the tests in the thread (and other sanitizers), see `git grep sanitizer ./ci`, but not in the memory sanitizer. This seems like it could be improved. See e.g. #17449

**Comment by MarcoFalke** [comment]
On a second thought, it might be better to just run with valgrind: https://github.com/bitcoin-core/secp256k1/pull/687#issuecomment-551794708

**Comment by practicalswift** [comment]
@MarcoFalke I've tried to add Valgrind to our Travis build before: Valgrind is very accurate but  and the problem is that Valgrind is super super super slow. Running the unit tests and the functional tests under Valgrind takes hours :(

Perhaps DynamoRIO's Dr. Memory could be a faster option. I haven't investigated that option yet.

Another alternative could be to run a subset of the tests under Valgrind and then use MSAN as a complement. With MSAN running all the tests including those excluded from the Valgrind run due to being too slow.

**Comment by MarcoFalke** [comment]
Maybe running a single functional test (and/or unit test) in valgrind would be a good start. #17449 would have been caught when Bitcoin Core just boots up on mainnet.

**Comment by practicalswift** [comment]
> Maybe running a single functional test (and/or unit test) in valgrind would be a good start.

Agreed: to start with something under `valgrind` would be better nothing :)

> #17449 would have been caught when Bitcoin Core just boots up on mainnet.

Do you mean "boots up on mainnet" as in when IBD is finished on mainnet?

FWIW, I've only gotten `valgrind` to warn about the #17449 case when `WarningBitsConditionChecker::Condition(…)` is being run. That happens in `UpdateTip` given that we're done with IBD.

Perhaps one would expect `valgrind` to warn earlier in the execution, such as when `{CreateChain,Select}Params(…)` is run. But that is not the case :)

**Comment by elichai** [comment]
https://github.com/bitcoin/bitcoin/pull/17568#issuecomment-558026462
