### ISSUE TITLE
Gitian (windows) results not deterministic when run on aarch64

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#17468]
Gitian can be run on aarch64, see #17409. However, the results are not deterministic.

I can't upload the full result, so here is the diffoscope (remove the .docx extension to extract):

[diffoscope.txt.tar.xz.docx](https://github.com/bitcoin/bitcoin/files/3843486/diffoscope.tar.xz.docx)

**Comment by MarcoFalke** [comment]
Depends seem to match. Here is the diffoscope html


[diffoscope.html.txt](https://github.com/bitcoin/bitcoin/files/3843667/diffoscope.html.txt)

**Comment by MarcoFalke** [comment]
I did a second build of windows on aarch64 and at least the results match the previous aarch64 run

**Comment by laanwj** [comment]
Which gcc cross-compiler package are you using on aarch64?

`g++-8-x86-64-linux-gnu` or `g++-7-x86-64-linux-gnu`? I guess the latter, because the descriptor uses the default native gcc compiler on bionic?

on aarch64:
```
$ x86_64-linux-gnu-g++-7 --version
x86_64-linux-gnu-g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
$ x86_64-linux-gnu-g++-8 --version
x86_64-linux-gnu-g++-8 (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0
```

on amd64:
```
$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
```

(it's slightly inconsistent that we use gcc 7 for x86 builds and gcc 8 for the rest, but okay)

**Comment by MarcoFalke** [comment]
Let's focus on guix
