### ISSUE TITLE
rpc: Removing g_rpc_node

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#17548]
`g_rpc_node` is an alias for the current node context. It would be nice to pass in the node context into each rpc method somehow and remove the g_rpc_node global.

Not sure how to do this, but here is a hint: https://github.com/bitcoin/bitcoin/pull/17407#discussion_r346488421

> One way `g_rpc_node` might go away is adding a `std::any context` member to `JSONRPCRequest` assigned to the node context, and having functions like `EnsureMempool` take `request` arguments and pull the context from the request.

**Comment by ryanofsky** [comment]
Adding a `std::any` or `void*` or similar `context` member to [`struct JSONRPCRequest`](https://github.com/bitcoin/bitcoin/blob/ae6943620ab369e8e0865c3ec2d2848ba9389325/src/rpc/request.h#L27-L40) is probably the simplest way to pass context to RPC methods and get rid of RPC globals without having to change the way RPC methods are written. But other ways would be possible like making RPC methods into objects: https://github.com/bitcoin/bitcoin/pull/16839#discussion_r324426030

But I wouldn't put much too much priority on getting rid of `g_rpc_node` and `g_rpc_chain` globals. It'd be nice to add `EnsureConnman` `EnsureBanman` functions similar to [`EnsureMempool`](https://github.com/bitcoin/bitcoin/blob/ae6943620ab369e8e0865c3ec2d2848ba9389325/src/rpc/blockchain.cpp#L57-L64) so the globals could be referenced in fewer places, but I don't think much would be gained practically by completely getting rid of them.

**Comment by MarcoFalke** [comment]
Yeah, I am mostly leaving this open to not forget about it. 

> But other ways would be possible like making RPC methods into objects

I think I wanted to make them objects anyway for some `RPCHelpMan` work.

**Comment by laanwj** [comment]
Concept ACK.

Putting the context in a thread-local variable would also work, but I prefer a context pointer on `JSONRPCRequest` to that kind of action at a distance.

Not convinced that JSONRPC methods should be objects. They're conceptually functions, defined as functions. It seems over-OOP to me.

**Comment by brakmic** [comment]
I have a question regarding **g_txindex**.

After I have removed **g_rpc_node** and **g_rpc_chain** in my PR https://github.com/bitcoin/bitcoin/pull/18647 I went searching for similar globals, that maybe could be removed the same way. And I found one: **g_txindex** which too is being used in two of the RPCs: **getrawtransaction** and **rest_tx**. That is, they rely on *GetTransaction* which actually uses *g_txindex*.

And as I have adapted RPCs to be called with NodeContext as their second argument, I would like to hear your opinions on expanding NodeContext by adding a **unique_ptr<TxIndex>** member to it.

So that *getrawtransaction* would receive **g_txindex** from NodeContext and then forward it to *GetTransaction*.

With this change we could also get rid of this third global variable (this of course depends on the fate of my PR).

Regards,

**Comment by MarcoFalke** [comment]
There is a pull for this, and this issue is low prio, so closing.
