### ISSUE TITLE
Document recommendations for testing releases

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#17552]
It would be nice to have a document with recommendations as to how to best test releases/release binaries (e.g. run in valgrind). The recommendations are preferably testing procedures that would benefit from being tested in differing host/network environments.

**Comment by MarcoFalke** [comment]
An issue I could imagine with "testing recommendations" is that they are done sporadically or not all all, because no one wants to spend time going through a long document with bullet points and check them off before every release.

Obviously we have the unit and functional tests, which is our primary point to put new tests in. Everyone should run them after compiling Bitcoin Core. For the gitian builds, I do this on all platforms: mac, win, linux.

When it comes to user testing, every user has their own use case for Bitcoin Core, so beside running the unit and functional tests, they should read the release notes and run their own integration tests (e.g. "Is my RPC wrapper still up to date with the all RPC changes") every time they update Bitcoin Core.

**Comment by dongcarl** [comment]
> they are done sporadically or not all all

I think that people who are currently doing testing will continue to do testing in their own way, and people who are not doing testing at all might be more inclined to do testing if they have some recommendations to help kickstart their brainstorming about about what they want to test. For example:

> they should read the release notes and run their own integration tests (e.g. "Is my RPC wrapper still up to date with the all RPC changes") every time they update Bitcoin Core.

This is probably one of **the most important things** to include in the recommendations.

What I'm suggesting is just some documentation on possible testing methodologies/tools, and that might belong in another repo, but it'd be nice to have a place to share and improve this information.
