### ISSUE TITLE
rpc: base58Prefixes in info rpc

### ISSUE THREAD

**Issue by nkostoulas** [bitcoin/bitcoin#17711]
Would it be useful to add base58Prefixes and other consensus/chainparams in an rpc (getblockchaininfo or other)? This could help people building external applications that connect to a bitcoin node and avoid having to hardcode all these parameters.

**Comment by MarcoFalke** [comment]
No objection, but also not sure if it makes sense to serve static const data over a remote call

**Comment by laanwj** [comment]
> but also not sure if it makes sense to serve static const data over a remote call

Agree. I think hardcoding (or at least, having your own constants for these in your applications) these things makes a lot of sense because they're not going to change without a reason you probably need to be aware of!

(Say, in the unlikely case that there would be a new kind of base58 address format, you wouldn't want your application to silently start accepting them without at least having looked over it)

**Comment by nkostoulas** [comment]
Well I believe there are applications where you don't really care about the value changing, you just need to be sure that the address/key you are deriving or using will be later accepted by a bitcoin node. But I guess you are right it's just a couple of consts that never change. I kinda envisioned that more on the Elements case to be honest, where you could end up with multiple chains and you needed to avoid hardcoding everything all over again.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
