### ISSUE TITLE
gui: HD icon is displayed when no wallet is loaded

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#17927]
Compile master, and run with `src/qt/bitcoin-qt -regtest -nowallet`. As expected, no icon is displayed. Load and unload a wallet. The `HD` icon remains.

On startup:
![on_startup](https://user-images.githubusercontent.com/863730/72410834-711b4c00-37a4-11ea-9a10-bfcf3db7ce68.png)

After a wallet load and unload:
![after_load_unload](https://user-images.githubusercontent.com/863730/72410838-737da600-37a4-11ea-8854-dd13301c0135.png)

**Comment by theStack** [comment]
The same behaviour also applies to the encryption icon, if you load a wallet that is encrypted.

**Comment by brakmic** [comment]
I could also show/hide the lock icon the same way I did with HD icon, but I am not sure if this should be packed together in a single PR. It's actually nothing complex, so it could maybe be better to avoid opening another one only because of an icon. 

For now, I have only changed the handling of HD icon.

**Comment by fanquake** [comment]
> but I am not sure if this should be packed together in a single PR.

@brakmic Given how simple the changes are here, I think it makes sense to just fix both in the same PR.

**Comment by promag** [comment]
> the same PR.

Agree.

**Comment by brakmic** [comment]
Ok, have updated the PR and renamed it too.
