### ISSUE TITLE
nTime as a uint32_t

### ISSUE THREAD

**Issue by barrystyle** [bitcoin/bitcoin#18182]
Short and sweet;
Linux has recently added support for 64bit timestamps to the kernel.
Since the resolution of nTime is limited to 4 bytes - or as a standard unix timestamp (pre-patch) if you prefer; wouldn't bitcoin be susceptible to the year 2038 bug?

**Comment by brakmic** [comment]
This doesn't look like a good "good first issue", imo. There is a certain template that should be used.
Maybe better let experienced devs formulate them.

**Comment by barrystyle** [comment]
If you are having trouble understanding what i've written, happy to explain further.

**Comment by brakmic** [comment]
What you have formulated is, imo, **not a good first issue** but rather a question.
Also, you **did not** follow the guides of this project, because you did not use the template Bitcoin devs use.

However, I don't want to (mis)use this for any philosophical discussions and will leave it for Core Devs to decide.

Regards,

**Comment by kristapsk** [comment]
You can't just simply change timestamp format used for Bitcoin blocks, that will be a consensus change and cause a hardfork. Such changes aren't decided in Bitcoin Core repo, must have broader discussion and follow BIP (Bitcoin Improement Proposal) process.

**Comment by barrystyle** [comment]
Just wanted to open a dialogue gentlemen.. the issue isn't going to go away.

On that note, you'd probably integrate a timestamp into the block's coinbase transaction and deprecate the existing variable.
