### ISSUE TITLE
scheduler test causing pthread_cond_timedwait: Invalid argument error  

### ISSUE THREAD

**Issue by amitiuttarwar** [bitcoin/bitcoin#18227]
## Problem
In #18037 I introduced code to mock the scheduler from functional tests. I added a `scheduler#MockForward` method & associated `scheduler_tests#mockforward` unit test. The unit test caused sporadic failures on one of the Travis machines & failures on Bitcoin builds.

After a couple attempts at small fixes [[1]](https://github.com/bitcoin/bitcoin/pull/18174) [[2]](https://github.com/bitcoin/bitcoin/pull/18188), we decided to [disable the test](https://github.com/bitcoin/bitcoin/pull/18211) as we investigate the underlying issue. 

## Failures
Some examples of failing builds 

Travis: [[1]](https://travis-ci.org/bitcoin/bitcoin/jobs/649620800) [[2]](https://travis-ci.org/bitcoin/bitcoin/jobs/651788952)
Note that it is always the travis machine with `x86_64 Linux [GOAL: install] [bionic] [no wallet]`

Bitcoin Builds: [[1]](https://bitcoinbuilds.org/index.php?job=5c006a9e-b8e6-4932-a6a8-3ead3d1fc188) [[2]](https://bitcoinbuilds.org/index.php?job=c1d3a0f5-7d47-40e6-9c9b-cac397c5ff30) [[3]](https://bitcoinbuilds.org/?job=7e61f7cd-ad26-4416-9f04-4e0101e1e8fc)

The test always fails in the same way: 
```
terminate called after throwing an instance of 'boost::wrapexcept<boost::condition_error>'
  what():  boost::condition_variable::do_wait_until failed in pthread_cond_timedwait: Invalid argument
unknown location(0): fatal error: in "scheduler_tests/mockforward": signal: SIGABRT (application abort requested)
```

## Reproducing the issue 
One of the issues that makes this really difficult to debug is the failure is hard to reproduce. I have not been able to reproduce it myself. In this section, I'm compiling the information from others that were able to reproduce.

* @jonasschnelli found that enabling ccache meant consistent failure, and clearing ccache meant consistent success. [[1]](https://github.com/bitcoin/bitcoin/pull/18037#issuecomment-588371299) [[2]](https://github.com/bitcoin/bitcoin/pull/18174#issuecomment-588363133) 

* @MarcoFalke was able to reproduce on a single CPU instance, but unable to extract much debugging information. [[1]](https://github.com/bitcoin/bitcoin/pull/18174#issuecomment-588554950).

## Relevant debugging information 
The `boost:condition_variable` triggers the `SIGABRT` as a result of the `pthread_cond_timedwait` returning an `Invalid argument`, or `EINVAL` error. According to the docs [[1]](https://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_cond_timedwait.html) & [[2]](https://linux.die.net/man/3/pthread_cond_timedwait), this indicates that either `The value specified by cond, mutex, or abstime is invalid` or `Different mutexes were supplied for concurrent pthread_cond_timedwait() or pthread_cond_wait() operations on the same condition variable.` 

## Next steps 
This bug doesn't seem urgent, but should be investigated and resolved. I'm opening this issue to track any relevant comments or findings. 

Thank you to everyone who has jumped in to take a look & thanks in advance to anybody willing to help continue the investigation 🙏🏽

**Comment by MarcoFalke** [comment]
For completeness, the other bugs that mention the same exception "Invalid argument" in the scheduler: #16307, #16027, #14200.

**Comment by fanquake** [comment]
@MarcoFalke Could you post the specs/setup for the Google Cloud instance you were using to reliably recreate the issue?

**Comment by MarcoFalke** [comment]
I think it was `n1-standard-1 (1 vCPU, 3.75 GB memory)` and it only happened after a reboot once.

Also, it only happened with `make -j 2 check`, as opposed to `src/test/test_bitcoin -t scheduler_tests`

**Comment by nothingmuch** [comment]
Although I haven't been able to replicate the failure, my current best guess is an invalid timespec passed to `pthread_cond_timedwait` from [the timed wait loop](https://github.com/amitiuttarwar/bitcoin/blob/df29a71f056e448763d05a40b07ff365b4526ba5/src/scheduler.cpp#L64).

I'm hoping someone can suggest a cleaner way of corroborating or ruling out this hypothesis (see below), especially since @amitiuttarwar told me that @ajtowns has concluded that an invalid timespec is *not* the cause.

#### Assumptions/observations:

- only `serviceQueue` waits on `newTasksScheduled`, one indefinite wait loop which terminates when the queue is not empty, and one timed wait loop which terminates when the scheduled time of the first task has been reached.

- It appears the failures always happens with `make depends` and therefore boost 1.70.0, which implies that [`wait_until` is used (as opposed to `timed_wait`)](https://github.com/amitiuttarwar/bitcoin/blob/df29a71f056e448763d05a40b07ff365b4526ba5/src/scheduler.cpp#L59-L67).

- `mockforward` [declares `CScheduler scheduler`](https://github.com/amitiuttarwar/bitcoin/blob/df29a71f056e448763d05a40b07ff365b4526ba5/src/test/scheduler_tests.cpp#L158), which isn't copied or moved, but is shared by reference with the [`serviceQueue` thread](https://github.com/amitiuttarwar/bitcoin/blob/df29a71f056e448763d05a40b07ff365b4526ba5/src/test/scheduler_tests.cpp#L162) (only one), and [the task that stops the scheduler](https://github.com/amitiuttarwar/bitcoin/blob/df29a71f056e448763d05a40b07ff365b4526ba5/src/test/scheduler_tests.cpp#L179).

- the error is returned after [there are already tasks in the queue](https://github.com/amitiuttarwar/bitcoin/blob/df29a71f056e448763d05a40b07ff365b4526ba5/src/test/scheduler_tests.cpp#L173) (as per boot test checkpoints, see build logs) but before [the queue servicing thread has terminated](https://github.com/amitiuttarwar/bitcoin/blob/df29a71f056e448763d05a40b07ff365b4526ba5/src/test/scheduler_tests.cpp#L180) (because only `serviceQueue` waits on the condition variable, and the only timed wait is at [on line 64](https://github.com/amitiuttarwar/bitcoin/blob/df29a71f056e448763d05a40b07ff365b4526ba5/src/scheduler.cpp#L64)).

- the `serviceQueue` thread and the test are not synchronized before the call to `MockForward`, so a race is possible:
  - `serviceQueue` may reach the timed wait loop with the original queue and then [woken up](https://github.com/amitiuttarwar/bitcoin/blob/df29a71f056e448763d05a40b07ff365b4526ba5/src/scheduler.cpp#L136) by [the call to MockForward](https://github.com/amitiuttarwar/bitcoin/blob/df29a71f056e448763d05a40b07ff365b4526ba5/src/test/scheduler_tests.cpp#L176) after the queue has been updated.
  - `MockForward` may update the queue for the updated task times before the 1st iteration of the timed wait loop.
    This seems less likely since the failure appears to have been introduced by the new mocking behavior, and `manythreads` already tests [scheduling of tasks for times in the past](https://github.com/amitiuttarwar/bitcoin/blob/df29a71f056e448763d05a40b07ff365b4526ba5/src/test/scheduler_tests.cpp#L56) (note, the function name implies milliseconds - or is it megaseconds? :wink: - but [the returned value is interpreted as microseconds](https://github.com/amitiuttarwar/bitcoin/blob/df29a71f056e448763d05a40b07ff365b4526ba5/src/test/scheduler_tests.cpp#L66))

#### Alternative explanations for `EINVAL` and evidence against them

- unintiialized condvar or mutex, since `pthread_cond_init` and `pthread_mutex_init` are called from the constructors of the scheduler member variables `boost::condition_variable newTasksScheduled` and `mutable boost::mutex newTasksMutex`
- destroyed condvar or mutex, since the scheduler lifetime is bound to the test's scope
- different mutex for same condvar, since there is only one `serviceQueue` thread[1]

As far as I'm aware the only way for the timespec to be invalid is if `tv_msec` is outside the range `[0, 1e9)`.

There is also some very weak evidence for this cause, namely condition variable and other timed wait related bugfixes mentioned boost release notes, but these generally pertain to win32, and non monotonic system clock values. Furthermore, such a bug only seems plausible if time values are converted (see my question below about `do_wait_until` variants and `internal_chrono_clock`).

#### Next steps

I suppose this can be validated by patching boost in make depends, so that it checks the `tv_msec` field of the timespec returned by `getTs` to see if this makes a difference on the CI machines that reliably fail.

However my understanding of C++ is at it's limit and it's not clear to me which definition of `do_wait_until` is used by [`wait_until`](https://github.com/boostorg/thread/blob/boost-1.70.0/include/boost/thread/pthread/condition_variable.hpp#L351-L380):

- [`inline bool condition_variable::do_wait_until`](https://github.com/boostorg/thread/blob/boost-1.70.0/include/boost/thread/pthread/condition_variable.hpp#L105-L142)
- [private function template](https://github.com/boostorg/thread/blob/boost-1.70.0/include/boost/thread/pthread/condition_variable.hpp#L460-L490)

Additionally, it's not clear to me which definition of `wait_until` itself is used, i.e. when does `detail::internal_chrono_clock` correspond to `boost::system_clock`, but that doesn't seem consequential.

In either case, sanity checks could on the following `getTs` calls' return values could be added in a patch:

- https://github.com/boostorg/thread/blob/boost-1.70.0/include/boost/thread/pthread/condition_variable.hpp#L122
- https://github.com/boostorg/thread/blob/boost-1.70.0/include/boost/thread/pthread/condition_variable.hpp#L127
- https://github.com/boostorg/thread/blob/boost-1.70.0/include/boost/thread/pthread/condition_variable.hpp#L474

but like I said I'm hoping someone can suggest a simpler approach, finds flaws in my reasoning, since I'm not really looking forward to trying this approach without being able to replicate the failure locally.

[1] furthermore, if `BOOST_THREAD_PROVIDES_INTERRUPTIONS` is defined `boost::condition_variable` [will use an internal mutex](https://github.com/boostorg/thread/blob/boost-1.70.0/include/boost/thread/pthread/condition_variable.hpp#L122) instead the one corresponding to the lock argument

**Comment by ajtowns** [comment]
> I'm hoping someone can suggest a cleaner way of corroborating or ruling out this hypothesis (see below), especially since @amitiuttarwar told me that @ajtowns has concluded that an invalid timespec is _not_ the cause (edit: i seem to have interpreted that too strongly, apologies to both)

> As far as I'm aware the only way for the timespec to be invalid is if `tv_msec` is outside the range `[0, 1e9)`.

I think this is a typo -- should be `tv_nsec` (nanoseconds).

And yeah that's the only way I can see it happening per http://sourceware.org/git/?p=glibc.git;a=blob;f=nptl/pthread_cond_timedwait.c;h=7278ec45b0eb0b48be50fe832fcd17ae988dca27;hb=HEAD

Okay, I guess I can delete the paragraph about how that doesn't seem plausible. I added:

```
#include <pthread.h>
#include <errno.h>
inline int my_pthread_cond_timedwait(pthread_cond_t *cond,
       pthread_mutex_t *mutex,
       const struct timespec *abstime)
{
    if (abstime->tv_nsec < 0) {
        if (abstime->tv_sec < 0) return EISDIR;
        else return ENOTDIR;
    }
    if (abstime->tv_nsec >= 1000000000l) return ENOTBLK;
    return pthread_cond_timedwait(cond,mutex,abstime);
}
#define pthread_cond_timedwait(c,m,t) my_pthread_cond_timedwait(c,m,t)
```

as the very first thing in scheduler.cpp and ran it on travis, and got:

```
terminate called after throwing an instance of 'boost::wrapexcept<boost::condition_error>'
  what():  boost::condition_variable::do_wait_until failed in pthread_cond_timedwait: Is a directory
```

(Ref: https://travis-ci.org/ajtowns/bitcoin/jobs/656619767?utm_medium=notification&utm_source=github_status and https://github.com/ajtowns/bitcoin/commits/202002-pthread )

so seems like it's getting an invalid timespec passed in, with both `tv_sec < 0` and `tv_nsec`, so I'm guessing as a result of int-division-rounding-towards-zero making ns_to_timespec mess up in https://www.boost.org/doc/libs/1_70_0/boost/thread/detail/platform_time.hpp . But pthread_cond_timedwait expects an absolute time since the unix epoch, so trying to pass through a negative value is crazy, and I can't see anywhere that should be causing that...

**Comment by MarcoFalke** [comment]
Those are the steps that lead to the exception (with example values filled in for illustrative purposes):

* We start in the scheduler thread, passing down `timeToWaitFor` with a value of `1583005659124748450` to the condition variable `wait_until`. ( https://github.com/bitcoin/bitcoin/blame/715dbbe9e8b64fd4b556a0b0720b44d68c3b5e32/src/scheduler.cpp#L64 )
* Boost will take that time point and subtract the current time point (now) from it, yielding a `d` of value `-180003638322`. This is about 180 seconds or 3 minutes in the past, because the first event in the queue was scheduled 2 minutes into the future, but the scheduler was mocked 5 minutes into the future. ( https://github.com/boostorg/thread/blob/boost-1.70.0/include/boost/thread/pthread/condition_variable_fwd.hpp#L270 )
* Immediately after, Boost will add the current time again (taking a different clock). The internal clock gives `176260088289` and thus the result `-3743550033` is passed down to `do_wait_until`. ( https://github.com/boostorg/thread/blob/boost-1.70.0/include/boost/thread/pthread/condition_variable_fwd.hpp#L271 )
* `do_wait_until` passes this `timeout` with value `{tv_sec=-3, tv_nsec=-743550033}` straight through to `pthread_cond_timedwait`, which then spits out `Invalid argument`. ( https://github.com/boostorg/thread/blob/boost-1.70.0/include/boost/thread/pthread/condition_variable.hpp#L122 )

Reported upstream: https://github.com/boostorg/thread/issues/308

**Comment by ajtowns** [comment]
@MarcoFalke nice!

While I was thinking it was a mutex problem I had a go at switching scheduler.cpp to the sync.h primitives to see if that would make the bug obvious. Might be worth doing anyway, and I think the code in the standard libraries for converting to `timespec` avoids the boost bug above. Opened #18234 if anyone wants to take a look.
