### ISSUE TITLE
settxfee 0.00000000 returns true

### ISSUE THREAD

**Issue by mrbabtc** [bitcoin/bitcoin#18315]

**Comment by fjahr** [comment]
You did not provide what the behavior is that you would have expected from `settxfee`. So I am not sure if you were aware, but it is a feature of `settxfee` that you can deactivate that fee parameter by passing in 0. `true` is correct as a return value here since the call succeeds. But I agree that this feature is not documented properly and also the return value can be confusing, even if you are aware of the feature. I am trying to improve both of these issues in  #18467.

**Comment by MarcoFalke** [comment]
I think another issue is that `settxfee 1111111` returns true :man_shrugging:

**Comment by fjahr** [comment]
> I think another issue is that `settxfee 1111111` returns true 🤷‍♂

Why stop there? `src/bitcoin-cli settxfee 21000000` returns true as well ;)

Yes, there is not any upper bound to the fee rate you can set aside from total supply. Is there already precedent for restricting that user choice? I could see that we give a warning that the fee appears to be high but I am not sure what value to compare this to. Since this is a persistent setting I don't think any current dynamic estimate is a good reference.

**Comment by MarcoFalke** [comment]
I think there is some kind of -maxtxfee wallet command line setting

**Comment by fjahr** [comment]
> I think there is some kind of -maxtxfee wallet command line setting

Good idea, I have used this now.

**Comment by fjahr** [comment]
@mrbabtc could you take a look at #18467 and let me know if this fixes your issue? It does not change the return value but improves documentation about the behavior.

**Comment by mrbabtc** [comment]
> @mrbabtc could you take a look at #18467 and let me know if this fixes your issue? It does not change the return value but improves documentation about the behavior.

Sorry , I wasnt checking it
And I think that settxfee could be confusing because min relay fee is 1 sat/byte
