### ISSUE TITLE
build: building for just bench fails to link due to libevent symbols

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#18373]
Configuring to build only `bench` i.e: `./configure --with-gui=no --with-libs=no --with-utils=no --with-daemon=no --disable-tests` currently fails to link with:
```bash
  CXXLD    bench/bench_bitcoin
Undefined symbols for architecture x86_64:
  "_evhttp_uridecode", referenced from:
      urlDecode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libbitcoin_util.a(libbitcoin_util_a-url.o)
  "_event_enable_debug_logging", referenced from:
      UpdateHTTPServerLogging(bool) in libbitcoin_server.a(libbitcoin_server_a-httpserver.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by brakmic** [comment]
I'll take this one.

**Comment by brakmic** [comment]
Btw. @fanquake ,

While going through [Makefile.bench.include](https://github.com/bitcoin/bitcoin/blob/master/src/Makefile.bench.include#L46) I discovered this: $(EVENT_C**LF**AGS)

This should certainly be $(EVENT_C**FL**AGS)

Not sure if this would also be the solution to the actual problem as I'm still going through the Makefile, so I'd like to consult with you first before proposing anything.

**Comment by fanquake** [comment]
> This should certainly be $(EVENT_CFLAGS)

Good catch! In any case that should also be fixed.

**Comment by brakmic** [comment]
@fanquake ,
A possible fix could be done by using an explicit LDFLAG **-levent** as shown in [my repo](https://github.com/bitcoin/bitcoin/compare/master...brakmic:bench-compilation).

But before I open a PR I also have another question: should we also remove the double **LIBBITCOIN_SERVER** from [here](https://github.com/brakmic/bitcoin/blob/bench-compilation/src/Makefile.bench.include#L51). Not sure if we should open a new issue because of this. 

This already got removed from Makefile.am in https://github.com/bitcoin/bitcoin/pull/17910 so I suppose it would make sense to get rid of it here as well.

**Comment by MarcoFalke** [comment]
Yeah, if it compiles and links, it can be removed.

**Comment by brakmic** [comment]
> Yeah, if it compiles and links, it can be removed.

Yes, it does. Have tested it. Will then add it to this PR.
