### ISSUE TITLE
test: macOS functional tests still failing intermittently 

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#18794]
The functional tests were re-enabled on macOS in #18778. However it looks like they are still suffering from intermittent failures. i.e: https://travis-ci.org/github/bitcoin/bitcoin/jobs/680353191#L3136. The `OSError: [Errno 41] Protocol wrong type for socket` error in feature_assumevalid looks like the same one that was reported in #17240 when the tests were first disabled.

**Comment by RandyMcMillan** [comment]
The issue seems to be with client.py

https://github.com/python/cpython/blob/master/Lib/http/client.py#L228

https://github.com/RandyMcMillan/bitcoin/blob/client.py.latin3/test/functional/test_framework/authproxy.py#L142


The test data seems ok on macOS:
![Screen Shot 2020-04-28 at 9 38 55 AM](https://user-images.githubusercontent.com/152159/80496393-25e20f00-8937-11ea-824d-48039c7ac01a.png)

**Comment by RandyMcMillan** [comment]
The other part of the issue may be that Travis is symlinking to Python3.7 after looking for Python3.5 
Maybe minimum support should be bumped to Python3.7
