### ISSUE TITLE
QRCode address in image is not readable

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#19103]
Somehow the resolution of the QRCode image is not high enough.
Native wpkh addresses are non readable and legacy/p2sh addresses are not good readable.
Haven't tested on other OSes than macOS.

<img width="599" alt="Bildschirmfoto 2020-05-29 um 09 52 07" src="https://user-images.githubusercontent.com/178464/83235531-55807300-a192-11ea-8c5c-0f88481ecad1.png">

<img width="599" alt="Bildschirmfoto 2020-05-29 um 09 53 21" src="https://user-images.githubusercontent.com/178464/83235524-51ecec00-a192-11ea-8cb3-bcd580724be6.png">

**Comment by BitcoinCorp** [comment]
not good **since 0.19** on macOS

**Comment by promag** [comment]
This might be an issue with the font used. Anyway, why not remote the address from the image? It's shown below.

**Comment by promag** [comment]
I've comment out
```
        // calculate ideal font size
        qreal font_size = GUIUtil::calculateIdealFontSize(paddedRect.width() - 20, text, font);
        font.setPointSizeF(font_size);
```
So it would use the default font size and also sucks. On my system the point size of `QFontDatabase::FixedFont` is 10 and only with antialias it displays fine.

I'm not sure if the idea is to have pixel perfect text, but in that case maybe we should ship with such font so that it's the same in all platforms?

Otherwise we could
 a) use a better font 
 b) enable antialias
 c) increase image size

ping @luke-jr.

**Comment by fanquake** [comment]
Moved to the GUI repo: https://github.com/bitcoin-core/gui/issues/54.
