### ISSUE TITLE
Error: Cannot obtain a lock on data directory

### ISSUE THREAD

**Issue by heaven** [bitcoin/bitcoin#19167]
Getting this error when trying to store the data directory on a network drive (using Time Capsule drive). I simply don't have 280GB of disk space on my mac for the initial sync. Deleting the `.lock` and restarting the app doesn't help. There's no debug output also, it only creates the lock file and exists.

**Expected behavior**

It should be able to store the data on network-attached devices.

**Actual behavior**

Getting this error.
<img width="502" alt="Screen shot 2020-06-04 at 16 58 18" src="https://user-images.githubusercontent.com/126732/83767586-80813000-a686-11ea-9ff1-834dec9b573f.png">

**To reproduce**

Install the wallet and choose the data directory to be on a network-attached drive.

**System information**

Bitcoin Core 0.20.0
Mac OS 10.15.5

**Comment by pstratem** [comment]
Some network filesystems simply do not support file locking.

Possibly this is one of them?

**Comment by fanquake** [comment]
Closing this until more information is available.

**Comment by dhruv** [comment]
I wanted to sync a full, non-pruned node on to an Apple Time Capsule storage drive. Thought solving this issue might be useful for others as well. But I hit a wall. Here are my notes in case it's useful for the next person who gets interested in this issue:

- bitcoind creates a .lock file on datadir
- This is done using the `fcntl` sys call
- Sidenote: Filesystem locks in unix are advisory only. They only really protected against other instances of well-behaved applications. Advisory file locks are made by the OS keeping track of a pid that currently holds the lock. This is more involved over NAS storage because the lock-holding process can be on other network computers as well.
- Apple Time Capsule uses AFP(Apple Filing Protocol) over TCP and `fcntl` does not seem to work as expected.
- Changing the code to use the `is_wsl` workaround in `src/fs.cpp FileLock::TryLock` for AFP allows bitcoind to capture the lock using the `flock` syscall instead of `fcntl`. However, then it seems that the lock is simply ignored by another well-behaved bitcoind process.
- Further down the execution path, leveldb is unable to acquire locks as well. This is likely also because of a similar issue but changing leveldb is likely more involved in time.
- I decided to give up on this approach to run a full node.
