### ISSUE TITLE
[code review] Isn't this check redundant?

### ISSUE THREAD

**Issue by MithrilMan** [bitcoin/bitcoin#19223]
https://github.com/bitcoin/bitcoin/blob/9ad6f14175c19b5d47267c3dd5840c14bad43c83/src/validation.cpp#L3711

If i'm following right the flow of the code, when we hit this lane `pindex` should be always equal to nullptr thus this check may be omitted

**Comment by promag** [comment]
ACK, the branch where `pindex` is set early returns.

**Comment by jnewbery** [comment]
I agree. The line below:

https://github.com/bitcoin/bitcoin/blob/9ad6f14175c19b5d47267c3dd5840c14bad43c83/src/validation.cpp#L3715

could also be changed to directly change `*ppindex` to `nullptr`.

Seems like it's been this way since the function was added in https://github.com/bitcoin/bitcoin/pull/3884
