### ISSUE TITLE
Follow up from recent libsecp256k1 subtree update

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#19263]
Opening this to track the potential followups, [mentioned by](https://github.com/bitcoin/bitcoin/pull/19228#issuecomment-641795558) @real-or-random, after the libsecp256k1 update in #19228.

> If we do those two changes (the second change belonging to this repo), we will have a clean copy of ecdsa_signature_parse_der_lax again. But maybe this is non-trivial enough to go to a second PR. I'm volunteering to open a PR after I digged through all the stuff now.

[comment](https://github.com/bitcoin/bitcoin/pull/19228#issuecomment-642352251):
> @real-or-random Thanks for pointing that out. I added a commit to rename privkey to seckey in key.cpp (as a scripted diff). I've left the DER parsing code be for now, as it seems unclear what changes to address where.

[comment](https://github.com/bitcoin/bitcoin/pull/19228#issuecomment-643406092):
> >  I've left the DER parsing code be for now, as it seems unclear what changes to address where.

> Ok, let's do this in a different PR.

**Comment by real-or-random** [comment]
I'll be gone for a few days but my plan is to first to get a clean version upstream (https://github.com/bitcoin-core/secp256k1/issues/758) and then PR the clean version here.

**Comment by MarcoFalke** [comment]
Is this still an issue?

**Comment by real-or-random** [comment]
Yeah, this is still an issue. It's not the end of the world, but we should track it somewhere. Having said this, it may be easier to track the issue only in https://github.com/bitcoin-core/secp256k1/issues/758. So we could close this issue here because it's not directly relevant to Core.

Status: My attempt to solve it (https://github.com/bitcoin-core/secp256k1/pull/781) didn't get traction. Maybe I could  try to open another PR which is less aggressive.

**Comment by fanquake** [comment]
> Having said this, it may be easier to track the issue only in https://github.com/bitcoin-core/secp256k1/issues/758.

Ok. Lets track upstream for now.
