### ISSUE TITLE
gui: freezes on Ubuntu 20.04 when using a different data location

### ISSUE THREAD

**Issue by AndaPlays** [bitcoin/bitcoin#19313]
Hey, 
so I installed Bitcoin Core via the files provided on Bitcoin.org (Linux txz), on a fresh Ubuntu 20.04 VM. I followed the Instruction from the site too.

When prompted with the "Welcome" window, I chose a different directory in a mounted SMB share. After clicking on "Ok", [Bitcoin Core will start but will stay on the loading screen](https://youtu.be/i7dz6nbEGOA). I did check the directory and Bitcoin Core did create a few files(no debug tho), so It has Read & Write permissions.  

I tried it with the files from Bitcoin.org, Snap Store, and with the repo from luke-jr. Always getting the same error. When using the default settings, It works.

[Also Bitcoin Core will not show anything in the window for searching a different directory.](https://youtu.be/BTjBAmWVEow)

**Comment by MarcoFalke** [comment]
Please check your debug.log for possible causes; Alternatively you can upload it here.

You can find the debug.log in your [data dir](https://github.com/bitcoin/bitcoin/blob/master/doc/files.md#data-directory-location).

**Comment by AndaPlays** [comment]
@MarcoFalke Well with a custom datadir Bitcoin Core will only create the .bitcoin folder and within this folder the files: bitcoind.pid, folder "block", folder "wallets" and .lock. Nothing else, doesn't matter how long I wait. 
![folder](https://user-images.githubusercontent.com/37880697/84940738-8ba17a80-b0e0-11ea-8207-8663f0ca19c6.PNG)

**Comment by MarcoFalke** [comment]
Can you either attach gdb to see where it hangs or start it from the command line with `-printtoconsole` enabled?

**Comment by AndaPlays** [comment]
I get
 `
node@node:~$ /usr/local/bin/bitcoin-qt -printtoconsole
Error: Unable to create the PID file '/media/bitcoin/.bitcoin/bitcoind.pid': No such file or directory
node@node:~$ /usr/local/bin/bitcoin-qt -printtoconsole
Error: Unable to create the PID file '/media/bitcoin/.bitcoin/bitcoind.pid': No such file or directory
node@node:~$ 
`

**Comment by AndaPlays** [comment]
I don't know why but starting Bitcoin Core via the command
`/usr/local/bin/bitcoin-qt -datadir=/media/bitcoin/`
did work and runs just fine now. So I guess the initial setup/GUI has a problem.

**Comment by ryanofsky** [comment]
So many bizarre things happening here. If everything is working now, maybe close this issue, otherwise we probably need more information about the problem. You can run `bitcoin-qt -choosedatadir` to get intro screen to show up again.

- "Bitcoin Core will not show anything in the window for searching a different directory" video is very strange, completely empty directory tree, maybe a qt bug?
- Also very strange how loading screen hangs with no text. Not even `Unable to create the PID file` error you reported later. When that error is triggered locally, I see a popup dialog, not a blank loading screen. I would try running `strace bitcoin-qt` to see where loading is getting stuck and what the system is trying to do.

To narrow down why datadir `/media/bitcoin` works but not `/media/bitcoin/.bitcoin` doesn't work it would help to experiment:

- Check filesystem permissions, try liberalizing adding full read write and other access for everyone to debug
- Check share permissions, again see if liberalizing helps
- Check smb mount options, try removing restrictions
- Maybe try a different smb server, or different filesystem (fat vs ntfs), or turning on auditing to look for errors
- Try using using a folder name that doesn't have leading dot in ".bitcoin"

Also feel free to share more information about your smb mount options, smb server config, which ubuntu image is being used, host vm, host os, etc

**Comment by jarolrod** [comment]
See: https://bitcointalk.org/index.php?topic=2673041.0

The user documents that bitcoin core will not work on their SMB file share drive. The user also explains that it works using their NFS drive.

Considering the vulnerabilities that have plagued SMB (WannaCry, EternalBlue), maybe it's better to move to a different filesystem.

**Comment by hebasto** [comment]
Closing?

**Comment by fanquake** [comment]
Given no additional information, closing for now.
