### ISSUE TITLE
TransactionError::ALREADY_IN_CHAIN inconsistency 

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19363]
If a transaction is already in the block chain, and all of its outputs are spent, the `BroadcastTransaction()` fails to detect the correct transaction status. It returns `TransactionError::MISSING_INPUTS` instead of `TransactionError::ALREADY_IN_CHAIN`.

The related code: https://github.com/bitcoin/bitcoin/blob/80fd474e402bb003c3a427f1997eb649e69138ba/src/node/transaction.cpp#L32-L37

I think that `TransactionError::ALREADY_IN_CHAIN` should be returned in all cases when the transaction is in the block chain, or it should be dropped from the code at all as inconsistent.

What are other opinions?

**Comment by willcl-ark** [comment]
Although it is inconsistent I slightly prefer the idea of returning the most accurate information available to the user.

Following this logic instead of removing this error type, we could take two new actions to try and increase the chance that the caller gets more accurate information back:

1. Inside `BroadcastTransaction()` add a call to `GetTransaction()` on the condition that the user has `txindex` enabled
2. Augment [`HandleATMPError`](https://github.com/bitcoin/bitcoin/blob/fe1b3256888bd0e70d0c9655f565e139ec87b606/src/node/transaction.cpp#L22-L26) to include a more detailed error string in the `TxValidationResult::TX_MISSING_INPUTS` case, which might prompt a recipient to find another way to check if the transaction is already in the chain.

**Comment by ryanofsky** [comment]
> I think that `TransactionError::ALREADY_IN_CHAIN` should be returned in all cases when the transaction is in the block chain, or it should be dropped from the code at all as inconsistent.

#30212 implements the second option. It gets rid of already in chain error code since that case can't be reliably detected, and returns already in utxo set, or missing inputs instead.
