### ISSUE TITLE
libevent: Error from accept() call: Invalid argument on Android termux (arm)

### ISSUE THREAD

**Issue by stefanwouldgo** [bitcoin/bitcoin#19432]
After running for an undetermined time (days), bitcoind starts emitting thousands of these errors per second:
`libevent: Error from accept() call: Invalid argument`
this eventually crashes the Android device because the log fills up the SD card.

**Expected behavior**

just run on. This had not occured before 0.20. 

**To reproduce**

I don't know what triggers this. I have reproduced it a few times by just letting the node run for a few days.

**System information**

termux package bitcoin-0.20. As described by the build script [here](https://github.com/termux/termux-packages/tree/master/packages/bitcoin). Build includes static dependencies from the official bitcoind dependency tree.

Running on LineageOS 16  (Android 9) unofficial on a Sony Xperia Z (yuga) device.

**Comment by stefanwouldgo** [comment]
The bug ist still present in 0.20.1, also happening on a Motorola G5 running stock Android 8.1, and can be reproduced for example by simply turning off wifi on the device for a moment (or otherwise disturbing network connectivity).

**Comment by willcl-ark** [comment]
Since this was reported:

* There have been no additional reports of occurance
* Lineage OS has been updated from v16.0 to v20.0
* Bitcoin Core has been updated from v0.20 to v24.0.1
* libevent in Bitcoin Core depends was [updated](https://github.com/bitcoin/bitcoin/pull/21991) to 2.1.12-stable (which their script [appears to use](https://github.com/termux/termux-packages/blob/master/packages/bitcoin/build.sh#L25))

(and is anyone still running a full node on Android phone)

@MarcoFalke perhaps this can be closed?
