### ISSUE TITLE
signrawtransactionwithwallet fails to sign non-wallet inputs (0.20 only; before/after already fixed)

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#19737]
#17204 introduced a test that uses `signrawtransactionwithwallet` to sign a non-wallet input (providing the necessary solution as a param).

At least 0.20 didn't allow this. Bisect reveals that the behaviour change was in bde7c9fa38775a81d53ac0484fa9c98076a0c7d1 (part of #16528, descriptor wallets).

Is this change intended behaviour, or a bug?

**Comment by fanquake** [comment]
cc @jonatack

**Comment by achow101** [comment]
This is intended behavior and actually appears to be a regression in 0.20.

Backporting the test to 0.19 makes it pass. The failure in 0.20 looks to be because we aren't correctly handling the condition where a transaction being signed is already fully signed and it's just falling through to a `return false`. I guess this was accidentally fixed.
