### ISSUE TITLE
Spurious CI failure: cirrus CI timeout

### ISSUE THREAD

**Issue by sdaftuar** [bitcoin/bitcoin#19864]
Not sure if this is the right place to report it, but I saw this job failure today:
https://cirrus-ci.com/task/6078479919742976

I'll try re-running but opening this issue in case others see this kind of thing too.

**Comment by MarcoFalke** [comment]
There are multiple options:

* Do nothing and reset builds because the timeouts are intermittent.
* Move to self-hosted runners/ci and hope they run more stable and don't time out. (Downside is that this needs maintenance)
* Remove tests until no timeouts can be observed. (Will be hard to decide which tests to drop, especially considering that our current tests don't even result in adequate coverage)
* Remove tsan test completely and run it once before every release. (Downside is that failures will be fixed last minute or not at all)
* Remove tsan test and run it nightly. (Downside is that failures will be fixed after they happened, nightly builds will fail until they are fixed)
* Pay cirrus ci to have no 2h timeout. (Downside: Forked repos would time out)
* Temporarily bump the CPU and memory to buy time.
* Something else ... ?
