### ISSUE TITLE
Use orange icon for bitcoin account

### ISSUE THREAD

**Issue by Bosch-0** [bitcoin/bitcoin#20098]
Currently the account that hosts this repo and several others uses the black bitcoin icon which (as far as I'm concerned) is the Bitcoin Core brand icon. Would it not be more on-brand to use the orange icon for this account and the black Bitcoin Core icon for the bitcoin-core account? A discussions was had several weeks ago around branding here https://github.com/bitcoin-core/gui/issues/89 

Visualized below:

![Group 114](https://user-images.githubusercontent.com/55287964/95338088-1fdc5b00-08e5-11eb-8c5f-208e55df038b.png)

[Here](https://www.figma.com/file/4dO1LqPY0WAgp5d1Bz3U8j/Bitcoin-Core-Designs?node-id=16%3A14) is the orange icon on Figma that can be exported (as SVG, PNG, JPG etc.) and used.

Posted an issue over at https://github.com/bitcoin-core/gui/issues/100 regarding changing the orange icon to black for the bitcoin-core account.

**Comment by MarcoFalke** [comment]
The bitcoin account hosts the Bitcoin Core repository, so I don't think anything needs to change here?

**Comment by Bosch-0** [comment]
Updated OP with a visualization. 

Although it does host that repo is the bitcoin account not more representative of Bitcoin the entity (or network) rather than Bitcoin Core the entity? If the icon is changed for bitcoin-core https://github.com/bitcoin-core/gui/issues/100 and not here both icons would be black, which would be confusing from a brand perspective. 

What is the reasoning behind having the bitcoin, bips libbase58 and libblkmaker repos separate from the bitcoin-core account? Apologies, I am probably missing some context here.

**Comment by MarcoFalke** [comment]
The bips repo shouldn't be under bitcoin-core/bips because it is about Bitcoin Improvement Proposals, not Bitcoin Core Improvement Proposals. Also, `libbase58` and `libblkmaker` are independent from Bitcoin Core, so they shouldn't be hosted under bitcoin-core either. The reason bitcoin/bitcoin hasn't been moved to bitcoin-core is that some external services/scripts might depend on it living under bitcoin/bitcoin. GitHub allows redirects to be created, but I don't know how well they work.

Closing for now, because the topics have been discussed (and concluded) in the past already.
