### ISSUE TITLE
Remove `reqSigs` from output of decoderawtransaction and other RPCs

### ISSUE THREAD

**Issue by sanket1729** [bitcoin/bitcoin#20102]
IRC logs
> sanket1729: How can `decoderawtransaction` RPC know reqSigs if the output scriptpubkey is p2sh/p2wsh? I think it is returning 1 everytime. 
sipa: sanket1729: it only works for bare multisig
sipa: we should probably just remove it

The output parameter for `reqSigs` is confusing as it outputs `1` for all scripts but bare multisig in the scriptpubkey. Considering the limited applicability of `reqSigs` and (slightly) confusing output(`1`) in almost all cases, I think it is best if we remove it. 

I don't have the bandwidth to tackle this, so opening up the issue for book-keeping. I also think this is a good first issue for new contributors if there are no concept NACKs.

Affected RPCs:

- gettxout

- decodescript

- decoderawtransaction

- getrawtransaction

**Comment by MarcoFalke** [comment]
Another option to removing it would be to only have it present when a bare multisig is found

**Comment by NicolasDorier** [comment]
meh, nobody care about bare multisig anymore anyway

**Comment by MarcoFalke** [comment]
Ok, made it a "good first issue" to remove.

#### Useful skills:

* Bitcoin Script
* Bitcoin Core RPC server

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by prayank23** [comment]
I can work on this. Removing L1107 https://github.com/bitcoin/bitcoin/blob/dde104963b3ba2e24bb3b383351ddcbef52a0240/src/rpc/blockchain.cpp#L1107 should fix `gettxout` I guess or maybe need to make more changes. 

Was looking at this PR for reference: https://github.com/bitcoin/bitcoin/pull/19646

**Comment by sanket1729** [comment]
Agreed, nobody uses bare multi-sig. We should probably remove it. 

Hi @prayank23, here is a possible workflow that I would use.

- You can start by looking at all the RPCs listed in the remove the `reqSigs` field from that. 
- You can also grep for `reqSigs` in the root directory to find more occurrences and remove them if appropriate. 
- Try to run unit tests and let the failures guide you where things need to the fixed/removed. 
- My suspicion is that we can also remove the code that has the bare multisig logic that computes this field. 
- You may also need to run python functional tests (see `test/functional`) to check if there are tests that are broken because of this. 
- Since, this field is being removed, try to find comments around the code are removing and remove those too.

**Comment by prayank23** [comment]
@sanket1729 I made changes in https://github.com/prayank23/bitcoin/commit/33d3757688b5269a1d033aea8aae7e358141dc4d

But getting errors while running the command `make check` because tests are failing even though I removed `reqSigs` from json files used for testing except txcreatemultisig1.json (wasn't sure about it):



<pre>
ERROR - Output formatting mismatch

2020-10-10 22:15:17,871 - ERROR - FAILED_TESTCASES:
['Deletes a single input from a transaction (output in json)',
 'Deletes a single output from a transaction (output in json)',
 'Adds an nlocktime to a transaction (output in json)',
 'Creates a new transaction with three inputs and two outputs (output in json)',
 'Create a new transaction with a single output script (OP_DROP) in a P2SH (output as json)',
 'Create a new transaction with a single output script (OP_DROP) in a P2WSH (output as json)',
 'Create a new transaction with a single output script (OP_DROP) in a P2SH, wrapped in a P2SH (output as json)',
 'Creates a new v1 transaction with a single input and a single output, and then signs the transaction (output in json)',
 'Creates a new transaction with a single pay-to-witness-pubkey output (output as json)',
 'Creates a new transaction with a single pay-to-pub-key output, wrapped in P2SH (output as json)',
 'Creates a new v1 transaction with one input, one address output and one data output (output in json)',
 'Creates a new transaction with one input, one address output and one data (zero value) output (output in json)',
 'Creates a new transaction with one input with sequence number and one address output (output in json)',
 'Adds a new input with sequence number to a transaction (output in json)',
 'Creates a new transaction with a single 2-of-3 multisig output (output in json)',
 'Creates a new transaction with a single 2-of-3 multisig in a P2SH output (output in json)',
 'Creates a new transaction with a single 2-of-3 multisig in a P2WSH output (output in json)',
 'Creates a new transaction with a single 2-of-3 multisig in a P2WSH output, wrapped in P2SH (output in json)',
 'Uncompressed pubkeys should work just fine for non-witness outputs']
</pre>

**Comment by nginocchio** [comment]
Hello, does this issue still require work to be done on it?

**Comment by sipa** [comment]
It is being worked on in #20286.

**Comment by josex3000xp** [comment]
Great post! I've read something about it in https://www.mintme.com  I like reading information of this kind and on this side you may find.
