### ISSUE TITLE
qa: Intermittent error in wallet_resendwallettransactions.py

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#20143]
https://travis-ci.org/github/hebasto/bitcoin/jobs/735078189#L5109:

```
AssertionError: Predicate ''''
        def test_function():
            if check_connected:
                assert self.is_connected
            return test_function_in()
''' not true after 240.0 seconds
```

**Comment by MarcoFalke** [comment]
The scheduler thread runs in a different thread than the RPC thread and message handling thread, as the `mockscheduler` call is non-blocking and there is no way to observe to-be-trickled txids over RPC or P2P, the only way to synchronize this event I see is over `assert_debug_log`. Fixed in #20112 


Longer term, `mockscheduler` should probably be blocking until all events that are scheduled in the past have been executed.
