### ISSUE TITLE
Hardcoded seeds for Torv3 addresses

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#20239]
For the 0.22 release we'll want to start hardcoding Torv3 addresses instead of (or in addition to) Torv2.

The biggest challenge here is not how to hardcode them, although that will require a few minor script and code changes, but how to collect them. The release process is to get the addresses from DNS seeders, however these currently don't support the `addrv2` message nor Torv3 addresses in the first place. Nor do they really have a need to.

**Comment by Saibato** [comment]
We would have non of this problems, if we had just encoded one v3 address in 3 or 4 ipv6 ADDR messages with some checksum and hash sort indexes btw.

But its not to late to use this method to hard encode them and have with some minor changes in the seeders software a DNS A/AAAA  compatible way,
If we don't want to use SRV records, what is even a greater hassle, 

On the other hand, since we seed with Tor only anyway with ADDR or ADDRv2 messages we learn form the first ipv4 or ipv6 DNS response when we try to resolve the seeders FQDN.
We could just call them directly over a Tor onion address,  its almost the same outcome.
and we would stay in Tor and not use exit nodes,
Some or one seeder must only update one of there nodes and learn from the ADDRv2 messages.
That should build up fast if ppl use 0.21.and gossip ADDRv2
If we call then these v3 node directly on first virgin bootstrap, by  just add them to the seeds list like we do with signet we stay in Tor and bootstrap with learned v3 addresses and leak even less,
For storage in the code we would just add onion as the fqdn in the list that is only a miner change, since vseeds can hold even now fqdn like the seeders name.

**Comment by laanwj** [comment]
> We would have non of this problems, if we had just encoded one v3 address in 3 or 4 ipv6 ADDR messages with some checksum and hash sort indexes btw.

I don't think there's any guarantee for intermediate DNS servers to keep the results in the same order, or even not to remove results. But it doesn't matter, it's a red herring in the first place: there is no a reason to serve them over DNS. A node behind Tor can't do the kind of DNS lookup that requires multiple results.

**Comment by Saibato** [comment]
>  A node behind Tor can't do the kind of DNS lookup that returns multiple results.

Exactly that's my point all the time and its even hard to say if a rouge exit node give us even the first entry correct when we resolve th seeders names or give us even a correct socket on return to a real bitcoin full node and because Tor only nodes would have and do bootstrap anyway over ADDR messages of the socket returned when we ask for seeder names or if we use the hard encoding, if we say -dnsseed=0, we could have just called seeders Tor addresses full nodes in Tor diretly and have let all other ip4/ip6 nodes us dns A/AAAAA records as is and would be backwards compatible?
