### ISSUE TITLE
Invalid json from getwalletinfo when scanning is in progress

### ISSUE THREAD

**Issue by shesek** [bitcoin/bitcoin#20297]
I'm sometimes getting an invalid json reply from `getwalletinfo` when rescanning is in progress.

The invalid part is this: `"scanning":{"duration":19,"progress":}}` (no value for `progress`).

I can't reliably reproduce this, but I did manage to run into this 3 times now (once every 10-20 attempts or so).

I'm running v0.20.0 and testing against a regtest instance. This happens while doing a batched `importmulti` of 2000 addresses (none of which have history).

**Comment by shesek** [comment]
from #bitcoin-core-dev:

    <sipa> shesek: my theory is that somehow the begin and end of the rescan have the same progress value, so there is a division by zero

**Comment by theStack** [comment]
@shesek: Thank you for reporting this problem! sipa's theory was right, this happens whenever the begin and end of the rescan have the same progress value (which is the case for single block rescans). It can be easily reproduced by continuosly performing single block range rescans and then calling the `getwalletinfo` RPC a few times.  I opened a PR to fix the problem (#20344) by assigning the progress value directly for this special case instead of using the formula, see its description for more details.

**Comment by shesek** [comment]
@theStack Thanks for swiftly investigating and fixing this!
