### ISSUE TITLE
Build with MSVC missing boost dependency

### ISSUE THREAD

**Issue by tobysharp** [bitcoin/bitcoin#20792]
**While following the build instructions in `build_msvc/README.md`, I encountered an unexpected missing dependency issue involving e.g. boost/optional.hpp.**

The readme file `build_msvc/README.md` states
> The `msbuild` project files are configured to automatically install the `vcpkg` dependencies.

I was expecting that following the steps listed in this file, I would be able to build Bitcoin Core for Windows using Visual Studio.

It seems that the dependencies (or some at least) haven't been automatically installed, as the doc implies. Should they be manually installed? If so, let's amend the build instructions accordingly.

Here is an example of the compile error. Boost has not been installed at this point.

> 1>------ Build started: Project: libbitcoin_wallet, Configuration: Release x64 ------
> 1>wallet.cpp
> 1>D:\dev\bitcoin\src\optional.h(10,10): fatal error C1083: Cannot open include file: 'boost/optional.hpp': No such file or directory
> 1>Done building project "libbitcoin_wallet.vcxproj" -- FAILED.

Cloned from github today. 

`git checkout v0.21.0rc3`

Windows 10 x64
Visual Studio 2019 v 16.7.7

Probably just needs an update to the Windows build documentation?

**Comment by tobysharp** [comment]
I found more detailed instructions at https://github.com/fanquake/core-review/blob/master/windows.md and will try this to resolve the issue next.

**Comment by soma42** [comment]
@tobysharp try:
```
vcpkg install --triplet x64-windows-static berkeleydb boost-filesystem boost-multi-index boost-signals2 boost-test boost-thread libevent[thread] zeromq double-conversion
vcpkg integrate install
py -3 build_msvc\msvc-autogen.py
msbuild /m build_msvc\bitcoin.sln /p:Platform=x64 /p:Configuration=Release /t:build```


also be sure you are actually building x64 and not x86.

**Comment by tobysharp** [comment]
@soma42 This appears to work just fine. After also downloading the appropriate Qt build, my build completed as expected. Would you like me to submit an edit to the msbuild doc?

**Comment by soma42** [comment]
@tobysharp what I posted to you were the instructions from v0.20. I think since then, changes were made that make this step unnecessary. There may be differences when building with msbuild and from inside Visual Studio 2019. I cannot really say if the new method does or not work correctly, I'd have to try that on a clean machine.

It would be better the maintainer of the msvc build looks at this and decides if there is an issue in the build scripts or documentation...

**Comment by tobysharp** [comment]
For clarity, I tried the build originally both using the command line and using the Visual Studio IDE, and both methods produced the same errors. After executing the two commands given by @soma42 above in the appropriate directories, the build completed fine. The key difference was the two `vcpkg` lines:

```
vcpkg install --triplet x64-windows-static berkeleydb boost-filesystem boost-multi-index boost-signals2 boost-test boost-thread libevent[thread] zeromq double-conversion
vcpkg integrate install
```

These should probably be (re-)added to the `build_msvc\readme.md` file.

**Comment by adamjonas** [comment]
@sipsorcery mind taking a look?

**Comment by sipsorcery** [comment]
@tobysharp it could be your version of vcpkg is too old. The ability to install the dependencies from a manifest file was only added to vcpkg late last year.

You can check your version using:

````
build_msvc> vcpkg version
Vcpkg package management program version 2020.11.12-nohash

See LICENSE.txt for license information.
````

The idea with the manifest file is that instead of needing to manually enter the list of dependencies on the command line you can do:

````
build_msvc> vcpkg install --triplet x64-windows-static
````

If your vcpkg is new enough it should automagically install the dependencies from the [vcpkg.json](https://github.com/bitcoin/bitcoin/blob/master/build_msvc/vcpkg.json) file into the `build_msvc\vcpkg_installed` directory. This has the added advantage of keeping the dependencies separate from any other vcpkg dependencies you might install in the future (something which does become a problem if you use vcpkg a lot).

And in fact you don't need to call vcpkg at all since it will add tasks to `msbuild` to look for a manifest file and call the install command as part of the build. 

If you can confirm whether or not this is your problem I can fix the instructions to note the required vcpkg version.

**Comment by MarcoFalke** [comment]
Let me know if this is still an issue
