### ISSUE TITLE
Binding to multiple anonymous networks (esp. I2P)

### ISSUE THREAD

**Issue by grarpamp** [bitcoin/bitcoin#2091]
Suggesting that bitcoind be able to bind to multiple anonymous (and regular) networks at once.
Inbound queries would reply out the same bind they were received on.
Outbound initiates/broadcasts might be sent from all binds, or if impossible or out of context, to a specified one.
Goal: Allow one daemon to service all networks [1] at once.
[1] IPv4, IPv6, Tor, I2P, Phantom

Note it should always be made possible option to not bind to '*' (all addresses),
but only to ones supplied.

I'm not certain if -externalip can do this. -discover in doc/Tor.txt says:
'If you want to run a dual stack, reachable from both Tor and IPv4 (or IPv6), you'll need to either pass your other addresses using -externalip'
which implies maybe it can, but offers no syntax. Maybe it is a doc bug.

-externalip=foo.onion (or Tor's OnionCat IPv6 /48)
-externalip=bar.i2p (or I2P's GarliCat IPv6 /48)
-externalip=6addr (.phantom / interpreted from its IPv6 /48 prefix)
-externalip=6addr
-externalip=4addr

Also, since socks context via -proxy breaks down with more than one such anonymous net, there would also need to be:
-tor=host:port (in Tor, in bitcoin)
-i2p=host:port (in I2P, not in bitcoin)
-phantom=host:port (not in Phantom, not in bitcoin)
and maybe
-proxyipv4=host:port
-proxyipv6=host:port

**Comment by str4d** [comment]
Note that in addition to being necessary for I2P support, this change will be necessary to migrate to Tor's next-gen onion services (which will have addresses that are the same length as I2P's B32s).

**Comment by laanwj** [comment]
> cjdns cannot use this method

Nit: Not true (anymore?) - cjdns uses [a subset of IPv6 addresses](https://en.wikipedia.org/wiki/Cjdns#Address_Generation), and bitcoind works fine over it.

**Comment by laanwj** [comment]
> Note that in addition to being necessary for I2P support, this change will be necessary to migrate to Tor's next-gen onion services (which will have addresses that are the same length as I2P's B32s).

I'm planning to work on a BIP for this. Now that Tor v3 hidden services are becoming more common, I think it's about time to extend the P2P protocol with a new kind of `addr` message that supports 256-bit network address (+ 8 bit network id + 16 bit port + ? bit service flags + 32 bit last seen time) instead of just the current 128 bit IPv6.

There was some discussion of this in the IRC meeting today:
https://botbot.me/freenode/bitcoin-core-dev/2018-05-31/?msg=100660820&page=4

Some additional ideas that came up:
- No longer embed Tor services in IPv6 onioncat (could keep doing this for HS v2, but just as well have separate network class for that)
- How much to reserve for service bits (or whether it should be more than 32 as currently) wasn't clear yet.
- There were questions whether something should be added with regard to BIP151 (encryption), such as gossiping pubkeys - but probably not, as this is trivial to MiTM.
- Using new `addr` to gossip the storage range of blocks for pruning - however, it is not clear how this would be more useful than NODE_NETWORK_LIMITED, given that ranges tend to change faster than nodes can gossip.

While looking around I found that there was some discussion in the zcash repository about this, but no concrete proposals yet:
https://github.com/zcash/zcash/issues/1111
https://github.com/zcash/zcash/issues/3051
(and see also discussion in #9214)

**Comment by laanwj** [comment]
I've made a start with the addrv2 BIP spec here: https://gist.github.com/laanwj/4fe8470881d7b9499eedc48dc9ef1ad1
Will start on a reference implementation next, and if that seems feasible post to the mailing list.

@str4d it would be awesome if you could have a look some time if the I2P parts make sense.

**Comment by Fonta1n3** [comment]
> I've made a start with the addrv2 BIP spec here: https://gist.github.com/laanwj/4fe8470881d7b9499eedc48dc9ef1ad1
> Will start on a reference implementation next, and if that seems feasible post to the mailing list.
> 
> @str4d it would be awesome if you could have a look some time if the I2P parts make sense.

Is it possible to also add tor V3 authentication so that attacking tor nodes over p2p becomes infeasible. Currently with V2 there seems to be a lot of attack vectors, adding the native V3 auth would go a long way to preventing any future attack vectors.

**Comment by Fonta1n3** [comment]
> > Note that in addition to being necessary for I2P support, this change will be necessary to migrate to Tor's next-gen onion services (which will have addresses that are the same length as I2P's B32s).
> 
> I'm planning to work on a BIP for this. Now that Tor v3 hidden services are becoming more common, I think it's about time to extend the P2P protocol with a new kind of `addr` message that supports 256-bit network address (+ 8 bit network id + 16 bit port + ? bit service flags + 32 bit last seen time) instead of just the current 128 bit IPv6.
> 
> There was some discussion of this in the IRC meeting today:
> https://botbot.me/freenode/bitcoin-core-dev/2018-05-31/?msg=100660820&page=4
> 
> Some additional ideas that came up:
> 
> * No longer embed Tor services in IPv6 onioncat (could keep doing this for HS v2, but just as well have separate network class for that)
> * How much to reserve for service bits (or whether it should be more than 64 as currently) wasn't clear yet.
> * There were questions whether something should be added with regard to BIP151 (encryption), such as gossiping pubkeys - but probably not, as this is trivial to MiTM.
> * Using new `addr` to gossip the storage range of blocks for pruning - however, it is not clear how this would be more useful than NODE_NETWORK_LIMITED, given that ranges tend to change faster than nodes can gossip.
> 
> While looking around I found that there was some discussion in the zcash repository about this, but no concrete proposals yet:
> [zcash/zcash#1111](https://github.com/zcash/zcash/issues/1111)
> [zcash/zcash#3051](https://github.com/zcash/zcash/issues/3051)
> (and see also discussion in #9214)

Is it possible to also add tor V3 authentication so that attacking tor nodes over p2p becomes infeasible. Currently with V2 there seems to be a lot of attack vectors, adding the native V3 auth would go a long way to preventing any future attack vectors.

**Comment by adamjonas** [comment]
Given that [BIP155](https://github.com/bitcoin/bips/blob/master/bip-0155.mediawiki), #18884 (completed) and #20685 (in-progress) have all moved forward since this was last commented on, this can probably be closed.
