### ISSUE TITLE
Could someone PLEASE change crass "Done loading" to "Finished Loading". A simple change

### ISSUE THREAD

**Issue by PigletBoy** [bitcoin/bitcoin#21034]
Every time I start core I cringe at the message.

**Comment by PigletBoy** [comment]
I know that is trivial, but for a product like this it is a minor, simple change that will appease grammatically correct English speaking
users.

**Comment by michaelfolkson** [comment]
There are 63 [results](https://github.com/bitcoin/bitcoin/search?p=6&q=%22done+loading%22&type=code) when you search for "Done loading" in the repo (mostly due to foreign language translations). I can't imagine this is a priority for GUI devs. Plus this is the wrong repo. The Core GUI repo is [here](https://github.com/bitcoin-core/gui).
