### ISSUE TITLE
Modify `testmempoolaccept` to handle client's `max_raw_tx_fee` check failure

### ISSUE THREAD

**Issue by ariard** [bitcoin/bitcoin#21074]
See https://github.com/bitcoin/bitcoin/pull/21062#discussion_r568583132

**Comment by MarcoFalke** [comment]
testmempoolaccept handles this case since it was written. See also the test

https://github.com/bitcoin/bitcoin/blob/f72d80b07af8ecbb2f9df1e87344eb465186f19d/test/functional/rpc_rawtransaction.py#L478-L480

**Comment by MarcoFalke** [comment]
Note the reason has been changed from `absurdly-high-fee` to `max-fee-exceeded`

**Comment by ariard** [comment]
@MarcoFalke As of ea96e17, `testmempoolaccept`'s "allowed" field is documented "If the mempool allows this tx to be inserted". Your transaction might be mempool valid but doesn't pass the client belt-and-suspender, a different check.

This is ambiguous and IMHO we should have a different result field to dissociate cleanly. And also nicely return fees to offending caller and such allow correction ?

**Comment by MarcoFalke** [comment]
> As of ea96e17, testmempoolaccept's "allowed" field is documented "If the mempool allows this tx to be inserted".

That is the case since the call was added in commit b55555da3e25a47f1e7fced7f09d4f0bf8198624.


> we should return allowed=true in that case.

That'd be a breaking change, so I'd rather not do that.

> This is ambiguous

This is documented, so shouldn't be ambiguous:

```
2. maxfeerate      (numeric or string, optional, default=0.10) Reject transactions whose fee rate is higher than the specified value, expressed in BTC/kB
```

Maybe you are asking for the reject reason to be better documented in that case? Simply checking the reject reason should be sufficient in this case to dissociate cleanly.

**Comment by glozow** [comment]
Conceptually, I agree that the information given isn't as precise as it could be. If we could start from scratch, I would do it differently. The idea for #19339 not changing `allowed` from False to True was, as @MarcoFalke said, because that'd actually be a breaking change, so it just changes the reject reason instead. I don't think users would be surprised by the behavior given current documentation.

Moving forward, if I were to propose something, I'd maybe have `allowed` represent "everything ok," and then for "allowed=False" add a `problem-type` field for `CONSENSUS`, `MEMPOOL_POLICY`, `USER_CONFIG`, or `UNFINISHED_VALIDATION`. Just throwing the idea out there.

**Comment by Modusto253** [comment]
https://api.blockchair.com/bitcoin/addresses/balances?
https://api.blockchair.com/{btc_chain}raw/block?{:height}[],...,{:hash}[]
https://api.blockchair.com/{:btc_chain}/blocks?{:query}
https://api.bitcoin.com/{:eth_chain}/dashboards/block/{:hash}[]
https://api.bitcoin.com/{:eth_chain}/dashboards/blocks/{:height}][,...,{:height}[]
https://api.blockchair.com/{eth_chain}/dash
