### ISSUE TITLE
Issues with compiling with bdb 

### ISSUE THREAD

**Issue by josephkniest** [bitcoin/bitcoin#21143]
After downloading and installing the bdb dependency in the contrib/ dir, I try this:

./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"

checking for natpmp.h... no
checking for boostlib >= 1.58.0 (105800)... yes
checking whether the Boost::System library is available... yes
configure: error: Could not find a version of the Boost::System library!

I have already installed boost with

"apt-get install -y libboost-dev"

I've been following this doc:

https://jonatack.github.io/articles/how-to-compile-bitcoin-core-and-run-the-tests

**Comment by fanquake** [comment]
> "apt-get install -y libboost-dev"

This won't work, because it wont install Boost System. Our [docs](https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#dependency-build-instructions) list the required boost dependencies: `libboost-system-dev libboost-filesystem-dev libboost-test-dev libboost-thread-dev`. You should actually install them if you're trying to build Bitcoin Core.

In any case, now that you're running into issues following instructions that are not in this repository, please don't open issues here.
