### ISSUE TITLE
guix: Brainstorm w/re guix.sigs repo layout

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#21273]
A few ideas for modernizing the layout as we're creating a new `guix.sigs` repo:

1. Hierarchy would look something like: `guix.sigs/$TAG/$HOST(-codesigned)/$SIGNER/SHA256SUMS`
2. We can move `contrib/gitian-keys` to this new `guix.sigs` repo

These are just some initial thoughts, please let me know if this sounds reasonable without bike-shedding 😬

**Comment by achow101** [comment]
I don't think the only signature should be the commit. It makes it harder to verify a particular version after the fact because then you involve git and having to find the commit in the git history. Not to mention the fact that occasionally, the hashes file can change if someone does a rebuild (e.g. after clearing caches). I like the current method of a hashes file and then `.sig` of that file. It would just be a `SHA256SUMS.sig` in addition to the `SHA256SUMS`.

**Comment by dongcarl** [comment]
> I don't think the only signature should be the commit...

True!

**Comment by dongcarl** [comment]
Layout is now implemented in: #21462
