### ISSUE TITLE
"Unable to parse settings.json" at startup after disk was full

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#21340]
This was reported to me by someone who had a crash issue after the disk was full, ostensibly unable to write `settings.json` and ending up with a truncated file. The solution was obvious in retrospect: delete it. But not everyone is going to figure this out by themselves.

Should this error be fatal at all? Could it be ignored and logged? Or is a warning then deleting it better (at least in the GUI, that's harder to do for the daemon).

Another thing to look into might be to write the file atomically so that this doesn't occur.

**Comment by mattwilson888** [comment]
So the `settings.json` file is becoming corrupted after the disk is full? That seems like a problem which should be avoided. I'm not sure deleting it, and removing any settings which may be important to the user should be the official solution.

**Comment by laanwj** [comment]
Yes, it is a problem that should be avoided, but even then it can still happen and there needs to be a way to recover. I do agree silently deleting it would not be a good thing. A dialog at startup to continue with "reset settings" might do the trick better.

**Comment by ryanofsky** [comment]
I think bitcoin-core/gui#379 should resolve this. It clarifies the error and adds an option in the gui to reset the file

**Comment by kristapsk** [comment]
> So the `settings.json` file is becoming corrupted after the disk is full? 

When disk is totally full on Linux, any file randomly can be truncated to 0 size (the one you will try to overwrite at that moment). Guess solution could be to rename old file to temporary name before writing the new one and deleting old one only after the new one is saved correctly?

**Comment by ryanofsky** [comment]
> When disk is totally full on Linux, any file randomly can be truncated to 0 size (the one you will try to overwrite at that moment). 

Interesting. Is this documented somewhere? It definitely suggests regardless of any write errors that the settings read code should be treating an empty file the same as a non-existent file, and just ignoring it instead of triggering a fatal error.

This is an easy change to make but I'd also be curious to hear from @laanwj if he knows whether the file was truncated to size 0.

> Guess solution could be to rename old file to temporary name before writing the new one and deleting old one only after the new one is saved correctly?

I could be misunderstanding but I think this describes what happens currently: https://github.com/bitcoin/bitcoin/blob/df2b5dadfb2dc21b05e5a60b71987fb5b96201f5/src/util/system.cpp#L572-L579, but maybe there could be additional syncs or checks added?

**Comment by kristapsk** [comment]
> Interesting. Is this documented somewhere?

Haven't looked at the kernel code in detail for this, just my personal experience (had old blog written in PHP long long time ago where everything was saved in text files instead of proper database and file got truncated to zero bytes when partition ran out of space, IIRC code just read everything into memory, modified and then tried to overwrite old file).

**Comment by ryanofsky** [comment]
> It definitely suggests regardless of any write errors that the settings read code should be treating an empty file the same as a non-existent file, and just ignoring it instead of triggering a fatal error.

Thinking about this more, I disagree with what I wrote earlier. Even if a settings file is truncated to size 0 and the old settings are completely lost (as opposed to partially corrupted), I still think the safest thing for `bitcoind` to do is refuse to start until the corrupt file is cleared away. It would unsafe to assume no important settings were saved before the corruption happened and just start anyway, because there could have been critical settings affecting security (sandbox settings) or privacy (tor settings, wallet settings) or performance (pruning, coins cache size) that would be important not to ignore before starting. So I don't think it would be good to treat a size 0 settings.json file differently than any other corrupt settings.json file.

I also don't know of a way of avoiding corruption when writing to a full disk that would work better then the current approach of renaming a new file over the old one. Maybe bitcoin should generally shutdown or avoid writing things if disk space gets too low, though.

I think since `bitcoind` is non-interactive, the best thing it can do on startup when settings are corrupt is show an error about the corruption, and exit like it is currently doing. Since `bitcoin-qt` is interactive, I think the change in bitcoin-core/gui#379 adding a dialog button to reset settings provides a decent way to recover there, and should resolve this issue

![new-read-error](https://user-images.githubusercontent.com/7133040/124977636-b669b400-dffe-11eb-8d35-02eda95f48c0.png)

**Comment by kristapsk** [comment]
Another thing - in this case `settings.json` was anyways "empty" (just `{ }`). Probably we should avoid creating it at all if there are no settings to save there?

**Comment by ryanofsky** [comment]
> Another thing - in this case `settings.json` was anyways "empty" (just `{ }`). Probably we should avoid creating it at all if there are no settings to save there?

I don't have a firm opinion on this, but the settings file is written on startup unconditionally (unless `-nosettings` is specified) to:

- Show an error message as early as possible if the file is not writable, instead of later when wallets are loaded or when settings are changing, so changes are not lost if there is a write error and problems can be addressed more easily.
- Help debug configuration issues. Let someone see what settings file is in use from the directory listing and file modification time and avoid confusion about what settings path is in use

**Comment by ryanofsky** [comment]
> Had this on a Debian based machine recently. This error isn't written in `debug.log` (makes sense, settings haven't been loaded yet, so you don't know location of a file), on Systemd based machines only way to see this error will be to `sudo su - bitcoin` and then manually try to launch `bitcoind` process. Which isn't too user friendly.

This seems bad. I would expect the message also to be written to stderr and show up in the journald log file. I noticed the command you used is `journalctl -u bitcoin` and maybe that should be `journalctl -u bitcoind`? But maybe also there is problem with the debian systemd file not capturing stderr. This seems like something that could be addressed and discussed further if you have more information and want to open an issue about the missing error.



> 
> ```
> $ sudo systemctl status bitcoind
> * bitcoind.service - Bitcoin daemon
>      Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
>      Active: activating (auto-restart) (Result: exit-code) since Wed 2022-07-20 10:00:17 CEST; 23s ago
>     Process: 1354 ExecStart=/usr/local/bin/bitcoind -daemon -pid=/run/bitcoind/bitcoind.pid -conf=/home/bitcoin/.bitcoin/bitcoin.conf -datadir=/home/bitcoin/.bitcoin -startupnotify=chmod g+>
> 
> Jul 20 10:00:17 hostname systemd[1]: bitcoind.service: Control process exited, code=exited, status=1/FAILURE
> Jul 20 10:00:17 hostname systemd[1]: bitcoind.service: Failed with result 'exit-code'.
> Jul 20 10:00:17 hostname systemd[1]: Failed to start Bitcoin daemon.
> $ sudo journalctl -u bitcoin
> -- Logs begin at Wed 2022-07-20 09:57:42 CEST, end at Wed 2022-07-20 10:00:26 CEST. --
> -- No entries --
> $ sudo su - bitcoin
> $ bitcoind -daemon -pid=/run/bitcoind/bitcoind.pid -conf=/home/bitcoin/.bitcoin/bitcoin.conf -datadir=/home/bitcoin/.bitcoin
> Error: Failed loading settings file:
> - Unable to parse settings file /home/bitcoin/.bitcoin/settings.json
> ```

**Comment by dongcarl** [comment]
One of my boxes running `v24.0.1` just encountered a low storage situation, and `/var/lib/bitcoind/settings.json` was truncated to 0 size.

From my `journalctl`:
```
Mar 20 11:33:05 hostname bitcoind[935629]: Error: Failed loading settings file:
Mar 20 11:33:05 hostname bitcoind[935629]: - Unable to parse settings file /var/lib/bitcoind/settings.json
Mar 20 11:33:05 hostname systemd[1]: bitcoind.service: Control process exited, code=exited, status=1/FAILURE
```

> This seems bad. I would expect the message also to be written to stderr and show up in the journald log file.

Unfortunately the current [`bitcoind.service`](https://github.com/bitcoin/bitcoin/blob/40e1c4d4024b8ad35f2511b2e10bf80c5531dfde/contrib/init/bitcoind.service) in the repo does not print logs to `journald`, which I think is unfortunate. Here's my fix: https://github.com/bitcoin/bitcoin/pull/25975
