### ISSUE TITLE
createmultisig with uncompressed pubkeys ignores value of addr_type enum

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#21368]
Tested in v0.21.0

```
createmultisig 1 '["04ceba29da1af96a0f2ef7cda6950b8be2baeb1adf12c0d5efebb70dbcaa086ba029cd82a0cfb8dedf65b8760cf271f2b8a50466bbf0b9339c5ffefbe2a4165326"]' p2sh-segwit
{
  "address": "3LfGXVPHtrC9A99JNiAPnygnQuPdpASvN3",
  "redeemScript": "514104ceba29da1af96a0f2ef7cda6950b8be2baeb1adf12c0d5efebb70dbcaa086ba029cd82a0cfb8dedf65b8760cf271f2b8a50466bbf0b9339c5ffefbe2a416532651ae",
  "descriptor": "sh(multi(1,04ceba29da1af96a0f2ef7cda6950b8be2baeb1adf12c0d5efebb70dbcaa086ba029cd82a0cfb8dedf65b8760cf271f2b8a50466bbf0b9339c5ffefbe2a4165326))#dyera70q"
}
```
same result for:
```
createmultisig 1 '["04ceba29da1af96a0f2ef7cda6950b8be2baeb1adf12c0d5efebb70dbcaa086ba029cd82a0cfb8dedf65b8760cf271f2b8a50466bbf0b9339c5ffefbe2a4165326"]' bech32
```

Best if this throws an error telling the user it won't make a nonstandard address.

**Comment by theStack** [comment]
At least according to the corresponding functional test this seems to be desired behaviour:
https://github.com/bitcoin/bitcoin/blob/1a4a9305c2d25eafa5ad5365b4daa2bd15fc6e05/test/functional/rpc_createmultisig.py#L81-L85
(one of the pubkeys in `keys` is in uncompressed form)

I agree though that we should rather throw an error here if we can't fulfill what the user desires, rather than silently changing the address type. Ping @achow101 who wrote this part of the test.

**Comment by achow101** [comment]
This is the expected behavior, but I suppose it is surprising to the user. Maybe we could add a warning to the `createmultisig` output that informs the user what happened?

**Comment by theStack** [comment]
Thanks for clarifying -- then at least warning the user is a good idea. But how? The only way I see is adding a "warnings" field to the RPC result, not sure this is in-line with out RPC design guidelines.

**Comment by achow101** [comment]
What we've done for other RPCs is to add a `warnings` field in the returned object.
