### ISSUE TITLE
windows: settings.json issue

### ISSUE THREAD

**Issue by asalentsvpns666** [bitcoin/bitcoin#21974]
i am trying to install bitcoin core but cant it keeps saying unable to open or save the settings.json file or somehting like this i have uninstalled and reinstalled ten times same thing i even tried putting it on my exteernal hard drive and had same issue how do i fix so i cna download and install bitcoin core?
![Capture](https://user-images.githubusercontent.com/58276498/118471637-95a37300-b6cd-11eb-9c1b-d6f140a58aa4.PNG)

**Comment by jonatack** [comment]
Hi @asalentsvpns666, which version of Bitcoin Core are you installing (from the downloaded binary or from source?), do you see a `settings.json` file in your data directory, and if yes, what permissions does that file have?

**Comment by MarcoFalke** [comment]
Generally, it is not recommended to set the datadir to a top level directory like `D:\`.

Does anyone know if the uninstaller effectively clears the gui persisted settings like `-resetguisettings` does?

**Comment by noberk** [comment]
@asalentsvpns666  Try to switch other disk, or using Virtual Machine?

**Comment by ryanofsky** [comment]
I thought bitcoin-core/gui#379 might help address this issue, but it doesn't really. All it might do is make the "Settings file could not be written" error dialog a little more readable.

I guess the ideal thing to do in the gui when the datadir exists but isn't writable would be to prompt the user and give a choice of whether to exit or choose a new data directory. This would require shuffling the qt init code a bit since the settings file is written after `Intro::showIfNeeded` is called.

**Comment by hebasto** [comment]
@asalentsvpns666

Could you a build from the current branch? If error persists, what is its description now?

**Comment by asalentsvpns666** [comment]
gave up and built my own yours has to many problems not worth the time. no
offense

**Comment by hebasto** [comment]
Could be closed?

**Comment by asalentsvpns666** [comment]
if you mean the support ticket yes
