### ISSUE TITLE
gui: 0.21.1 Recent transactions tab expands entire window beyond screen resolution

### ISSUE THREAD

**Issue by ZenulAbidin** [bitcoin/bitcoin#22246]
When a transaction is displayed in the Overview window on Bitcoin Core 0.21.1, the entire window stretches beyond the screen resolution depending on how many recipients there are in the transaction, even when not focuses on the Overview page. 1-recipient transactions inappropriately expand longer than normal but are still visible in its entirety, but 2 or more recipient transitions expand the tab - and the entire window with it - towards the right. Shrinking the window horizontally is disabled.

**Expected behavior**

The transaction tuple is truncated according to the window size with a maximum length computed for the "recent transactions":

(0.21.0 behavior): ![bitcoin core 0.21.0](https://i.imgur.com/gNc2HcC.png)

First transaction is a 1-recipient transaction, second one is a 2-recepient transaction and the rest are blocks mined from regtest -generate.  They are truncated if they are larger than the Qt tab size for "recent transactions"

**Actual behavior**

There is no limit to the length of the recent transactions tab and it forces the horizontal dimension of the window to be exactly the size of the longest transaction tuple listed in the recent transactions tab.

(0.21.1 behavior): ![bitcoin core 0.21.1](https://i.imgur.com/yCVCBt0.png)

The mined blocks transactions fit, but the 1-recipient transaction and the 2-receipient transaction stretch too far to the right, as if a size limit was not being set for the tab.

**To reproduce**

This issue can be consistently reproduced.

- Start bitcoind in regtest and in another terminal run `bitcoin-cli --regtest -generate 110` (this is to create bitcoins needed to make the problem transactions)
- Shut down bitcoind and open bitcoin-qt in regtest
- Generate two receiving addresses using Receive > Create New Receiving Address
- Go to the Send tab, add two receiving address and send them an arbitrary amount of BTC in a single transaction and press Send (the amount is irrelevant)

(at this point you may create another transaction to any address using one receiving address if you want, to compare the difference)

- Switch to Overview Tab to view the non-truncated transactions. Note that the window will already appear expanded if you simply open a wallet with such transactions.

**System information**

Bitcoin core 0.21.1 precompiled from bitcoincore.org, Linux KDE5 Ubuntu 20.04 running Qt 5.9.8, display resolution 1366x768

**Comment by hebasto** [comment]
It seem the behavior was changed in https://github.com/bitcoin-core/gui/pull/176.

@ZenulAbidin 

Could you move this issue into https://github.com/bitcoin-core/gui/issues?

**Comment by hebasto** [comment]
Fixed in https://github.com/bitcoin-core/gui/pull/365.

**Comment by jarolrod** [comment]
**Note:** Thanks for investigating and finding this regression. Next time you find something related to the GUI, please open it up in: https://github.com/bitcoin-core/gui

Confirming this regression on the `0.21.1` branch and so subsequently also on the current `master` branch

The screenshots below show the behavior of the `v0.21.0` tag when there are multiple addresses in the transactions list. Under the `Multi-Transaction` table you will note that the multiple transactions are loaded.

| Start           | Generate     | Multi-Transaction             |
| ----------- | ----------- | ------------------------ |
| ![0210-start](https://user-images.githubusercontent.com/23396902/122316247-82acda00-cee9-11eb-90ba-01e416dfb85e.png) | ![0210-gen](https://user-images.githubusercontent.com/23396902/122316256-893b5180-cee9-11eb-8cf5-47262c015742.png) | ![0210-multi](https://user-images.githubusercontent.com/23396902/122316263-8d676f00-cee9-11eb-924f-f64d0a7fc4e6.png) |

The screenshots below shows what happens if we take this wallet and open it with Bitcoin Core compiled from the `v0.21.1` tag vs opening it up with Bitcoin Core compiled from [#365](https://github.com/bitcoin-core/gui/pull/365):

| Open Wallet with 0.21.1 | Open Wallet with  [#365](https://github.com/bitcoin-core/gui/pull/365) | 
| ----------------------- | ---------------------------------------------------------------------- |
| ![0211-multi](https://user-images.githubusercontent.com/23396902/122316430-dd463600-cee9-11eb-8f7d-67dfcca59c45.png) | ![test-365-resize](https://user-images.githubusercontent.com/23396902/122316635-3dd57300-ceea-11eb-8b32-15a7f0dbeb3e.png) |

This confirms that commit [d476f41d5f16e3f9f6f59f358cb5649657081384](https://github.com/bitcoin-core/gui/pull/365/commits/d476f41d5f16e3f9f6f59f358cb5649657081384) of  [#365](https://github.com/bitcoin-core/gui/pull/365) fixes this issue.

**Comment by fanquake** [comment]
Moved to https://github.com/bitcoin-core/gui/issues/373.
