### ISSUE TITLE
use consistent bytes <-> hex-string conversions in functional test framework

### ISSUE THREAD

**Issue by theStack** [bitcoin/bitcoin#22605]
Right now in the functional test framework, conversions from hex-string to bytes and vice-versa are done in different ways:
- convert `bytes_obj` to hex-string: binascii.hexlify(bytes_obj), bytes_obj.hex()
- convert `hex_str` to bytes object: binascii.unhexlify(hex_str), binascii.a2b_hex(hex_str), bytes.fromhex(hex_str)

For consistency reasons, only the built-in way of using `bytes` (class) methods should be used (see also MarcoFalke's comment https://github.com/bitcoin/bitcoin/pull/22593#issuecomment-890918620):
- bytes.fromhex() (https://docs.python.org/3.7/library/stdtypes.html#bytes.fromhex)
- bytes.hex() (https://docs.python.org/3.7/library/stdtypes.html#bytes.hex)

This seems to be the most natural and modern way to do it, without a need to import any libraries, and the other ones using binascii should be replaced by those. As an example, see PR #22593 which replaced a helper `hex_str_to_bytes` (which in turn used binascii.unhexlify) with `bytes.fromhex()`. For quickly identifying instances the command `git grep binascii` can be used, though one would need to check that there is maybe uses of binascii that are still legit.

#### Useful skills:
- Python 3 basic skills, knowledge of fundamental data types string and bytes

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by theStack** [comment]
Would be nice if a maintainer could tag this as "good first issue"

**Comment by Zero-1729** [comment]
@theStack I'd like to take a shot at this.

**Comment by MarcoFalke** [comment]
@Zero-1729 Looks like this was already picked up in #22617

**Comment by Zero-1729** [comment]
Wow, didn't expect to see this 😂 (I assumed making my intentions public [here](https://github.com/bitcoin/bitcoin/issues/22605#issuecomment-891207706) was a good safeguard). In any case, it doesn't look like he nailed all the changes to the `test_framework`.

Nonetheless, I am not sure what to do with [this branch](https://github.com/Zero-1729/bitcoin/tree/test-remove-binascii-in-test-framework) now. But I might as well breakdown the changes here:

Removed all instances of `binascii` methods in the test framework. I also ran all the affected functional tests to ensure nothing broke.

This commit 91b5350119a160df3eaa4e6eaff4e9ede97a51e6 takes out all `binascii` calls and replaces them with `bytes.hex` and `bytes.fromhex` where appropriate. Certain changes to some files are based on the following realisation/assumption:

```
bytes.hex(data) == binascii.hexlify(data).decode()
bytes.hex(data).encode() == binascii.hexlify(data)
```

If the above is incorrect, the changes based on it can simply be discarded.

P.S.: Since some of the files modified in the branch are outside the `test_framework` they might need to be dropped to avoid the inevitable conflict with other existing PRs. There is a [parent branch](https://github.com/Zero-1729/bitcoin/tree/test-replace_binascii_fn_calls) with all these changes and more, intended to get rid of all instances of `binascii` in the repo, and making `git grep binascii` yields nothing.

**Comment by Saviour1001** [comment]
@Zero-1729 I tested your branch on my end and it works correctly. I would suggest to close #22617 and just consider <code>https://github.com/bitcoin/bitcoin/commit/91b5350119a160df3eaa4e6eaff4e9ede97a51e6</code> for fixing this issue.

**Comment by Zero-1729** [comment]
@Saviour1001 thanks for testing! I just opened the PR.

**Comment by MarcoFalke** [comment]
Not fixed completely: https://github.com/bitcoin/bitcoin/pull/22619#issuecomment-892899665

**Comment by Zero-1729** [comment]
@MarcoFalke Thanks for the edit.

@theStack The last usage of `binascii` is in the following Python code comment in [`src/test/serfloat_tests.cpp`](https://github.com/bitcoin/bitcoin/blob/master/src/test/serfloat_tests.cpp#L102:L110). Do I also tackle that, so `git grep binascii` no longer yields anything?

**Comment by Damian8610** [comment]
bc1q3zua40e2jxkt00mqss28pthk0ltaa5d07vgt94

**Comment by Damian8610** [comment]
Jjjj

**Comment by theStack** [comment]
> @theStack The last usage of `binascii` is in the following Python code comment in [`src/test/serfloat_tests.cpp`](https://github.com/bitcoin/bitcoin/blob/master/src/test/serfloat_tests.cpp#L102:L110). Do I also tackle that in the follow-up, so `git grep binascii` no longer yields anything?

Yes, I'd suggest to also tackle the Python code comment. Happy to review within the next days :)

**Comment by Zero-1729** [comment]
Just pushed the changes.
