### ISSUE TITLE
signrawtransaction returns "complete" : false  sometimes when it really is complete

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#2265]
When doing offline signing of unknown txins with the scriptpubkey provided on the command line signrawtransaction returns complete false when the transaction is really completed.

**Comment by kouloumos** [comment]
This issue is reported for txins unknown to bitcoin, i.e not in the mempool or blockchain, thus the scriptPubKey has to be provided explicitly. 

The existing functional tests at [`wallet_signrawtransactionwithwallet.py`](https://github.com/bitcoin/bitcoin/blob/master/test/functional/wallet_signrawtransactionwithwallet.py), [`rpc_signrawtransactionwithkey.py`](https://github.com/bitcoin/bitcoin/blob/master/test/functional/rpc_signrawtransactionwithkey.py) are already checking against this behavior and what is reported seems to not be an issue anymore or it's reproduction is more complicated.  I've also try to reproduce this manually on regtest but I still was not able to do so. 


Note: 

- The referenced [`signrawtransaction` ](https://bitcoincore.org/en/doc/0.16.0/rpc/rawtransactions/signrawtransaction/)RPC was fully removed in v0.18. and since replaced with `signrawtransactionwithkey` and `signrawtransactionwithwallet`.
- Functional tests for this RPC were introduced much later with https://github.com/bitcoin/bitcoin/pull/5937

**Comment by MarcoFalke** [comment]
> what is reported seems to not be an issue anymore or it's reproduction is more complicated.

Ok, I guess if it is not yet fixed, it can be reopened the next time someone has steps to reproduce.
