### ISSUE TITLE
walletcreatefundedpsbt fails unexpectedly with "insufficient funds"

### ISSUE THREAD

**Issue by GambolingPangolin** [bitcoin/bitcoin#22821]
I would like to use bitcoin core to track watch-only addresses and create PSBTs.  For my use case, I tried to use `walletcreatefundedpsbt` with fully specified inputs and outputs, mostly for the purpose of modifying the outputs to achieve a certain fee rate for the transaction.  I define outputs with pre-fee amounts, then set `fee_rate` and `subtractFeeFromOutputs`.

**Expected behavior**

The RPC call should succeed and give me a PSBT where each output amount is a little less than the argument amount, to cover the fee.

**Actual behavior**

The call fails with "Insufficient funds".  If I use `getnewaddress` and fund an output paying to this address instead, the call works as expected.  The problem only appears when the output I am trying to spend is watch-only.

**To reproduce**

This script demonstrates the problem in a minimal scenario: https://gist.github.com/GambolingPangolin/587c46e9e5421a5401973406a0869519

**System information**

Bitcoin Core v0.21.1 downloaded from bitcoincore.org.

Ubuntu 20.04

**Comment by achow101** [comment]
I don't think there is any bug here, just a misunderstanding of how the software works.

There are a few possible issues with the provided script that could cause an insufficient funds message.

First, your input specification could be incorrect. You have specified `"vout": 0`, but there is no guarantee that the UTXO you want is at index 0. If the UTXO is not in the wallet, then the wallet will not know anything about it and cannot create the transaction.

Second, You have only imported the address, not the public key. The wallet does not have enough information to estimate the size of the transaction so it is unable to choose inputs. You will need to import a public key rather than just the address.

**Comment by GambolingPangolin** [comment]
@achow101 Thanks for your comments!

My example script does indeed have the incorrect `vout` configured.  I corrected it and can confirm that when the outpoint is correct (known via the call to `listtransactions`), the call to `walletcreatefundedpsbt` fails with the same error.  

Your second point makes a lot of sense.  I was expecting the wallet to use a heuristic, such as assume all signatures are as large as possible, rather than failing.  It seems appropriate to have a different error message here, if this is indeed what is happening.

**Comment by GambolingPangolin** [comment]
@achow101 I updated the [script][script] and verified that your suggestion to import the public key does give the expected result.  Thanks for your help!

[script]: https://gist.github.com/GambolingPangolin/587c46e9e5421a5401973406a0869519
