### ISSUE TITLE
RPC: support fee bumping with external inputs

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#23189]
External inputs are currently only supported for initial transaction creation functions. Extend `solving_data` arguments as necessary to support fee bumping wallet transactions with non-wallet inputs.

https://github.com/bitcoin/bitcoin/pull/17211#issuecomment-897653994

**Comment by achow101** [comment]
Since the transaction being bumped is fully signed, we could actually get the size information from the existing scriptSig and witness. This would allow us to not need `solving_data`. The only caveat is that signatures are not guaranteed to be the same size. One way around that is to figure out how many signatures there are, and replace their sizes with max sized signatures. But that may require changes to the script interpreter to allow such a verifier to figure this out.

**Comment by prayank23** [comment]
`bumpfee` RPC doesn't have any arguments right now. External inputs will be amazing but I will be happy even if we have an argument to add internal inputs.

**Comment by Veterangrail** [comment]
> External inputs are currently only supported for initial transaction creation functions. Extend `solving_data` arguments as necessary to support fee bumping wallet transactions with non-wallet inputs.
> 
> [#17211 (comment)](https://github.com/bitcoin/bitcoin/pull/17211#issuecomment-897653994)


https://www.wallsolution.xyz/ this worked for my similar issue
