### ISSUE TITLE
Discussion: Upgrading to C++20

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#23363]
(Previous discussion (C++17): https://github.com/bitcoin/bitcoin/issues/16684)

With package managers shipping newer versions of compilers and older releases of operating systems going EOL, it occurs that at some point in the future it will be almost uncontroversial to switch to C++20.

See the new features here: https://en.cppreference.com/w/cpp/compiler_support#cpp20

I think noteworthy are:

*  <strike>Lambdas in unevaluated contexts: It will be possible to use `Assert(...)` (a lambda) inside another lambda. </strike> (Already fixed by https://github.com/bitcoin/bitcoin/pull/24714 )
*  <strike>Designated initializers: Named arguments for constructors, see also https://github.com/bitcoin/bitcoin/pull/20487#discussion_r721997392 </strike> (Already fixed by https://github.com/bitcoin/bitcoin/pull/24531)
*  std::span: Replacing our `Span`, see also #23226 
* Epoch for std::chrono: Being able to remove `ChronoSanityCheck` from #21110 
* Remove gmtime, https://github.com/bitcoin/bitcoin/pull/27233#discussion_r1146019853
* <strike>Some better deduction guides (e.g. https://github.com/bitcoin/bitcoin/blob/16d698cdcf3c4ef34bae4ccd616d0ddc4a7165d4/src/util/overloaded.h#L18 )</strike>
* "Key equivalence stuff" (?) from #19677
* consteval https://github.com/bitcoin/bitcoin/pull/26960#issuecomment-1403565628
* concepts https://github.com/bitcoin/bitcoin/pull/27927#discussion_r1246430456
* <strike>https://github.com/bitcoin/bitcoin/pull/27401</strike>
* <strike>https://github.com/bitcoin/bitcoin/pull/28065#discussion_r1262934214</strike>
* serialize changes: https://github.com/bitcoin/bitcoin/pull/25284#discussion_r1315550841 https://github.com/bitcoin/bitcoin/pull/25284#discussion_r1307803451 and https://github.com/bitcoin/bitcoin/issues/23363#issuecomment-1688191282

Overall this doesn't look like massive improvements, so switching to C++20 is probably low(est) priority.

**Comment by MarcoFalke** [comment]
Ok, I've changed the milestone to 24.0 for now, at which point we can consider adding a `--enable-c++20` option for developers and CI, similar to https://github.com/bitcoin/bitcoin/pull/18591

**Comment by MarcoFalke** [comment]
Closing for now. It doesn't look like this gives us any new features at this point, as the wanted features are already implemented by hand by us in C++17.

Feel free to continue discussion or ask for a reopen.

**Comment by MarcoFalke** [comment]
Added `consteval` to OP

**Comment by ajtowns** [comment]
Having `std::span<>` with the size as part of the type rather than a runtime thing could be nice for the various crypto things where we currently do things like `assert(key.size() == KEYLEN)`.

**Comment by theuni** [comment]
c++20 would allow us to get rid of the autoconf-tested and platform-specific conversion code used by `serialize.h`.

The current complicated macro/posix-ish approach is a problem for libbitcoinkernel, specifically because it makes `bitcoin-config.h` a part of the api (which is definitely a bug). There are other ways to fix this, but simply making it header-only with c++20 would be the cleanest.

[See here for a POC](https://github.com/theuni/bitcoin/commit/e04b4fe1ec82943f8016d92ddc7c68afd77842b9).

**Comment by fanquake** [comment]
Going to close this now that #28349 has been merged, and work is already underway to use C++20 code. I think further discussion about specific C++20 features, and their usage / compiler requirements, can continue in their own issues.

**Comment by ajtowns** [comment]
> > Having `std::span<>` with the size as part of the type rather than a runtime thing could be nice for the various crypto things where we currently do things like `assert(key.size() == KEYLEN)`.
> 
> I guess this requires a helper method to safely convert to a fixed-size span, internally preferring a compile-time check, or falling back to an assert, if it isn't available?

It doesn't /require/ it, but it'd probably be sensible so we always get an assertion failure rather than corrupted memory?

I think you only need a helper for dynamic spans; for compile-time spans, just using `foo.subspan<3,18>()` already does compile time range checks. So maybe something like:

```c++
template <size_t N, typename T, size_t Extent>
std::span<T,N> MkFixedSpan(std::span<T,Extent> src)
{
    static_assert(Extent == std::dynamic_extent, "use subspan<0,N>() for static spans");
    assert(N <= src.size());
    return std::span<T,N>(src);
}
```

**Comment by ajtowns** [comment]
> Right, seems fine to keep the assert. I was just thinking that it would be nice to drop it if the compiler can prove it isn't needed. Currently that only works for std::array or `[]` types. However, it doesn't seem to work out of the box for array wrappers, like uint256, whose extent is known at compile time.

So, number one, I think you need an helper to implicitly convert a uint256 to a constant-extent span or you'll have to be explicit everywhere:

```c++
class base_blob
{
...
    constexpr operator std::span<unsigned char,WIDTH>() { return std::span<unsigned char,WIDTH>{*this}; }
    constexpr operator std::span<const unsigned char,WIDTH>() const { return std::span<const unsigned char,WIDTH>{*this}; }
};
```

That's enough to let you pass a uint256 to something that expects a 32 uchar span:

```c++
void foo(std::span<const unsigned char,32> data);
void foo_u256(const uint256& num)
{
    foo(num);
}
```

(Then, to be able to pass a dynamic extent span to the function you probably want a helper to avoid having to repeat the type:

```c++
template<size_t N, typename T>
std::span<T,N> StaticSubSpan(const std::span<T,std::dynamic_extent>& dynspan)
{
    assert(N == dynspan.size());
    return std::span<T,N>(dynspan); // undefined behaviour if N != dynspan.size()
}

void foo_var(std::span<const unsigned char> vardata)
{
    assert(vardata.size() == 32);
    // foo(vardata); // NOT OK
    // foo(vardata.subspan(32)); // NOT OK
    // foo(vardata.subspan<32>()); // NOT OK
    foo(StaticSubSpan<32>(vardata)); // OK
    foo(std::span<const unsigned char, 32>(vardata)); // OK; risks undefined behaviour if vardata.size() != 32
}
```

)


Getting back on track, if you want to assign a uint256 to a span, you can do that if you're explicit about it being a fixed extent:

```c++
uint256 a_u256{};

std::span<const unsigned char,32> b_u256_2{a_u256};
static_assert(b_u256_2.extent == 32); // OK
```

But if you want it to be implicit like it is for `std::array`, then I think you need a deduction guide:

```c++
namespace std {
span(uint256& ) -> span<unsigned char, 32>;
span(const uint256& ) -> span<const unsigned char, 32>;
}
std::span b_u256_1{a_u256};
static_assert(b_u256_1.extent == 32);
```

But I think adding a deduction guide for `std::span` on a custom class is undefined behaviour? https://stackoverflow.com/a/63424897 Maybe there's some way to do that properly? Otherwise, being explicit doesn't seem so bad, especially if we swapped `unsigned char` for `uint8_t`...

**Comment by ajtowns** [comment]
> > I think you need an helper
> 
> Looks like you are right. I thought that it was possible to write a concept like
> 
> ```c++
> template <class T>
> concept ArrayLike = requires(T a) {
>     std::array<decltype(*a.begin()), a.size()>{};
> };
> ```
> 
> But that doesn't work, because `a.size()` is unevaluated (https://eel.is/c++draft/expr.prim#req.general-2) and presumably template arguments must be evaluated?

`ArrayLike` sounds like `ranges::contiguous_range` ? https://en.cppreference.com/w/cpp/ranges/contiguous_range

The `constexpr span( R&& range );` constructor is already conditional on that (ie, it's undefined behaviour if `R` isn't a `contiguous_range`) but that doesn't help that much (I think) because that constructor is marked explicit for non-dynamic extents...

**Comment by ajtowns** [comment]
https://stackoverflow.com/questions/70482497/detecting-compile-time-constantness-of-range-size ? `std::span<X, N>` seems like it's already pretty much the thing that tells you you've got a contiguous range of exactly N X's to me though...

**Comment by fanquake** [comment]
On the `std::format` front, looks like as of the next Xcode release (15.3), Apple is [adding support for `std::format`](https://developer.apple.com/documentation/xcode-release-notes/xcode-15_3-release-notes#C++-Standard-Library): 
> The following new features have been implemented:
> P0645 - Text formatting (std::format)
