### ISSUE TITLE
bitcoin-cli validateaddress return value

### ISSUE THREAD

**Issue by jsarenik** [bitcoin/bitcoin#23572]
```
$ bitcoin-cli validateaddress invalid
{
  "isvalid": false,
  "error": "Invalid address format"
}
$ echo $?
0
```

**Expected behavior**

```
$ bitcoin-cli validateaddress invalid
{
  "isvalid": false,
  "error": "Invalid address format"
}
$ echo $?
1
```

I expect the process return value to be greater than zero and this would help a lot in scripting.

**To reproduce**

Just run the commands listed above. 100% reproducible on current master 19815b096.

**Comment by MarcoFalke** [comment]
Duplicate of #18476?

**Comment by jsarenik** [comment]
#18476 seems similar, but this one differs in its goals. Current output for `validateaddress` is correct and there is no need to change it, just the returned value when the process ends would simplify the scripts which now has to process the output and decide success/failure status of the bitcoin-cli command in another step (while some other bitcoin-cli commands properly return what they should, see below).

Successful exit status example (`return` = 0)

```
$ bitcoin-cli getblockhash 1
00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048
$ echo $?
0
```

Error exit status example (`return` > 0)

```
$ bitcoin-cli getblockhash 800000
error code: -8
error message:
Block height out of range
$ echo $?
8
```

**Comment by w0xlt** [comment]
The `getblockhash` returns an exit status other than 0 because a block height out of range [throws an exception](https://github.com/bitcoin/bitcoin/blob/4cc998ce9d1445cae3c8a60443980221196ab508/src/rpc/blockchain.cpp#L827).
The bitcoin-cli client detects this exception and [returns the error code](https://github.com/bitcoin/bitcoin/blob/4cc998ce9d1445cae3c8a60443980221196ab508/src/bitcoin-cli.cpp#L1156).
But `validateaddress` [simply returns a JSON with the error message](https://github.com/bitcoin/bitcoin/blob/4cc998ce9d1445cae3c8a60443980221196ab508/src/rpc/misc.cpp#L84-L89). It doesn't throw an exception.

The reason is that out of range block height is not expected in normal flow. However, if you validate an address, it can be invalid, so the server simply returns that information.

But if there is an understanding that `validateaddress` should throw an exception, I can open a PR to change this behavior.

**Comment by jsarenik** [comment]
@w0xlt Thank you for explanation. I am actually OK with it as it is. Closing the issue which was just a high-level UNIX idea from my scripting point of view.

Example work-around:

```shell
#!/bin/sh

bitcoin-cli validateaddress $address | grep -q Invalid && {
  echo this is done when address is invalid
}
```

See where it is used in practice: https://github.com/jsarenik/bitcoin-faucet-shell/blob/13ac1dedc08747f79edd5f07d5037171394544b7/cgi-bin/GET.sh#L15
