### ISSUE TITLE
Use AppData\Local instead of AppData\Roaming

### ISSUE THREAD

**Issue by gusarov** [bitcoin/bitcoin#2391]
In Windows OS, please, use AppData\Local (%LocalAppData% in Win7) instead of AppData\Roaming (%AppData%)
The roaming folder is intended for synchronization with roaming profile storage, this is why all software should keep only small and absolutely necessary files here, which can make sense in other machine for the same user. Take look at browsers - they stores cache history in local folder and browser settings in roaming, this is correct. An average size of roaming profile for typical user is about 100..150MB (which can be easily transferred via LAN to any user's PC), but Bitcoin's folder have 16GB wich is inappropriate.
At the same time you can think about ability to manually specify storage location, because of such a huge size. Most modern PC have SSD with quite limited capacity (64, 80, 128) for system drive and separate HDD of several TB in size. Personally I have to create Symbolic Link to store Bitcoin's storage on alternative drive.

**Comment by MarcoFalke** [comment]
There is `-blocksdir` now for finer-grained control

**Comment by gusarov** [comment]
Essentially issue is not resolved. I do understand that I can easily solve this for myself, but I raised this issue to help new users with default configuration and to help improve current architecture. For me this is clearly architectural flaw. I do understand that you can not just change default lookup path, because somebody already have the storage in another dir, but there are many ways to solve it, e.g. a flag in new path marking that it been initialized here our old path must be considered first.

**Comment by MarcoFalke** [comment]
Are you saying that `-blocksdir` should be exposed as an option in the gui intro dialog?

**Comment by gusarov** [comment]
No, this is not about exposing options, the option is exposed. 
![image](https://user-images.githubusercontent.com/1462777/91112720-dea02c80-e651-11ea-8c5c-abcb6875bc65.png)

This is about default data directory. It is incorrect to use Roaming directory for large files, the default directory on Windows should be under %LocalAppData%.

**Comment by MarcoFalke** [comment]
Ah, so for fresh installations it could make sense to split the blocksdir and the datadir between Local and Roaming. For existing installations this can not be changed.

The new settings.json might come in handy when implementing this.

**Comment by ryanofsky** [comment]
I kind of think the whole bitcoin datadir should go in %LocalAppData% by default, not %AppData%. It's true that large block and index files don't make more sense in %AppData%. But I'd think that smaller sensitive files like wallets and cookies also should not be mirrored and roam across the network. Also I could see use of %AppData% instead of %LocalAppData% breaking locks and possibly leading to corruption.

Maybe the thing to do is to change [`GetDefaultDataDir`](https://github.com/bitcoin/bitcoin/blob/f8462a6d2794be728cf8550f45d19a354aae59cf/src/util/system.cpp#L641-L665) to continue returning `%AppData%\Bitcoin` if already exists for backwards compatibility, but otherwise return %LocalAppData%\Bitcoin.
