### ISSUE TITLE
feature_init.py issue

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#23989]
https://github.com/bitcoin/bitcoin/pull/23737#discussion_r779576100

**Comment by MarcoFalke** [comment]
I think it might be better to open the stream as a raw byte stream, if possible.

After all the lines are dropped anyway and don't need to be decoded.

**Comment by sogoagain** [comment]
Good idea. Opening the file as a byte stream is no problem.
I'll fix it like that.

Thank you for answer.

**Comment by mzumsande** [comment]
I wonder what is the root cause, i.e. why non-unicode characters can appear in the log in the first place.
Is the simultaneous writing to (by bitcoind LogPrint commands) and reading from (python) the issue because the writing of a given line can be non-atomic?
Also, should there be a wait in the `while(True)` python loop?

**Comment by MarcoFalke** [comment]
> I wonder what is the root cause, i.e. why non-unicode characters can appear in the log in the first place.

I assume that the file was read partially while some emoji was written?

**Comment by mzumsande** [comment]
> I assume that the file was read partially while some emoji was written?

Ah yes, could be the "₿" from the path name, which starts with 0xe2 (the byte reported in https://cirrus-ci.com/task/6633293054476288?logs=ci#L5910 )
