### ISSUE TITLE
edit src/index/base.cpp

### ISSUE THREAD

**Issue by katesalazar** [bitcoin/bitcoin#24354]
**Is your feature request related to a problem? Please describe.**
txindex sync message will print more than exactly twice a minute
because current_time and last_log_time are in seconds, it jitters
by one second
https://github.com/bitcoin/bitcoin/blob/1e8aa02ec5cc2819c67ef40a7573c4b23a4c11cc/src/index/base.cpp#L168

**Describe the solution you'd like**
change '<' with '<=' makes the message
appear [twice exactly a minute][0], in
https://github.com/bitcoin/bitcoin/blob/1e8aa02ec5cc2819c67ef40a7573c4b23a4c11cc/src/index/base.cpp#L168
for consistency, probably as well in
https://github.com/bitcoin/bitcoin/blob/1e8aa02ec5cc2819c67ef40a7573c4b23a4c11cc/src/index/base.cpp#L174
(among others?) but I'm not interested in analyzing implications of
changing that line 174

**Describe alternatives you've considered**
I suppose there's a way to change this by using millisec resolution in these time variables.

**Additional context**
thanks!

[0]: https://github.com/bitcoin/bitcoin/blob/1e8aa02ec5cc2819c67ef40a7573c4b23a4c11cc/src/index/base.cpp#L21

**Comment by RandyMcMillan** [comment]
REF: [94b4f8bbb9e7e37f3057b47bf13a74de12b8e0cc](https://github.com/bitcoin/bitcoin/blame/94b4f8bbb9e7e37f3057b47bf13a74de12b8e0cc/src/index/txindex.cpp)

We can deduce that these PARAMETERS were actually set arbitrarily. SYNC_LOG_INTERVAL and SYNC_LOCATOR_WRITE_INTERVAL currently equal 30 seconds. In both cases the LogPrintf() and the Commit() are limited to at best executing at 30+1 seconds intervals - this is due to GetTime() returning time in seconds by default. @[katesalazar](https://github.com/katesalazar) is correct in here assertion that millisecond resolution may be beneficial. Coupled with benchmarking analysis, 30 seconds could safely be reduced to 20 seconds or even 15 seconds?

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
