### ISSUE TITLE
rpc: Deprecate the RPC createmultisig

### ISSUE THREAD

**Issue by michaelfolkson** [bitcoin/bitcoin#24638]
It was [discussed](https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2022-03-22#793794;) on IRC that the utility RPC `createmultisig` is old and pretty pointless (even more so than when it was introduced) and that the `deriveaddresses` RPC can do everything `createmultisig` can do. Hence deprecate the `createmultisig` RPC.

#### Useful skills:

Basic understanding of the Bitcoin Core RPC interface and deprecation process. If and when the RPC is deprecated the functional test rpc_createmultisig.py can also be removed.

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by michaelfolkson** [comment]
> rpc_createmultisig also checks addmultisigaddress, so I don't think it can be removed after removing createmultisig

A smaller test called something like rpc_addmultisigaddress perhaps?

@MarcoFalke: This is the argument against deprecating it. Every RPC has a maintenance cost though e.g. regularly running the associated RPC test and debugging of that test (#20183). Taking this perspective to the extreme ends up with a bunch of overlapping RPCs, no one knows why they are there (not a good user experience) and an ever expanding set of useless functional tests (not a good developer experience).

**Comment by MarcoFalke** [comment]
https://github.com/bitcoin/bitcoin/issues/20183 has nothing to do with the createmultisig RPC. It was a general issue of the user running a lot of functional tests on slow hardware, running into timeouts. The issue would have existed even if the createmultisig RPC was already removed with the test. Even if the issue was related to the RPC, I think having to debug a test issue once a year (or having to do minimal maintenance like bumping the copyright header once a year on the file) is an acceptable cost. And there will (either intentionally or accidentally) always be overlapping RPCs. If this was something to avoid, we could start removing almost all optional features.

I am not against adding documentation to clarify that another RPC exists and that one of them is considered "soft" deprecated. I am against forcing users to either run vulnerable EOL versions of the software or make them potentially rework their whole software stack during an upgrade.

**Comment by michaelfolkson** [comment]
Never deprecating a RPC and associated test ever again (and only adding to the list of RPCs, RPC tests) doesn't sound great to me but fair enough. I'll close this.

> I am not against adding documentation to clarify that another RPC exists and that one of them is considered "soft" deprecated.

Ok thanks, I'll consider doing this.

**Comment by michaelfolkson** [comment]
For now added a StackExchange [post](https://bitcoin.stackexchange.com/questions/112983/what-does-the-bitcoin-core-rpc-createmultisig-do-should-it-be-deprecated/) on the createmultisig RPC.

**Comment by 1440000bytes** [comment]
> For now added a StackExchange [post](https://bitcoin.stackexchange.com/questions/112983/what-does-the-bitcoin-core-rpc-createmultisig-do-should-it-be-deprecated/) on the createmultisig RPC.

I was expecting an example in the answer. It would help users.

> bitcoin-cli createmultisig 2 "[\"03789ed0bb717d88f7d321a368d905e7430207ebbd82bd342cf11ae157a7ace5fd\",\"03dbc6764b8884a92e871274b87583e6d5c2a58819473e17e107ef3f6aa5a61626\"]"

How can users create 2of2 multisig address from 2 public keys using `deriveaddresses`?

**Comment by michaelfolkson** [comment]
@1440000bytes:

> How can users create 2of2 multisig address from 2 public keys using deriveaddresses?

I think it is just:

`bitcoin-cli deriveaddresses "sh(multi(2,<pubkey>,<pubkey>))"`

Let me check that though before adding to the StackExchange answer.

**Comment by sipa** [comment]
FWIW, I suggested that it might be reasonable to deprecate this, mostly because I thought it was pretty outdated (P2SH multisig only, intended for the old annoying multisig workflow that predates descriptors/PSBT and you'd need to supply redeemscript arguments to all RPCs). Turns out that it (and `addmultisigaddress`) actually underwent a number of changes the last few years I had forgotten about (in particular, reporting a descriptor too).

**Comment by michaelfolkson** [comment]
@sipa: Thanks. If `deriveaddresses` isn't a strict superset of `addmultisigaddress` I personally find that a much stronger argument against deprecation than the "someone might still be using it" argument. I get that there's subtleties here that I'm most likely misunderstanding too.

**Comment by MarcoFalke** [comment]
I am pretty sure that `deriveaddresses` is still a strict superset of `createmultisigaddress`.

I also still think that it doesn't hurt to mention `deriveaddresses` in the `createmultisigaddress` help.

**Comment by sipa** [comment]
Yes, it's a strict superset.

My point is that I was just wrong about how useful `createmultisig` still is.
