### ISSUE TITLE
Missing GPG pubkey of 9D3CC86A72F8494342EA5FD10A41BDC3F4FAFF1C Aaron Clauson (sipsorcery)

### ISSUE THREAD

**Issue by Geoknyda** [bitcoin/bitcoin#25075]
The [SHA256SUMS.asc](https://bitcoincore.org/bin/bitcoin-core-23.0/SHA256SUMS.asc) file for the 23.0 release contains a signature from Aaron Clauson (sipsorcery) 9D3CC86A72F8494342EA5FD10A41BDC3F4FAFF1C but it cannot be validated using hkps://keyserver.ubuntu.com.

```
$ gpg --verify SHA256SUMS.asc SHA256SUMS
...
Signature created on Friday, April 22, 2022 4:56:54 AM
With unavailable certificate:
ID: 0x9D3CC86A72F8494342EA5FD10A41BDC3F4FAFF1C
You can search the certificate on a keyserver or import it from a file.
...
```

This key is present in [keys.openpgp.org](https://keys.openpgp.org/vks/v1/by-fingerprint/9D3CC86A72F8494342EA5FD10A41BDC3F4FAFF1C) but the [user ID is stripped](https://superuser.com/a/1485255/868401) and the import fails. I haven't been able to locate the key in other keyservers.

**Comment by fanquake** [comment]
@sipsorcery

**Comment by sipsorcery** [comment]
I never seem to have much luck importing my key into the key servers, admittedly I only try a few times.

The command below just worked:

`gpg --keyserver keyserver.ubuntu.com --send-keys 9D3CC86A72F8494342EA5FD10A41BDC3F4FAFF1C
gpg: sending key 0A41BDC3F4FAFF1C to hkp://keyserver.ubuntu.com`

Otherwise here's my public key:

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBFw7KuoBEACZfC7z4dchYLvI1NYGQ1phiTxXIQpD2geM51iOzSR1g7Vn5j2u
EdODiHFeCRAMQGdRK2AXdREdfI+cvkO3wghIhcjMsdRAyIcBjVgsu4hF4DZsCzt0
0zcZDRsJx/cnSWHRSYryUKIzUzzOF7GXnwEwFEl7B6P0uusGFUdCVsKy3Iq/BedB
EfF8YsuwBhzgHF79QOpVNIObBqYYpDjp5NIePKxckfgJ+Ur2H4pYugdQhlrZD7b8
r/ICMoLSHKXHw+EkI84HWiNs5K7PR/W3OCWYGvPfJVmCvA0lsf/wOrrPx9AuWLkn
YxTK6b70CjKjwueEM3pGc/A7NmuJBtUL8nolgnO9bf0f2/xFhRX+FaYUBxkydwV7
SnH3JG33lrrWtD2PktA+C5UKRxKmj0C+P3fnfH3YHJiTHLaT5rFEHC3YlstQaBk6
bTFq7jc9ERPwYRKdtLgK+MvluRwaosCw5wkb1Iqe0z3Rwl0WQ8C21Js1Rd2tR+uP
w1lgMh/jiFaw1TmbdL96282xKbHPQ3daXFoaYzC7nFpCdWOIFc0zMCqQo0nEuzM/
aaG8h6qOxp58qFyf6G8AGSXdpX5rzHyljGWTmdEJ2ORZmKtzFsoF4oCcaLTHRJve
pTI+K47zMoO+sgdRdnLzaqCr4wMg/IszPSOOcjwh38Fx/kH5gTtYLbYZKwARAQAB
tDFBYXJvbiBDbGF1c29uIChzaXBzb3JjZXJ5KSA8YWFyb25Ac2lwc29yY2VyeS5j
b20+iQJUBBMBCgA+AhsDBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAFiEEnTzIanL4
SUNC6l/RCkG9w/T6/xwFAmHipJQFCQtLFCoACgkQCkG9w/T6/xwRLw//QBlcapEh
onAyjnblqIaT2BlmcDcx6WlYg73HFGjm0x0ZDdpJ2MAVqARekbxSPodnU6xIj1Z8
iOmMdMOqbPlwi4IriJtbNJepvpjGHgvHScgWyur3cy13Nk+TbH0KVIEqDfnD7Avo
AK2GXtzGgjOsxnGrQlT7nSmZu5lKBROoKIUUmTnHDJ7DIuBLiHMOKi/bCuE3L0tW
fH88id04agxs+VglIF+rRgsdm2iZEwRSfLx7iPI7gTK9Sw904xc8Soc0j/z61KVd
K99SnHCYmSqSTyXO6f2PPEiV46KrP+PLT0vosBfzj4vusTjQONE1+Dnl604cPq9e
vcTN9PA17iFg9AIuqJDKmea2yFACQFA8+DvLOGf4aHB142QP8cZ3sBzBnTUqFXL3
fL8aHjsBUO0QrpJrKwmuiN/HGG84heq8lKsL8TeCSWlGuOMeyECn2N+Fl26ruuem
2+u1ldHGaYzM00tfrEhq0Hf2a3jfVLoHL21gBCxYmKgFFmB2uq2vu9vy6DPXnytk
SRMIa7gpb7tjhC09BRixUD1wWXNIIgQNoukC+0rWRjetq8/+t0JyWOhZcFFIrVn7
lbZ//G86y7qSuOKnAymNjWdZQI0s4YoVicg9OycykMh84XnIuKshk0zIl1ZCmpOS
xaMfLazYb3swtiuGFFaNkAuU4ijYs4inlH6JAlQEEwEKAD4WIQSdPMhqcvhJQ0Lq
X9EKQb3D9Pr/HAUCXDsq6gIbAwUJBaOagAULCQgHAgYVCgkICwIEFgIDAQIeAQIX
gAAKCRAKQb3D9Pr/HGeHD/91ZocnSrU8v62qjJn0Bw8YBOBkCGgpAODl9tYyk16h
XWPIA3hoo/YErlmfWOoq+MRTYndAI/nGvLGo4muDSYKq7UnNsrMdvvwYElFcGvM9
NWbNYPF2EvQEC2uXLMKbZtRh7tbCffnVbSGkjQ4Ls0eZi2AX4+RVngMnAzGhFRzZ
O3NncP43OI2j1yZVo9xEwyJ3V58KJeeGLld6qjTTKQku6MzBaMoUERNxC/Qd0HIL
AZEoBkfmGIreIqjwsorqyt2U+0LZIsYYm1JWcEdnH3oZACp5Yx4Yc30YLxThDXpI
77DFQYwyQ7TxzFOPhUVN5MEcgsGHxtgXQOa3UpwgOXA9XbgjNTSgGADA3Nvyhcbp
csAUIq1s6Jzo9kmpl1Mtp8X2Rup/bmgBfc50i2V9j1RDgO/4JjY/x9UaFXL3d3qu
ab7+liQIfaObtlXDfLBgC5YhD7JB1UbqUNCezSbUp+sEe0D2N8F/fQtATohPiR2E
G+HnryFGlIqgjm8MBSz3PMQKj90DnJoi7MTYSnbNjavHTN1X5Lhr3+bYVyxOvwCv
R4F3OYAA6e9bF0VH+fgqb3lpWPfZ+x7kPNY2SDjDgWNrlxB72VmgahofF97Ac2LJ
fpUdRH4xN4pIjf6qfCgtNFX/25uxRu02108zhxq2qRzmBof6hR6lS347kS1YvAhy
Q7kCDQRcOyrqARAAttovJ8RIIPE93IxPklhCEnDOldy1ek/wLbLITYzNcbUQxBAA
nGZKvCRV6F4r+r0v7wf63WI5ZkX90I1tNwc/llH3dVqFVm4dceymmIouVmahsv5S
5iVIGsF1HK89fpKxgbXmDAbTJg0B3tBKh/qwL9HhXRB9J28JPMmVIkCY+k1ujEt4
e3eFwvoxMO3u7SBZIeM2gGeRC8H6BAO8gVVjA0aBCe3tBVWP38MeUcDydWVpBRSm
9Zg33APJvuQnaKykJMbT2cnj1ST+2tn/6buUWkPRN3FR7i7iCjtLzDhPM4FTxf9v
RBQ8YtLl47k4Brf0M1Z6pV7HnsyjMNxEBsYyFSHHN1dOqTsDVeFMEDU4dOLd7zwI
XuT9nmDk0db+moIRjKT07UJp7CmSumIjf3QiqDWMhM5YKPRSn03xfTaWCmK7Hwj5
Vh6DXGx7OVaggo525WAe1RZnBjW7EmiGkyQh/Mxn2O4Wz8rei2KPMkyxp9GXmI5z
3uy2X1t6VSHKMesqT47v8c5RQEwBVXxsIToCFrnfkvKvsyskFMAM7N4+QWmBdSUH
llg+YEsQSW+nzI4D3Yomd0q9609cj3QRWj25J6UxjVJs/fexOkEDPl72j5/Q6HAw
dzdydHCp80vqlIpbGXkSnErFF2jJxHCH7j8JkbhVi/qK+568VQ9Hqj1vE1kAEQEA
AYkCPAQYAQoAJgIbDBYhBJ08yGpy+ElDQupf0QpBvcP0+v8cBQJh4qPVBQkLSxNr
AAoJEApBvcP0+v8cFL4P/i3yXM4nnoCEnvOVsMsUASny5AlFpu+t6lsS1o8OsNGt
jd8eTuxTI7c6jGmowyvPcSk5jenV2+RS1NbIMFatJS84cvI9mcc5V3oubVBS6Hj+
03K0YhlPJZDiUFjE9h4NkBzqF5MdP8b6kXtErpLo/jtC7XtuppvVREZSJcj7PovC
vDTD3pHw9rqFgZLNXvRUtuSuNixXTf4cOkuvOatKQhrby+0Bcu0nnoeWTJrxgtxI
Ph2+ASLlgRiGHag4xrxsjhqAA2qBdcj6fbhq5MQFYGIWHKtAQt+y6Dy6uOKz3uuL
1JzYjxo+KoMlW6kxZnnLF8AdUOwnB9qwbrcBJM2g96ppb7OHFlbjwhFs8RqUq1yX
rXk0+LmahnDprRbJKW7PXgUadknO0ppdV+jLWUDub5k0NybRNvVkHfoaerAiCddK
DRw0UXcdAWtTGKR5cLGft6kim8oe5VSPmKH8BUYDYeGHIFObnH+c9aSxs7t7EH7J
QCH3QosGtxRhFVlBj0xhT3S+eoknDHncN8vFFSdb+IOYf898yOn9iJK8nXT3F/Mt
Q5nOAtzEDoes2PToyXBNyOw0BKAEh5MZSCDoo3ClIdJ/gEbYv9ifzhjUa4bG35A1
LP6Lka8/Qa0PHuIjBbLKHhNQnLsVtxqMjcyxA3sL4ivZtVFuImmWlKiPPewVvszq
=cVKF
-----END PGP PUBLIC KEY BLOCK-----

**Comment by MarcoFalke** [comment]
See the docs https://keys.openpgp.org/about/usage#gnupg-upload

```
$ curl -T - https://keys.openpgp.org < your_key
Key successfully uploaded. Proceed with verification here:
https://keys.openpgp.org/upload/eNXu0D_PU97VHPd0_P2cpeN7-zkvNFToecdzkwwRLf5UJqcO3bMZUrhCrs48H0I5fDI1_UydkPG61PnzgGpgmKob0xciTWh66PRsPLwn_X8sNGVepx37KyG_smfYvKaYDFVVl3va33vwu3b4E1FFvk5upkEbvDiKFjDj8U0084PtJ1fnFTpgYnk7GFpsmCBYFIf_kaFoZUEszdxnldZOqYu1vg

**Comment by sipsorcery** [comment]
^ Thanks!

Done, [https://keys.openpgp.org/search?q=aaron%40sipsorcery.com](https://keys.openpgp.org/search?q=aaron%40sipsorcery.com).
