### ISSUE TITLE
subtractfeefromamount=true fails with insufficient funds

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#25129]
Was: https://github.com/bitcoin/bitcoin/issues/25030

Steps to reproduce:

```
wget https://github.com/bitcoin/bitcoin/files/8688722/datadir_node0.tar.gz
tar -xvf datadir_node0.tar.gz
export DD='-datadir=./node0/'
bitcoin-qt $DD &
bitcoin-cli $DD loadwallet rpc_online
bitcoin-cli $DD -named sendtoaddress address=bcrt1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq3xueyj amount=1966.66779818 subtractfeefromamount=true

**Comment by MarcoFalke** [comment]
Maybe this should be replaced by sendall in the tests, but I am wondering if the bug should be fixed or ignored.

cc @Xekyo @achow101 https://github.com/bitcoin/bitcoin/pull/24118

**Comment by achow101** [comment]
The bug would probably be fixed by #23534, however I think changing to use `sendall` is the more correct fix.

**Comment by Xekyo** [comment]
Looking at how the test works, and seeing that it creates transactions sending random recipient amounts up to the full balance, it seems likely that it occasionally creates some tiny UTXOs that are skipped during AvailableCoins(…) due to having a negative effective value. Since line 448 where this error occurs is trying to empty the wallet, using `sendall` seems right.

**Comment by MarcoFalke** [comment]
yeah, changing the test is a gfi

#### Useful skills:

* Bitcoin Core functional test framework and RPC methods

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by ekkis** [comment]
I have this issue in trying to use bitcoin-cli but there is no `sendall` command.  suggestions?

**Comment by achow101** [comment]
`sendall` will be available in the next major release. You can build the master branch from source if you need it now.

Otherwise you can achieve the same thing by manually choosing all of the utxos in your wallet. `listunspent` will provide you the utxos and you can use them with `send` or the raw transaction or psbt workflows.

**Comment by ekkis** [comment]
wonderful.  thank you
