### ISSUE TITLE
Parallel compact block download

### ISSUE THREAD

**Issue by ajtowns** [bitcoin/bitcoin#25258]
There have been a couple of old attempts to enable parallel compact block downloads, see #9447 and #10984. There are additional notes in #16172.

The idea is that we currently might request missing transactions for a new block from the first peer to announce the block to us; but if that peer is a miner (or close to a miner), that peer might be busy (eg it might be in ConnectTip), and not able to reply quickly, while some other node has meanwhile obtained the block and is able to quickly give you the few transactions you're missing.

Therefore, at some point we should pick up the patches in those earlier PRs, or otherwise solve this :)

**Comment by instagibbs** [comment]
This also seems to happen with spy(?) nodes which are the first to send a header, but then never end up responding to requests for the full block. Due to recent mempool chop, the chances of requiring a round-trip for slightly-later-but-behaving high bandwidth peer's cb goes way up, and currently cannot be accommodated.

couple of questions to think about:
1) should the 2nd download only work for outbound connections? currently there are 3 hb peers possible, and only one outbound is "protected". Sybil nodes can take up 2 inbound slots pretty easily. Perhaps if first to announce is outbound, we allow an inbound as second as well?
2) is 10 transaction diff as per https://github.com/bitcoin/bitcoin/pull/10984 reasonable with today's mempool characteristics?

**Comment by Sjors** [comment]
If we wait a little bit before the second attempt, and if we track which peers have since announced the header, we could pick from a larger set. Randomly and maybe with a preference for outbound. We can rely on high bandwidth mode compact block peer(s) for speed, but then for reliability use a bit more patience. Maybe we could even do one attempt at a getting compact block and then a few seconds later ask for a regular block.

**Comment by mzumsande** [comment]
should this stay open for a while as per https://github.com/bitcoin/bitcoin/pull/27626#issuecomment-1557224231?

**Comment by instagibbs** [comment]
We could open a new issue with fresh context as well, summarizing the discussion to this point?

**Comment by fanquake** [comment]
> should this stay open 

The PR shouldn't stay open, but we can open a tracking issue if needed.
