### ISSUE TITLE
bitcoin-cli createwallet error : Compiled without sqlite support

### ISSUE THREAD

**Issue by furkandamar-ox** [bitcoin/bitcoin#25805]
I installed bitcoin core on ubuntu server (I got help from: https://baloian.medium.com/how-to-setup-and-run-a-bitcoin-full-node-on-ubuntu-a106fb86dbb3).

The following commands work fine:

bitcoin-cli -getinfo

bitcoin-cli getblockchaininfo

bitcoin-cli getnetworkinfo

bitcoin-cli getpeerinfo
I get this error when I want to create a new wallet: request :

bitcoin-cli createwallet adminwallet
response :

error code: -4

error message:

Compiled without sqlite support (required for descriptor wallets)

**Comment by fanquake** [comment]
I'd suggest using our build documentation: https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md, rather than random, year-old medium articles.

The issue is that sqlite wasn't available when you compiled (it's not metioned in the article at all). You should [install it](https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#linux-distribution-specific-instructions) and recompile, if you want to use descriptor wallets.
