### ISSUE TITLE
rpc: prevent non-zero value OP_RETURN outputs in sendrawtransaction

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#25899]
While some protocols require value attached to OP_RETURN outputs, this otherwise seems like a mistake.

Setting the value to 0 should really be done by the wallet/script creating the transaction (like createrawtransaction does for `data` outputs). However, as an additional check, similar to the high-fee check, sendrawtransaction could also check for non-zero value OP_RETURN outputs.

This should be configurable by a new RPC argument.

See also https://transactionfee.info/charts/output-opreturn-amount/

#### Useful skills:

* Bitcoin Core RPC code
* Transaction output types
* Bitcoin Core functional tests

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by mariosanchezgarcia** [comment]
Este problema creo que es culpa mia

**Comment by sristis0202** [comment]
Hi! I would like to work on this. Please assign

**Comment by amritabithi** [comment]
Considering all of the applications using nonzero outputs in op_return, wouldn't it make more sense to just have an option to prune this before saving it to disk?  Would it not be better to deal with one optional flag on the node instead of complicating countless apps that are already using the previously assumed behavior?  Nothing is gained through this change that cannot be accomplished with existing pruning code for op_return, unless I am misunderstanding something.

**Comment by achow101** [comment]
> Considering all of the applications using nonzero outputs in op_return

It's unclear to me why any application needs to use non-zero op_returns. It is literally just burning money. While there are some applications where burning money is the point, I don't think we should really be encouraging/enabling those. Just because someone uses a particular feature does not mean it is necessarily good or worth keeping. Furthermore, I would not be surprised if many of those applications are burning money accidentally. A few developers I have spoken to were surprised that 0 value op_returns were allowed because they were not aware of the exception to the dust limit for op_returns. Application developers may have the same misconception.

> wouldn't it make more sense to just have an option to prune this before saving it to disk?

Disk space is not the concern. Whether the amount is 0 or something else doesn't matter, it still takes up the same amount of space. We're already pruning op_returns from the UTXO set. Rather the point is to add a protection for users. The purpose is to prevent users from accidentally burning money. In general, we should erect barriers to users throwing away their money as it is often done by accident.

**Comment by 1440000bytes** [comment]
> It's unclear to me why any application needs to use non-zero op_returns. It is literally just burning money. While there are some applications where burning money is the point, I don't think we should really be encouraging/enabling those.

Why is burning an issue? Projects that do proof of burn and similar things won't be able to use `sendrawtransaction` and figure out other ways to broadcast transactions.

**Comment by MarcoFalke** [comment]
Please read the description. It says "This should be configurable by a new RPC argument." So everyone can still burn as much money as they want after they toggle the value of the new RPC optional argument.

**Comment by 1440000bytes** [comment]
Sorry I misunderstood the issue and linked pull request. I thought all non zero OP_RETURN would get rejected.

**Comment by CrypticBantu** [comment]
Hi, I would like to work on this, could you assign this to me please?

**Comment by officialfrancismendoza** [comment]
I'd like to work on this. Please assign

**Comment by ShitcoinsSuck** [comment]
This change breaks RPC client libraries and applications, and potentially everything downstream of them.

One example--electrum wallet allows non-zero sends to OP_RETURN.  There are valid use cases for this.  This is broken in bitcoin 25.0 because to add the new argument would require changes to everything downstream of bitcoin core, including rust-bitcoincore-rpc, electrs, and electrum wallet.  It could theoretically be hacked in by having a default setting at the direct client of the bitcoin core rpc (rust-bitcoincore-rpc in this case), but this would be a hack.

It might make more sense to either remove this new argument or change the default to 21quadrillion sats.  This allows the downstream users to decide the level of "protection" they want vs prior bitcoin versions, rather than forcing the change on them.
