### ISSUE TITLE
24.0 RC Testing Guide Feedback

### ISSUE THREAD

**Issue by kouloumos** [bitcoin/bitcoin#26092]
This issue is to discuss the [24.0 Release Candidate Testing Guide](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/24.0-Release-Candidate-Testing-Guide). If you have any issues with or feedback on the document, please leave a comment here.

You can also use https://github.com/kouloumos/rc24-guide-feedback-repo/pull/1 as an easier way to directly suggest changes.

Note: This is for feedback on the document, not on Bitcoin Core or on the 24.0 changes. 

Thank you for taking the time to help with the testing guide!

**Comment by glozow** [comment]
Some suggestions for things to add:

- Observe pre-syncing step during IBD (#25717)
- Try new RPC sendall (#25874)
- Try new RPC gettxspendingprevout (#24408)
- Try -mempoolfullrbf option (#25353)

**Comment by vasild** [comment]
To test https://github.com/bitcoin/bitcoin/pull/25355:

Run an I2P node with `-i2pacceptincoming=0` (since this is when #25355 engages) and

* Verify that connectivity is ok, maybe combine with `-onlynet=i2p` to make it obvious if it does not work
* Confirm that our address is different for each outgoing connection, e.g. `bitcoin-cli getpeerinfo |jq 'map(select(.network == "i2p" and .inbound == false)) |map({addrbind: .addrbind})'`

Run an I2P node with `-i2pacceptincoming=1` and confirm that we use the same I2P address for ourselves for all outgoing connections.

There is a followup to that feature at https://github.com/bitcoin/bitcoin/pull/26065. Maybe wait for it to be merged (or manually merge it for the testing).

**Comment by kouloumos** [comment]
Thank you for your suggestions!

Observing the pre-syncing step during IBD [was just added to the testing guide](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/24.0-Release-Candidate-Testing-Guide#observe-the-new-headers-pre-synchronization-phase-during-ibd). A very important change, not sure how I missed it the first time. 

I'll now try to include @vasild's suggestion and then think about how to include the -mempoolfullrbf option.

The new RPCs are simpler to include, I'll deal with them later.

**Comment by kouloumos** [comment]
**Update**: 
[Testing transient addresses for I2P outbound connections](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/24.0-Release-Candidate-Testing-Guide#testing-transient-addresses-for-i2p-outbound-connections) and [Testing your localized GUI for ambiguities between shortcuts](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/24.0-Release-Candidate-Testing-Guide#testing-your-localized-gui)(after suggestion from @hebasto ) are now part of the testing guide.

**Comment by satsie** [comment]
Nit: This line in [Observing the logs](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/24.0-Release-Candidate-Testing-Guide#observing-the-logs) refers to the wrong field name:

```
The peer that is currently involved in the presync phase will have its presynced_height field set, instead of -1.
```

Instead of `presynced_height` it should be `presynced_headers`

**Comment by rserranon** [comment]
I couldn't make this work on signet:
`./contrib/signet/getcoins.py -c $BINARY_PATH/bitcoin-cli -a myHeFvPiKR39FpXfzztENQekHdUoFKordv bitcoin_cli_args signet datadir="/tmp/24-rc-test"`

**Comment by LarryRuane** [comment]
> I couldn't make this work on signet: `./contrib/signet/getcoins.py -c $BINARY_PATH/bitcoin-cli -a myHeFvPiKR39FpXfzztENQekHdUoFKordv bitcoin_cli_args signet datadir="/tmp/24-rc-test"`

What worked for me looks slightly different from what you did (note I specified the double-dash, and also a dash before `signet` and `datedir`):
```
contrib/signet/getcoins.py -c $BINARY_PATH/bitcoin-cli -a tb1qae9c7qks34w0a3cvm4f9xlq9q8nf5226zje5tq -- -signet -datadir=$DATA_DIR
```

**Comment by rserranon** [comment]
> @rserranon
> 
> > I couldn't make this work on signet: `./contrib/signet/getcoins.py -c $BINARY_PATH/bitcoin-cli -a myHeFvPiKR39FpXfzztENQekHdUoFKordv bitcoin_cli_args signet datadir="/tmp/24-rc-test"`
> 
> What worked for me looks slightly different from what you did (note I specified the double-dash, and also a dash before `signet` and `datedir`):
> 
> ```
> contrib/signet/getcoins.py -c $BINARY_PATH/bitcoin-cli -a tb1qae9c7qks34w0a3cvm4f9xlq9q8nf5226zje5tq -- -signet -datadir=$DATA_DIR
> ```

Thanks LarryRuane, that way to send the params worked, unfortunately the captcha is not accepting my answer. I also had to install ImageMagic.

**Comment by kouloumos** [comment]
Thank you @satsie for the typo and @LarryRuane @rserranon for the signet faucet script. I ended up reverting that section back to the previous version which had just the website for people to paste their address. It makes it less complicate.

**Comment by pablomartin4btc** [comment]
Regarding the i2p testing, I think we could include some screenshots as how the logs would look like in terms of the outcoming/ incoming connections as of the usage of the `i2pacceptincoming` param and the `cli getpeerinfo` command we need to run in order to get them.

`i2pacceptincoming=1` (accepting incoming connections => your I2P address is the same for all outgoing connections).
![image](https://user-images.githubusercontent.com/110166421/195895485-cba24b04-6a91-44d8-b159-941cbbef3165.png)

`i2pacceptincoming=0` (not accepting incoming connections => your I2P address is different for each outgoing connection).
![image](https://user-images.githubusercontent.com/110166421/195894882-f6ace2e5-eb42-49cf-bb39-4148191fb182.png)

**Comment by pablomartin4btc** [comment]
On the same subject, **i2p testing**, I don't know if someone went thru the same issue on Ubuntu, after installing i2p and starting the router (`i2prouter start`), bitcoind wasn't able to reach peers as there were connection errors, in my case and as I found on [bitcoin.stackexchange](https://bitcoin.stackexchange.com/questions/110866/unable-to-use-i2p-on-ubuntu-20-04-21-04), this was due to the SAM bridge app wasn't running, as it doesn't by default, perhaps we can add a small reference on the guide about this also.

**Comment by danielabrozzoni** [comment]
Nit: 24.0rc3 has been tagged, but the guide still points to the rc2 (https://github.com/bitcoin-core/bitcoin-devwiki/wiki/24.0-Release-Candidate-Testing-Guide#1-grab-latest-release-candidate)
