### ISSUE TITLE
Remove RegisterValidationInterface()

### ISSUE THREAD

**Issue by vasild** [bitcoin/bitcoin#26210]
`RegisterValidationInterface()` takes a bare pointer, remembers it and other threads use it afterwards. This puts a burden on the caller to properly maintain the lifetime of the object which adds complexity and is a source of bugs (https://github.com/bitcoin/bitcoin/issues/25365, https://github.com/bitcoin/bitcoin/pull/26188#discussion_r982751603).

`shared_ptr` exists with the purpose of resolving that problem exactly. We already have `RegisterSharedValidationInterface()`. I think it should be possible to replace all usages of `RegisterValidationInterface()` with the "Shared" alternative. It is used in:

* `BaseIndex::Start()` passing `this`, is already suggested in [#25365](https://github.com/bitcoin/bitcoin/issues/25365#issuecomment-1251314646) (see last paragraph), [#24230](https://github.com/bitcoin/bitcoin/pull/24230) "already does this".

* `AppInitMain()` passing `g_zmq_notification_interface` which is a global raw ptr, can be changed to global `shared_ptr`.

* `AppInitMain()` passing `node.peerman.get()` which is `unique_ptr`. Extracting the raw pointer from `unique_ptr`, saving it somewhere else and using it from other threads defeats the purpose of using `unique_ptr` because we must now manually manage the lifetime of the object. `NodeContext::peerman` should be changed from `unique_ptr` to `shared_ptr`.

This should make it possible to remove `RegisterValidationInterface()` and `UnregisterValidationInterface()` (which is already deprecated).

Chasing concept ACK.

**Comment by ryanofsky** [comment]
> `shared_ptr` exists with the purpose of resolving that problem exactly.

I don't actually think `shared_ptr` is a good solution for allowing clients to unregister from validationinterface generally. It works ok for the wallet, because wallet is already using shared_ptr. But for validationinterface clients that aren't already using shared_ptr, it means they have to start using it, and still have to deal with complications of having notifications arrive after unregistering, even if they don't have to deal with the use-after-free complication anymore.

I also don't think current solution of having clients call `SyncWithValidationInterfaceQueue` is optimal either. It works ok as long as clients only need to unregister during shutdown. But if they want to unregister other times this could make them wait for a backlog notifications they don't actually depend on.

Just out of curiousity I looked into whether it would be possible to implement a blocking unregister call that would prevent any notification from arriving after unregistering, and it doesn't look so complicated, so maybe it could be helpful in the future:

<details><summary>Diff</summary>
<p>

```diff
diff --git a/src/validationinterface.cpp b/src/validationinterface.cpp
index 613c5b65ef6..4f8e88e13e0 100644
--- a/src/validationinterface.cpp
+++ b/src/validationinterface.cpp
@@ -33,9 +33,18 @@ private:
     //! count is equal to the number of current executions of that entry, plus 1
     //! if it's registered. It cannot be 0 because that would imply it is
     //! unregistered and also not being executed (so shouldn't exist).
-    struct ListEntry { std::shared_ptr<CValidationInterface> callbacks; int count = 1; };
+    struct ListEntry { std::shared_ptr<CValidationInterface> callbacks; int count = 1; std::function<void()> on_erase; };
     std::list<ListEntry> m_list GUARDED_BY(m_mutex);
     std::unordered_map<CValidationInterface*, std::list<ListEntry>::iterator> m_map GUARDED_BY(m_mutex);
+    //! Condition variable triggered when callback unregistered and freed.
+    std::condition_variable m_erased;
+
+    std::list<ListEntry>::iterator ListErase(std::list<ListEntry>::iterator it) EXCLUSIVE_LOCKS_REQUIRED(m_mutex)
+    {
+        m_erased.notify_all();
+        if (it->on_erase) it->on_erase();
+        return m_list.erase(it);
+    }
 
 public:
     // We are not allowed to assume the scheduler only runs in one thread,
@@ -53,13 +62,20 @@ public:
         inserted.first->second->callbacks = std::move(callbacks);
     }
 
-    void Unregister(CValidationInterface* callbacks) EXCLUSIVE_LOCKS_REQUIRED(!m_mutex)
+    void Unregister(CValidationInterface* callbacks, bool block) EXCLUSIVE_LOCKS_REQUIRED(!m_mutex)
     {
-        LOCK(m_mutex);
+        WAIT_LOCK(m_mutex, lock);
         auto it = m_map.find(callbacks);
         if (it != m_map.end()) {
-            if (!--it->second->count) m_list.erase(it->second);
+            bool free = !--it->second->count;
+            if (free) ListErase(it->second);
             m_map.erase(it);
+            if (!free && block) {
+                bool erased = false;
+                assert(!it->second->on_erase);
+                it->second->on_erase = [&] EXCLUSIVE_LOCKS_REQUIRED(m_mutex) { erased = true; };
+                m_erased.wait(lock, [&] { return erased; });
+            }
         }
     }
 
@@ -71,7 +87,7 @@ public:
     {
         LOCK(m_mutex);
         for (const auto& entry : m_map) {
-            if (!--entry.second->count) m_list.erase(entry.second);
+            if (!--entry.second->count) ListErase(entry.second);
         }
         m_map.clear();
     }
@@ -85,7 +101,7 @@ public:
                 REVERSE_LOCK(lock);
                 f(*it->callbacks);
             }
-            it = --it->count ? std::next(it) : m_list.erase(it);
+            it = --it->count ? std::next(it) : ListErase(it);
         }
     }
 };
@@ -140,10 +156,10 @@ void UnregisterSharedValidationInterface(std::shared_ptr<CValidationInterface> c
     UnregisterValidationInterface(callbacks.get());
 }
 
-void UnregisterValidationInterface(CValidationInterface* callbacks)
+void UnregisterValidationInterface(CValidationInterface* callbacks, bool block)
 {
     if (g_signals.m_internals) {
-        g_signals.m_internals->Unregister(callbacks);
+        g_signals.m_internals->Unregister(callbacks, block);
     }
 }
 
diff --git a/src/validationinterface.h b/src/validationinterface.h
index a929a3d56bf..75907e89ced 100644
--- a/src/validationinterface.h
+++ b/src/validationinterface.h
@@ -24,7 +24,7 @@ enum class MemPoolRemovalReason;
 /** Register subscriber */
 void RegisterValidationInterface(CValidationInterface* callbacks);
 /** Unregister subscriber. DEPRECATED. This is not safe to use when the RPC server or main message handler thread is running. */
-void UnregisterValidationInterface(CValidationInterface* callbacks);
+void UnregisterValidationInterface(CValidationInterface* callbacks, bool block = false);
 /** Unregister all subscribers */
 void UnregisterAllValidationInterfaces();
 
@@ -181,7 +181,7 @@ private:
     std::unique_ptr<MainSignalsImpl> m_internals;
 
     friend void ::RegisterSharedValidationInterface(std::shared_ptr<CValidationInterface>);
-    friend void ::UnregisterValidationInterface(CValidationInterface*);
+    friend void ::UnregisterValidationInterface(CValidationInterface*, bool);
     friend void ::UnregisterAllValidationInterfaces();
     friend void ::CallFunctionInValidationInterfaceQueue(std::function<void ()> func);
 
```

</p>
</details>

I guess I'm not sure what next steps should be. I'd like to move forward with #26215 and #26188 to fix immediate race and TSAN problems with indexes. And I'd like to move forward with #24230 to switch from indexes from using `RegisterValidationInterface` to `RegisterSharedValidationInterface` without requiring indexes themselves to be `shared_ptrs` with unpredictable lifetimes. After that I do think having a blocking `UnregisterValidationInterface` that stops sending notifications after unregistering could be useful to clean up other problems that may be remaining or that come up in the future.

**Comment by willcl-ark** [comment]
Closing this as it has not had any activity in a while. If you are interested in continuing discussion on this, or you feel that it is sufficiently important, please leave a comment so that it can be reopened.
