### ISSUE TITLE
Use descriptor wallets by default in functional tests

### ISSUE THREAD

**Issue by S3RK** [bitcoin/bitcoin#26511]
Since 23.0 descriptor wallet is the default wallet type.
As part of the transition it also make sense to make it default wallet type for functional tests

**Comment by MarcoFalke** [comment]
This is a two-line patch, no? Seems easier to just create the pull instead of an issue?

**Comment by kouloumos** [comment]
Default wallet type (if no `--descriptors` or `--legacy-wallet` flag is provided) is determined here
https://github.com/bitcoin/bitcoin/blob/f0c646f026e652082e798800136dc06c734fdab6/test/functional/test_framework/test_framework.py#L215-L220

The suggestion is to prefer sqlite instead of the currently preferred BDB. Makes sense.

Minor correction, I believe that descriptors are [the default since 23.0](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-23.0.md#wallet)
