### ISSUE TITLE
In Bitcoin Core, fees are represented by a fictitious unit (kvB). 

### ISSUE THREAD

**Issue by redarmyfaction** [bitcoin/bitcoin#26729]
I've noticed that the fictional unit 'kvB' is used in Bitcoin Core.  I looked into this for a few months and couldn't find a single standard or even mention of a unit called 'kvB' anywhere online.  Even the old kB notation used in Bitcoin is incorrect.

Pretty much everyone agrees on that **Bitcoin** is referring to the unit size of **bit**.

**1024 bits ((2<sup>10</sup> bits) bits)** is equal to **1 kibibit**, and is represented by the symbol **Ki**.

GNU/Linux users are well acquainted with the symbols **KiB** and **MiB**, which stand for Kibibyte and Mebibyte, respectively. 

Some of the recent pulls that introduced this issue in Bitcoin:
@MarcoFalke https://github.com/bitcoin/bitcoin/commit/6da3afbaee5809ebf6d88efaa3958c505c2d71c7
@jonatack      https://github.com/bitcoin/bitcoin/commit/94f83534e4b771944af7d9ed0f40746f392eb75e

While I am not a member of the Bitcoin organization on GitHub, **I request that this issue be assigned to me** because I would like to contribute to Bitcoin Core by resolving this issue.

**Comment by kouloumos** [comment]
In 'kvB', 'v' stands for virtual. This notation was introduced with SegWit, where the block size limit was replaced with a four million weight unit limit, which introduced a new way to “count” transaction data; instead of transaction size, a new metric was defined, called “virtual size” (in this case virtual bytes). You can find a reference to virtual size in [BIP141](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#transaction-size-calculations) and there is [a great explanation on stackexchange for how block weight works](https://bitcoin.stackexchange.com/questions/67113/how-does-segwit-reduce-transaction-size-when-the-signature-is-simply-moved-to-a/67115#67115).

You can find a lot of references in the repository for `vbytes` as well as `BTC/kvB` and `sats/vB`. With a quick search it seems that it might be true that there is no easy to find explanation on what virtual bytes are.

**Comment by willcl-ark** [comment]
@redarmyfaction in addition to what @kouloumos kindly explained to you, if you want to tackle an issue then you don't need to wait for it to be assigned to you, simply go ahead and open a pull request. If your changes are worthwhile they will attract the reviews needed from other contributors.

In my personal opinion it seems unlikely that changing Kilo to Kibi would be desirable. Removing `vbytes` also seems undesirable because -- as explained in the SE answer -- this unit exists for backwards compatibile comparisons with non-segwit transactions where pre-segwit transaction "sizes" in `bytes` are comparable with segwit transaction `vbyte` sizes.

**Comment by fanquake** [comment]
Feel free to open a Pull Request if you have something meaningful to contribute, and it will be reviewed like any other. However it's becoming clear that nothing worthwhile is going to be accomplished in this thread, so I'm going to close it.
