### ISSUE TITLE
Network Drive (NAS) Support

### ISSUE THREAD

**Issue by byjlw** [bitcoin/bitcoin#26939]
Would be great if I we could use an smb drive as the data drive.

**Comment by willcl-ark** [comment]
Hey @byjlw, what exactly did you have in mind here? Can you not mount the smb drive and use as it the datadir for some reason?

**Comment by byjlw** [comment]
No, it results in lock errors. This was the best context on the issue I've found so far

https://bitcoin.stackexchange.com/questions/60541/is-it-possible-to-use-bitcoin-core-on-mac-os-sierra-saving-the-data-on-the-netwo

5


+50
Core (more specific levelDB, the database library used) does not support network drives. Also, the UTXO access (chainstate) must be as fast as possible and should run on an internal drive, ideally an SSD.

**Comment by willcl-ark** [comment]
Thanks, I didn't know. 

Also seems like there are some workarounds in this [closed issue](https://github.com/bitcoin/bitcoin/issues/7981). The context there also indicates that outside of advising that you symlink old .dat block files to the smb drive (via custom script) there is not much that we can do about it in Core due to levelDB limitations.

That said, I'd re-iterate what was said in that thread: you really don't want your chainstate database (`$DATADIR/chainstate`) or block index (`$DATADIR/blocks/index`) on a slow networked disk as fast access is needed for these, but raw block (`blk*.dat`) and maybe their undo files (`rev*.dat`), which comprise the bulk of a node's storage requriements, are probably ok on a networked drive.

**Comment by byjlw** [comment]
Yes, agree on storage speed. In my case though, it's RAID SSD disks on a 1000mb/s network, so faster than most single internal storage solutions.

**Comment by willcl-ark** [comment]
I don't have an `smb` drive to test with, but I did test with an `nfs` NAS that running with the `-blocksdir=/path/to/network/drive` option appears to work without issue. Therefore I can see two potential solutions for you:

1) Run bitcoind with the `datadir` on an internal disk, and use option `-blocksdir=...` to configure blocks and their associated revision files to be stored on your networked RAID array, which will only leave a few 10's of GB on your internal drive.

2) Periodically stopping `bitcoind` and transferring the blk*.dat and rev*.dat files onto your network drive using one of the scripts found in  issue #7981.

If you feel that the `-blocksdir` option solves your problem then feel free to close this issue. If you think there should be another resolution then let us know and leave it open.

**Comment by byjlw** [comment]
Thanks I'll try this out

**Comment by fanquake** [comment]
@byjlw What's the status of this / result of your testing?

**Comment by byjlw** [comment]
Came up with a different solution. Will close this issue.
