### ISSUE TITLE
BIP158: block filter encoding is inefficient in case of hash collisions

### ISSUE THREAD

**Issue by Kixunil** [bitcoin/bitcoin#27003]
The elements in the block filter are de-duplicated on insertion into a set, however [the hashes are not](https://github.com/bitcoin/bitcoin/blob/ceb74b844caff459a8747ef013e61476e73a3c48/src/blockfilter.cpp#L35-L44). This means a zero is encoded in the filter for each collision. The client never cares about these so they should not be needed.

Is this actually a bug or am I missing something?

For reference, [the same issue is present in the Rust library](https://github.com/rust-bitcoin/rust-bitcoin/issues/1444).

**Comment by john-moffett** [comment]
It appears to be a bug (or at least an inefficiency), but I think the practical implications are pretty minimal, as collisions should only occur about `1/784931` of the time on average for the basic filter. 

It does [appear](https://github.com/bitcoin/bips/blame/master/bip-0158.mediawiki#L115) that the BIP calls for a "set" of the hashes, which implies no duplicates, but it's not explicit.

**Comment by earuak** [comment]
The problem described in relation to the BIP158 is indeed a real problem. When two different elements map to the same hash value (hash collision), the block filter ends up containing a higher number of false positives than expected.

The most common solution for dealing with hash collisions is to use a hash function with a lower collision probability, such as SHA-256 instead of SHA-512. In addition, insertion of duplicate elements in the block filter can be avoided by adding functionality to remove elements from the filter.

It is important to note that while the presence of false positives can be a disadvantage of the block filter, it is still a useful technique to reduce the bandwidth load on blockchain transactions and can be effective if used correctly.

However, it is important that developers are aware of block filter limitations and implement necessary measures to address these limitations.

**Comment by pinheadmz** [comment]
This is not a Bitcoin Core problem and should be addressed on the mailing list to update the BIP.
