### ISSUE TITLE
Show an ajusting percentage of balance to be used in a transfer.

### ISSUE THREAD

**Issue by Suffice** [bitcoin/bitcoin#2723]
Perhaps show a percentage of a person's total balance that will be used for a transaction at the active input figure.

Many have accidentally sent 10x or more of what they meant to send because of some extra digits, or miscalculated denomination. Yet most understand about what percentage of their balance they want to send, and they can then check the percentage to be certain that it's not excessive or too little.

If someone is to send two or more transactions at once, to adjust the percentages accordingly. 

OR:

Show a cautionary message by the transaction form if the amount exceeds a configurable percentage of balance.

**Comment by MeshCollider** [comment]
I don't personally think this is useful (percentage of wallet is not really a useful safety metric IMO, if you have 50 BTC then sending 1 BTC is still a lot to accidentally lose, regardless of the total wallet balance), and there has been no discussion on it since 2013, so I think this should be closed.
