### ISSUE TITLE
Compiling a bitcoin core version that accepts transactions over 100vkb

### ISSUE THREAD

**Issue by batriskaweb3** [bitcoin/bitcoin#27490]
### Please describe the feature you'd like to see added.

i couldnt manage to find any label that fits this,
when people try to inscribe ordinals that are bigger than 400kb they can not be able to because bitcoin core doesnt allow transactions over 100kvb
even though that would require the person to be a miner or pay miners for it but it still would be nice to guide us on how to compile such bitcoin core version

### Describe the solution you'd like

a guide on what code changes should be done to compile such version

### Describe any alternatives you've considered

trying to look through the code to understand it and do it myself

**Comment by fanquake** [comment]
> a guide on what code changes should be done to compile such version

**Comment by pinheadmz** [comment]
The max standard tx size is defined in this line in `policy.h`:

https://github.com/bitcoin/bitcoin/blob/d908877c4774c2456eed09167a5f382758e4a8a6/src/policy/policy.h#L26-L27

Since there are no configuration options node operators can use to change this value, it's reasonable to assume that most if not all Bitcoin Core nodes on the network enforce it. Therefore, even if you were to alter your own software to accept heavier transactions, they would likely not get relayed to any of your peers.

I think this issue should be closed, and discussion moved to stack exchange, note that a few similar questions have already been posted: https://bitcoin.stackexchange.com/search?q=MAX_STANDARD_TX_WEIGHT

If you think the standardness rules should be changed network-wide, probably the bitcoin-dev mailing list is a good place to start, although I expect such a proposal to meet a lot of resistance.

**Comment by batriskaweb3** [comment]
thanks alot
any idea why this error could be occurring?
`Making all in src
make[1]: Entering directory '/home/doodles/bitcoin/src'
make[2]: Entering directory '/home/doodles/bitcoin/src'
  CXX      bitcoind-bitcoind.o
  CXX      init/bitcoind-bitcoind.o
  CXX      libbitcoin_node_a-addrdb.o
  CXX      libbitcoin_node_a-addrman.o
  CXX      libbitcoin_node_a-banman.o
  CXX      libbitcoin_node_a-blockencodings.o
In file included from ./txmempool.h:24,
                 from blockencodings.cpp:13:
./policy/packages.h:20:62: error: static assertion failed
   20 | static_assert(MAX_PACKAGE_SIZE * WITNESS_SCALE_FACTOR * 1000 >= MAX_STANDARD_TX_WEIGHT);
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:9405: libbitcoin_node_a-blockencodings.o] Error 1
make[2]: Leaving directory '/home/doodles/bitcoin/src'
make[1]: *** [Makefile:18956: all-recursive] Error 1
make[1]: Leaving directory '/home/doodles/bitcoin/src'
make: *** [Makefile:824: all-recursive] Error 1`

**Comment by pinheadmz** [comment]
If you're modifying the source code, you won't get much help with build errors here. I think we should close this issue.

**Comment by willcl-ark** [comment]
I agree this should be closed here. @batriskaweb3 has already been given guidance on the procedure they can follow to propose changes to relay policy and also other more suitable avenues to ask questions like this:

> I think this issue should be closed, and discussion moved to stack exchange, note that a few similar questions have already been posted: [bitcoin.stackexchange.com/search?q=MAX_STANDARD_TX_WEIGHT](https://bitcoin.stackexchange.com/search?q=MAX_STANDARD_TX_WEIGHT)
> 
> If you think the standardness rules should be changed network-wide, probably the bitcoin-dev mailing list is a good place to start, although I expect such a proposal to meet a lot of resistance.

**Comment by fanquake** [comment]
Closing for now.
