### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by Martinlopez-hash** [bitcoin/bitcoin#27522]

**Comment by Gezegorz1** [comment]
Grzegorz W Od: Will ClarkWysłano: poniedziałek, 24 kwietnia 2023 01:02Do: bitcoin/bitcoinDW: SubscribedTemat: Re: [bitcoin/bitcoin] Open source (Issue #27522) Closed #27522 as not planned.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
