### ISSUE TITLE
Compute 'short id' when transaction joins mempool

### ISSUE THREAD

**Issue by brunoerg** [bitcoin/bitcoin#27706]
When a node receives a `cmpctblock` it has to verify to its check mempool in order to know whether it has all the required transactions to construct that block. If it doesn't, it will send `getblocktxn` to fetch the missing tx{s}. 

`PartiallyDownloadedBlock::InitData` shows we have to iterate the whole mempool in order to get the short id and do the verifications, see:
```cpp
for (size_t i = 0; i < pool->vTxHashes.size(); i++) {
    uint64_t shortid = cmpctblock.GetShortID(pool->vTxHashes[i].first);
    std::unordered_map<uint64_t, uint16_t>::iterator idit = shorttxids.find(shortid);
    if (idit != shorttxids.end()) {
        if (!have_txn[idit->second]) {
            txn_available[idit->second] = pool->vTxHashes[i].second->GetSharedTx();
            have_txn[idit->second]  = true;
            mempool_count++;
        } else {
            // If we find two mempool txn that match the short id, just request it.
            // This should be rare enough that the extra bandwidth doesn't matter,
            // but eating a round-trip due to FillBlock failure would be annoying
            if (txn_available[idit->second]) {
                txn_available[idit->second].reset();
                mempool_count--;
            }
        }
    }
    // Though ideally we'd continue scanning for the two-txn-match-shortid case,
    // the performance win of an early exit here is too good to pass up and worth
    // the extra risk.
    if (mempool_count == shorttxids.size())
        break;
}
```

This means that every time we receive a compact block we have to iterate the whole mempool and calculate the "short id"s all over again. Couldn't`CTxMemPool` have a hashmap where we could store the transactions' short id right after joining the mempool and remove it once the tx gets confirmed/out of mempool?

**Comment by brunoerg** [comment]
cc: @Davidson-Souza

**Comment by pavel-vasin** [comment]
Short IDs, as they are specified in BIP 152, cannot be computed in advance because their formula includes a block header (and a random nonce) in addition to a transaction content.

**Comment by brunoerg** [comment]
Makes sense, thanks for the clarification!

**Comment by Davidson-Souza** [comment]
@pavel-vasin Yes, you're right. The compact block relay design, as it currently exists, does not permit computations.

> Salting the hash computation using the block header is needed to prevent intentional collisions, and is the price for using short ids.

Does it really need to be the block header? If we kept a random, per connection byte-array used for salting, how could an attacker cause intentional collisions?

(Thinking outside BIP152 context) If we hold a per connection salt, and a rolling hash map for mempool transactions, we could avoid the mempool iteration entirely. Since we only keep a few high-bandwidth connections, and hash sets are very small, it's not really a memory usage penalty, IMO. If our peer misbehave, we can detect it, once they would create an uncommon number of collisions.

I guess a first good step would be benchmarking this code path, and see how it impacts the whole block compact propagation logic.

**Comment by pavel-vasin** [comment]
>Does it really need to be the block header? If we kept a random, per connection byte-array used for salting, how could an attacker cause intentional collisions?

If PoW or something similarly strong is not involved then the attacker can create collisions for a chosen set of nonces. An algorithm of the attack is straightforward:
1. Connect to a next victim
2. Negotiate a nonce
3. Bruteforce transactions that collide under the nonce
4. Go to step 1

**Comment by fanquake** [comment]
Ok. Closing for now. Discussion can continue, but it's not clear why this is an issue. General questions /discussion can also be asked/happen in IRC etc.
