### ISSUE TITLE
25.0 RC Testing Guide Feedback

### ISSUE THREAD

**Issue by ismaelsadeeq** [bitcoin/bitcoin#27736]
This issue is to discuss the [25.0 Release Candidate Testing Guide](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/25.0-Release-Candidate-Testing-Guide). If you have any issues with or feedback on the document, please leave a comment here.

Note: this is for feedback on the document, not on Bitcoin Core or on the 25.0 changes. Please see the [#27621](https://github.com/bitcoin/bitcoin/issues/27621) for instructions on how to report bug/results.

Thank you for your feedback

**Comment by theStack** [comment]
Thanks for creating this testing guide! I didn't have a chance to look at any of the detailled steps yet, but have a suggestion to add two other features to test. v25.0 will be the first release where Bitcoin Core takes internal use of the compact block filters (BIP158, enabled via `-blockfilterindex=1`), rather than only serving them to peers. There is on one hand a new RPC call `scanblocks` [1] which looks for blocks containing a certain set of passed descriptors by using block filters, and on the other hand a feature "fast wallet rescan" which automatically does the same for relevant output scripts belonging to a descriptor wallet to significantly speed-up wallet rescans.

Relevant links:
- `scanblocks` RPC: [original PR](https://github.com/bitcoin/bitcoin/pull/23549), [follow-up PR adding the option to filter out false-positives](https://github.com/bitcoin/bitcoin/pull/26325)
- fast wallet rescan: [PR](https://github.com/bitcoin/bitcoin/pull/25957), [review club session](https://bitcoincore.reviews/25957), [simple idea how this could be tested](https://github.com/bitcoin-core-review-club/website/pull/554#issuecomment-1236931732)

[1] this was easy to miss as it has only been added to the release notes recently: https://github.com/bitcoin/bitcoin/pull/27686#issuecomment-1560862446

**Comment by ismaelsadeeq** [comment]
Thank you @theStack for pointing this out, these are important features, I will add them to the guide.

**Comment by D33r-Gee** [comment]
OS: Ubuntu 20.04

Hello found an issue running the bonus test ["Test Command specified by shutdownnotify..."](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/25.0-Release-Candidate-Testing-Guide#test-command-specified-by-shutdownnotify-are-executed-synchronously-before-shutdown)

The following command didn’t work:
bitcoind-test -daemon -shutdownnotify="bcli touch hello.txt"

However after looking at the [#23395](https://github.com/bitcoin/bitcoin/pull/23395) PR, removing the bcli worked:
bitcoind-test -daemon -shutdownnotify="touch hello.txt"

**Comment by evansmj** [comment]
Just documenting a discussion for a `bcli stop` command to be added at the end of -daemon sections. Mine was running in the background and was giving me failed to connect to any endpoint errors, calling `pkill bitcoind-test` resolves it but the experts in the chat think we should add to the guide calls to `bcli stop`.  

stickies-v 12:02:47
evansmj: cc abubakarsadiq yeah i think adding a `bcli stop` command at the end of every section that started with running bitcoind in `-daemon` mode makes sense 

abubakarsadiq Abubakar12:42:11
Yeah, to avoid such issues. I remember I had to pkill bitcoind which has to stop all my bitcoin nodes running, thanks for pointing that out evansmj, also thanks stickies-v for the ping

**Comment by evansmj** [comment]
> OS: Ubuntu 20.04
> 
> Hello found an issue running the bonus test ["Test Command specified by shutdownnotify..."](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/25.0-Release-Candidate-Testing-Guide#test-command-specified-by-shutdownnotify-are-executed-synchronously-before-shutdown)
> 
> The following command didn’t work: bitcoind-test -daemon -shutdownnotify="bcli touch hello.txt"
> 
> However after looking at the [#23395](https://github.com/bitcoin/bitcoin/pull/23395) PR, removing the bcli worked: bitcoind-test -daemon -shutdownnotify="touch hello.txt"

i experienced the same issue with the original command, and your command resolved it and generated my hello.txt.

**Comment by ismaelsadeeq** [comment]
Thank you @evansmj and @D33r-Gee for all your feedback the guide has been updated.

**Comment by D33r-Gee** [comment]
> Thank you @evansmj and @D33r-Gee for all your feedback the guide has been updated.

with pleasure!

**Comment by fanquake** [comment]
25.0 has been tagged. So closing this issue (conversation/testing of final can continue).

**Comment by ismaelsadeeq** [comment]
All comments and suggestions have been addressed, Thank you everyone for the feedback.
