### ISSUE TITLE
wallets created on master get corrupted when processed with v25

### ISSUE THREAD

**Issue by mzumsande** [bitcoin/bitcoin#27915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I randomly encountered this by loading a wallet created from master with an older version. I could trace it down to bd13dc2f46ea10302a928fcf0f53b7aed77ad260 (#26076), but I don't know descriptor wallets enough to understand what's going on (cc @Sjors @achow101).

### Expected behaviour

`bitcoind` starts, or at least tells me to use a later version if #26076 was a breaking change instead of corrupting `wallet.dat`.

### Steps to reproduce

(master, clean chain): 
`createwallet -regtest ""`
(v25.0rc2):
first `bitcoind -regtest` succeeds
then stop and restart the node: The second `bitcoind -regtest` leads to an InitError:
`Error: Error: Unable to expand wallet descriptor from cache`
now, the wallet cannot be loaded by either version.

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v25.0rc2 / master

### Operating system and version

Ubuntu

**Comment by Sjors** [comment]
Does it also happen the other way around?

Nothing in that PR should change the key material, so the cache of derived keys should be the same too. I'll investigate and add an explicit test for this case.

**Comment by mzumsande** [comment]
> Does it also happen the other way around?

No, wallets created in 25.2 are loaded without problems in master for me.

**Comment by fanquake** [comment]
Can someone clarify what version(s) we are talking about here. 25.2 doesn't exist. There is currently "master", 25.x, 25.0, 24.x, 24.1. etc

**Comment by mzumsande** [comment]
Sorry, I meant v25.0rc2

**Comment by furszy** [comment]
@mzumsande give #27920 a shot please. It fixes the issue for me.
Still, while in a first glance looks ok, will think more about it.

**Comment by Sjors** [comment]
Can't we derive the ID from the literal string as stored in the wallet database?

**Comment by Sjors** [comment]
@achow101 wrote in the PR:

> Once we assign the id, we should just store it and remember what it is rather than regenerating it whenever we want it.

This seems better than my suggestion above to store the raw string.

**Comment by furszy** [comment]
> @achow101 wrote in the PR:
> 
> > Once we assign the id, we should just store it and remember what it is rather than regenerating it whenever we want it.
> 
> This seems better than my suggestion above to store the raw string.

That would work for newer versions, not for the previous ones. We can't do much there. Old releases will still read the descriptor, and calculate the id by hashing the apostrophe formatted descriptor string.

The main point here is that every single descriptor record in the wallet database is keyed by the descriptor id. So.. if we change the spkm id calculation in newer versions, old software versions will not be able to connect the descriptor entries: keys, caches, etc. with the descriptor itself.
And, even worst, after finish the loading process, the wallet will store a new descriptor entry (because the wallet re-writes the descriptor post `TopUp()`), keyed by the hash of the apostrophe formatted descriptor string... which is what causes this unrecoverable state.

Overall, I don't think that there is a good workaround for the downgrading topic. We cannot change the past, unless we make people migrate to a newer database format, or..  we store records duplicated in the db.. with the two possible ids.. but that would be the dirties thing ever.

So, I think that we will have to live with the apostrophe formatted descriptor string IDs for now. Which is not ideal, but.. it isn't really an issue anyway.

**Comment by Sjors** [comment]
Living with apostrophe is one option, but the other is to prevent downgrades. This can be done by making `WALLET_FLAG_GLOBAL_HD_KEY` mandatory, see https://github.com/bitcoin/bitcoin/pull/26728/files#r1081289252. That only works if that PR lands before the 26 branch-off. We can leave this PR open in case #26728 doesn't make it in time.

The third option is to revert #26076 which would be my least favourite.

**Comment by furszy** [comment]
> Living with apostrophe is one option, but the other is to prevent downgrades.

Haven't seen #26728 yet but preventing downgrades on descriptors wallets sounds bad for me. Users already face enough difficulties with their legacy wallets and the migration process for now. We should try to avoid breaking the descriptors wallet compatibility now too.

Furthermore, I believe this isn't a major problem really, we just had a bad design decision by making the software calculate the db key on-demand, but it is not the end of the world. We can stick to the current implementation and clearly state that descriptor IDs are calculated by hashing the apostrophe-formatted descriptor string. And, in the future, if we ever want to replace the db key for something better, we can take the opportunity to propose a better overall database format and implement the changes all at once.

**Comment by Sjors** [comment]
I'm still worried that something like this will happen again because it's so brittle. E.g. if we change something in miniscript.

**Comment by furszy** [comment]
> I'm still worried that something like this will happen again because it's so brittle. E.g. if we change something in miniscript.

You mean changing the string representation of a miniscript output descriptor between releases will cause the same issue that we are having here with the hd path. Hmm, that opens a bigger can of worms. Good that we are now aware of it and can be careful with the modifications there.

Maybe not for the next release (because I think that we are not planning to introduce new miniscript changes for now) but.. the incompatibility idea started getting more traction on me too.. this might also suit well for a new record type and an automatic migration process.

Will keep thinking about it.

At least with #27920, and as long as we don't introduce changes in the descriptor string representation, we gain time to figure out the best way to solve this.

**Comment by luke-jr** [comment]
Maybe we should consider it an error to load a wallet if the descriptors can't all be round-tripped? (and consider it a bugfix for 25.x, while also trying to avoid triggering it for a while)

**Comment by furszy** [comment]
> Maybe we should consider it an error to load a wallet if the descriptors can't all be round-tripped? (and consider it a bugfix for 25.x, while also trying to avoid triggering it for a while)

Yeah, that is already done in #27920 (fc5565eb). It will prevent ugly stuff from happening from now on.

**Comment by Sjors** [comment]
I'll review the apostropocalypse fix soon, thanks.
