### ISSUE TITLE
test: Use `pathlib` over `os.path`

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#28362]
### Motivation

`os.path` is quite verbose in the tests and is problematic, because strings can be appended to it, for example it is possible to type:

```py
>>> os.path.join('a/') + '/../b.txt'
'a//../b.txt'
```

This may lead to issues down the line when the tests are run on Windows and expect a different path separator.

### Possible solution

While some uses of `os.path` are hard(er) to replace, with questionable benefits, I think removing the use of `TestNode.datadir` and replacing it with `TestNode.datadir_path` is a good first step.

### Useful Skills

* Compile Bitcoin Core and run the python tests
* Basic familiarity with the Bitcoin Core RPC, and the python tests
* `os.path` and `pathlib` knowledge

### Guidance for new contributors

Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by miles170** [comment]
I would like to work on this.

**Comment by ns-xvrn** [comment]
If @miles170 doesn't mind, I would like to attempt this one. I've changed all the refs in functional tests  (18 files) and `test_node.py` had some methods where I think it also makes sense to pass Path object instead of datadir str so that `os.path.join` can be avoided in those places as well. All functional tests passed on my local.

Let me know if I should submit this PR or if I should also try to change os.path.join usage.

Changes here:
https://github.com/ns-xvrn/bitcoin/commit/dcaed3316620f9fb72d372df0a1b60b0349d5d38

**Comment by ns-xvrn** [comment]
Understood, will do. Just did another commit, but not completely done yet. A dozen more files remaining, I should've this completed in a day or two.

**Comment by ns-xvrn** [comment]
I have made the changes and just did a single clean commit. I was able to remove most of the `os.path.join` references, there's a handful remaining in the files where those are just using config strings to join in a single use pattern and since those use the string output using Path won't be very much value add (will have to typecast as strings again). I will do a PR once CI/CD is successful (I saw it automatically kicked off last time on my changes but doesn't seem like the latest one is - I assume it should pick up from workflow automatically).

**Comment by ns-xvrn** [comment]
So CI/CD kicked off and ran successfully after I did "sync fork", I have created the PR #28388 . Hopefully I have submitted the PR according the contribution policy. Let me know if anything needs an amend.

**Comment by ns-xvrn** [comment]
There were some issues when I opened the PR: https://github.com/bitcoin/bitcoin/pull/28388/checks

I've fixed the linting issues from that list but I'm not sure about the rest of the issues so I would appreciate if anyone can advise on those so I can fix those and resubmit another PR.

**Comment by hebasto** [comment]
> There were some issues when I opened the PR: [#28388 (checks)](https://github.com/bitcoin/bitcoin/pull/28388/checks)
> 
> I've fixed the linting issues from that list but I'm not sure about the rest of the issues so I would appreciate if anyone can advise on those so I can fix those and resubmit another PR.

A PR itself is a proper place to review and discuss any issues. Just open it and follow reviewers' comments.
