### ISSUE TITLE
Bitcoin Core - Transaction without permition

### ISSUE THREAD

**Issue by hugomenezes85** [bitcoin/bitcoin#29049]
Hi,
I open my Wallet Bitcoin Core and i notice a transaction with my total amount without any my permition.
Any one can help?

![bitcoin](https://github.com/bitcoin/bitcoin/assets/153444557/9a71cfb4-3e32-48c1-a476-4db2609cb3c4)

**Comment by hugomenezes85** [comment]
![bitcoin2](https://github.com/bitcoin/bitcoin/assets/153444557/acff6016-6f7d-4478-b2ec-ee16bb092749)

**Comment by hugomenezes85** [comment]
![Captura de ecrã 2023-12-10 165542](https://github.com/bitcoin/bitcoin/assets/153444557/db34a3b4-3c9d-4e65-95bf-d7f1253769f1)

**Comment by Cryptomaster001** [comment]
Hello @hugomenezes85,
can you post the transaction hash?

**Comment by hugomenezes85** [comment]
Hi,YesCumprimentosHugo MenezesNo dia 10/12/2023, às 16:58, Cryptomaster001 ***@***.***> escreveu:﻿
Hello @hugomenezes85,
can you post the transaction hash?

**Comment by hugomenezes85** [comment]
> Hello @hugomenezes85, can you post the transaction hash?

Hi, i think its this picture. 
![bitcoin2](https://github.com/bitcoin/bitcoin/assets/153444557/49d9013b-b730-42a3-bad4-5fd87f8179d8)

**Comment by willcl-ark** [comment]
Hello @hugomenezes85 .

I'm sorry to hear about your unauthorised transaction. If this has really taken place without your knowledge it could indicate that someone has obtained a copy of your wallet file, private key(s) or other senstive key material in order to make this transaction. This would also correlate with Bitcoin Core not needing to open the wallet for this to happen -- Bitcoin Core did not make the transaction, only picked up that it had occured from the blockchain. I'd encourage you to check your computer, logs and backups for signs of compromise.

Unfortunately this issue tracker is not the place to get help/support on this so I'm going to close it. 

For support in investigating your potential compromise you can try other forums such as Reddit: https://www.reddit.com/r/Bitcoin/ , IRC https://webchat.freenode.net/#bitcoin or Bitcointalk: https://bitcointalk.org/
