### ISSUE TITLE
assumeutxo: nTx and nChainTx in RPC results are off

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#29328]
AssumeUtxo mocks the `nTx` value of headers after the last background block and before the snapshot header with `nTx=1`. This means that the `getblockheader` and `getchaintxstats` RPCs return the wrong `nTx` or `txcount` fields for those blocks.

Not sure if anything should be done about this?

**Comment by mzumsande** [comment]
> I don't know if this is true, but if it is true, it seems like `GuessVerificationProgress` could just report progress based on block heights instead of transaction counts

If we can do that, we should get rid of nChainTx altogether. I think that its only other use is for `HaveNumChainTxs` which doesn't use its value but checks whether it is 0. That would also save some memory and eliminate problems like #29258.

However, just using block heights would be very inaccurate because the first ~300k blocks are almost empty.
Maybe we could plot the `nChainTx` for each block, use non-linear regression to fit some mathematical function (e.g. some polynomial, possibly piecewise) to approximate it, and then use that and get rid of `nChainTx`?

**Comment by ryanofsky** [comment]
> If we can do that, we should get rid of nChainTx altogether.

Oh, I don't think we should use block heights instead of _real_ nChainTx values, because as you say using block heights would be very inaccurate. I'm just suggesting we could use block heights instead of _fake_ nChainTx values, and we would not be worse off because currently the fake nChainTx values are set to block heights. Also probably it probably be good to estimate the number of transactions in BLOCK_ASSUMED_VALID blocks by interpolating between nChainTx in the snapshot block, and nChainTx in the last validated block, instead of assuming each block before the snapshot has 1 transaction.

**Comment by mzumsande** [comment]
I see, I misunderstood. Still might also be worth thinking about getting rid of `nChainTx` in the long run (which has been discussed before in #13875), but that is off-topic here.

**Comment by ryanofsky** [comment]
> I don't think this is true. For example, it is possible that a block was downloaded and the `nTx` value was set, but the block later turned out to be invalid. Thus `IsValid()` will return false, but the `nTx` value is real.

Good point. Maybe the practical consequences would not be too bad if it just causes nTx to be omitted from rpc results when in some cases it shouldn't be. But this seems like another reason to want get rid of the fake assumeutxo nTx and nChainTx values, so we can simply treat 0 values as invalid, and nonzero values as valid.

**Comment by Wwwwwwuuuuu** [comment]
Please help me figure out why this transaction is not confirmed?8f62acf0f0ddc3e38db2e8ec2755f4e54aa5bf616d685e2f3361155fc9d44125

**Comment by ryanofsky** [comment]
Attempting to get rid of the fake values in #29370
