### ISSUE TITLE
loadwallet hangs on forever!

### ISSUE THREAD

**Issue by EazyServer** [bitcoin/bitcoin#29525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I had a running bitcoin core 22.0.0 on a linux computer which was running fine 8 months ago. I turned on this machine today and trying to access a wallet but the wallet loading takes forever and never returns success or fail!
I have then updated the core to 26.0.0 and that didn't make any difference.
Every other aspect seems to be working fine include creating and loading the newly created wallets.
I have tried the console but again not difference 
![Screenshot 2024-03-01 at 15 53 45](https://github.com/bitcoin/bitcoin/assets/19202935/d0f34cee-4381-4562-af19-befaff26acba)

### Expected behaviour

Expect success or fail prompt with an error message on fail.

### Steps to reproduce

Not sure how that can be replicated without sharing my wallet!

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

26.0.0

### Operating system and version

Linux Debain 11 bullseye

### Machine specifications

The OS runs on proxmos VM, which runs on hp rack server. Happy to provide more specific info if helpful.

**Comment by achow101** [comment]
Large wallets (those with many transactions or addresses) can take a long time to load. If your wallet is large, it may simply be that the wallet is taking a long time to load rather than there being a failure.

If you simply let it go on, does it ever complete, and if so, about how long did that take?

**Comment by EazyServer** [comment]
> Large wallets (those with many transactions or addresses) can take a long time to load. If your wallet is large, it may simply be that the wallet is taking a long time to load rather than there being a failure.
> 
> If you simply let it go on, does it ever complete, and if so, about how long did that take?

Here is an updated after leaving it running 
![Screenshot 2024-03-01 at 19 26 50](https://github.com/bitcoin/bitcoin/assets/19202935/e3d8903c-7511-4721-9319-426025ffe3fd)

I know for a fact that I only have a handful of transactions so I suspect that would be the reason.

**Comment by achow101** [comment]
Ah, so the long loading time would be because it is rescanning, although the failed rescan is a bit odd. Can you post the contents of your debug.log file? There should be log lines about laoding and rescanning the wallet, including some mention of why it failed.

**Comment by EazyServer** [comment]
After the fail loadwallet yesterday I shutdown the machine, I turned it on today and that wallet loaded in about 40 secs.
I have another wallet "exploere2" and that took another 3 hours to load same as yesterday. and it also take about 30 - 40 secs to load! 
why is it still taking a long time (30 sec) to load after the rescan? it used to be instant 8 months ago!

here is a screen grab of the log, which doesn't match the error on the console!

![Screenshot 2024-03-02 at 14 01 09](https://github.com/bitcoin/bitcoin/assets/19202935/3676590e-b5dc-4dcd-a729-976aeb74ec35)

**Comment by furszy** [comment]
What I can infer from the few logging lines you shared is that your wallet scanned 1637 blocks in a minute. Which means that the process should have started 283.201 blocks behind the tip. Can you please provide the entire rescan logs to confirm this information? (search for where it says "Rescan started from block xxx").
Also, can you share your hardware information please.

> why is it still taking a long time (30 sec) to load after the rescan? it used to be instant 8 months ago!

The wallet stores the last scanned block. The loading procedure triggers a chain scan when it detects that it is behind the chain tip. The reason it takes 30 seconds after the initial loading is because your wallet is up-to-date with the tip now.

**Comment by furszy** [comment]
Another question, were you actively using any RPC command when this happened?. Something that could explain the delay is a heavy usage of RPC commands that locks the node's main mutex.

**Comment by EazyServer** [comment]
That's the start of the log and there are about 500 lines of logs related to this wallet, mixed with other log entries..

![Screenshot 2024-03-03 at 14 11 06](https://github.com/bitcoin/bitcoin/assets/19202935/09573917-485a-4d42-a563-8e8bf92cbe98)

Here is somewhere while still scanning:
![Screenshot 2024-03-03 at 14 13 54](https://github.com/bitcoin/bitcoin/assets/19202935/7876d446-2262-4954-a8ef-4c296c31256d)
And I already shared the end of the log for this wallet.

My node is not RPC heavy at all (a standard bitcoin node)

Looking at the logs and your guys comments I now I understand the reason why it took ages, but it would be great to show some of these logs in the console or at least ave the `--verbose` flag.
If I see this in the console `Rescanning last 542872 blocks (from block 289831)` I would understand that there is a scanning in progress and it may take a while to load. I didn't know that wallets need scanning before this 😅

Also, it just caught my eye the rescanning starting from block 289831! I know for a fact that I was at least at block 700000, 8 months ago! what's the reason staring further beyond block 700000?

HW info from Proxmos:
![Screenshot 2024-03-03 at 14 28 19](https://github.com/bitcoin/bitcoin/assets/19202935/24f7b64c-ef21-44b8-8b6d-67239b871585)

**Comment by furszy** [comment]
> it would be great to show some of these logs in the console or at least use a --verbose flag.

`--verbose` is for the RPC command output information. are you asking for partial updates while the RPC command is being executed?. Because that would break the http server specs; one request must receive a single response. Also, any console output would appear at the server console and not at the client one.

Something we could theoretically do is return early, with more info, by making the `loadwallet` inner rescan procedure async but this has the drawback of a possible "silent" wallet unload when the initial rescan fail.

**Comment by EazyServer** [comment]
Yes it would be great to get partial updates while doing `loadwallet` as this potentially time consuming process.
Even if it says `Executing... Rescanning last X blocks (from block Y)` instead of a not very informative `Executing...` prompt.

Thanks for all the help anyways 👍

**Comment by willcl-ark** [comment]
Closing this as it has not had any activity in a while. If you are interested in continuing discussion on this, or you feel that it is sufficiently important, please leave a comment so that it can be reopened.
