### ISSUE TITLE
Testnet fixed seeds don't work

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#29574]
Compile master (0fa9f17332a6d9b2eb6e3d9f9102bfd2d9c6f516). Remove `peers.dat` & `anchors.dat`. Run `bitcoind -dns=0 -dnsseed=0 -testnet`:
```bash
2024-03-06T11:04:41Z init message: Done loading
2024-03-06T11:04:41Z msghand thread start
2024-03-06T11:04:42Z Adding fixed seeds as -dnsseed=0 (or IPv4/IPv6 connections are disabled via -onlynet) and neither -addnode nor -seednode are provided
2024-03-06T11:04:42Z Added 0 fixed seeds from reachable networks.
```

Mainnet seems to work as expected:
```bash
2024-03-06T11:05:42Z msghand thread start
2024-03-06T11:05:42Z opencon thread start
2024-03-06T11:05:42Z Adding fixed seeds as -dnsseed=0 (or IPv4/IPv6 connections are disabled via -onlynet) and neither -addnode nor -seednode are provided
2024-03-06T11:05:42Z Added 801 fixed seeds from reachable networks.
2024-03-06T11:05:47Z New outbound-full-relay v1 peer connected: version: 70016, blocks=833399, peer=2
2024-03-06T11:05:48Z Synchronizing blockheaders, height: 833399 (~100.00%)
```

From what I can tell (using the release bins) this has been broken since at least `24.x`.

**Comment by willcl-ark** [comment]
This is because all the seeds we have for testnet are `NET_ONION`: https://paste.256k1.dev/xosamodiga.log and so get filtered by the predicate in `ThreadOpenConnections`:

```cpp
seed_addrs.erase(std::remove_if(seed_addrs.begin(), seed_addrs.end(),
                                [&fixed_seed_networks](const CAddress& addr) { return fixed_seed_networks.count(addr.GetNetwork()) == 0; }),
                 seed_addrs.end());
```

```gdb
>>> p fixed_seed_networks
$3 = std::unordered_set with 2 elements = {
  [0] = NET_IPV6,
  [1] = NET_IPV4
}
```

In fact, as far as I can tell it doesn't appear that we have **ever** had ipv4 seeds for testnet? So perhaps this is a (historical and) purposeful decision. It appears this has been the case since [2014](https://github.com/bitcoin/bitcoin/commit/a60120e951ae94d0553c5515229432e016fb0657) when this file was introduced. I roughly checked a few version previous and only found references to mainnet seeds. This would seem like an odd decision to me though, so perhaps I'm missing something here.

For mainnet we have _nodes_main.txt_ which includes auto-fetched addresses from a dns seeder, and _nodes_main_manual.txt_ which adds onion and I2P seeds.
By contrast for testnet _nodes_test.txt_ is not in fact ipv4 addresses, but manually-added tor v3 addresses.

If we want testnet nodes to be able to sync without relying on dns seeds then we should consider adding some testnet IPV4 addresses.

**Comment by fanquake** [comment]
> This would seem like an odd decision to me though, so perhaps I'm missing something here.

I agree. I'm not sure why we'd only want to ship onion seeds for testnet, as that only makes it, if anything, slightly less usable. Maybe they can be added, and the test in feature_config_args extended to cover testnet.

**Comment by mzumsande** [comment]
> I'm not sure why we'd only want to ship onion seeds for testnet, as that only makes it, if anything, slightly less usable.

I think the reason is that we have working dns seeds for testnet, but since these don't provide onion addresses, we needed some mechanism to find peers to make it possible to bootstrap with `-onlynet=onion`. If we added fixed IPv4 and IPv6 seeds for testnet, they would just have the role of a backup mechanism anyway. This is obviously important for mainnet, but maybe not really necessary for testnet?

**Comment by fanquake** [comment]
> This is obviously important for mainnet, but maybe not really necessary for testnet?

Possibly, but it seems to just slightly reduce usability for no real benefit? I guess we were also inconsistent not shipping fixed i2p or cjdns seeds for testnet either, but with the current update i2p will now be shipped.

**Comment by achow101** [comment]
I'm currently working on a new DNS seeder and crawler that we'd be able to use for generating the fixed seeds for all networks. This will also include onion, i2p, and cjdns nodes so they don't have to be done manually as we are doing now.

**Comment by willcl-ark** [comment]
See #30008

**Comment by fanquake** [comment]
This was fixed.
