### ISSUE TITLE
Tons of Socks5() connect to x.x.x.x:8333 failed: connection refused-messages when i use TOR - why?

### ISSUE THREAD

**Issue by kosuodhmwa** [bitcoin/bitcoin#29759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Gets tons of Socks5() connect to x.x.x.x:8333 failed: connection refused-messages

### Expected behaviour

No messages like that

### Steps to reproduce

- install tor via apt-get

- add that to /etc/tor/torrc file:
ControlPort 9051
CookieAuthentication 1
CookieAuthFileGroupReadable 1

- restart tor service

- add that to ~/.bitcoin/bitcoin.conf file:
proxy=127.0.0.1:9050
listen=1
bind=127.0.0.1

- start bitcoind service

### Relevant log output

Many lines like that:

Socks5() connect to x.x.x.x:8333 failed: connection refused

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

Most current

### Operating system and version

Debian 12.5.x

### Machine specifications

Oracle VirtualBox VM, Debian 12.5.x on Windows 10 Pro x64 Host System

**Comment by kosuodhmwa** [comment]
Installed as described on https://en.bitcoin.it/wiki/Setting_up_a_Tor_hidden_service AND

1.) "usermod -a -G **debian-tor** BITCOIN_USER" instead of "usermod -a -G **tor** BITCOIN_USER"

2.) Then a OS restart after that user / group permission change thing

**Comment by kosuodhmwa** [comment]
(BITCOIN_USER = root)

**Comment by kosuodhmwa** [comment]
Maybe the problem is that IPv6 is disabled via sysctl.conf on that system?

**Comment by kosuodhmwa** [comment]
![image](https://github.com/bitcoin/bitcoin/assets/24782840/cf9126db-53ef-4cf7-8d25-cc24ea60429a)

**Comment by kosuodhmwa** [comment]
Nobody knows what the problem is?

**Comment by pinheadmz** [comment]
What exact commit did you compile from? Does it include #29649 ?

**Comment by kosuodhmwa** [comment]
How can i get the version number from the source i've got from master GIT repo i've compiled?

**Comment by pinheadmz** [comment]
`git rev-parse HEAD`

**Comment by mzumsande** [comment]
I also get these errors sometimes when running with Tor. While they appear on some outgoing connection attempts, other connections are successful, so there seems to be nothing wrong on my end fundamentally. While a timout does not lead to a log entry in debug.log, answers from the SOCKS5 proxy with "general failure" and "connection refused" are logged, and it is not clear to me when which of the three happens.

So I wonder if this happens every time and you can't make successful connections, or only sporadically (in which case there could be no problem except for possibly overzealous logging).

**Comment by vasild** [comment]
As @mzumsande mentioned above, some errors like these are normal because they are printed whenever we fail to connect to a Tor peer. Not all Tor peers are online all the time. Does `bitcoin-cli getpeerinfo` show that you have at least one outbound connection to a Tor node? With some filtering: `bitcoin-cli getpeerinfo |jq 'map(select(.inbound == false and .network == "onion")) |map({connection_type: .connection_type, addr: .addr, network: .network})'`.

If you cannot establish any connection to a Tor node, then there is a real problem in your setup.

> Socks5() connect to x.x.x.x:8333 failed: connection refused

This error comes from the Socks5 proxy (aka the Tor daemon) if it cannot connect to the destination we asked for. Do you get only IP addresses in those messages (`x.x.x.x`) or also onion addresses (e.g. `ydvbxdzs6w5wefifiqsqntpbd7tliofenqih5hlnz34546fvy4ab7iid.onion`)?

There is an inconsistency wrt logging connection failures: IPv4 and IPv6 connection failures are logged only if running with `-debug=net`:
https://github.com/bitcoin/bitcoin/blob/3b987d03a49964995dced76889634561fd363d28/src/netbase.cpp#L551
https://github.com/bitcoin/bitcoin/blob/3b987d03a49964995dced76889634561fd363d28/src/netbase.cpp#L574
whereas Tor connection failures are logged as errors unconditionally:
https://github.com/bitcoin/bitcoin/blob/3b987d03a49964995dced76889634561fd363d28/src/netbase.cpp#L448

**Comment by kosuodhmwa** [comment]
**The source code from the master branch i've compiled is:**
**_root@debian-12-btc-node:~/bitcoin# git rev-parse HEAD_** gives me the following output:
0fa9f17332a6d9b2eb6e3d9f9102bfd2d9c6f516

**Comment by kosuodhmwa** [comment]
`0fa9f17332a6d9b2eb6e3d9f9102bfd2d9c6f516`

**Comment by kosuodhmwa** [comment]
Now i saw that i also have message like that: 

`2024-04-03T20:43:47Z Socks5() connect to 77.7.121.181:8333 failed: general failure`

**Comment by kosuodhmwa** [comment]
**_"Do you get only IP addresses in those messages (x.x.x.x) or also onion addresses (e.g. ydvbxdzs6w5wefifiqsqntpbd7tliofenqih5hlnz34546fvy4ab7iid.onion)?"_**

No, only for IP addresses as shown on post above. @vasild

**Comment by kosuodhmwa** [comment]
![sn](https://github.com/bitcoin/bitcoin/assets/24782840/ac1474d5-1224-43a2-8e7a-a13b935f7e04)

**Comment by kosuodhmwa** [comment]
Maybe it's an idea to check these servers (they will be listed via console output) via "telnet [IP_ADDRESS] 8333"... 

If i dont get an anwser from telnet (TCP), then the problem is on these hosts / servers. If i get an answser, there is a problem on my side

**Comment by kosuodhmwa** [comment]
ok thx

**Comment by kosuodhmwa** [comment]
closed

**Comment by kosuodhmwa** [comment]
-> easy to bypass with <./bitcoind | grep -v -e 'Socks5'>
