### ISSUE TITLE
Rethink thread_local (take 2)

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#29952]
After dbfca4a815d2dbef69f3b634c24b875bc1d22afc from the 23.x release (and fe1b3256888bd0e70d0c9655f565e139ec87b606 from 25.x), I think the `--disable-threadlocal` can now be dropped, as those commits removed the need for it?

cc @hebasto @fanquake

**Comment by laanwj** [comment]
Concept ACK (if indeed all platforms we care about can do this now, including mingw)

**Comment by laanwj** [comment]
@vasild Do you know if C++ thread-local storage is still broken on FreeBSD?

**Comment by laanwj** [comment]
i think the main problem with the map approach is that it doesn't clean up data when threads disappear, this is something that TLS handles automatically, and also why it's so hard for platforms to get right

**Comment by vasild** [comment]
It just occurred to me on Friday evening and I forgot about this during the weekend - we may have a bug in our code and FreeBSD may just be the messenger - we return a reference to the `thread_local`, store it in `CLockLocation`, from there in the global `lockdata` / `lock_stack`. It looks like the reference in `lockdata` may still be existent after the thread has exited.

@maflcko, thanks for the `string_view` hint!

**Comment by vasild** [comment]
This is indeed some problem in FreeBSD's libc which I reported upstream with a minimal, reproducable test case:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=278701

Is anybody interested in reviewing the patch I posted above if I PR it:
https://github.com/bitcoin/bitcoin/issues/29952#issuecomment-2079776241
reworked to return `std::string_view` to the callers, but still storing the thread name in `char []`? That would work around the FreeBSD weird message printout because the `thread_local` variable will not have a destructor.

As for storing a reference to `thread_local` in a global variable - that is dangerous and should be avoided IMO. I checked that there is no bug currently in the code but it looks fragile.

**Comment by laanwj** [comment]
> reworked to return std::string_view to the callers, but still storing the thread name in a thread_local char []?

Yes. i think (for this one very rare exception) it's acceptable to store a string in a fixed-size buffer. To not need a destructor and heap deallocation when a thread goes away, works around a large part of the complexity of handling thread-local data.

And making it use `string_view` throughout the changed functions instead of `char*` is a good idea, a lot less ugly.

**Comment by vasild** [comment]
> Is anybody interested in reviewing the patch I posted above if I PR it: [#29952 (comment)](https://github.com/bitcoin/bitcoin/issues/29952#issuecomment-2079776241)

PRed at https://github.com/bitcoin/bitcoin/pull/30095

**Comment by hebasto** [comment]
Ported to the CMake-based build system in https://github.com/hebasto/bitcoin/pull/214 and https://github.com/hebasto/bitcoin/pull/220.
