### ISSUE TITLE
(EDITED) How was the average size of blk*.data chosen?

### ISSUE THREAD

**Issue by jdom1824** [bitcoin/bitcoin#30056]
(EDITED)

List of implementation changes:
- new database layout: 
  - 2 leveldb's (coins/ and blktree/ subdirs), replacing blkindex.dat
  - separate directory (blocks/) with block data (in the usual format, but smaller files) and undo data
- database keys are of the form (char,key) instead of (string,key) for reasons of compactness
- there is no txid-to-diskpos index anymore, only blkid-to-diskpos and txid-to-unspent-outputs
  - this makes getrawtransaction only work on unspent outputs (and slower)
    - an optional txid-to-diskpos index is planned
- some new very specialized serializers are added (compact variable-length integer, compact amount, compact txout)
- block index does not store hashBlockNext anymore - this is reconstructed from hashBestBlock at startup
- at startup, automatically reorg to the best block in blktree/blocks
- new RPCs: gettxoutsetinfo and gettxout operate on the coins database
- no more CTxIndex in-scope: instead, a global pcoinsTip (representing the coin db) and pblocktree (representing the blktree db)
  - intended to be moved to separate modules/classes, properly encapsulated
- blktree database contains statistics about the block file (size, which blocks in it, times, heights, undo stats, ...)
- blktree database contains flag per block that determines the degree of validation it had, to allow future headers-first mode
- block files are pre-allocated (in batches of 16 MiB, the files grow to max 128 MIB), to reduce fragmentation
- transaction hashes are cached, and typically never calculated more than once

Included in the pullreq, but technically separate:
- do -loadblock= and bootstrap.dat import in a separate thread
- add check for strict DER encoding for signatures, and standard public keys

_Originally posted by @sipa in https://github.com/bitcoin/bitcoin/issues/1677#issuecomment-7794418_

Hello, is there any formula or performance tests to choose the size of 128 MB as chunksize in blk*.data files?

**Comment by willcl-ark** [comment]
This issue tracker is used to track technical issues related to the Bitcoin Core code base.

General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com/) or the #bitcoin IRC channel on the [Libera Chat](https://libera.chat/) network.

For proposed protocol changes you can post to the bitcoin-dev [mailing list](https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-dev).

For general bitcoin discussion you can try [bitcointalk](bitcointalk.org) or [reddit.com/r/bitcoin](reddit.com/r/bitcoin) 

----------------

Searching for questions like this on StackExchange may directly yield [answers](https://bitcoin.stackexchange.com/questions/50693/why-are-blk-dat-files-134200000-bytes), otherwise you can simply post your new question there.
