### ISSUE TITLE
"netinfo" doesn't show IPv6 "Local addresses"

### ISSUE THREAD

**Issue by lcharles123** [bitcoin/bitcoin#30165]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behaviour

"Local addresses" section of "netinfo" does not show the IPv6 addresses added using  "externalip" config option. (Probably there is no announce of this addresses).
Bitnodes.io show the version string of all IPs, but after put many of the IPv6 on active monitoring, only the first one specified with "externalip" are "UP" and the others are "UNREACHABLE".
(These are not my real addresses).

root@debianpc:~# bitcoin-cli -netinfo
`  Bitcoin Core client v27.0.0 - server 70016/Satoshi:27.0.0/

         ipv4   onion     i2p     npr   total   block
    in          0       1       0       7       8
    out         6       3       1       0      10       2
    total       6       4       1       7      18

  Local addresses
  143.22.123.17                                                     port   8333    score     27
  qsddczpwthdeddm3viv4brhxbbxdm5eh5ywasdfmmaefctwrrgjdw5hmid.onion     port   8333    score      4
  awxyf6dvprtsssixojegfwjdn5xka62kpxecbwdovk23ohpqm.b32.i2p       port      0    score      4
`

### Expected behaviour

root@debianpc:~# bitcoin-cli -netinfo
`  Bitcoin Core client v27.0.0 - server 70016/Satoshi:27.0.0/
  
         ipv4   onion     i2p     npr   total   block
    in          0       1       0       7       8
    out         6       3       1       0      10       2
    total       6       4       1       7      18

  Local addresses
  143.22.123.17                                                       port   8333    score     27
  2006:f10:0:aa::234                                                port   8333    score     16
  2006:f10:0:aa::111                                                port   8333    score     16
  qsddczpwthdeddm3viv4brhxbbxdm5eh5ywasdfmmaefctwrrgjdw5hmid.onion     port   8333    score      4
  awxyf6dvprtsssixojegfwjdn5xka62kpxecbwdovk23ohpqm.b32.i2p       port      0    score      4
`

### Steps to reproduce

This is a very specific setup:
1. In a machine A with no public IPv4 nor IPv6 address, start bitcoind with these options:

 #a public ipv4 and ipv6 address of another machine, let's say machine B
externalip=143.22.123.17 
externalip=qsddczpwthdeddm3viv4brhxbbxdm5eh5ywasdfmmaefctwrrgjdw5hmid.onion
externalip=2006:f10:0:aa::234
externalip=2006:f10:0:aa::111

2. Now establish a reverse ssh tunnel from machine A to B
on machine A, run:
 autossh -N -f -o "ExitOnForwardFailure=yes" -o "ServerAliveInterval=10" -o "ServerAliveCountMax=3" -R 143.22.123.17:8333:127.0.0.1:8333 root@IP_machine_B

3. Test all the externalip's using bitnodes.io, they shoud be reachable on the default port now. This configuration should provide IPv6 connectivity to the local node and the -netinfo should show the IPv6 announced using externalip config option (like it did with the public IPv4 specified).

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

v27.0.0

### Operating system and version

Debian 11

**Comment by lcharles123** [comment]
root@debianpc:~# bcli getnetworkinfo
{
  "version": 270000,
  "subversion": "/Satoshi:27.0.0/",
  "protocolversion": 70016,
  "localservices": "0000000000000c09",
  "localservicesnames": [
    "NETWORK",
    "WITNESS",
    "NETWORK_LIMITED",
    "P2P_V2"
  ],
  "localrelay": true,
  "timeoffset": -8,
  "networkactive": true,
  "connections": 68,
  "connections_in": 58,
  "connections_out": 10,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": false,
      "reachable": true,
      "proxy": "127.0.0.1:9050",
      "proxy_randomize_credentials": true
    },
    {
      "name": "i2p",
      "limited": false,
      "reachable": true,
      "proxy": "127.0.0.1:7656",
      "proxy_randomize_credentials": false
    },
    {
      "name": "cjdns",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00001000,
  "incrementalfee": 0.00001000,
  "localaddresses": [
    {
      "address": "143.22.123.17",
      "port": 8333,
      "score": 127
    },
    {
      "address": "qsddczpwthdeddm3viv4brhxbbxdm5eh5ywasdfmmaefctwrrgjdw5hmid.onion",
      "port": 8333,
      "score": 4
    },
    {
      "address": "awxyf6dvprtsssixojegfwjdn5xka62kpxecbwdovk23ohpqm.b32.i2p",
      "port": 0,
      "score": 4
    }
  ],
  "warnings": ""
}

**Comment by lcharles123** [comment]
> Edit: probably not the issue, but did you try using the -discover config option?

Yes, but the addresses are unreachable anyway in local network, because the node are IPv4 only (and behind NAT).

I guess I found the cause, because function `AddLocal` checks for connectivity on each -externalip entry using local interfaces, for IPv4 and others, its easy because it takes the normal way to the address. But there is no solution to reach v6 addresses on a machine v4 only without some config and external service. So a good modification on the code to allow adding the local v6 address can not be made. Or there is another way?

**Comment by willcl-ark** [comment]
Presumably in your setup your reverse SSH is connecting via ipv4, therefore bitcoind will detect it has an "active" (localhost) ipv4 connection and decide that its external ip address must be the one you gave it via the `- externalip=143.22.123.17` option.

OP reads to me that you want to have Node (A) bitcoind advertising both ipv4 and (an) ipv6 address(es) which are both reachable on Node (B), so that other nodes can connect to your node (A) via ipv4 or ipv6 on Node (B). Is that correct?

The simplest solution of all IMO, is just to advertise ipv4 and ipv6 on Node (A), have them work and be externally connectable, then simply connect Node (B) to node (A) with a single, regular ipv4 connection. Why the need to advertise phantom addresses from one node via another? Just apply the setting on the node it applies to.

In the case that you really need this other behaviour, Node (B) would have to proxy traffic from an ipv6 address to an ipv6 address on Node (A), perhaps using something like:

```bash
ssh -R [B's IPv6]:8333:[A's IPv6]:8333 user@B
```

At that stage it might be better/easier to investigate something like this for nginx on Node (B):

```config
# Node (B) nginx.conf

server {
    listen 8333;  # IPv4
    listen [::]:8333 ipv6only=on; # IPv6

    location / {
        # determine which address to proxy to
        set $backend_address "";
        
        if ($remote_addr ~ ":") {
            set $backend_address "[A's IPv6 address]";
        }
        
        if ($remote_addr !~ ":") {
            set $backend_address [A's IPv4 address];
        }
        
        proxy_pass http://$backend_address:8333;
    }
}
```

If A cannot listen on ipv6 on your network, and you _really_ want this setup, then you may need to forward B's IPV6 traffic to a different ipv4 port on A, and investigate using iptables (or similar) to reroute traffic from that port to an internal-only IPV6 address.

All that said, general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com/) or the `#bitcoin` IRC channel on the [Libera Chat](https://libera.chat/) network. And I think that would be the best place for the converstation to go from here.

If you agree, I think we can close this issue at this point?

**Comment by willcl-ark** [comment]
OK I'm going to close this for now.

Feel free to open a new issue or comment here if you are still experiencing this problem.
