### ISSUE TITLE
cmake: Step "-- Looking for C++ include boost/test/included/unit_test.hpp" takes a long time

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#30787]
It looks like this step is taking longer than the entire `cmake -B` without it. Is there a reason why it takes so long, and whether it can be sped up?

**Comment by hebasto** [comment]
It compiles and links the minimal code that uses the `boost/test/included/unit_test.hpp` header. Verifying that the header simply exists could be an alternative.

**Comment by fanquake** [comment]
It's actually irrelevant for all platforms other than windows with vcpkg (as far as I'm aware), and was added to work around how boost is packaged there (we didn't have an equivalent in autotools). It should be scooped as such, rather than making all other platforms run the (pointless) slow check.

**Comment by fanquake** [comment]
> Yeah, that seems ideal, given that this was done for autotools as well, 

Where in Autotools were we running checks to verify the existence of singlular boost headers at configure time?

**Comment by fanquake** [comment]
> I haven't confirmed this, but I assumed it checked for boost/version.hpp existence (and version conformance).

We did do a high-level check for the existence of a Boost installation, and sufficient version (and that is what is also done in CMake now), but not compilation checks for individual headers (otherwise we should add checks for all Boost headers that we might happen to `#include`, i.e `boost/multi_index/*`, if we think they might be missing for some reason).

I think either making this faster, i.e no compilation, or scoping it to vcpkg is fine.

>  It compiles and links 

Should it be doing anything link related, if our Boost usage is header only?
