### ISSUE TITLE
28.0rc1 synchronizes much slower on Windows

### ISSUE THREAD

**Issue by vostrnad** [bitcoin/bitcoin#30833]
Bitcoin Core 28.0rc1 (both pre-built and self-built binary) on Windows 10 synchronizes much slower than 27.0 after around block 120,000 when blocks stop being almost empty. I'm running with default settings (dbcache=450, pruning disabled).

Time to synchronize to block 300,000: (measured around 10 runs each, alternating between the versions)
27.0: **695 seconds**
28.0rc1: **2760 seconds**

![28.0rc1](https://github.com/user-attachments/assets/060a1e18-7f97-4e86-9ba8-5bf867b3510e)

Running the Linux pre-built binary in WSL doesn't show the slowdown, so it's probably limited to Windows.

~~I'm going to bisect this, but that will definitely take me a while. If anyone suspects a commit/PR that I should look at first that might help.~~ I've bisected this down to #28052, for more details see https://github.com/bitcoin/bitcoin/issues/30833#issuecomment-2335184072.

**Comment by vostrnad** [comment]
I actually benchmarked #28280 right before it got merged: https://github.com/bitcoin/bitcoin/pull/28280#issuecomment-2268695679

From the results it definitely seems that PR is not to blame and the regression happened later.

**Comment by andrewtoth** [comment]
https://github.com/bitcoin/bitcoin/pull/30326?

**Comment by andrewtoth** [comment]
Reason I suspect #30326 is because `try_emplace` must be doing more work than just `find` and is only called after blocks stop being full because previous coins are now being looked up to be spent.

Relevant stackoverflow https://stackoverflow.com/questions/24209592/performance-of-emplace-is-worse-than-check-followed-by-emplace

**Comment by achow101** [comment]
Only did one run of each but I have basically the opposite result: 4406 seconds for 27.1, and 2949 for 28.0rc1.

**Comment by andrewtoth** [comment]
@vostrnad when you say synchronizes, do you mean running with `-reindex-chainstate` or are you starting with a fresh data directory and downloading blocks from peers? If the latter, are you downloading blocks from a node in your local network?

**Comment by vostrnad** [comment]
@andrewtoth I updated the OP. I'm synchronizing from a local node with a fresh datadir each time.

**Comment by davidgumberg** [comment]
I'm trying to get a Windows box setup to reproduce this myself, but if you get a chance, could you do a run of both again with `-debug=bench` set, and post the final set of [bench] logs that get written to debug.log?

**Comment by vostrnad** [comment]
I've bisected this down to #28052. From the benchmark results it appears to be solely responsible for the slowdown between 27.0 and 28.0rc1 (so #30326 should be fine @andrewtoth).

@davidgumberg Please let me know if you still need those bench logs.

**Comment by vostrnad** [comment]
@sipa No, it's exactly the same with `-blocksxor=0`.

**Comment by davidgumberg** [comment]
> @sipa No, it's exactly the same with `-blocksxor=0`.

This has uncovered a bug in #28052, `InitBlocksdirXorKey` does not return an empty `std::vector<std::byte>` when the `-blocksxor=0` argument is used, it instead [returns](https://github.com/bitcoin/bitcoin/blob/fa460884406b35b0dee75af23f42e8b4c4acbebc/src/node/blockstorage.cpp#L1185) a [vector with 8 bytes equal to zero](https://github.com/bitcoin/bitcoin/blob/fa460884406b35b0dee75af23f42e8b4c4acbebc/src/node/blockstorage.cpp#L1152):

```cpp
static auto InitBlocksdirXorKey(const BlockManager::Options& opts)
{
    std::array<std::byte, 8> xor_key{};
    
    if (opts.use_xor && fs::is_empty(opts.blocks_dir)) {
        // Only use random fresh key when the boolean option is set and on the
        // very first start of the program.
        FastRandomContext{}.fillrand(xor_key);
    }
    
    // [...]
    return std::vector<std::byte>{xor_key.begin(), xor_key.end()};
}
```

In turn, this causes us to go through the XOR logic of [`AutoFile::detail_fread()`](https://github.com/bitcoin/bitcoin/blob/fa460884406b35b0dee75af23f42e8b4c4acbebc/src/streams.cpp#L10-L22) and [`AutoFile::write()`](https://github.com/bitcoin/bitcoin/blob/fa460884406b35b0dee75af23f42e8b4c4acbebc/src/streams.cpp#L66-L88) since the block autofiles' `std::vector<std::byte> m_xor` are [initialized](https://github.com/bitcoin/bitcoin/blob/fa460884406b35b0dee75af23f42e8b4c4acbebc/src/node/blockstorage.cpp#L1190) to the return value of `InitBlocksdirXorKey`.

E.g.: https://github.com/bitcoin/bitcoin/blob/fa460884406b35b0dee75af23f42e8b4c4acbebc/src/streams.cpp#L10-L23

I have a branch (https://github.com/davidgumberg/bitcoin/commit/aa0be4031cbe5bed407bc7a1753875cc1c4ddccb) that should fix this issue when `-blocksxor=0` but I haven't tested yet

I also managed to reproduce (n=1) the issue on Windows 10 LTSC Build 17763:

```bash
bitcoind.exe -dbcache=450 -stopatheight=300000 -debug=bench -connect=localnode:8333
```

28.0rc1 took 7,368 seconds
27.1 took 3,594 seconds

**Comment by fjahr** [comment]
> This has uncovered a bug in https://github.com/bitcoin/bitcoin/pull/28052, InitBlocksdirXorKey does not return an empty std::vector<std::byte> when the -blocksxor=0 argument is used, it instead [returns](https://github.com/bitcoin/bitcoin/blob/fa460884406b35b0dee75af23f42e8b4c4acbebc/src/node/blockstorage.cpp#L1185) a [vector with 8 bytes equal to zero](https://github.com/bitcoin/bitcoin/blob/fa460884406b35b0dee75af23f42e8b4c4acbebc/src/node/blockstorage.cpp#L1152):

I may be missing something because I am looking at the blocksxor stuff the first time but that doesn't seem to be a bug. When XOR is disabled we still write the xor file with zeros. There is even a functional test for that behavior: https://github.com/bitcoin/bitcoin/blob/master/test/functional/feature_blocksxor.py#L64 Your branch seems to change that expected behavior.

**Comment by tdb3** [comment]
Seems worth experimenting with:

https://github.com/bitcoin/bitcoin/blob/fa460884406b35b0dee75af23f42e8b4c4acbebc/src%2Fstreams.cpp#L76-L80

I wonder if the array creation, the copy, or the xoring here are to blame? Experimenting with the all 0s xor key can enable isolation.

**Comment by QBlockQ** [comment]
Try raising the dbcache setting to allocate more memory for caching (e.g., dbcache=1000 or more) to improve sync performance.  Also, consider enabling pruning could speed up synchronization.

**Comment by davidgumberg** [comment]
> > This has uncovered a bug in #28052, InitBlocksdirXorKey does not return an empty std::vectorstd::byte when the -blocksxor=0 argument is used, it instead [returns](https://github.com/bitcoin/bitcoin/blob/fa460884406b35b0dee75af23f42e8b4c4acbebc/src/node/blockstorage.cpp#L1185) a [vector with 8 bytes equal to zero](https://github.com/bitcoin/bitcoin/blob/fa460884406b35b0dee75af23f42e8b4c4acbebc/src/node/blockstorage.cpp#L1152):
> 
> I may be missing something because I am looking at the blocksxor stuff the first time but that doesn't seem to be a bug. When XOR is disabled we still write the xor file with zeros. There is even a functional test for that behavior: https://github.com/bitcoin/bitcoin/blob/master/test/functional/feature_blocksxor.py#L64 Your branch seems to change that expected behavior.

You're right, creating an xor.dat with all zeroes when `-blocksxor=0` was intended, so not a bug in that PR. Still, the fact that when a user disables xor'ing blocks we still perform all the usual XOR logic, but with an XOR pattern of zeroes doesn't make sense to me, and it seems like an unintended side effect of https://github.com/bitcoin/bitcoin/pull/28052 .

I tested https://github.com/davidgumberg/bitcoin/commit/aa0be4031cbe5bed407bc7a1753875cc1c4ddccb with `-blocksxor=0` and the same Windows setup and the performance regression goes away.

My bench logs indicate that the regression is coming from writing block undo data, the difference between the (reported) total block connection time between v27.1 and v28.0rc1 is +1,337.85 seconds for v28, and the difference in (reported) time spent writing undo block data is +1,579.31s for v28:

<details>

<summary>Version 28.0 rc1 bench logs</summary>

```diff
 [bench]   - Using cached block
 [bench]   - Load block from disk: 0.57ms
 [bench]     - Sanity checks: 0.02ms [5.37s (0.02ms/blk)]
 [bench]     - Fork checks: 0.40ms [159.15s (0.53ms/blk)]
 [bench]       - Connect 512 transactions: 2.95ms (0.006ms/tx, 0.002ms/txin) [303.09s (1.01ms/blk)]
 [bench]     - Verify 1180 txins: 3.45ms (0.003ms/txin) [425.49s (1.42ms/blk)]
+[bench]     - Write undo data: 26.38ms [2296.37s (7.65ms/blk)]
 [bench]     - Index writing: 0.46ms [148.03s (0.49ms/blk)]
 [bench]   - Connect total: 31.98ms [3281.81s (10.94ms/blk)]
 [bench]   - Flush: 2.44ms [246.56s (0.82ms/blk)]
 [bench]   - Writing chainstate: 0.89ms [107.89s (0.36ms/blk)]
 UpdateTip: new best=000000000000000049a0914d83df36982c77ac1f65ade6a52bdced2ce312aba9 height=300001 version=0x00000002 log2_work=78.499665 tx=38464301 date='2014-05-10T06:51:23Z' progress=0.035833 cache=641.2MiB(5186028txo)
 [bench]   - Connect postprocess: 0.64ms [261.25s (0.87ms/blk)]
+[bench] - Connect block: 36.53ms [4041.91s (13.47ms/blk)]
```

</details>

<details>

<summary>Version 27.1 bench logs</summary>

```diff
 [bench]   - Using cached block
 [bench]   - Load block from disk: 1.03ms
 [bench]     - Sanity checks: 0.02ms [5.58s (0.02ms/blk)]
 [bench]     - Fork checks: 0.36ms [154.95s (0.52ms/blk)]
 [bench]       - Connect 173 transactions: 1.39ms (0.008ms/tx, 0.003ms/txin) [330.82s (1.10ms/blk)]
 [bench]     - Verify 435 txins: 2.02ms (0.005ms/txin) [478.57s (1.60ms/blk)]
+[bench]     - Write undo data: 1.24ms [717.06s (2.39ms/blk)]
 [bench]     - Index writing: 0.33ms [152.89s (0.51ms/blk)]
 [bench]   - Connect total: 5.11ms [1754.52s (5.85ms/blk)]
 [bench]   - Flush: 1.35ms [310.98s (1.04ms/blk)]
 [bench]   - Writing chainstate: 0.33ms [149.58s (0.50ms/blk)]
 UpdateTip: new best=000000000000000082aee4ff546c1db5e1aa5f9bfbaa0c76300a792b3e91fce7 height=300003 version=0x00000002 log2_work=78.499897 tx=38464563 date='2014-05-10T06:58:47Z' progress=0.035342 cache=510.6MiB(4668409txo)
 [bench]   - Connect postprocess: 0.86ms [356.88s (1.19ms/blk)]
+[bench] - Connect block: 8.68ms [2704.06s (9.01ms/blk)]
```

</details>

<details>

<summary>

My modified branch of 28.x with `-blocksxor=0` bench logs

</summary>

```diff
 [bench]   - Using cached block
 [bench]   - Load block from disk: 0.23ms
 [bench]     - Sanity checks: 0.01ms [5.35s (0.02ms/blk)]
 [bench]     - Fork checks: 0.29ms [150.64s (0.50ms/blk)]
 [bench]       - Connect 512 transactions: 2.18ms (0.004ms/tx, 0.002ms/txin) [308.30s (1.03ms/blk)]
 [bench]     - Verify 1180 txins: 2.58ms (0.002ms/txin) [448.44s (1.49ms/blk)]
+[bench]     - Write undo data: 1.62ms [758.14s (2.53ms/blk)]
 [bench]     - Index writing: 0.30ms [127.39s (0.42ms/blk)]
 [bench]   - Connect total: 5.72ms [1710.90s (5.70ms/blk)]
 [bench]   - Flush: 2.31ms [258.95s (0.86ms/blk)]
 [bench]   - Writing chainstate: 0.49ms [142.43s (0.47ms/blk)]
 UpdateTip: new best=000000000000000049a0914d83df36982c77ac1f65ade6a52bdced2ce312aba9 height=300001 version=0x00000002 log2_work=78.499665 tx=38464301 date='2014-05-10T06:51:23Z' progress=0.035817 cache=641.2MiB(5186028txo)
 [bench]   - Connect postprocess: 0.89ms [305.06s (1.02ms/blk)]
+[bench] - Connect block: 9.64ms [2531.72s (8.44ms/blk)]
```

</details>

**Comment by andrewtoth** [comment]
> My bench logs indicate that the regression is coming from writing block undo data, the difference between the (reported) total block connection time between v27.1 and v28.0rc1 is +1,337.85 seconds for v28, and the difference in (reported) time spent writing undo block data is +1,579.31s for v28:

This is saying that the total time for writing undo block data exceeds total block connection time. But, writing undo block data is a subsection of block connection time, so it should always be less no?

Also, the logs show `Using cached block`, meaning it is not counting saving the block itself to disk in the `Connect block` benchmark. So, actually saving the blocks in `AcceptBlock` might be taking even more time than writing the undo blocks.

**Comment by davidgumberg** [comment]
@andrewtoth 
>> My bench logs indicate that the regression is coming from writing block undo data, the difference between the (reported) total block connection time between v27.1 and v28.0rc1 is +1,337.85 seconds for v28, and the difference in (reported) time spent writing undo block data is +1,579.31s for v28:
>
> This is saying that the total time for writing undo block data exceeds total block connection time. But, writing undo block data is a subsection of block connection time, so it should always be less no?

Sorry, I did not express that well, the two numbers I gave are the delta between v27.1 and v28.0rc1, total time spent writing undo block data is 2,296.37s in v28 and 717.06s in v27.1. Total time spent doing block connection is 4041.91s in v28.0rc1 and 2704.06s in v27.1.
 
Other parts of the v28 sync are faster (at least in my n=1 run~~s~~) , e.g. flushing the temporary `CCoinsViewCache` takes ~60 fewer seconds in v28 compensating for the increased time spent writing undo data.

> Also, the logs show Using cached block, meaning it is not counting saving the block itself to disk in the Connect block benchmark. So, actually saving the blocks in AcceptBlock might be taking even more time than writing the undo blocks.

I see, I guess that explains why the difference in wall clock time taken (v28 took 3,774 more seconds) is more than double the size of the slowdown reported by the ConnectBlock bench logs (v28 took 1,337.85 seconds longer doing block connection).

---

@tdb3
> Seems worth experimenting with:
> 
> https://github.com/bitcoin/bitcoin/blob/fa460884406b35b0dee75af23f42e8b4c4acbebc/src%2Fstreams.cpp#L76-L80
> 
> I wonder if the array creation, the copy, or the xoring here are the long pole in the tent? Experimenting with the all 0s xor key can help isolate.

It seems there was some prior discussion around this in #28060 which may be of interest:
https://github.com/bitcoin/bitcoin/pull/28060#discussion_r1260260590

---

I wonder if this issue could be caused by number of calls we make to `fwrite` because of the write buffering in xor path of `AutoFile::write()`, maybe platforms other than windows are optimizing our writes into batches behind the scenes? I don't know much about how I/O works behind the scenes, just a guess.

**Comment by mzumsande** [comment]
I managed to get my windows installation compiled (Windows 10 Pro 22H2), didn't observe a notable difference in the benchmarks.
I'm still in the process of trying to test the sync speed, but if it's due to the undo data, then a reindex-chainstate should be sufficient to see the difference?! Did anyone try that already?

**Comment by hebasto** [comment]
> I managed to get bitcoind compiled on my windows installation (Windows 10 Pro 22H2, MSVC 2022), didn't observe a notable difference in the benchmarks.

I hope everyone measuring performance on Windows has disabled all antivirus software, at least for the data directory. Right?

**Comment by vostrnad** [comment]
@hebasto Yes, I have disabled antivirus for both the data directory and the directory where the binaries are located, I checked that the antivirus CPU utilization stays low during the benchmarks, and I'm using identical directory locations for both versions so they wouldn't be treated differently by the antivirus anyway.

**Comment by QBlockQ** [comment]
Just a suggestion (you may send me a BIG thanks after a decade), why don't you consider integration of post-quantum cryptography (PQC) in this time for the next release of Bitcoin Core 27.1.  PQC integration code is ready!

**Comment by achow101** [comment]
Discussion from today's IRC meeting is that we should move forward with @davidgumberg's patch and default to false on Windows for this release.

**Comment by davidgumberg** [comment]
@achow101 Reworking the patch that fixes disabling XOR, will open a PR later today if @sipa's [patch](https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2024-09-12#1726151549-1726151530;) to remove the `ftell` that happens on the XOR path doesn't fix this issue.
