### ISSUE TITLE
Signal and/or RPC call to re-read config file

### ISSUE THREAD

**Issue by mikegogulski** [bitcoin/bitcoin#309]
It would be handy in certain circumstances to be able to update the config file and then ask bitcoind to parse it again (when updating rpcallowip filters, for example). An RPC command like "readconfig" would be good. Trapping for a SIGHUP on Unix would be cool, too.

**Comment by jnewbery** [comment]
This has been requested a few times, but it's actually quite tricky to get right. Lots of the config options are read at startup and affect behaviour during initialisation. Making sure that re-reading and re-applying the config file correctly changes the internal state is going to be very difficult, and may lead to all kinds of weird edge cases.

I think a more realistic ask is adding support to change the specific individual config options through RPC methods.

I'm concept NACKish on this. Not because I don't think it's a useful idea, but because I think it's just too difficult to get right.

I suggest we close this with 'up for grabs'.
