### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by cyphra** [bitcoin/bitcoin#31107]
### Please describe the feature you'd like to see added.

[bitcoin_es.ts.gz](https://github.com/user-attachments/files/17409519/bitcoin_es.ts.gz)

**Comment by fanquake** [comment]
Thanks for helping with translations! However, changes to translations as well as new translations are submitted to [Bitcoin Core's Transifex page](https://www.transifex.com/projects/p/bitcoin/).

Translations are periodically pulled from Transifex and merged into the git repository. See the [translation process](https://github.com/bitcoin/bitcoin/blob/master/doc/translation_process.md) for details on how this works. So we do not accept translation changes as GitHub pull requests because the next pull from Transifex would automatically overwrite them again.
