### ISSUE TITLE
Follow-up from Moderation Rules

### ISSUE THREAD

**Issue by ariard** [bitcoin/bitcoin#31110]
Just to be sure this is not a compromised of the github platform itself:
https://github.com/bitcoin-core/meta/issues/11

**Comment by ariard** [comment]
Been a while I’ve not been on IRC to attend one of the regular meeting, so I’ll find time to do so during the coming weeks to clarify. There is no rush to clarify that.

After all, it might be just a contributor or maintainer with perms access to the bitcoin Github organization. She or he might have got drunk or be under drugs at some party, and slips the wrong button….

Still hope it’s not a real infrastructure issue, where bitcoin Github repository has been effectively compromised :/

**Comment by willcl-ark** [comment]
> Just to be sure this is not a compromised of the github platform itself:

I am not myself aware of any compromise of this platform, but we can wait for others to chime in on your issue at https://github.com/bitcoin-core/meta/issues/11

I have hidden your second comment as "off-topic", as it does not align with our moderation guidelines. Specifically:
- It's off-topic and doesn't contribute to technical discussion (that applies to this entire issue frankly).
- It speculates about individuals rather than focusing on ideas.

Please review our moderation guidelines for future contributions here in this repo. If you have concerns about repository security, please raise them through appropriate channels (as you already did prior to opening this issue here).

I am going to close this issue in this repository and we can continue the discussion in /meta.

**Comment by ariard** [comment]
> It speculates about individuals rather than focusing on ideas.

It’s not like some people with perm rights have actually done “fat fingers” mistakes in the past…( and I can go back in IRC logs here). If it’s an infrastructure compromise it’s still better to be verbose about it. Github fwiw is used for code distribution among the whole ecosystem. It’s very different than a bug directly affecting core code.

Better to continue the discussion in /meta.
