### ISSUE TITLE
bench: `linearizeoptimallyexample11` benchmark now running 4x slow than previously

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#31178]
According to https://corecheck.dev/benchmarks, the `linearizeoptimallyexample11` benchmark 4x'd it's execution time at some point in the last few days.
![Screenshot 2024-10-29 at 14 15 02](https://github.com/user-attachments/assets/96b20c6c-09af-4233-b643-64df88ed225f)

**Comment by m3dwards** [comment]
I have been able to recreate a roughly 2x slowdown on both x86 Linux and AArch64 Mac. Not quite as much as the corcheck.dev slowdown but still significant. Just for reference, corecheck.dev runs on AArch64 Linux.

I compared f0130ab1a1 (October 17th) with 97b790e844abd2 (October 19th).

I'll have a scan for the offending commit and worse case do a binary search.

**Comment by m3dwards** [comment]
The slowdown appears to be introduced with https://github.com/bitcoin/bitcoin/commit/1c7ca6e64de9b47b2295c81cb0fedd432ffaf001

Not sure why yet.

**Comment by davidgumberg** [comment]
> @m3dwards Thanks for digging! I believe that explains it: since #31093, `Assume()` calls are no longer optimized out in production builds.

I've reproduced this performance issue locally, and when you remove `g_fuzzing` from `inline_assertion_check` the regression goes away:

`./build/src/bench/bench_bitcoin -filter=LinearizeOptimallyExample11 -min-time=30000`

|branch      |               ns/op |                op/s |    err% |          ins/op |          cyc/op |    IPC |         bra/op |   miss% |     total | benchmark
|---------------|--------------------:|--------------------:|--------:|----------------:|----------------:|-------:|---------------:|--------:|----------:|:----------
|1c7ca6e    |      374,612,291.12 |                2.67 |    0.1% |7,324,884,820.00 |1,304,215,224.38 |  5.616 | 898,388,711.38 |    0.2% |     32.23 | `LinearizeOptimallyExample11`
|1c7ca6e~1|      301,758,341.60 |                3.31 |    0.3% |4,990,499,172.00 |1,050,585,438.00 |  4.750 | 352,054,044.90 |    0.3% |     32.48 | `LinearizeOptimallyExample11`
|no check g_fuzzing in assume 88a2427a68                |      300,695,825.00 |                3.33 |    0.1% |4,990,499,171.80 |1,046,167,482.50 |  4.770 | 352,054,044.70 |    0.3% |     32.39 | `LinearizeOptimallyExample11`


I recorded some flamegraphs that point to where the hot `Assume` call(s) are: [1c7ca6e](https://davidgumberg.github.io/fg/gfuzzregression/1c7ca6e.html) ([permalink](https://github.com/davidgumberg/fg/blob/23f595476cf083f9c08fb6ff2480b94a2d1cfd38/gfuzzregression/1c7ca6e.html)) vs [parent](https://davidgumberg.github.io/fg/gfuzzregression/parent.html) ([permalink](https://github.com/davidgumberg/fg/blob/23f595476cf083f9c08fb6ff2480b94a2d1cfd38/gfuzzregression/parent.html))

**Comment by ryanofsky** [comment]
I think it is worth looking for a better way to fix this because of the clumsiness of needing to compile two different versions of libraries when fuzzing is used.

It is not true that in general that `Assume` checks were "optimized out" before #31093 because the checks are performed before the `inline_assertion_check` function is called, so wouldn't be skipped in general just because the function is implemented differently. The compiler would be able to skip the checks if it knows they don't have side effects. But if it knows they don't have side effects, it should also be able to skip the checks when `g_fuzzing` is false. 

I think we should look at what compiler is doing here and see if there's a way we can get it to generate better code to fix the benchmark. Also if we can change the implementation of Assume to check `g_fuzzing` before running the Assume checks it might increase performance of the production builds generally in cases where the compile doesn't know if the checks have side effects.

**Comment by ryanofsky** [comment]
I could also be missing something, but doesn't `Assume(<check expression>)` just expand to `inline_assertion_check<false>(<check expression>, __FILE__, __LINE__, __func__, "<check expression>")` so unless the compiler knows `<check expression>` does not have side effects, must execute it and can't optimize it out? If `Assume` macro were implemented differently it could skip evaluating `<check expression>` at all.

**Comment by ryanofsky** [comment]
After testing this, it does seem like, in practice, the slowdown comes from checking the `g_fuzzing` variable, not from evaluating the assume condition. I don't agree with (or don't understand) Marco's logic that this was neccesarily the case, since before #31093 if the compiler knew evaluating the assume condition didn't have side effects and that result of the assume condition was not used, it would have no reason to evaluate it before #31093, but would need to evaluate it after #31093, so an optimization that would skip evaluating the assume condition when `g_fuzzing` is false could result in a speedup.

But in practice, the speedup that comes from doing this is relatively minor. When I run the LinearizeOptimallyExample11 benchmark on master, I get around 1.4 operations per second. With a change to skip evaluating the assume condition when `g_fuzzing` is false, this increases to 1.5 operations per second. But if I revert #31093, it increases to 1.8 operation to second.

Change I was tested with was:

<details><summary>diff</summary>
<p>

```diff
--- a/src/util/check.h
+++ b/src/util/check.h
@@ -41,21 +41,24 @@ T&& inline_check_non_fatal(LIFETIMEBOUND T&& val, const char* file, int line, co
 void assertion_fail(std::string_view file, int line, std::string_view func, std::string_view assertion);
 
 /** Helper for Assert()/Assume() */
-template <bool IS_ASSERT, typename T>
+template <typename T>
 constexpr T&& inline_assertion_check(LIFETIMEBOUND T&& val, [[maybe_unused]] const char* file, [[maybe_unused]] int line, [[maybe_unused]] const char* func, [[maybe_unused]] const char* assertion)
 {
-    if (IS_ASSERT || std::is_constant_evaluated() || g_fuzzing
-#ifdef ABORT_ON_FAILED_ASSUME
-        || true
-#endif
-    ) {
         if (!val) {
             assertion_fail(file, line, func, assertion);
         }
-    }
     return std::forward<T>(val);
 }
 
+constexpr bool AbortOnFailedAssume() {
+#ifdef ABORT_ON_FAILED_ASSUME
+   return true;
+#endif
+   if (std::is_constant_evaluated()) return true;
+   if (g_fuzzing) [[unlikely]] return true;
+   return false;
+}
+
 // All macros may use __func__ inside a lambda, so put them under nolint.
 // NOLINTBEGIN(bugprone-lambda-function-name)
 
@@ -76,7 +79,7 @@ constexpr T&& inline_assertion_check(LIFETIMEBOUND T&& val, [[maybe_unused]] con
     inline_check_non_fatal(condition, __FILE__, __LINE__, __func__, #condition)
 
 /** Identity function. Abort if the value compares equal to zero */
-#define Assert(val) inline_assertion_check<true>(val, __FILE__, __LINE__, __func__, #val)
+#define Assert(val) inline_assertion_check(val, __FILE__, __LINE__, __func__, #val)
 
 /**
  * Assume is the identity function.
@@ -88,7 +91,7 @@ constexpr T&& inline_assertion_check(LIFETIMEBOUND T&& val, [[maybe_unused]] con
  * - For non-fatal errors in interactive sessions (e.g. RPC or command line
  *   interfaces), CHECK_NONFATAL() might be more appropriate.
  */
-#define Assume(val) inline_assertion_check<false>(val, __FILE__, __LINE__, __func__, #val)
+#define Assume(val) inline_assertion_check(!AbortOnFailedAssume() || (val), __FILE__, __LINE__, __func__, #val)
 
 /**
  * NONFATAL_UNREACHABLE() is a macro that is used to mark unreachable code. It throws a NonFatalCheckError.
```
</p>
</details>
