### ISSUE TITLE
[Qt] Do you want to rebuild the block database now? No -> crash

### ISSUE THREAD

**Issue by Diapolo** [bitcoin/bitcoin#3136]
I'm using -txindex in my normal environment, when using payment requests without the client running, the client is started without any parameters and detects the missing -txindex and asks me ``Do you want to rebuild the block database now?`` answering no here crashes the client.

https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L834

@sipa Can you check that part of the code, as most of it was done by you :).

Edit: Error is on Win7 x64 and it's a BEX (Buffer Overflow Exception).

**Comment by dexX7** [comment]
I tested this on Windows 8.1 x64 and Windows 10 TP and this issue affects the 0.9, 0.10 releases, as well as the master branch (build via Gitian route).

To reproduce:

1. Start `bitcoin-qt.exe`, pointing to a new datadir (`-datadir=xxx`, `-choosedatadir`)
2. Shutdown the client
3. Start `bitcoin-qt.exe -txindex=1`
4. Decline to rebuild index
5. Crash

A similar event can be triggered and observed, when executing `bitcoind.exe` without `rpcuser` and `rpcpassword` defined, which also results in an application crash.

FWIW, I uploaded the crash report, including error dump files: http://bitwatch.co/uploads/AppCrash_bitcoin-qt_w10x64.zip (1.414 KB)

Running `Process Monitor` hints a buffer overflow during the shutdown:

![bufferoverflow](https://cloud.githubusercontent.com/assets/5836089/6568061/dff6402e-c6d1-11e4-9ccf-43a1c2dced41.png)

This error does not occure, when using `-disablewallet` or a wallet-less build.

**Comment by dexX7** [comment]
As follow up: it's a memory access violation and I sort-of debugged it on an assembler level, where I saw that the crash occured when jumping to `0xFEEEFEEE + x`, which indicates previously [freed memory](https://www.google.de/search?q=0xFEEEFEEE) on Windows.

The hint about `const std::string string() const { return string(codecvt()); }` was golden, as this indeed pointed to root cause. [Boost path](https://github.com/boostorg/filesystem/blob/boost-1.55.0/src/path.cpp) uses a static initialized pointer internally, which appears to be deinitialized during shutdown, but if this is not done by the main thread, the pointer appears to be already deinitialized, even though there is still an attempted access later. An appearingly working solution was to force the initialization by the main thread.

**Comment by jonasschnelli** [comment]
Tested with #5877 on top of current master (https://builds.jonasschnelli.ch/pulls/5877/) on Windows 7. Crash no longer happens.
Testes also current master on same Window 7 instance and could reproduce the reindex->abort crash.

**Comment by laanwj** [comment]
Thanks a lot for testing @jonaschnelli! Closing this.

**Comment by Diapolo** [comment]
@laanwj This needs to be reopened, as the bug was reintroduced or is at least still present! I'm going for a much simpler fix and will open a pull in a few minutes.

**Comment by Diapolo** [comment]
See #6282...
