### ISSUE TITLE
Only DoS-ban on blocks that contain invalid proof-of-work

### ISSUE THREAD

**Issue by gavinandresen** [bitcoin/bitcoin#3195]
This is half of an idea from http://www.tik.ee.ethz.ch/file/49318d3f56c1d525aabf7fda78b23fc0/P2P2013_041.pdf

Full idea:  Relay blocks as soon as the quick, transaction-independent checks are done (most critically, has-valid-proof-of-work).

To avoid any network-splitting potential, that can only be done if relaying blocks with valid proof-of-work but (say) an invalid transaction does NOT trigger a DoS-ban.

I think that should be done for the 0.9 release.

**Comment by rebroad** [comment]
@petertodd can you reference the soft-fork in question once it has a pull request please?

**Comment by Sjors** [comment]
Compact Blocks behave like this nowadays, right?

**Comment by gmaxwell** [comment]
@Sjors Depends on what you mean by "this".  If a peer explicitly requests it you'll forward blocks to them that meet a subset of block validity requirements, but not otherwise, and they'll only ban you if the block is invalid in that subset you were supposed to still have checked.  The subset includes hash tree consistency, so you're required to have access to all the data for the block: you won't relay a block where you don't know enough to check if it was valid or not.  This avoids the above discussed attacks where block payload is withheld, the fact that the behaviour has to be requested avoids the problem of sending invalid data to clients that expected us to validate for them.
