### ISSUE TITLE
Implement coinjoin in wallet

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#3226]
It would be useful to support coinjoin in the client and GUI. This would allow people to combine their transactions with random other people to increase privacy.
(See https://bitcointalk.org/index.php?topic=279249.0 for @gmaxwell's original proposal)

~~The simplest implementation would be 'where the users send their input and output information to some meeting point server, and the server creates the transaction and asks people to sign it.~~ 
~~The server learns the mapping but no one else does, and the server still can't steal the coins ~~
~~This server would be set in the configuration, and could be a TOR hidden service for extra privacy.~~

~~Initially this would be a simple (http/https based?) protocol that drops the transaction plus a timeout value and a way to request the current status. Later on, this could be extended with blinding, and/or a solution that does not rely on servers (or relies on P2P network changes, for example with @lukejr's proposal https://gist.github.com/luke-jr/5409899).~~

~~in the RPC and GUI this requires a way to queue transactions with a configurable timeout. The transactions will then either be queued locally, or if one is configured, sent to the meeting point server.~~

(commented out my original proposal, making use of an existing system, e.g. joinmarket would be much better than reinventing the wheel)

**Comment by Giszmo** [comment]
A year went by, JoinMarket is struggling to get something working but runs into exactly what CoinShuffle identified as their problem. ChoinShuffle is still only a paper. DarkWallet is discontinued since almost a year …

Did I miss something? Any decentralized protocol that actually works yet, to base work on?

**Comment by ABISprotocol** [comment]
@Giszmo Yes, there is something that works and could probably be integrated soon, though it's unclear of what priority it would get in the grand scheme of everything else? It's called Confidential Transactions, by @gmaxwell 
https://bitcointalk.org/index.php?topic=1085273.0
Includes a Borromean ringsig similar in some ways to BCN - explainer on it here 
https://bitcointalk.org/index.php?topic=1077994.0
It's a feature of Elements https://github.com/ElementsProject/elements
@laanwj

**Comment by sipa** [comment]
Confidential transactions is not CoinJoin. It's pretty much exactly the opposite: CT protects transaction amounts, CoinJoin protects address linkage. Combined they are very powerful, though.

**Comment by ABISprotocol** [comment]
@sipa Clearly CT is not CoinJoin, no-one here has claimed that it is.  Simply put, CT actually works.

**Comment by sipa** [comment]
@Giszmo is asking about any decentralized protocol for CoinJoin that actually works. CT is a consensus rule for protecting transaction amounts, it doesn't have anything to do with the question.

**Comment by ABISprotocol** [comment]
Then provide an example of functional CoinJoin, being as there are examples out there and the bounty on it was long ago claimed.

**Comment by sipa** [comment]
I fail to understand what you're arguing for.

You're very welcome to go suggest CT in Bitcoin or explore how it could be implemented. But this is not the place for it.

This issue is about bringing CoinJoin to Bitcoin. A commenter is asking whether there exists a working decentralized version protocol for CoinJoin to base their work on. I don't know the answer to that. You bringing up a completely unrelated privacy improvement is not useful, and I'm pointing that out.

Note: I have nothing against CT; I'm even responsible for part of the its implementation in Elements Alpha. All I'm asking is to stick to the issue.

**Comment by ABISprotocol** [comment]
@sipa, I'm asking you to stick to the issue and contribute.  Instead of sniping, add your piece and answer @Giszmo's question.

**Comment by laanwj** [comment]
@Giszmo I've heard some positive noises that Joinmarket is actually starting to be used. It's making progress (one indicator is issues like #7101 being opened).

@ABISprotocol Realize you're accusing one of the most important contributors to bitcoin of 'sniping'. CT is indeed not related to coinjoin and thus off-topic here, but you started mentioning it not @sipa, so what you say applies to you: stick to the issue.

**Comment by MarcoFalke** [comment]
> @Giszmo: A year went by, JoinMarket is struggling [...]

Do you have any data to support your claim?

**Comment by Giszmo** [comment]
Love CT and can't wait to see them replece current version bitcoin transactions but that's 5 years from now.

Joinmarket has very serious privacy leak and dos problems. Fake takers learn about makers. Failed joins leak info but don't help for future joins. Auth UTXOs complicate the protocol and leak information to the makers. All that would not be a show stopper for wallet integration as it probably can be fixed (changing the api) but my gut feeling tells me that CoinShuffle will be superior very soon and I don't want to bet on the wrong horse here.

**Comment by ABISprotocol** [comment]
No-one has yet answered @Giszmo's question at https://github.com/bitcoin/bitcoin/issues/3226#issuecomment-161395746

**Comment by laanwj** [comment]
If no one answers a question that likely means that no one knows an answer.

**Comment by ABISprotocol** [comment]
@laanwj @Giszmo Please see the following resources which may answer the question:

https://github.com/bitcoin/bitcoin/issues/3226#issuecomment-65111673

and possibly some of the discussion here also, tangentially:

https://github.com/bitcoin-dot-org/bitcoin.org/pull/1129

Note also Stealth addresses, CoinJoin available as js libraries: 
http://bitcoinjs.org 
and
 $ npm install stealth.js 
 $ npm install coinjoin.js
These can be found at:  
https://github.com/darkwallet/stealth.js
https://github.com/darkwallet/coinjoin.js
Note: these repositories were last updated Oct. 2014

**Comment by AdamISZ** [comment]
@Giszmo as I expressed [here](https://github.com/JoinMarket-Org/joinmarket/issues/156#issuecomment-123017246) and in the following comment, what CoinShuffle achieves is orthogonal to the privacy leak issue, which is based on JoinMarket's design of makers announcing utxos - which itself is central to the solution to the coordination problem that JoinMarket provides. To put it another way, one could add CoinShuffle to JoinMarket, at the cost of quite a bit of extra complexity, and there would be significant benefit, but it would not solve *that* problem. Solutions I believe are more along the lines of what's [here](https://gist.github.com/AdamISZ/9cbba5e9408d23813ca8)

**Comment by Giszmo** [comment]
It's probably not a fair, in depth answer but as @AdamISZ aka /u/waxwing reminded me of my lacking answer, here is my [comment on reddit](https://www.reddit.com/r/joinmarket/comments/427wlm/mycelium_is_finishing_up_coinjoinjoinmarket_aint/cz8cdnp) on where I stand in that matter:

> /u/waxwing I owe you a reply there and I didn't get to it all week now, after your reminder [here](https://www.reddit.com/r/Bitcoin/comments/41dj0v/coinjoin_and_the_mycelium_wallet_sounds_very/cz2vike?context=3). Your reply links to "link collections" and always when I tried to reply I got lost in the tenth link or so but I'm pretty sure there is no real big misunderstanding on my part. JoinMarket is fighting the good fight and does consider using CoinShuffle, too, and Daniel Krawisz [implementing it](https://github.com/DanielKrawisz/shuffle-java) as open source, can only help with that. And with CS implemented and not having a "market" to get transactions that are wanted, we might need JM again but I don't think that this is the case. Paying makers to mix, is in my opinion counterproductive to get honest makers and therefore I hope to avoid makers all together.

> Our current concept is to have mixing accounts, where Mycelium would on auto-pilote shuffle coins to the desired degree of mixing and warn the user if he wanted to spend insufficiently mixed coins, preferably making this a default behavior for new HD accounts (but to spend mining fees for our users by default is really a tricky thing. But CS could have its fees sponsored but that's details for later)

**Comment by ABISprotocol** [comment]
Oh, wait, wait.  I knew this would come up. To be fair, Mycelium is doing excellent work, and I know they are now partnering (or working on partnering) with Samourai, and all that.  But what they are doing isn't CoinJoin actually...  It's CoinShuffle in java.

I believe the only functional CoinJoin was that developed for DW.  Somebody correct me if I'm wrong and drop a link to a repository showing another example of CoinJoin in action.

**Comment by raedah** [comment]
@ABISprotocol https://github.com/JoinMarket-Org/joinmarket/ is functional.  See http://joinmarket.io/ and  https://github.com/bitcoin/bitcoin/pull/7101

**Comment by AdamISZ** [comment]
@ABISprotocol @raedah unfortunate timing, but **all** the bots crashed today due to rather trivial bug(the first time such a thing has happened in 6-8 months!). 

So joinmarket.io shows much less activity than usual. But anyway, yes, ABISprotocol's statement is definitely wrong; more to the point, it's easy to verify for oneself by simply running a joinmarket bot; you can do a coinjoin any time, usually anything up to 10 btc can easily be done with say 5-10 counterparties, immediately.

@Giszmo I've answered on reddit, but I think the point I was making here stands; Coinshuffle doesn't address the fact that you need to announce input addresses. You can "solve" that problem with a central server of course.

**Comment by ABISprotocol** [comment]
@raedah @AdamISZ  It's good to know I'm wrong on this point!  TYVM!

**Comment by Giszmo** [comment]
I feel like I repeat myself and to put it bluntly, here is why I believe that [with JoinMarket, spies win](https://www.reddit.com/r/joinmarket/comments/427wlm/mycelium_is_finishing_up_coinjoinjoinmarket_aint/cz8ye0y). Mixing only makes sense when

* no player has an incentive to be all counter-parties in a mix (makers get paid)
* no player can track the matching (taker knows the matching)

@ABISprotocol so technically you might claim that my solution (mix coins in a CoinShuffle account inside the wallet, then spend as normal transaction from there) is no coinjoin because the payment isn't coinjoin? I would see that way more nuanced: Having a shuffling account would allow us to add trickling payments, where low priority payments can be made using shuffling, paying in increments to a BIP47 address. I would love to get my salary this way. It would only be a question of the contract giving this flexibility but then, why not have a payment every other day in varying amounts?

But yes, to do a privacy enhancing coinjoin transaction for an ad-hoc payment, something like JoinMarket would still be needed. At least until CTs are implemented in Bitcoin, at which point coinshuffle could be enhanced for ad-hoc payments and joinmarket wouldn't be needed anymore.

**Comment by AdamISZ** [comment]
@Giszmo and as I have just answered in that reddit thread, Coinshuffle does not remove the possibility of the kind of spying you envision. According to your bullet points, you're making the argument that because there is a financial incentive to take part, large scale sybil-to-spy is likely, but it's a weird argument. No large spying organisation would be motivated by small coinjoin fees anyway (and indeed would choose very small/zero/negative fees). So effectively you're saying that the absence of a market incentive would makes sybil less likely - but that's just sybiling to make money, and is a problem that needs to be addressed with some kind of commitments; it's got nothing to do with Coinshuffle.

**Comment by ABISprotocol** [comment]
@Giszmo CoinShuffle is not the same thing as CoinJoin.  CoinShuffle is based on the idea of CoinJoin but is different.  From the CoinShuffle original paper, "CoinShuffle is inspired by CoinJoin to ensure security against theft and by the accountable anonymous group communication protocol Dissent to ensure anonymity as well as robustness against DoS attacks." However, CoinShuffle is _not_ the same as CoinJoin.  Joinmarket, on the other hand, is a "CoinJoin implementation with incentive structure to convince people to take part."

The original CoinJoin was published here, bounty was claimed in same message:
https://bitcointalk.org/index.php?topic=279249.msg3016952#msg3016952
What appeared to have evolved from that is
https://github.com/darkwallet/coinjoin.js
and https://darkwallet.github.io/coinjoin.js/

Please correct if I am wrong here, but I am thinking that CoinShuffle is not considered a CoinJoin implementation, but something that is similar to it.

**Comment by ABISprotocol** [comment]
Hola CoinJoin thread folk, I just noticed this, [a GUI joinmarket app in progress](https://github.com/AdamISZ/JMBinary/blob/master/README.md) (ty @AdamISZ). Making things easier is important.

**Comment by laanwj** [comment]
I've played with joinmarket for a bit and I think it's getting pretty usable.

Would be awesome if bitcoin core's wallet was able to interface with joinmarket to send transactions.

**Comment by chris-belcher** [comment]
My current way of thinking for integrating joinmarket with Bitcoin-qt is to use the -walletbroadcast=0 flag. 
From https://github.com/JoinMarket-Org/joinmarket/issues/103 :

> Set -walletbroadcast=0 and get the tx hex, extract from it the inputs and outputs, create a coinjoin from that information and broadcast it. The GUI might show an odd double spend attempt but the coinjoin tx will win because the non-coinjoin was never broadcast.

Of course you can send coinjoins from your Bitcoin Core wallet today by using the joinmarket sendpayment.py script with the --rpcwallet flag, which gets UTXOs, a change address and private keys through json-rpc and uses them to create a coinjoin. However its a command line app which only developers can love.

**Comment by ABISprotocol** [comment]
Yep, it would be great to see this joinmarket functionality as an option in Core.

**Comment by Sjors** [comment]
Concept ACK on some sort of mixer support. Ideally using one of the new protocols that allow for signature aggregation, since a combination of increased privacy and lower cost would likely increase the number of users and thus the size of the anonymity set. In that case I vote for calling it "compression".
