### ISSUE TITLE
Should the GUI have a "you're sending again to the same place you sent before"?

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#3266]
when you try to send to some place you've already sent, perhaps there should be a polite "You've already sent X btc to this destination in TXN y on date Z. Do you want to continue?"  which should help people avoid some of the incidents they've had with double paying.

**Comment by MarcoFalke** [comment]
It would also help to educate about address reuse.

**Comment by CryptAxe** [comment]
Do either of you have any thoughts as to how to implement this? Looping through the wallet's transactions and comparing the destination address to what the user wants to send to now seems possible, but maybe not the best approach?

**Comment by luke-jr** [comment]
I set a label for every payment, so whenever I go to pay an address a second time, it already loads that label up... which I take as an implicit warning (and then I go complain to whoever gave me the same address twice). Making it an explicit warning sounds like a good idea, and can probably be done with some flag on the addressbook entry easily enough.

**Comment by laanwj** [comment]
Indeed, searching the address book should be enough, which is much faster than searching the transactions.

**Comment by CryptAxe** [comment]
Alright heres a simple solution I am testing out. This will just check if the address you have pasted into the send coins entry address field exists in the address book already, and display a warning message if it does.

This will also display the error message if you create a receiving address from the request dialog and then try to send a payment there. I'm not sure if that is a problem because users probably aren't doing that too often.

I also noticed that the label field is not cleared when a new address without a label is pasted, the UI displays the old label so I fixed that as well.

https://github.com/CryptAxe/bitcoin/commit/0698a278274c32b2b90901561d1f8f510cd4890a

**Comment by luke-jr** [comment]
1. If you type a label before the address, you don't want it cleared.
2. Consider the scenario where a user gets a loan, and saves the repayment address in his address book for later. I would consider it a bug if he got a warning when he tried to send to it the first time. So some explicit flag is needed (it can be set on the address book entry went it is used for sending).
3. "Address reuse is not recommended!" is too soft and unclear. I suggest "You have already paid this address!", and making it a hard error with a manual override (dialog with an "Ignore and send anyway" option?)

**Comment by CryptAxe** [comment]
Thank you for the feedback. In this new branch I made it so that an address will be marked as used when it is sent to via UI.  If the user tries to send to that address again, a warning message will popup and require that they accept the consequences to continue. If multiple recipients are entered, each will be checked and the user will need to verify that they want to reuse each one before the send tx confirmation dialog is shown.

I'm open to suggestions on the language in the popup message, but I copied a reddit comment from Luke which I believe sums it up nicely. 

https://github.com/CryptAxe/bitcoin/commit/44d74135ed7c18e43691b6d6c017574a86846ee5

**Comment by CryptAxe** [comment]
![snap](https://cloud.githubusercontent.com/assets/8107318/22630727/cd1cb33a-ebb3-11e6-93ee-4246dc1a5ee7.png)

**Comment by luke-jr** [comment]
Just add a new key to destdata?

**Comment by CryptAxe** [comment]
Handling tagging the address as used in the same way the labels are done just made more sense to me. This way would make it easier, I think, to add whether or not the address is used to the address book view as well (just a few lines would need to be added). I hope to update the address book view to be search-able and filterable in the near future and being able to show only unused / used addresses would be a useful filtering option.

The loop looking up destdata and the loop I wrote to lookup the used value are basically identical with the destdata loop being slightly more complicated but probably no real performance difference. I can change it still though of course if I am missing something that makes the way I did it worse. Thanks!

**Comment by luke-jr** [comment]
AFAIK the destdata exists specifically for extending the address book like this.

**Comment by CryptAxe** [comment]
The address table model actually doesn't even know about the destdata as far as I see. It would be possible to add the used value to destdata, but it would be a lot more work to add that to the address book view. I still think adding the used state to the address model is the way to go, maybe this will convince you:

https://github.com/CryptAxe/bitcoin/commit/dc347b30e5c76b0a7e66c935a466fd03b612a187

**Comment by luke-jr** [comment]
No reason AddressTableEntry can't use destdata to get the used flag?

**Comment by CryptAxe** [comment]
Alright I give up and will do it your way :+1: Do you have any feedback on the popup message text or anything else before I make the "final" draft?

**Comment by luke-jr** [comment]
```C++
tr(
    "You have sent to the Bitcoin address %1 already!\n\n"
    "Sending to the same address twice is technically not supported and will reduce your own security as well as the privacy of all Bitcoin users."
).arg(address) + "\n"
```

**Comment by CryptAxe** [comment]
https://github.com/CryptAxe/bitcoin/commit/9d94192464cbee9abacc32cb3537468c4c79aa35

**Comment by luke-jr** [comment]
Looks more or less good enough to open a pull request at least.

**Comment by CryptAxe** [comment]
Thanks for helping!

**Comment by promag** [comment]
Related to #13756.

**Comment by promag** [comment]
> Doubling payments is an actual mistake that people make

@gmaxwell this case is different because both the destination and the amount must duplicate to be considered double payment. I consider this case orthogonal - the message should warn it's double payment and possible the option to see the last payment).

**Comment by fanquake** [comment]
Moved to https://github.com/bitcoin-core/gui/issues/648.
