### ISSUE TITLE
Unconventionally named Application Support directory

### ISSUE THREAD

**Issue by cbrunnkvist** [bitcoin/bitcoin#3459]
If a user intends to uninstall the app, it would be nice if the related cache data (the potentially huge blockchain cache) were deleted too. According to common convention, a directory created under Library, say:  `~/Library/Application Support/${TheApp}` should match, or start with, the name of its creator. Dependent files can start with "TheApp", e.g. you can have `TheApp-common` and so on.

In our case of the GUI BitCoin client, the application is distributed as "**Bitcoin-Qt**" and as a consequence anyone looking for related files will fail finding `~/Library/Application Support/Bitcoin` as it does not match =~ `/^Bitcoin-Qt.*/`. _AppZapper_ is a common example of this.

Related: http://stackoverflow.com/questions/5029410/how-to-detect-files-related-to-an-app-on-a-mac

**Comment by laanwj** [comment]
Similar issue as "Use AppData\Local instead of AppData\Roaming #2391" or "Uninstaller should have option to remove data (except for wallet) #993", except for OSX instead of Windows.

Care would have to be taken not to remove the `wallet.dat` on uninstall.

**Comment by Sjors** [comment]
I don't think this is worth fixing. The biggest problem is already covered by #993, which is that the standard way people uninstall the wallet won't get rid of the blockchain data, and that manually deleting this is risky if the user is not careful.

Once a user finds out that they didn't save as much space as expected, they'll Google how to manually do this. If they use Finder to look at their Library directory, they can't possibly miss "Bitcoin". If they use the console and are lazy enough to use tab completion, they won't miss it either.

That said, I like the idea of renaming the app to just "Bitcoin" on OSX, as "QT" doesn't add any value and I don't think it has much brand value these days, unlike e.g. "Bitcoin Core". But such a rename doesn't seem worth the risks @laanwj described.

**Comment by kpabsad** [comment]
How to print your own checks?

Printing your own checks mean that you would never run out of checks, and that your checks will be unique. However, you need to know how to do this correctly in order to be right. Learn how to print your checks by yourself; the procedure and requirements, so that you can determine what is perfect for you.
You can save lots of money also by printing your own checks moreover it is convent and keep a good searchable history and report of checks you paid by having a good check printing software. 
The requirements for printing your own checks include the following:
-	Blank Check Paper stock: special paper that prevents tempering or duplicating of your checks.
-	Check Printing Software- Preferably Online Based fro easy access
-	Printer- Any Printer you already have.
To print your own checks, you can either obtain partially printed ones, it is called Pre Printed Checks or you could decide to create it from the scratch. The second option is great; it is cheaper and print checks on demand. Have some Blank Check Paper and get good check printing software
The check printing software handles creation of the checks (which is the toughest part); you could set all these details in the setting of the check printing software. After these are done for you, all you need to do is insert this check in your own printer and then fill in the details, such as the amount transacted, payee, and internal notes or memos. Online Check Writer, Versa Check and Chax are all the most popular check printing software. Online Check Writer is a cloud based one giving flexibility to print checks from any device verses versa check and chax offline based. 
With check printing Software, you can customize you checks. Further, a majority of their applications work with popular software and web applications, such as www.OnlineCheckWriter.com. With these off your neck, you can only focus on the essential aspects of check printing.
Alternatively, you could print your own checks from scratch. You can design your checks by yourself if you have graphics design skills and time to spare. However, a faster method of doing this is by using check printing website, www.OnlineCheckWriter.com. Check printing software or web applications help you with the designing and carries out all the hard work. Check printing applications do not stop at creating your checks for you; they help with other things like tracking payments, and so on.
Equipment for Printing Checks
Most regular printers can print out your checks, but if you want to create them from scratch, you should use magnetic ink. Magnetic ink is more expensive and tougher to find than local ink. Although you can use normal ink, there are some downsides to that, which we will explore further in this article. After check 21 act MICR printer is not really needed, all the checks are processed through image now days-OCR.

**Comment by MarcoFalke** [comment]
> I created #11959 specifically for OSX uninstall.

Let's continue discussion there, then
