### ISSUE TITLE
SAV reported bitcoind infected w Silly.218, crashed bitcoind (likely false positive)

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#4069]
OS: Win 7 x64
Bitcoin core: 0.9.1

While running bitcoind.exe --reindex:

```c:\Program Files\Bitcoin\daemon>bitcoind.exe --reindex```
```Error: System error: Database I/O error```

Symantec Anti Virus detected Silly.218 in ```chainstate\052878.sst``` directory (other names under which the malware is known: Virus.DOS.Dutch_Tiny.163.a (Kaspersky), Silly.218 (Symantec), Tiny-Family #3 (Avira)). Hash of the pattern detected: ```E272F4FF4AD99D1C48C4888990893FC6193DB1CB9849C69B1710069BBD047E0D```

As the file was automatically quarantined and deleted (I can't change SAV default settings), that crashed bitcoind and corrupted the bitcoin DB. 

Internet search on this yielded no results. This looks like a false positive.

**Comment by dexX7** [comment]
> @wyager: In fact, if this must be implemented, please keep this disabled by default. Either only build this *into windows builds*, or leave it as a checkbox (if checked by default, only on windows machines).

Just as slightly related side note: in July I received a report that ClamXav on OS X appears to cause DB curruptions as well. Based on the logs, the synchronization failed after block 294007 due to an error in the block header. I haven't verified the report, but appearingly the DB corruption was not a one-time event.

**Comment by laanwj** [comment]
Should be fixed by #6650, which is merged fo r 0.12
