### ISSUE TITLE
Windows GUI (0.10.0rc1)

### ISSUE THREAD

**Issue by aduser2** [bitcoin/bitcoin#5570]
Send dialog does not appear consistent in windows32:
- Double frame around "pay to"-dialog (screenshot 1)
- "Transaction fee"-dialog squeezes "pay to"-dialog (screenshot 2)
- When "transaction fee"-ialog is closed, space remains (screenshot 3)
- More intuitive order of dialogs would be pay to - coin control - transaction fee

![cs1](https://cloud.githubusercontent.com/assets/10347403/5576862/94f67b82-9005-11e4-9616-4efe0cbd6fc1.jpg)
![cs2](https://cloud.githubusercontent.com/assets/10347403/5576863/98612042-9005-11e4-96e5-845c4f3b71f3.jpg)
![cs3](https://cloud.githubusercontent.com/assets/10347403/5576867/a4ec61e6-9005-11e4-9816-d565a4b91195.jpg)

**Comment by Diapolo** [comment]
- Double frame around "pay to"-dialog (screenshot 1)

That is because you can have more receipients, which are embedded in that UI elememt then. It may look a little weird with just one, but that has always been the case.

- "Transaction fee"-dialog squeezes "pay to"-dialog (screenshot 2)

Right, the main window should be resized to compensate for the additional UI elements shown. Too bad this doesn't happen automatically. (@laanwj Any ideas for this?)

- More intuitive order of dialogs would be pay to - coin control - transaction fee

I agree on this one here ;).

**Comment by jonasschnelli** [comment]
@aduser2 would you mind giving this issue a better title?

IMO these are the expected behavior as also written by @Diapolo.
Should be closed or rewritten as feature request.
