### ISSUE TITLE
[QT] Win: icon coloring issue tray-menu

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#5625]
@luke-jr would you mind have a look at it?

![bildschirmfoto 2015-01-09 um 11 13 47](https://cloud.githubusercontent.com/assets/178464/5678297/195285ea-97f1-11e4-81b4-dfa3577e6f1e.png)

Light blue color for std. theme is okay.
I still would prefer the black one... but i'm fine with the auto-color.

![bildschirmfoto 2015-01-09 um 11 03 46](https://cloud.githubusercontent.com/assets/178464/5678305/42cdae68-97f1-11e4-9f23-1817ea301db5.png)
![bildschirmfoto 2015-01-09 um 11 15 47](https://cloud.githubusercontent.com/assets/178464/5678306/4728eb08-97f1-11e4-820b-44167fcd3407.png)

classic theme also looks okay:
![bildschirmfoto 2015-01-09 um 11 16 27](https://cloud.githubusercontent.com/assets/178464/5678310/5a81ec54-97f1-11e4-9730-0afebea478a3.png)

**Comment by laanwj** [comment]
The dark blue looks nice, the light blue just doesn't have enough contrast with the white. I think light colors should only be used on dark backgrounds.

**Comment by jonasschnelli** [comment]
@laanwj Agree with that. I'm also questioning myself if it makes sense to use the color-manipulating on windows. I would prefer black icons on windows.
Linux makes sense.
OSX will always be black.

**Comment by Diapolo** [comment]
I also said that a few days ago, it looks a little strange IMHO.

**Comment by jonasschnelli** [comment]
@Diapolo I open this issue to move the discussion from the close PR (https://github.com/bitcoin/bitcoin/pull/5493)

**Comment by jonasschnelli** [comment]
Related to #5653

**Comment by zander** [comment]
As mentioned elsewhere;

In any example I try to find having monochrome icons that follow the text color just isn't what happens, and the result just looks broken. Its completely inconsistent with all the other apps because they all use color icons. Its also inconsistent with itself because the "Show / Hide" for instance is not actually the logo you see in the taskbar, its got a different color.

Bottom line, I have zero applications on either Windows (8.1) nor on Linux (KDE and Gnome) that have monochrome icons in their systray context menu. So this just doesn't look consistent in any way at all.

Sorry if this is not the place to have this discussion; without a mailinglist its really really hard to find "decisions" that just don't get seen by me and any other stakeholders.  So please tell me where you actually talk about these things.

**Comment by laanwj** [comment]
Ubuntu has monochrome (even: grey) icons in their systray.

**Comment by zander** [comment]
Sure, the icons are monochrome.   But the popup menu icons are not.

**Comment by laanwj** [comment]
Here they are, at least the 'official' ones, this shows e.g. the language selection menu:
![naamloos](https://cloud.githubusercontent.com/assets/126646/5720141/f44424dc-9b17-11e4-97db-98c25886f851.png)
It's the same for the network menu, and battery. Everything is grey. Just as I like it. Xpra is the odd duck out by having a colored icon and colored icons in the menu.

In any case, to go back to the issue: I don't think it's really disturbing but yes, having send and receive in a different color as the others is inconsistent.
