### ISSUE TITLE
Send coins dialog: Transaction Fee doesn't consider zero-fee transaction possibility

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#5650]
The "Transaction Fee" at the bottom of the send coins dialog always shows the configured amount even when zero-fee is checked and possible.

**Comment by Diapolo** [comment]
I can confirm this and also wondered, why that is the case. IMHO @cozz implemented the current solution, perhaps he can clarify this?

**Comment by cozz** [comment]
Its not implemented and its not trivial to do so, because you would need to run the coin selection algorithm, guess the transaction size and then decide whether or not the tx is going to be zero-fee.

Coin control does that, when you use coin control and select the inputs manually. It also shows if zero-fee in the coin control labels. In the coin control case, we could set the label to zero, if zero-fee, that would be easy.

**Comment by Sjors** [comment]
Zero fee isn't possible anymore, right?
