### ISSUE TITLE
"Preferences" menu opens "command line options" when using French language (OSX)

### ISSUE THREAD

**Issue by lunokhod** [bitcoin/bitcoin#5800]
When clicking on the "Preferences" menu when using French language, the "command line options" window opens instead of the usual preferences pane. I note that this works correctly when using English and a few other languages that I tested.

Bitcoin core version 10.99.0
OS: OSX 10.9.5

**Comment by theuni** [comment]
Confirmed. This is a weird one. It seems to be caused by some string matching gone bad.

The french translation of "Command-line options" is "Options de ligne de &amp;commande". When translating "Options..." at runtime, it finds matches the "Options de ligne de &amp;commande" and opens that window.

Weird.

This can be confirmed by the following hack-test-fix.

``` diff
diff --git a/src/qt/locale/bitcoin_fr.ts b/src/qt/locale/bitcoin_fr.ts
index 71a1519..82a6bef 100644
--- a/src/qt/locale/bitcoin_fr.ts
+++ b/src/qt/locale/bitcoin_fr.ts
@@ -416,7 +416,7 @@
     </message>
     <message>
         <source>&amp;Command-line options</source>
-        <translation>Options de ligne de &amp;commande</translation>
+        <translation>.Options de ligne de &amp;commande</translation>
     </message>
     <message>
         <source>Show the Bitcoin Core help message to get a list with possible Bitcoin command-line options</source>
```
With that in-place, both menus work as expected.

It looks like a pretty clear Qt bug to me. Maybe we can work around by inserting some invisible garbage into the string for now?

Or as a different work-around, we could probably change "Options..." to "Preferences...", since we're setting the PreferencesRole on it anyway. That'd mean updating all translations though.

**Comment by laanwj** [comment]
Huh, so this is a bug in Qt and not just a wrong translation on Transifex?

**Comment by jonasschnelli** [comment]
I try to find a solution.
Behavior is documented at http://qt-project.org/doc/qt-4.8/qmenubar.html (section "QMenuBar on Mac OS X").
I think it's not a QT bug, it's more or less a strange way of handling menus on mac.
