### ISSUE TITLE
Negative balance v0.10

### ISSUE THREAD

**Issue by ondra-novak** [bitcoin/bitcoin#5840]
![clipboard01](https://cloud.githubusercontent.com/assets/9439234/6425647/e56ca2dc-bf33-11e4-9518-56cbc48b8f15.png)

Possible reason: Spent outputs are subtracted from main account. Other accounts contain watch-only addresses

**Comment by afk11** [comment]
You should not mix raw transactions with accounts. This is usually a big contributor to this problem. Generally speaking, this feature does not scale well and likely will be deprecatedas it never functions the way people want it to..

**Comment by ondra-novak** [comment]
Where I mentioned raw transactions?
Does it mean that accounts are useless?
I just tested watch-only addresses feature. I wished to watch multiple real (existing) wallets.

**Comment by ondra-novak** [comment]
I can see a little confusion. What is account and what is label? Transactions in bitcoin-qt are shown labeled by account name. Outgoing transactions remain without label, so they are probably assigned to main account. 

![clipboard01](https://cloud.githubusercontent.com/assets/9439234/6426743/debfc4ce-bf69-11e4-99df-1d59590617e1.png)

**Comment by benjyz** [comment]
Yes, accounts are useless / should never be used. Unfortunately this fact is not well published. It's planned for deprecation.

**Comment by ondra-novak** [comment]
Ok, i got it. So watch addresses are useless too. You cannot watch spent transactions on each separately (through API).

**Comment by sipa** [comment]
Watch addresses are not useless, but they're not intended to provide a "per-address balance". You can see for individual transactions on which address they arrived (so you can discover who paid), but all coins in the wallet are considered common to the entire wallet. The advised way of dealing with this is by using a new address for every incoming transaction anyway.

It sounds like you're looking to have "multiple wallets" which do not share coins, rather than just multiple addresses. This is not supported right now.

**Comment by ondra-novak** [comment]
I am trying to figure use-case of such feature.... anyway, this is not the topic of this issue. 
In conclusion: 
 - accounts are useless, and will deprecated soon
 - bitcoin-core cannot be used to watch multiple wallets, it still requires some third part application.

Closing ticket, thank you.
