### ISSUE TITLE
bitcoind and bitcoin-qt from ppa:bitcoin/bitcoin crashes on Ubuntu 14.04 amd64

### ISSUE THREAD

**Issue by grasputin** [bitcoin/bitcoin#5856]
When installed on 64-bit Ubuntu 14.04 system

sudo add-apt-repository ppa:bitcoin/bitcoin -y
sudo apt-get update
sudo apt-get install bitcoin-qt -y

bitcoind and bitcoin-qt are crashing, printing:
Segmentation fault (core dumped)

~/.bitcoin/debug.log contains the following:
https://gist.github.com/grasputin/45d387bf1d34c2ce285c

**Comment by paveljanik** [comment]
The `debug.log` contents is normal.
As we do not know what your distro is doing with the source, please report to your distro.
Please provide more details to your distro/packager - e.g. the `gdb` output etc. Try also running `bitcoind` instead of `bitcoin-qt` to help your distro/packager to investigate the issue.

As we can't help you here, please close this issue.

**Comment by grasputin** [comment]
Aren't you responsible for ppa:bitcoin/bitcoin?
Who is, then? I reckon ppa is a separate thing from the distro.

**Comment by sipa** [comment]
@TheBlueMatt runs the ppa.

**Comment by grasputin** [comment]
Emailed him.
I thought here is the place to raise this issue. Oh well, closing it then.

**Comment by sipa** [comment]
Feel free to report back here, in case it would turn out to be an upstream issue.
