### ISSUE TITLE
Ability to disconnect/ban peers from the GUI

### ISSUE THREAD

**Issue by PRabahy** [bitcoin/bitcoin#5866]
This is a feature requests, not a bug.

Now that I have been using the new Peers screen in bitcoin-qt, I have noticed that there are several peers that are doing something that I don't like (using too much bandwidth, multiple connections from the same ip, etc.) I would like an option to right click on a peer and be able to disconnect or ban them. Also, it would be nice if the same right click menu had an option to reserve an inbound slot for a specific peer, but that would likely be a bit more tricky.

**Comment by laanwj** [comment]
There aren't even RPC commands to do this. Those should come first. I think it'd be nice to have, although having to babysit your peer list shouldn't necessary.

**Comment by jonasschnelli** [comment]
I also like the idea of having a RPC command `disconnectpeer` and `banpeer` (over a `peer id` or `peer ip` arg).
A context menu in the GUI-Console with those function could make sense.

**Comment by MrKrzYch00** [comment]
I can say that implementing banpeer is not that hard actually. I did it myself in cloned sourcecode as a part of addnode rpc command (addnode IP:port ban) and it seems to work, the ban code also performs disconnect. However just disconnecting can be less of use since that peer can reconnect right away (unless we are blocking incoming connections).

Another thing to note is some peers disconnecting/banning other peers that are syncing with network, for example people with low upload limit that are lagged (I myself have max ~80KiB/s upload). I doubt that it will be abused to that extent, but it can always hurt the network, though.

**Comment by aussiehash** [comment]
+1

**Comment by LeMiner** [comment]
As a full node owner, I'm going to +1 this as well. It'll be a great addition to QT

**Comment by MrKrzYch00** [comment]
For ban code I use this modification: https://github.com/MrKrzYch00/bitcoin/commit/0672b0feafecab98409790eabd52b56939b954e4
so far I have no problems with it running.

**Comment by jonasschnelli** [comment]
This is possible now. See #6315. Closing.
