### ISSUE TITLE
Localization bug w/ unicode in debug console

### ISSUE THREAD

**Issue by fsb4000** [bitcoin/bitcoin#5895]
![bug](http://i58.tinypic.com/4j486s.jpg)
If I set English(Settings->Options->Display->User Interface language) then I get correct
```
"errors" : "This is a pre-release test build - use at your own risk - do not use for mining or merchant
```

**Comment by jonasschnelli** [comment]
Checked with lang=zh_CN.
There is an issue (but QT only).

![bildschirmfoto 2015-03-14 um 13 16 16](https://cloud.githubusercontent.com/assets/178464/6651643/5ee499f8-ca4c-11e4-91c2-06e97308504c.png)

when going over bitcoin-cli shell looks fine because the error comes back in english:
![bildschirmfoto 2015-03-14 um 13 17 40](https://cloud.githubusercontent.com/assets/178464/6651645/8aeacaf4-ca4c-11e4-9fa5-83b8f5294c91.png)
