### ISSUE TITLE
Spending (some) data carrying outputs with non-canonical public keys

### ISSUE THREAD

**Issue by dexX7** [bitcoin/bitcoin#5939]
I run http://redeem.bitwatch.co/ to provide a tool for users to cleanup leftovers from bare multisig data carrying transactions and recently I received a few reports of issues, when signing the sweeping transaction.

Until some point Counterparty, as primary entity to name here, used to embed data as non-canonical public keys without valid public key prefix in bare multisig scripts, where one valid public key was intended to be used for redemption.

With `SCRIPT_VERIFY_STRICTENC` and `CheckPubKeyEncoding()` however, it appears that those transactions are no longer signable or spendable, as far as I can see.

I'm not sure, if this can be solved, or if there might be an alternative, but currently it looks like an estimated amount of 160k unspent dust-ish outputs seem to be affected. The actual redemption rate was unfortunally never very high though.

**Comment by yampi1** [comment]
I noticed that I could only redeem one output at a time.It seems currently you can't spend multiple multisig utxo in one tx.

**Comment by sipa** [comment]
@dexX7 Since 0.10, such transactions are indeed non-standard, unless it's the first pubkey that is valid. Note that these are intentionally NOT made invalid by BIP66, so even though they're non-standard (which may be relaxed), they will remain valid in blocks.

@yampi1 The number of UTXOs spent has no impact at all.
