### ISSUE TITLE
Ability to pause bitcoin miming while running the gui

### ISSUE THREAD

**Issue by ScottDeans** [bitcoin/bitcoin#5986]
When i was testing bitcoin i kept running low on physical memory so i was not able to launch the app, so it would be good to have the ability to run bitcoin gui without the need to have its mining running,

**Comment by sipa** [comment]
You almost certainly do not have a miner running when using the Bitcoin GUI (unless you called the `setgenerate` RPC, or started with the `-gen` command-line option).

Bitcoin Core implements a full node, which validates all transactions on the network (including all of history, when it first runs). Likely the load on your system you are seeing is just due to work for this validation.

If you're not willing or not capable of running a full node due to the resources it requires, you can use different Bitcoin software with different security models.

**Comment by colinkelly** [comment]
It may simply be that your bitcoin client is downloading the blockchain... which is huge. I doubt that you are trying to solo mine with your cpu lol, if so, please quit that ;)

**Comment by sipa** [comment]
If the load from catching up is too high for your system, starting with `-par=1` may help.
