### ISSUE TITLE
Notification commands:  Max outstanding throttling and ignore during reindex/rescan.

### ISSUE THREAD

**Issue by cheako** [bitcoin/bitcoin#6031]
During a reindex bitcoind launched hundreds of shells, crippling the server and getting the hosting company involved.  Please implement throttling and add a filter to prevent calls when working with historical data.

**Comment by laanwj** [comment]
... and that's one of the reasons why notification through running a shell command is a bad idea. If we'd use a socket based approach, this would be much less problematic.

Which kind of notification is the problem here? It's already tried to mitigate this, by only calling the block notifications when not `IsInitialBlockDownload`. This isn't the case for wallet notifications I think.

**Comment by cheako** [comment]
There is a socket RPC already and if you'd use the P2P socket you could get exactly what you're asking for.  Though it'd take a moment to add an option to send notifications to a fifo.

I've both wallet and block running the same script.
