### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by y** [bitcoin/bitcoin#6056]
can't  build latest git master (734f80a5d18821f4f6d0488996655c6e35ce160c).
boost version 1.58
    ...
    CXX      wallet/libbitcoin_wallet_a-rpcwallet.o
    In file included from wallet/rpcwallet.cpp:7:
    In file included from ./base58.h:21:
    In file included from ./script/standard.h:12:
    In file included from /opt/local/include/boost/variant.hpp:22:
    /opt/local/include/boost/variant/get.hpp:212:42: error: implicit instantiation of undefined template 'boost::STATIC_ASSERTION_FAILURE<false>'
        typedef ::boost::static_assert_test< sizeof(::boost::STATIC_ASSERTION_FAILURE< (((boost::detail::variant::holds_element<boost::variant< T0 , T1 , T2 , T3 , T4 , T5 , T6 , T7 , T8 , T9 , T10 , T11 , T12 , T13 , T14 , T15 , T16 , T17 , T18 , T19 >, U >::value)) == 0 ? false : true) >)> boost_static_assert_typedef_216 ;
                                            ^
    /opt/local/include/boost/variant/get.hpp:284:12: note: in instantiation of function template specialization 'boost::strict_get<const CScriptID &, CNoDestination, CKeyID, CScriptID, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>' requested here
        return strict_get<U>(operand);
            ^
    wallet/rpcwallet.cpp:2333:48: note: in instantiation of function template specialization 'boost::get<const CScriptID &, CNoDestination, CKeyID, CScriptID, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>' requested here
                    const CScriptID& hash = boost::get<const CScriptID&>(address);
                                                ^
    /opt/local/include/boost/static_assert.hpp:87:26: note: template is declared here
    template <bool x> struct STATIC_ASSERTION_FAILURE;
                            ^
    1 error generated.
    make[2]: *** [wallet/libbitcoin_wallet_a-rpcwallet.o] Error 1
    make[1]: *** [all-recursive] Error 1
    make: *** [all-recursive] Error 1

**Comment by easye** [comment]
Note that this failure occurs for the v0.10.1 tag as well.

Is there a statement somewhere of the versions of dependencies that Bitcoin Core has been tested with?

**Comment by theuni** [comment]
I've just verified this problem. It's due to the breaking change in boost 1.58 (See the variant notes here: http://www.boost.org/users/history/version_1_58_0.html)

Fix is coming right up.

**Comment by dvinas** [comment]
Just a comment for anyone who might be trying to build from tag "v0.9.5" (the latest release version, as of the time of writing) on Mac OS X:

I am not able to compile this tag, due to the above issue.  Fix #6076 does fix this, HOWEVER, if you do the obvious thing, which is switching back to master in order to build, be sure to re-open the document "Mac OS X Build Instructions" (doc/build-osx.md) and notice the changed prerequisites under "Install dependencies using Homebrew".  It seems there have been some recent changes to these dependencies.

Old version (v0.9.5): 
brew install autoconf automake libtool boost miniupnpc openssl pkg-config protobuf qt

New version (master):
brew install autoconf automake berkeley-db4 libtool boost miniupnpc openssl pkg-config protobuf qt5 libevent

I failed to do this, which resulted in my having the older build document open in one window, while I switched to a different tag and tried to build with the same dependencies. This will lead to the following error when trying to execute './configure':

configure: error: libevent not found.

No amount of searching the web helped me realise my mistake, hence the reason I'm leaving this comment.  My pain is your gain.

It's also worth noting that, although Boost 1.59 is rumoured to fix the above issue, and would theoretically allow compilation of tag v0.9.5, it is not yet available via Homebrew.  Hence, your best bet is to revert to master, and do the above.
