### ISSUE TITLE
qt vs boost

### ISSUE THREAD

**Issue by promag** [bitcoin/bitcoin#6167]
Why does bitcoind depend on boost and not only Qt? There are lots of benefits using Qt.

**Comment by paveljanik** [comment]
Qt is optional (for the GUI part of Bitcoin Core). Boost is used all over the source code both for command line services and GUI. `bitcoind` itself does not need graphical UI, because it is controlled via cmdline and RPC calls.

Please do not ask questions via Issues and close this issue as it is no issue.
