### ISSUE TITLE
 Missing bitcoin.conf and wallet.dat out of nothing

### ISSUE THREAD

**Issue by book89** [bitcoin/bitcoin#6182]
I posted issue #6170  and was satisfied with the "solution", but i'm not anymore.

I just logged to the linux virtual machine in my Windows PC that i was using to deploy for the remote server and the same files are missing. The difference is that bitcoind was not running, no bitcoin operations were being done at all. I just tried to run bitcoind and it warned i had no .conf. 

In both cases #6170 and in the virtual machine i was using ubuntu 12.04 and bitcoin latest version from ppa:bitcoin/bitcoin. That's odd.

Only these are left in /root/.bitcoin/
blocks  chainstate  database  db.log  debug.log

My personal computer is not compromised as i supposed my remote linux server was, my wallet on Windows is safe here with considerable amount of bitcoins.

**Comment by laanwj** [comment]
This is extremely odd. However, if bitcoind is not running, nor any other software in this repository at the moment that happens, it cannot be caused by our software. Thus no point opening issues here.

You are also the only person reporting this problem. It sounds like an issue with your local deployment scripting, where a spurious operation deletes your wallet and config file.

**Comment by yokesh351** [comment]
Experiencing this same issue on AWS server, any solution? Conf file gets deleted automatically, same happens for me for LTC and BCH sometimes

**Comment by promag** [comment]
@yokesh351 can you provide more details of your case in a new issue and like to this one?

**Comment by yokesh351** [comment]
i used to run BCH, LTC, BTC in aws server for an exchange. In AWS i had an option in security groups for SSH access to make it accessible from anywhere. but i dont think so it is because of it. Randomly at unpredictable situations, the conf file gets deleted automatically. Is there any step to prevent this?
