### ISSUE TITLE
my antminer can not access bitcoind rpc

### ISSUE THREAD

**Issue by buana** [bitcoin/bitcoin#6270]
hello all i just upgrading my bitcoin core from 0.93 to 10.02 , but the results  my antminers machine can not access bitcoind and remain as a dead pool ( i create my own pool for solo mining using NOMP) , any suggestion ? because when i try to make it back to bitcoin core 0.9.3 again , i dont have any incoming connections anymore , please help

**Comment by jonasschnelli** [comment]
Would you mind being more specific? Error messages, debug logs?

**Comment by fanquake** [comment]
I'd also suggest look at the release notes for 0.10.0. Including the [RPC access control changes](https://github.com/bitcoin/bitcoin/blob/7b6c847f67e96bfc672e48a49ce7bc0510439492/doc/release-notes.md#rpc-access-control-changes).

**Comment by buana** [comment]
thank you for the reply ,  my bitcoin.conf settings are 

# By default, only RPC connections from localhost are allowed.  Specify
 # as many rpcallowip= settings as you like to allow connections from
 # other hosts. As of Bitcoin Core 0.10.0, wildcards are no longer allowed.  Use one of the sample forms below.
 # NOTE: opening up the RPC port to hosts outside your local
 # trusted network is NOT RECOMMENDED, because the rpcpassword
 # is transmitted over the network unencrypted.
 #rpcallowip=10.1.1.34
 rpcallowip=192.168.1.99
 rpcallowip=192.168.1.9
 rpcallowip=192.168.1.85
 #rpcallowip=172.16.0.0/24

its okay when i use bitcoin core 0.93 but when i upgrade it to 10.02 my miners not hashing , when i try to return to 0.93 obsolete , update required on the console when i type getmininginfo and incoming connections drop to 0 till now . I have no IT background so i cant dig more with this issue 
thank you

**Comment by laanwj** [comment]
What is your setup? The antminer and bitcoind instance run on different hosts? 
The antminer is one of 192.168.1.99, 192.168.1.9, 192.168.1.85?
Can you reach bitcoind yourself from your local host using bitcoin-cli?

It's curious that you don't get any connections with 0.9.3. That version should still work, at least if you use the binary from the site. There are some problems if you use a distro-provided version or compile yourself (due to an OpenSSL fork problem), in which case you need to upgrade to 0.9.5 (see https://bitcoin.org/bin/bitcoin-core-0.9.5/).
