### ISSUE TITLE
"Need to upgrade" warning was not displayed.

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#6302]
Regarding #6275, although the latest version doesn't get stuck, there's still the issue that the software did not notify the user that there was a need to upgrade. Has this issue been fixed?

**Comment by laanwj** [comment]
No network alert went out because of the OpenSSL fork issue, but it was widely publicized on the mailing list and other places. It was hard to target this one because it doesn't affect official releases, just self-built versions and some distribution packages.

@gavinandresen's forks and weird network behavior notifier (#6256) would have picked this up, though.
