### ISSUE TITLE
discovery of incorrect IPv6 address

### ISSUE THREAD

**Issue by Geremia** [bitcoin/bitcoin#6375]
My bitcoin.conf file contains these flags:

    min=1
    server=1
    onion=127.0.0.1:9050
    listen=1
    discover=1

`getnetworkinfo` says IPv6 is working on my node:

    {
    "name" : "ipv6",
    "limited" : false,
    "reachable" : true,
    "proxy" : "127.0.0.1:9050"
    }

Yet, no IPv6 peers connect to my node, although many have in the past with this same bitcoin.conf configuration. Only IPv4 and a couple Onion peers currently connect.

Also, `getnetworkinfo` says, for all my protocols (Onion, IPv4, & IPv6):

    "proxy" : "127.0.0.1:9050"

Yet, only the Onion protocol should be going through the proxy (per the `onion=127.0.0.1:9050` flag in my config file).

I am running Bitcoin Core version v0.10.2 (64-bit).

(cf. [this BitcoinTalk.org thread](https://bitcointalk.org/index.php?topic=1106020) and [Bitcoin StackExchange question](https://bitcoin.stackexchange.com/q/38365/4334))

**Update:** See my comment:

**Comment by Geremia** [comment]
The issue was that `bitcoind` was discovering my wrong IPv6 address. (It mistook my link IPv6 address for my public one.) I turned off `discover` and set my IPv4 and IPv6 addresses manually with `--externalip`.

**Comment by laanwj** [comment]
I cannot reproduce the -onion issue on master. `-onion=127.0.0.1:9050` gives:
```
    {
      "name": "ipv4",
      "limited": false,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }, 
    {
      "name": "ipv6",
      "limited": false,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }, 
    {
      "name": "onion",
      "limited": false,
      "reachable": true,
      "proxy": "127.0.0.1:9050",
      "proxy_randomize_credentials": true
    }
```
Could be that this is fixed recently, but are you sure you're not accidentally passing a `-proxy=XXX` as well? `-onion` has existed for ages and this was never reported before. I also haven't ever noticed although I'm using it on one of my nodes.

The IPv6 discovery problem is interesting. Since 0.10 it detects your external address from what peers report. However if it is using an proxy for all outgoing connections, it will never see it.
