### ISSUE TITLE
Remote third parties are able to create accounts in your wallet file

### ISSUE THREAD

**Issue by breymoz** [bitcoin/bitcoin#6431]
By typing listaccounts in the console i found an account called "Refund from Bitpay.com", i received a refund from Bitpay.com and the transaction somehow was able to write an account to my wallet file.

I found that it was very invasive and not compliant with privacy considering you can't even delete accounts.

Version 0.10.0

**Comment by laanwj** [comment]
That is a label interpreted as account name. The GUI doesn't use accounts, but uses the same database fields for labels. You cannot use both the GUI and accounts in bitcoind interchangably safely..
Note that accounts are deprecated and will be removed in a future release (#3816).

**Comment by zebra21** [comment]
It does not even show the label in the GUI, but it is shown in the console.

It is actually exposed to the outside world at the moment they have physical access to your machine and a password will not even be required. Just a simple example, imagine one's wife type listaccounts in husband's wallet and read "Refund from backpage.com"

I think this is a real issue and should be reopened if it is not possible to delete those labels.

**Comment by laanwj** [comment]
Fair enough, but then the issue is not that 'a third party creates a label' but that the information is hidden and uneditable in the GUI. Labeling the refund is useful in practice.

Also: 
- if you use payment requests, the payment request itself will also be added to your wallet
- deleted/edited information may still be salvageable from unallicated blocks in the database

There is no expectation right now of privacy against people that can directly examine your wallet file.

> Just a simple example, imagine one's wife type listaccounts in husband's wallet and read "Refund from backpage.com"

In that case the way to hide it would be to use a second wallet, say, on an encrypted USB stick.

**Comment by luke-jr** [comment]
@breymoz Note that Bitpay did not generate the account or address themselves; that is just something built-in to the process of sending them a payment. Whenever you pay via BitPay (or anyone else using the payment protocol), you give them a refund address upfront in case they wish to return the funds.

**Comment by MeshCollider** [comment]
I don't think this needs to remain open considering the comments above
