### ISSUE TITLE
Script evaluated without error but finished with a false/empty top stack element

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#6496]
ERROR: CScriptCheck(): hash:7 VerifySignature failed: Script evaluated without error but finished with a false/empty top stack element

I keep getting these errors in the latest 0.11 bitcoin-qt. Each time it occurs, I need to manually get it to reconsiderblock for it to be able to continue again.

**Comment by rebroad** [comment]
@laanwj as a workaround for this, I have set up a script to monitor debug.log and issue the reconsiderblock command. Do we have any idea of the root cause for this though? How come there appears to be this random element to the validation?

**Comment by sipa** [comment]
@Rebroad my best guess is that either your CPU overheats or becomes
otherwise less stable under constant high load.

It's possible that 0.11 makes this more obvious, as it does much fewer disk
writes due to better caching, resulting in higher constant load on the CPU.

Have you tried running with -par=1? That tends to reduce such errors.

**Comment by rebroad** [comment]
@sipa yes, I am already running with par=1

**Comment by laanwj** [comment]
I've not seen any other reports of this issue, so it is likely a problem with your hardware or setup. Closing.

**Comment by PhoenixFS** [comment]
Hi! Is this thread closed... forever? I’m having the same error with Electrum 3.0.5.   Does any of this make sense to anyone?
