### ISSUE TITLE
Warn on the effects of turning prune on

### ISSUE THREAD

**Issue by jdevora** [bitcoin/bitcoin#6516]
I was having issues with the hard drive space on my laptop and decided to give it a try to the new prune option.

I read that you couldn't use your wallet if you turned "prune" on, but I wasn't aware of the real consequences.  If you wanted to use your wallet again, you had to download the WHOLE block chain again and for my 2 Mbits/s connection, that means DAYS....

I would like to suggest to include a WARNING message, explaining that you would lose access to your wallet until you download the whole blockchain again  if you turn PRUNE on.

**Comment by jonasschnelli** [comment]
In bitcoin core v0.11.x the wallet will be auto-disabled when using -prune. However the current master and therefore the upcoming version 0.12.0 will allow to run a wallet in pruned node.

**Comment by ajweiss** [comment]
While the wallet issue you hit will be fixed in the next version, there are other side effects to turning on pruning.  There's an open discussion in #6461 as to how to best handle this in the GUI case (I like Luke's suggestion) but it's still not totally clear how to warn appropriately in the daemon/config-file/headless non-GUI case.

Perhaps some sort of two step process for the initial conversion might make sense as well as some updated terminology?  (ie: instead of pruned nodes, we call them half nodes or lightweight nodes or something that would make people consider pruned nodes as something actually different from a fully validating node with the full blockstore).  This might make it more intuitive for people to go read up on what's going to happen if they "convert their full nodes to half nodes" so that they fully understand the ramifications of their actions before they run with something like -converttohalfnode to proceed with the operation...

**Comment by laanwj** [comment]
In retrospect it would have been preferable to **fail** when using prune without `-disablewallet`, instead of silently disabling it. That would have forced the user to think about this.
As usual, mentioning it in the release notes is not enough.
But it's too late for regrets about that. 0.12 will have full wallet support with prune.
