### ISSUE TITLE
Implement NODE_BLOOM, ability for nodes to disable serving BIP37 SPV clients.

### ISSUE THREAD

**Issue by evGUzQIEQaL4** [bitcoin/bitcoin#6578]
High reliability nodes running mining pools and merchants have no need to serve BIP37 bloom filters. Implementing the unnamed NODE_BLOOM BIP will allow nodes to display their willingness (or not) to serve SPV clients in this manor, allowing BIP37 functions to be disabled protects from [major denial of service problems](https://github.com/petertodd/bloom-io-attack). Not all nodes today support BIP37  and it is a hindrance that there is no signaling possible for it. 

http://sourceforge.net/p/bitcoin/mailman/message/31298904/

The service identifier would need to be altered from the original specification by @petertodd  as the specified bit has since been used by NODE_GETUTXOS in another client.

**Comment by petertodd** [comment]
Note that since the last time NODE_BLOOM was proposed, the landcape for (lite-)SPV clients has changed significantly in a few key ways:

1) @mikehearn's [Cartographer](https://github.com/mikehearn/httpseed) seed protocol has been created and deployed in production to allow (lite-)SPV clients to find nodes supporting arbitrary service bits, notable NODE_GETUTXOs.

2) Bloom filter usage has declined significantly, as lite-SPV clients are moving towards using centralized, trusted, servers run by the wallet authors. For instance [Mycelium](https://github.com/mycelium-com/wallet), [GreenBits](https://github.com/greenaddress/GreenBits), [AirBitz](https://www.reddit.com/r/Bitcoin/comments/3etohn/whats_wrong_with_breadwallet/ctirou5), and [Electrum](https://electrum.org/#home) all fall in this category.

3) Bloom filters [have been found](http://eprint.iacr.org/2014/763) to have severe privacy issues, offering essentially no privacy at all. Under many threat models a small number of trusted servers pose less privacy security risk than connecting to random, sybil-attackable, peers using unencrypted connections and giving those peers very accurate wallet contents information.

4) Finally, Bloom filters still have [unsolved DoS attack issues](https://www.reddit.com/r/Bitcoin/comments/3hjak7/the_hard_work_of_core_devs_not_xt_makes_bitcoin/cu9xntf?context=3), that will get significantly worse under upcoming blocksize increase proposals.

Re: service bit identifier, I'd just pick 1<<3

**Comment by dcousens** [comment]
So can we make serving them optional?

**Comment by petertodd** [comment]
@dcousens That's exactly the idea, which in turn gives a clean upgrade path as better solutions are found in the future.

**Comment by dcousens** [comment]
Also, what is the contents of 
http://sourceforge.net/p/bitcoin/mailman/message/31298904/ for those of us that have sourceforge.net blocked?

**Comment by petertodd** [comment]
@dcousens Here you go: http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2013-August/003158.html

**Comment by petertodd** [comment]
Incidentally, in case @evGUzQIEQaL4 is actually Mike and intends to troll this issue on reddit, I'll let someone else actually make a pull-req implementing this, because one of Mike's favorite schticks is "OMG THE CORE DEVS HATE SPV!!!" - never mind that I spent about 50% of the past year's billable hours working on figuring out how to add SPV to colored coin tech...

**Comment by evGUzQIEQaL4** [comment]
@petertodd Hate SPV is probably too strong, dislike not having an option in the core client is a better description. A number of nodes on the network (all pseudonode instances for example) already flat out ignore filterload commands, which happens to denial of service attack BIP37 wallets because they just don't expect that. NODE_BLOOM just allows nodes to inform BIP37 clients that their response to P2P commands just isn't going to arrive. BitcoinJ already has a hardcoded HTTP seed which only gives out peers responding to NODE_GETUTXOs, I don't imagine there will be any problem adding a check there for another bit. Leaving the commands enabled is just not a sensible idea given the attack surface.

**Comment by petertodd** [comment]
@evGUzQIEQaL4 Well, like I say, Mike frequently lies about this in public.

Oh, is that HTTP seed - the Cartographer protocol right? - implemented by default in BitcoinJ right now? That certainly negates most objections - lots of GETUTXOs nodes to go around these days, and I believe Gavin has said a few times that he supports separating the various functionalities of different types of nodes.

**Comment by evGUzQIEQaL4** [comment]
@petertodd Yes, it's in BitcoinJ, even preferred over DNS seeds in some circumstances.

https://github.com/bitcoinj/bitcoinj/blob/6f03669fbd6c368961a25dfd772751d1ca2a1b5b/core/src/main/java/org/bitcoinj/params/MainNetParams.java#L80-L88

**Comment by petertodd** [comment]
@evGUzQIEQaL4 Looks good. Interesting that there is no similar seed for testnet3: https://github.com/bitcoinj/bitcoinj/blob/6f03669fbd6c368961a25dfd772751d1ca2a1b5b/core/src/main/java/org/bitcoinj/params/TestNet3Params.java @mikehearn How do people do GETUTXO testing on testnet?

Not a big issue; I'm quite happy to add appropriate code to my DNS seed to ensure only NODE_GETUTXO nodes are returned.

**Comment by evGUzQIEQaL4** [comment]
@petertodd Slightly problematic is that BitcoinXT stomps on the protocol version bump, it alters to 70010 presumably as "20GB is cool for the message size". I suppose NODE_BLOOM would need to be higher than that, like 70037 or something? It would mean that BitcoinXT nodes could send addr and other messages larger than the message size Core limit and be DoS banned for it, but I don't see how to get around that.

**Comment by evGUzQIEQaL4** [comment]
Protocol version will also need to deviate slightly from the BIP proposal, 70002 collides with the XT attempted fork. Where protocol > 70037 NODE_BLOOM would be set for nodes which allow BIP37 requests, with any filteradd, filterload or filterclear message to a node without NODE_BLOOM set resulting in a DoS score increment.

**Comment by TheBlueMatt** [comment]
See branch at https://github.com/TheBlueMatt/bitcoin/tree/bloom. Will create a pull request after posting a BIP.

**Comment by evGUzQIEQaL4** [comment]
@TheBlueMatt perfect, the service bit needs to be 1 << 3 though, 1 << 2 collides with the bit for NODE_GETUTXOS.

**Comment by evGUzQIEQaL4** [comment]
@TheBlueMatt Perfect.

**Comment by evGUzQIEQaL4** [comment]
Closing, discussion should move to implementation at #6579.
