### ISSUE TITLE
Obfuscate database files

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#6613]
To avoid problems on Windows with Anti-Virus software, there needs to be an option to obfuscate the keys/values written to the database files, especially the UTXO database.
See #4069 for discussion.

It should be really simple, just enough to make it useless to put AV signatures in transactions. E.g. generate a random key on first start, store the key in the database, then XOR all subsequent data read/written to the database with that.

Possibly this obfuscation could include the block files as well, although I've never heard of problems with those - the most likely explanation is that AV software doesn't consider files above a certain size.

**Comment by jgarzik** [comment]
+1

**Comment by jamesob** [comment]
I'd like to try tackling this one, but I'm a little confused about where to start. Is the basic approach here something like

- On construction of `CCoinsViewDB`, check `db` to ensure that some value exists under key `xor_obfuscate` (or similar); if not, randomly generate one and write it to `db`
- On `CCoinsViewDB::BatchWrite()`, use `db.Read('xor_obfuscate')` to XOR the value of the serialized `Coin` objects being written
- On `CCoinsViewDB::GetCoins()`, use the `xor_obfuscate` value to reverse the XOR in `BatchWrite()`
- Add a flag to disable obfuscation

Does that sound like the right tack, or am I off?

In terms of testing, it looks like we'd get some incidental coverage out of `test/coins_test.cpp`, but are there any supplemental testcases that should be written?

**Comment by luke-jr** [comment]
Where are you handling un-obfuscated reads (eg, those written with older versions) after initialising the xor_obfuscate key?

**Comment by dcousens** [comment]
Concept ACK

**Comment by sipa** [comment]
jamesob: I would implement it at the LevelDB wrapper layer, rather than
CCoinsViewDB, as that would be more generic and IMHO easier.

The xor value could be cached inside the wrapper object - there is no need
to read it over and over again. You'd read it when opening the database,
and if it doesn't exist, generate and write it.

As Luke mentions, you also need to deal with non-obfuscated values. I
suppose we can institute a rule that a key value cannot start with a null
byte, and then store obfuscated values using (nullbyte + key) as key.
LevelDB is efficient for large amounts of keys that start with the same
sequence of bytes, so this would not hurt storage. You do need some
mechanism for erasing the old unobfuscated key when the new one is written.
This may have some performance impact...

Also, would it be overkill to use AES-CTR instead?

**Comment by jamesob** [comment]
@luke-jr @sipa good points, thanks.

@sipa, I think given the discussion in #4069 AES might be more than we need right now, and definitely has different performance characteristics than XOR does. Maybe something like that will be called for down the road, but for now it seems like an XOR should do the job.

It would be nice if we could somehow indicate obfuscation in the value itself, so that way we won't have to do two reads (and a potential write) for correction, but I think that may be a little too tricky, and we should just keep this as simple as performance constraints will allow.

Should we generalize the the obfuscation mechanism to the `CLevelDBWrapper`, maybe adding an `obfuscate` bool parameter to its constructor? or should we keep this fairly contained as a one-off solution for `CCoinsViewDB`? If anyone has any strong opinions, I'd like to hear them. Otherwise I'm going to move forward with a draft of the more general approach.

**Comment by laanwj** [comment]
> Where are you handling un-obfuscated reads (eg, those written with older versions) after initialising the xor_obfuscate key?

I'd say: make a database either obfuscated or not obfuscated.  Partially obfuscated databases are as incompatible with older versions as completely obfuscated ones, so there is no use for the middle road.

A new database would be 'born' obfuscated. An old database would be kept unobfuscated unless the user gives a command line option to obfuscate, which would obfuscate the entire database in one go in an upgrade process. This loses backward compatibility.

The two cases can be distinguished by the presence/non-presence of the obfuscation key, or e.g. add a MIN_VERSION like in the wallet. I think this makes implementation a lot easier and less error-prone.

> Also, would it be overkill to use AES-CTR instead?

As this is meant as a fast, lightweight obfuscation mechanism, using AES seems like overkill. The goal is to avoid trivial signature matching. I don't see what using a stronger crypto-system would add.

**Comment by jamesob** [comment]
@laanwj any examples of "upgrade processes" in the codebase that I can reference for this implementation?

**Comment by pstratem** [comment]
@sipa "LevelDB is efficient for large amounts of keys that start with the same sequence of bytes, so this would not hurt storage."

Does leveldb merge prefixes or something?

**Comment by sipa** [comment]
@pstratem Yes.

**Comment by pstratem** [comment]
@sipa it looks like there are already some special keys in the chainstate database?

**Comment by pstratem** [comment]
@laanwj There's certainly a disadvantage to not supporting mixed obfuscation databases.

Specifically if this is switched to the default then everybody is going to need to do the upgrade procedure, which is potentially slow and expensive.

**Comment by sipa** [comment]
@pstratem What special keys?

**Comment by pstratem** [comment]
@sipa 'B' is the best block 'l' is the last block

Everything else seems to be prefix || hash -> value

**Comment by sipa** [comment]
All keys are serialize(something), whether that something is a character or something more complex.

**Comment by jgarzik** [comment]
Transition thinking...
* Mixed obfuscation creates a mixed situation that lingers forever.
* Mixed obfuscation does not eliminate the problem for a user, even after the user upgrade.
* A one-time upgrade is painful only if done in the foreground

**Comment by pstratem** [comment]
@sipa right but the serialization of a single charater is ... a single character

**Comment by pstratem** [comment]
@jgarzik The upgrade being done in the background seems optimal.

**Comment by sipa** [comment]
Doing this in the background is pretty hard, as you need to prevent writing entries that a concurrent modification may be updating.

**Comment by jgarzik** [comment]
@sipa Then don't do it that way.  You also said -reindex was hard :)

e.g. create a unified view of new + old database; old db under the hood becomes read-only, all updates go to new db.

There are other approaches as well.

**Comment by sipa** [comment]
@jgarzik I agree, a partial state does not fix the problem. A UTXO entry that is not touched is never overwritten, so creating a UTXO with a virus signature in it, and then never spending it would leave AV software detecting the file as problematic until reindex anyway.

**Comment by sipa** [comment]
@jgarzik Didn't say it was impossible, but it's a non-trivial thing to do that requires careful testing (UTXO database errors can lead to consensus failure). I think for now I'm perfectly fine with an opt-in approach. We can add updating later.

**Comment by jamesob** [comment]
So: opt-in, atomic obfuscation for now, more sophisticated obfuscation-by-default scheme later?

**Comment by jgarzik** [comment]
IMO:
- NAK mixed obfuscation - all or none is cleaner, less complex and better reflects the future
- if all-or-none, obfuscation could easily become encryption with a swap of layers, without touching low-level db or upper-level bitcoin.
- turn on by default for new db or -reindex

**Comment by sipa** [comment]
Enabling by default on -reindex should be easy to do in this PR.

**Comment by sipa** [comment]
Another issue: we need a clean failure when downgrading. I don't think the chainstate has a version number, so that's problematic.

**Comment by jgarzik** [comment]
Presumably the failure mode is database-appears-totally-empty?

**Comment by sipa** [comment]
Hmm, no, it would read random garbage and try to deserialize it.

**Comment by jamesob** [comment]
What's the usecase for a downgrade? When would that actually happen?

**Comment by sipa** [comment]
People tend to try a new version but then find a problem, so need to revert to an earlier version of the client.

**Comment by gmaxwell** [comment]
My thought was that if there is no obf key, we set one and set it to all zeros.  Tada. Everyone is obfuscated.   On reindex we should reset the key.    Downgrade works fine, so long as you haven't reindexed since.  If you do downgrade after one you'll fail right away, on the chainstate check ... and it'll tell you to reindex!

**Comment by pstratem** [comment]
@gmaxwell Ha that's a nice solution.

**Comment by jamesob** [comment]
@gmaxwell very slick. :)

**Comment by dcousens** [comment]
@gmaxwell ha, :+1: good solution.
