### ISSUE TITLE
[univalue] Different get_int() behavior versus json_spirit

### ISSUE THREAD

**Issue by jgarzik** [bitcoin/bitcoin#6765]
IRC:
"listunspent 0 9999999999 [stuff]  fails because 9999999999 is too big."

Both json_spirit and univalue call .get_int() from listunspent(), and .get_int() method is defined to return 'int' in both cases.

It appears the out-of-range behavior is different for univalue, which is noticeable via RPC user interface.

**Comment by jgarzik** [comment]
A patch: http://gtf.org/garzik/bitcoin/patch.univalue_get_int

**Comment by laanwj** [comment]
How does json_spirit handle out of range integeres?
I'd say there is only one sane way to handle it: reject the input?

**Comment by laanwj** [comment]
static_cast will just *truncate* the number to 32 bit, NACK on that

**Comment by jonasschnelli** [comment]
Agree with @laanwj. What about if UniValue would throw an exception in case of a detected out-of-range int?

**Comment by laanwj** [comment]
@jonasschnelli That's what it does now, and is tested behavior. And the attached patch disables it.

**Comment by jgarzik** [comment]
@laanwj The patch precisely mimics json_spirit behavior, thus restoring the old RPC interface behavior.

The user (@gmaxwell) complained about the exception being thrown, as that causes a trickle down impact of making a previously-working RPC call now not work.

If we are to keep the new behavior, which _is cleaner and more type specific_, every .get_int() must be audited.

In theory the current get_int() call inside the RPC function is wrong, and an audit will fix that and any others.

**Comment by laanwj** [comment]
The old situation was clearly wrong to me - large numbers should not be silently ignored, let alone silently ANDed with `0xffffffff`.

This was a much larger risk than just rejecting the value. @gmaxwell was lucky that his arbitrary big value mapped to another large number in 32 bit integers. It could just as well have mapped to 1, or even -1 instead. The result would be much more "WTF" than a 'number too large' error.

The error signals a clear wrong input. Yes, this may mean people have to change cases where this happens in their interface, but this may help them isolate pesky hidden bugs. 

The new behavior is more strict but not *wrong* in any way. Working around it by restoring the previous broken behavior is not acceptable to me. If this means auditing uses of get_int, that is what should be done.

**Comment by dcousens** [comment]
NACK on restoring the broken behaviour.
Agreed with @laanwj that just because it might break an existing API, doesn't mean we should revert.

@jgarzik if you feel strongly,  maybe it should be noted in a README/CHANGELOG?

[xkcd](https://imgs.xkcd.com/comics/workflow.png) comes to mind.

**Comment by jgarzik** [comment]
This issue is not resolved.  Do not close until it is solved / release noted / audited.

**Comment by laanwj** [comment]
I don't regard it as an issue.

**Comment by jgarzik** [comment]
(pasting from IRC for the record)
The issue is
* user visible breakage occurred
* it was noticed in the field by users
* other get_int() calls should be checked for further unexpected behavior changes

I agree it is an improvement but we cannot simply assume it is a bug-free improvement.

**Comment by btcdrak** [comment]
NACK. I agree with @laanwj

**Comment by sipa** [comment]
@gmaxwell What is your expected behaviour here?

**Comment by jgarzik** [comment]
Folks, this is an issue not a PR.  There is nothing to NAK :)

This issue is open until the user visible breakage is fully analyzed and documented ,which I've assigned to myself.

**Comment by gmaxwell** [comment]
We have APIs where there is no way to provide an 'infinite' but where one is really expected.  Examples are the depths that listunspent and list transaction go back.  The positional arguments _require_ you to provide something in these places, even when you really just want the default.

As far as I can tell, what just about everyone does is mashes the button to get a really big good-as-infinite value. So far so good.  They bake these values into their command-lines and scripts etc. And the new behavior now fails with these values that worked before-- just because they hit 10 nines instead of 9.

For most of these things, I think saturating is appropriate. Yes-- it's not the most "type safe" behavior (though a saturating integer is a type that these could be defined as!), but JSON is not type safe. This was also the previously effective behavior. 

Consequence of not doing something here is that the interfaces becomes harder to use-- because now you have the mental load of the largest permitted value. Consequence of saturating is that users who've become confused and sent in some totally crazy wrong field and up getting the "effectively infinite" default behavior instead of what they really wanted.

**Comment by laanwj** [comment]
I think saturation would be good in this specific case, as it concerns a limit (and max is more-or-less infinite). It should definitely not be the default behavior of `get_int`. But adding a `get_int_saturate` (@gmaxwell's idea) and using it in listunspent would be a valid option.

**Comment by jgarzik** [comment]
Sufficiently old and undesired - closing
