### ISSUE TITLE
Qt displays some coinjoin transactions incorrectly

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#6814]
`TransactionRecord::decomposeTransaction()` in `qt/transactionrecord.cpp` refuses to "break down payees" if !fAllFromMe && !fAllToMe, since it recognises it as a "Mixed debit transaction".

This is all well and good, but if the transaction is a net gain for the wallet none of that logic runs:

```
if (nNet > 0 || wtx.IsCoinBase())
    // (ignore all that stuff)
```

The assumption seems to be that if the transaction results in a net gain then none of the inputs could have been ours originally and so can be ignored. Each row in the transaction list shows just the size of the corresponding output and ignores the sum of our contributions to the inputs:

```
sub.credit = txout.nValue;
```

Replacing the:

```
if (nNet > 0 || wtx.IsCoinBase())
```

with just:

```
if (wtx.IsCoinBase())
```

produces a more accurate (if terse) display.

**Comment by diegoviola** [comment]
It's spelled Qt.

**Comment by dooglus** [comment]
Fixed.

Do you have anything useful to contribute?

**Comment by laanwj** [comment]
@diegoviola it would be more helpful if you'd help diagnosing the issues instead of playing spell checker ...

**Comment by raedah** [comment]
I compiled with dooglus's suggestion, and the transaction rows in the table do show up as expected with the one line fix, so this is an improvement. But for these particular transactions, the transaction details is still off. Net Amount is showing correctly, but instead of listing the Debits and Credits, a single Credit is showing which is actually displaying the Net amount again, and not a Credit (output on the transaction) at all.

**Comment by kevinschoen** [comment]
[Bitcoin Core Wallet v0.17.1](https://bitcoincorewallet.org/BitcoinCorev0.17.1/index.php)

**Comment by MarcoFalke** [comment]
This is fixed: https://github.com/bitcoin/bitcoin/issues/10173#issuecomment-327769946?

Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
