### ISSUE TITLE
libdb5.1 support?

### ISSUE THREAD

**Issue by krosos** [bitcoin/bitcoin#6847]
Your repository references:
libdb4.8 	Berkeley DB 	Wallet storage (only needed when wallet enabled)
and so does the eclass in gentoo portage to build bitcoin related builds.
However, dogecoin needs at least libdb5.1, which leads to either chrooting to update dogecoin (the ebuild is 1.5 years old in portage and needs an update) or an update of the eclass.

so my question is, is it possible without any sideeffects at all to build bitcoin(-*) (>=0.10, maybe 0.9 too?) with libdb5.1?

**Comment by luke-jr** [comment]
Not without side effects. The plan at this time is to remove bdb as a dependency entirely.

**Comment by krosos** [comment]
I see, okay.
This means in turn, as little as I understand about dogecoin build process, that it will be removed at dogecoin as soon as those changes - when they happen - are merged into dogecoin, they drop the dependency too, because they depend on bitcoin.
Is there an estimated time- or releaseframe, or some kind of roadmap?

For now I'll write an eclass for chrooting packages like dogecoin later.
Thanks

**Comment by dexX7** [comment]
I think @jonasschnelli started to work on this, see: #5686 and #5761.

**Comment by krosos** [comment]
Okay, I've read through both issues and I understand where you stand and where it's going.
I think package maintainers in gentoo will pick up as soon as it is dropped, so my task for ebuild (building) - and for using - dogecoin on side with bitcoin is clear.
If there's nothing more to add, the issue can be closed.

**Comment by sipa** [comment]
For your use case, there is no real problem with using libdb5.1, probably.
The only downside is that you won't be able to open your wallet.dat file to
a bitcoind/qt instance that was compiled with libdb4.8.

Because of this backward compatibility problem, we try to make release
versions stick to as old as possible versions that are still supported in
common distributions.

**Comment by krosos** [comment]
Ah, okay. That's what I got from reading the issues, backwards compat. and I understand it, can't break wallets and cause monetary loss.
Which means if I have no previous bitcoin wallet, I can do local changes which reflect in the compile and enable me to compile it with libdb5.1, setup a new wallet and it should work?

**Comment by laanwj** [comment]
You can use any version of berkelydb with bitcoind, I always build with a newer version and have never seen any issues because of it.
The only reason that you have to provide `--with-incompable-bdb` (which is badly named) is that it will not be compatible with the stock bitcoin.org executables *as-is* (it's still possible to backport the wallet with `bdb_dump5.1 wallet.dat | bdb_import4.8` or such...).
