### ISSUE TITLE
UndoReadFromDisk: Checksum mismatch

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#6923]
As part of serious hammering as part of #6917 testing I think I found a new crash corruption issue (possibly a rare one).

The leveldb database was still OK, however the start-up check fails in a new place: in the undo data check:
https://github.com/bitcoin/bitcoin/blob/master/src/main.cpp#L1494

Haven't analysed the details but will keep the data around.

**Comment by laanwj** [comment]
According to @gmaxwell in #6917:
```
Difference in VM flushing behavior, I guess. We appear to be missing a FileCommit in UndoWriteToDisk-- I think we need to have synced the blocks and undo before calling the insert.

It would probably be better for performance if it wrote the block then undo, then did the syncs on both however.
```

**Comment by sipa** [comment]
Will have a look.

**Comment by sipa** [comment]
We don't need a FileCommit in UndoWriteToDisk, because we always call it via FlushBlockFile 1) before writing the block index data that refers to it (in FlushStateToDisk) and 2) when transitioning to a new disk block file (in FindBlockPos).

However, when reindexing, fKnown is set to true in FindBlockPos, so this flush is not called. That is the correct behaviour for the block files (which aren't being changed in a reindex), but incorrect for undo files (which are being rewritten).

I'm writing a fix.

**Comment by laanwj** [comment]
Looking at the debug.log I saved here I noticed something peculiar:
```
0001b070  65 3d 33 2e 39 4d 69 42  28 39 37 37 74 78 29 0d  |e=3.9MiB(977tx).|
0001b080  0a 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
0001b090  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00030d40  32 30 31 35 2d 31 30 2d  33 31 20 31 33 3a 35 31  |2015-10-31 13:51|
```
The crash also left a whole block of \x00 bytes at the end of the log. I suppose the space was allocated but the data wasn't actually written yet. It is to be expected as we don't ever sync the debug log to disk (just flush it, which flushes only application-side buffers), but this may give further insight into the kind of corruption.
