### ISSUE TITLE
Is the InitialBlockDownload() check in 'getheaders' too strict?

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#6971]
I was trying to sync a new node from an almost-synced node, and somehow it was ignoring the other node.

Some debugging traced the problem to: https://github.com/bitcoin/bitcoin/blob/master/src/main.cpp#L4307

I understand the rationale, of course, it makes no sense to share blocks if we're at the beginning of the chain. But we define 'initial block download' as 'hasn't received a block in the last 24 hours'. So it is also on while catching up.

Nodes which are almost-synced could in very well partake in serving old blocks, or am I missing something?

**Comment by laanwj** [comment]
Another option, which just solves my immediate problem, would be to override this check for whitelisted peers.

**Comment by sdaftuar** [comment]
The motivation for this restriction was to avoid responding to a getheaders when your chain might deviate from the checkpointed chain, because your peers that have the checkpointed chain will disconnect you.  (After changing the download logic to call getheaders on inbound peers, I wanted to avoid a situation where a newly syncing node could be partitioned from the network by a malicious peer that served it a bogus headers chain.)

This check is more restrictive than is needed for that -- I think I did it this way because I didn't want to introduce yet another function for determining "synced-ness" (or a new place in the code that uses  checkpoints).  Also, I think block relay only happens if you're out of InitialBlockDownload, so it didn't seem unreasonable to use it here as well, but we could loosen things up if we wanted to.

I assume the use case you're going for is to have two nodes be able to sync even if disconnected from the rest of the network?  If so the whitelisting approach seems reasonable to me.  As a minor nit, I think the whitelisting test gets the property backwards -- really what you'd want is to eliminate the restriction if your peer has whitelisted you, rather than the other way around, since then you could respond without fear of being disconnected -- but since it's likely both nodes are under common control anyway, it seems a minor issue.

Will review the PR.

**Comment by laanwj** [comment]
> I assume the use case you're going for is to have two nodes be able to sync even if disconnected from the rest of the network?

Right. I have a node A that isn't catched up fully, and node B that I want to sync from node A. B only connects to A. A is currently not connected to the internet, to make sure B gets all available I/O bandwidth.

**Comment by laanwj** [comment]
Apart from my own issue, I'm also somewhat concerned that this check will reduce the amount of nodes that are willing to serve blocks. But that is probably misguided.
Any node that usefully contributes to the network will be synced up to within 24 hours from the tip, I suppose...

**Comment by sdaftuar** [comment]
Yeah, I can't think of a common scenario where you'd start up a node and find an outbound peer that wasn't already close to caught up, and therefore unable to sync.  But if you wanted to loosen this up somewhat I think it'd be fine to do so.

Regarding the checkpoints, yes presently once we have the checkpointed headers, we will fail (see `CheckIndexAgainstCheckpoint`, called from `AcceptBlockHeader`) when trying to validate a header that forks prior to the last checkpoint, and we assign DoS points.

I think we're in the process of slowly loosening this up (eg with #5927 which will be new for 0.12), but I don't have a clear picture of the roadmap for doing so.  I do think that if you get invalid headers before the checkpointed chain (block height 295000 is the last checkpoint) that the node is either trying to attack you, or -- maybe more likely -- it has been attacked itself.  It's this latter point that worries me somewhat about not merging some kind of fix for 0.12 to prevent an attacker from partitioning the network now that #5927 is in (see https://github.com/bitcoin/bitcoin/pull/5927#issuecomment-152229444).

**Comment by luke-jr** [comment]
This also breaks rpc-tests/script_test.py, but is "worked around" by the whitelisted hack. IMO, that's pretty ugly. :(

**Comment by rebroad** [comment]
I think this issue should be re-opened, as it's still an issue for non-whitelisted peers. Why not make it only return is the active tip is below the last checkpoint?
