### ISSUE TITLE
Bitcoin GUI is not built when only qt4 is installed

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#7189]
From IRC:

@phantomcircuit: @jonasschnelli, ./configure doesn't detect qt4 on my debian jessie system 
i had to manually specify --with-gui=qt4

**Comment by MarcoFalke** [comment]
We switched to qt5 by default (#6938) and don't fall back to qt4, it seems.

**Comment by jonasschnelli** [comment]
I tend to feel that this is the correct behavior. We kind of deprecated Qt4 and it might lead to graphical issues. Qt5 is the environment that allows us to compete with other GUI apps.

IMO a manual -with-gui=qt4 in case of missing qt5 is okay because it makes user aware that they don't use the recommended dependencies.

**Comment by laanwj** [comment]
I agree that Qt4 is on its way out, but this was not the intention.

I've only changed the default, not the fallback mechanism. It could be that something broke there though. I'm not really good with autotools. @theuni can you take a look?
