### ISSUE TITLE
Debug window, Peers: appears connected when its not

### ISSUE THREAD

**Issue by raedah** [bitcoin/bitcoin#7195]
1) Connect two bitcoin-qt v0.11.2 instances together on a local network.
2) Turn off the router.
3) See debug window, peers, shows peer still in the list, with a very low ping time. View details and see that the Last Receive time is counting upward.
4) Plug back in the router, peers disappear from list as soon as network connectivity is reestablished.

Peers appearing connected with a low ping time, even though nothing is being received, is misleading to the user. This was tested on linux.

**Comment by laanwj** [comment]
A) Due to how TCP works, it is impossible to instantly detect the router disconnecting. It will just assume a temporary delay. It will instantly detect (and remove the entry) when connectivity is reestablished when  receives a RST as the other side (or router in case of NAT) doesn't know of the open connection.
B) Ping time can only be updated if a ping is in progress.

Though it could be improved somewhat: right now I think the ping time is only updated if the `pong` message is received, it could instead report the status of the last ping in progress (and like LastReceive count up if there is no answer).

**Comment by raedah** [comment]
> it could instead report the status of the last ping in progress (and like LastReceive count up if there is no answer).

I agree, that would do the trick.

**Comment by MarcoFalke** [comment]
If you select the node, it will show the last send/receive
