### ISSUE TITLE
bitcoin-qt transaction view should have default sort order by date

### ISSUE THREAD

**Issue by raedah** [bitcoin/bitcoin#7198]
Currently it is using the first column which is just a checkbox, and it causes failed transactions (such as double spend attempts) to always be at the top of the list. Default sort by date descending is the expected behavior.

**Comment by laanwj** [comment]
This behavior is intentional. Unconfirmed and failed transactions are supposed to be sorted to the top to signal something went wrong.
(what is missing, though, is a way to remove them. There are plans to add this in a future version)

Also date order is unreliable and ambiguous. Bitcoin transaction, in general, have no date field, so what the UI and RPC show is best effor' guesswork.

**Comment by raedah** [comment]
Running 0.12rc2, and noticed that conflicted transaction are now not appearing at the top. They are appearing in Date order. But this appears to be erroneous as, as its still the first column (transaction status) that is the selected sort order. Potentially more problematic, is that even clicking the first column will not sort the conflicted transactions to the top of the list, so manually going through the list is the only way to locate them. This became apparent only after doing a -rescan.

**Comment by raedah** [comment]
After reverting back to 0.11.2, with the automatic rescan completing, the behavior now remains the same in 0.11.2 as it was in 0.12rc2. But this behavior didnt occur until after having tested 0.12rc2. I did many rescans when on 0.11.2 and the behavior was never like this before. The conflicted transaction was sitting at the top of my transaction list for the last two months, and now it is no longer at the top.
