### ISSUE TITLE
Add BIP 101

### ISSUE THREAD

**Issue by specialen** [bitcoin/bitcoin#7202]
Bitcoin passed testing by Satochi with 340 GB blocks https://imgur.com/Tv3cNqc Bitcoin was made for this and you hold it back by greed.

**Comment by gmaxwell** [comment]
I think it's safe to say at this point that this project has rejected
BIP-101.

Of course-- we haven't rejected evolving Bitcoin's capacity.
I posted a capacity plan at
 http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-December/011865.html
which you may be interested in.

As far as that testing, what you're pointing to is a set of fraudulent
claims [*] written by someone who was very concerned with telling people
what they wanted to hear, and not very concerned with the complete set
of consequences.  Why? We may never know but perhaps it was because
in his planning success was the only thing he could see.

(See also: http://www.newyorker.com/business/currency/bizarre-saga-craig-wright-latest-inventor-bitcoin )

If you were already aware of these things, then I must ask you to please
not waste our time in the future.  I have no interest or ability to
personally convince every confused person in the world about this or
that fine technical detail, and no one else does either.  We need to
make progress on the paths we believe are best right now and not allow
unrealistic efforts to "fix" things forever to stall work indefinitely.
If you support that, you're welcome to join in.  If you don't, our work
has a free license that allows you to forge your own way.
