### ISSUE TITLE
"Direct access to weak symbol" warning in gitian macosx build

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#7337]
Not sure how serious this is, but while buildilng 0.12 in gitian a flood of the following errors appears:

```
ld: warning: direct access in HTTPReq_JSONRPC(HTTPRequest*, std::string const&) to global weak symbol UniValue::~UniValue() means the weak symbol 
cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in HTTPReq_JSONRPC(HTTPRequest*, std::string const&) to global weak symbol UniValue::~UniValue() means the weak symbol 
cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

**Comment by theuni** [comment]
This isn't a big deal but it is annoying. We had these in boost for a long time until visibility was fixed there. It's caused by not passing our visibility flags down to univalue.

There are 2 options here: pass our added flags down, or teach univalue about visibility. To be more specific, only the flags added inside of our own configure aren't passed along.
