### ISSUE TITLE
Missing new RPC calls in 0.12 release notes

### ISSUE THREAD

**Issue by promag** [bitcoin/bitcoin#7516]
In section `rpc-low-level-api-changes` there is no reference to, for instance, `fundrawtransaction`.

**Comment by laanwj** [comment]
Probably more than one:
<sipa> list of all new RPCs: disconnectnode, setban, listbanned, clearbanned, getblockheader, fundrawtransaction, estimatesmartfee, estimatesmartpriority, abandontransaction, importpubkey

**Comment by morcos** [comment]
I'm happy to write up some stuff for estimatesmartfee, estimatesmartpriority and abandontransaction, but I thought I had gotten some feedback that we didn't necessarily want to announce these things.  The first two because the API is still in flux, and I'd really like to announce abandontransaction, but some people objected because they don't think users should be doing that.

**Comment by laanwj** [comment]
Good point morcos.

It's not necessary to write a lot about them - the release notes are not a supplement for documentation, documentation should be found with `help <call>`. But mentioning adding them under "Low-level RPC API changes" makes sense.

If they're still experimental, one could add [EXPERIMENTAL] (same as Linux experimental features) or decide to withhold them from the notes completely, if that is an explicit choice and not just "we forgot".

**Comment by watashikokoto** [comment]
please check issue before 0.12

 https://github.com/bitcoin/bitcoin/issues/7535

thanks

**Comment by laanwj** [comment]
Closing - 0.12.0 final has been tagged, no longer possible to make changes here

**Comment by ruimarinho** [comment]
Just wanted to mention that when adding support for client libs even a small a reference for new or updated methods greatly improve this process.

**Comment by sipa** [comment]
The release notes for 0.12 can still be updated, but they're maintained in
master now (as we won't touch the 0.12 branch anymore).

**Comment by laanwj** [comment]
> Just wanted to mention that when adding support for client libs even a small a reference for new or updated methods greatly improve this process.

I agree. However, we cannot hold up the release because there are small open issues on the release notes. There was about a week time frame that someone could have picked this up.

(also, as @sipa says, the release notes *could* still be updated in master, see 0e3ccbfb26b11ea3d9ed7dfd39886d69097286e1. When I send out the release announcement mail I'll use the version from there)
