### ISSUE TITLE
0.12.0rc5 estimatefee 1 always returns -1

### ISSUE THREAD

**Issue by nomnombtc** [bitcoin/bitcoin#7545]
Hello,

I am not sure if this is on purpose or not, but it was working fine in 0.11.2
`bitcoin-cli estimatefee 1` always returns `-1` , higher values still work fine.

Bitcoind already runs since a few days so it should have enough info to estimate.

**Comment by morcos** [comment]
This is a known effect.  
estimatefee works by returning the lowest feerate such that 95% of recent transactions of at least that fee rate were confirmed within the target.  Before 0.12, the success threshold was 85% but this contributed to being too slow to react to changes in fee market conditions.

It is very difficult to have a fee which is high enough to confirm consistently in the next block, this is in part because of transaction propagation delay but mostly due to miners only recreating the block template periodically.

**Comment by nomnombtc** [comment]
Ok thanks for the explanation, this makes a lot of sense.
I guess I close the issue as it seems like expected behaviour.
