### ISSUE TITLE
rc5 release note credits typo?

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#7547]
https://github.com/bitcoin/bitcoin/blob/0.12/doc/release-notes.md

> Patick Strateman
> Patrick Strateman

So good they named him twice?

**Comment by fanquake** [comment]
There are multiple double naming occurrences in the credits, as it's it's just generated with a script that pulls names/handles from git commit history. Fixing it would require running through and matching "real names" to handles, and then figuring out which to remove, as some might prefer having their handle listed instead of their real name.

However obvious typos should probably be removed.

**Comment by laanwj** [comment]
This gets generated with a script.
And some of the almost-named-the-same people are actually different people, e.g. `Matt` and `Matt Corallo`.
But yeah this is an obvious one.

**Comment by laanwj** [comment]
Could make sense to unique-ify based on email instead of name next time. OTOH some people also have different mail addresses, especially if edited through the github interface.
If you want to be sensibly credited, use one git name, it saves a lot of trouble :-)
