### ISSUE TITLE
depends: Fallback mechanism may not be working properly

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#7627]
Today there was an issue with a corrupted boost download:
```
<MarcoFalke> of which: Fetching boost...
<MarcoFalke>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
<MarcoFalke>                                  Dload  Upload   Total   Spent    Left  Speed
<MarcoFalke>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
<MarcoFalke> 100   639  100   639    0     0   2017      0 --:--:-- --:--:-- --:--:--  2017
<MarcoFalke> sha256sum: WARNING: 1 computed checksum did NOT match
```
No indication of even trying the fallback download.

I already suspected this before with the fukushi.org certificate issue with libqrcode. The download was failing due to a certificate issue and it wasn't even trying our fallback. At least it didn't break with the `wget` -> `curl` change :-)

**Comment by MarcoFalke** [comment]
Links to the failing fallback:
* wget: https://travis-ci.org/bitcoin/bitcoin/jobs/112846086#L4033
* curl: https://travis-ci.org/bitcoin/bitcoin/jobs/112855470#L831

**Comment by theuni** [comment]
The issue here is that the download apparently succeeded. I'm not sure it makes sense to retry in case the hash doesn't match, seems quite unlikely that a subsequent immediate retry would work. Maybe there's an obvious case I'm missing, though?

Since it's boost, I'd say it's likely that sf.net had one of its "I'm going down but not throwing 404" moments.

**Comment by laanwj** [comment]
> I'm not sure it makes sense to retry in case the hash doesn't match, seems quite unlikely that a subsequent immediate retry would work

Right - It shouldn't retry the same location again, but it can try the fallback URL, which should still have the uncorrupted file.

**Comment by theuni** [comment]
Heh right. Not sure where my mind went there.
https://github.com/theuni/bitcoin/commit/59dacc0e56ae22b2a3b72d58caeecf082e1a59c6 should fix. I'd like to hold off on merging that until I can fix a few other little things while I'm in there though, since each touch of that file should trigger a rebuild of everything.

Won't be able to get to it until after MIT. No problem if you'd rather not wait. Though I suspect you'll be headed there soon too :)

**Comment by laanwj** [comment]
No hurry.
