### ISSUE TITLE
Strong Consensus-Driven Bitcoin

### ISSUE THREAD

**Issue by venzen** [bitcoin/bitcoin#7673]
Apologies for a non-technical post made to this list with the purpose
of congratulating the work done in Bitcoin Core.

I expreienced some time delay in getting this message posted due to the concerted efforts of a certain BTCdak who felt this encouraging message would be better suited to the shit-talking spew-breath at #bitcoin-discuss where I won't post because of the effluent manifested there.

Slap round your fucking head BTCdrak. You Andresen-legacy bossy man.

My message is:

For a change, a cool evening in the south of Thailand, with a new moon
encouraging introspection over the calm Andaman Sea.

Sincere gratitude to the core developers and all Core contributors.
Despite pervasive negative social mood towards this group and its
productive output, Bitcoin continues to improve in its security, the
efficiency of its network and its prospects for the future as Layer 1
of a thriving censorship-resistant asset-based economy.

Isn't it surprising how productive this space has become since the
departure of the disruptive Mike Hearn? R3 will discover that
blockchain is great - but impractical - without vested interest and
incentivised participation. Hopefully, habitual consensus breakers
such as Gavin Andresen will also, eventually, ostracize themselves
from this purpose-driven group. As always, continue proposing
innovative (even contentious) ideas, but campaign them at the peril of
your creditworthiness.

Please continue the endevour of making a defiant programmable money
that doesn't buckle to the demands of a failing credit-based economy
or the opportunistic business interests that serve it. Detractors,
such as Coinbase, are ultimately dependent for their survival on
Silicon Valley Bank - a satellite of the Fed - the antithesis of what
Bitcoin represents.

Regarding the invocation of ClassicCoin, my international base of
clients and I are committed to continue transacting on, and mining,
the Bitcoin Core blockchain, indefinitely. We do so because of the
fundamental value of the caliber of development happening in Core and
the innovation of Segregated Witness. As speculators, investors and
miners we welcome the latter-day fee increases and the fundamental
value embodied by network security and the Rule of Consensus.

You're doing great work here.

Long Live Bitcoin! Long Live!

best regards,
Venzen Khaosan

**Comment by paveljanik** [comment]
Looks like this is no issue in the reference client implementation and thus can be closed.

**Comment by jonasschnelli** [comment]
Agree with @paveljanik. Closing...

**Comment by laanwj** [comment]
Thanks for the encouragement! I tend to agree wholly with your message, it is the long game that counts, let's focus on the challenges ahead, instead of certain toxic personalities and short term Pyrrhic struggles.

Yes, you certainly had some difficulty posting this, sorry for that. @Btcdrak is not to blame for this, we have to be extremely strict with moderation. Due to previous waves of trolling, sockpuppeting, in every discussion venue that has remotely to do with bitcoin, we have to make sure that channels such as this stick to technical discussion only. Not because your message is at fault, but it could potentially trigger an avalanche of non-constructive, even abusive replies, wasting everyone's time. No, I don't like that either, but that's what the community made it into...

Thanks,
Wladimir

**Comment by venzen** [comment]
Understood. Thank you for your response and apologies for my drama and strong language.
