### ISSUE TITLE
sendmany subtractFeeFromAmount change

### ISSUE THREAD

**Issue by Crypto2** [bitcoin/bitcoin#7699]
Just an idea for a change to the subtractFeeFromAmount, have it deduct the fees in proportion to each address's amount versus applying it equally to all outputs. You end up with a situation like splitting a check equally when one person had a steak and the other had a salad currently.

**Comment by MarcoFalke** [comment]
I don't think you can compare paying fees to having a steak vs. salad. It is more like everyone gives the waiter two bucks (a fixed amount) because they were all served alike.

The fee is not a value relative to the value you send. I.e. you don't have to pay more fee because you send more. You can see it as a fixed value for every transaction you make, where the fee pays for the "footprint" of your transaction on the network.

I don't think it makes sense to have someone pay more when sending a larger amount as everyone receives the same service from the network.

**Comment by Crypto2** [comment]
It is somewhat relative if you have a lot of smaller inputs going into the transaction (ie. more bytes for the inputs going in to the transaction for the larger output vs the smaller ones.)

**Comment by MarcoFalke** [comment]
Closing for now due to lack of interest
