### ISSUE TITLE
Does fee estimation ignore empty blocks?

### ISSUE THREAD

**Issue by RHavar** [bitcoin/bitcoin#7769]
Sorry for the bad form, probably more of a question. But I was reading over the code trying to figure out why the fee estimates in 0.12 are seemingly such over-estimates, and can't find in the logic anywhere it would ignore empty blocks?

By empty block, I mean something like:
https://www.blocktrail.com/btc/block/404921

which is probably pretty useless for fee estimation purposes, and contributing to the effect that bitcoin can never estimate the fees required for 1 confirmation.

**Comment by morcos** [comment]
They are higher in 0.12 because they use a more conservative 95% threshold.  This is in part because you have to have a very high threshold to react quickly to changes in market conditions.

No fee estimation does not ignore empty blocks.  It doesn't really make sense to, the more empty blocks there are, the longer it'll take for your transaction to be included, that seems like information that should be conveyed.

It all comes down to what you really want to be asking when you ask "estimatefee X".  I interpreted the question to be what feerate do I need to have a very high likelihood of being included in one of the next X blocks.  In which case when X=1 there is really no fee that is high enough as your transaction may not have even propagated before the next block is found.

There has already been a request to add more configurability so that perhaps you could specify the threshold and ask two questions, like I want to know a 50% likelihood of 2 blocks and 99% of 5 blocks and then you could take the max of the fee rates returned.  I'm hoping to implement that for 0.13.

**Comment by RHavar** [comment]
Thanks, that makes sense
