### ISSUE TITLE
Every use of `getinfo` or `getwalletinfo` logs two wallet messages

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#7794]
I'm not sure if it was always the case, or whether it signifies an underlying problem, but it is weird:
```
2016-04-03 10:34:10 keypool reserve 1
2016-04-03 10:34:10 keypool return 1
```

**Comment by sipa** [comment]
It loads a reserve key in order to check its timestamp. We should really
provide a wallet function that computes that without that, though...

**Comment by jonasschnelli** [comment]
https://github.com/bitcoin/bitcoin/blob/0.12/src/wallet/wallet.cpp#L2569 -> It reserves a keypool key and returns it immediately (after getting its time). This is kind of ineffective because there are db operations included.

Why not accessing `setKeyPool.begin().nTime` while holding `cs_wallet` directly?

**Comment by laanwj** [comment]
> Why not accessing setKeyPool.begin().nTime while holding cs_wallet directly?

Good idea, but let's wrap that in a CWallet method.

**Comment by paveljanik** [comment]
The same happens when you use `getnewaddress`.

**Comment by laanwj** [comment]
Well with getnewaddress you'd expect a keypool line to be reserved (but not returned).

**Comment by laanwj** [comment]
Closing after #7816 merged which solves this.
