### ISSUE TITLE
Databse error / fatal error on ecternal encrypted HDD

### ISSUE THREAD

**Issue by StrammerMax93** [bitcoin/bitcoin#7987]
I have got some major errors as well on v.0.11.0 as on v0.12.1.

I use a truecrypt encrypted external HDD where the whole wallet and blockchain is stored. 
I start it with "W:\Mining\_Bitcoin_\Bitcoin\bitcoin-qt.exe -datadir=W:\Mining\_Bitcoin_\Bitcoin"

This is the way I used to do since years and it always worked fine that way (same external HDD, same encryption).

Since some month I get major errors escpeially database errors. 
I reindexed several times but got the same problem right afetr it again.

For more info and some debug logs see here: https://bitcointalk.org/index.php?topic=1454836.new#new

**Comment by kazcw** [comment]
This is exactly what a failing HDD looks like. It happens to every disk and is normal once the disk has been used for years. If you don't have backups of all important data on the disk, you should avoid using the disk until you have something to copy your data to.

**Comment by StrammerMax93** [comment]
I have those errors since months and I'm using the external HDD all day for several purposes - but never had any problems so far - excluding the bitcoin wallet. 
But yes - the external HDD is like 5 years old.. maybe it's really an issue with the hardware.

**Comment by kazcw** [comment]
Bitcoin is good at finding hardware problems because it moves relatively large amounts of data around and then it verifies that that data is intact.

Most hard drives keep a log of certain kinds of errors, called the "SMART" status. I don't know a good way to check that on Windows though, not my area of experience. A lot of external HD enclosures don't enable access to SMART status info so if you may need to find an enclosure that works or directly attach it to a computer (either as a second drive, or booting the computer from a Linux LiveCD to do the testing if you're up for that). You can try it first though, if the enclosure doesn't work with SMART the disk checking tool will say it can't test the disk.

**Comment by laanwj** [comment]
Closing this, as it is hard to rule out a local issue here. It looks a lot like failing hardware.
