### ISSUE TITLE
Are you going to add Trezor support?

### ISSUE THREAD

**Issue by mcccs** [bitcoin/bitcoin#8218]
Here's the list of the clients which support Trezor hardware.
http://doc.satoshilabs.com/trezor-apps/index.html

Is Core going to support it?

**Comment by laanwj** [comment]
Who are you asking?

In any case: support for hardware wallets would certainly be welcome, if someone implements it.

**Comment by luke-jr** [comment]
This is really something you should be asking SatoshiLabs. Core has supported the HD wallet primitives that would be needed to support hardware wallets since a few years now, they just haven't written the driver code.

**Comment by mcccs** [comment]
I searched for it, and I found the answer is *"No"*

> > Are you open for a (sort of) plugin of trezor with Bitcoin Core wallet/Bitcoin XT?

> It is technically doable, but it's not in our pipeline for now. We do not see Core as a software ready for common users. Even Core developers said they may eventually remove Wallet from the code, because it it hard to maintain such monolithic code. I rarely agree with them; Core should be just an minimalistic implementation of node enforcing network rules and keeping blockchain running. They should leave other parts of infrastructure to people with better skills for UX.

**Comment by mcccs** [comment]
I asked Trezor and got this answer:

> Sorry, but that particular Core developer is bullshitting you. BIP32 was
just added recently and BIP44 is still not ready in Core. We will not
put any effort until this is implemented by Core.

**Comment by sipa** [comment]
@luke-jr It's not very reasonable to say that it's just driver code that's missing. Sure, BIP32 derivation primitives have been implemented for years, but as long as the wallet does not actually use it for its keys, it would be pretty hard to support.

Of course, anyone is welcome to help move things forward with deterministic wallet and hardware wallet support.

**Comment by jonasschnelli** [comment]
Since `fundrawtransaction` supporting custom change addresses (merged recently https://github.com/bitcoin/bitcoin/pull/7518) hardware wallets like Trezor or the Digital Bitbox could provide a little client/driver that would allow using Bitcoin-Core together with a transaction signing over a different tool.

I'm also working (extremely low prio, since fall 15) on a BIP for a "detached signing" standard. I think the current wallet approaches (Copay, Electrum) to support multiple native USB implementations is bad and what we need is a standard in how wallets-application could interact with hardware wallets.

BIP32 is somehow required, but I could imaging it would also work with importing `n` addresses from a hardware wallet.

IMO Cores wallet should have a mode where all transaction signing is somehow asynchronous and in that more each signature will be requested over an interface (pipe / raw TCP / ZMQ / http [my preferred way]). Each hardware wallet could provide an interface together with an optional UI and other wallets could also use this "standard communication interface".

**Comment by micressor** [comment]
@jonasschnelli: When I understand you right, something like [trezord](https://github.com/trezor/trezord) may be such client/driver?
