### ISSUE TITLE
ASLR seems not to be working as it should on Windows

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#8248]
Had an interesting exchange on twitter today re: Windows security: https://twitter.com/CopperheadOS/status/745962747117076480

Seems that `dynamicbase` is not enough and:
- Something called `highentropyva` is necessary for (secure) ASLR on 64-bit.
- Standard link/build flags of mingw-w64 prevent ASLR from actually being used, due to lack of an executable relocation table.
- Rust worked around some mingw-w64 ASLR bugs here https://github.com/rust-lang/rust/commit/96f5eba4f5603c612464d6b1e961677e9d7084d3 and https://github.com/rust-lang/rust/issues/17684 (ASLR on Windows breaks thread-local variables)

At the least it should be verified using a debugger or something like sysinternals that the base address changes every invocation.

**Comment by laanwj** [comment]
Apparently to enable high-entropy ASLR [the image-base also needs to be set above 4GB](https://code.videolan.org/solaris/x264/commit/c01bf42117b811a0469f9f6c374f4a0daa98716d). 
```
                 LDFLAGSCLI="$LDFLAGSCLI -Wl,--image-base,0x140000000"
                 SOFLAGS="$SOFLAGS -Wl,--image-base,0x180000000"
```

**Comment by laanwj** [comment]
I've checked using Process Explorer and VMMap on Windows 10, and it looks like the windows executable is always loaded at the same offset:

- `0xb00000` for the 32-bit version
- `0xbf0000` for the 64-bit version

This is not the base address specified in the .exe (0x400000), but it doesn't seem randomized either.

**Comment by retep998** [comment]
You can easily check whether an executable has ASLR enabled by doing `dumpbin /headers foo.exe` where dumpbin is a program that comes with MSVC. Ideally you should see something like the following in the output:
```
            8160 DLL characteristics
                   High Entropy Virtual Addresses
                   Dynamic base
                   NX compatible
                   Terminal Server Aware
```
If only you could use msvc to compile the code, then you'd have all that by default.

**Comment by laanwj** [comment]
> You can easily check whether an executable has ASLR enabled by doing dumpbin /headers foo.exe where dumpbin is a program that comes with MSVC. Ideally you should see something like the following in the output:

That just checks the header bits (the same as your security check script already does using `objdump`). It does not actually check whether the address space is randomized in practice, which I did by checking the memory maps at runtime.

> If only you could use msvc to compile the code, then you'd have all that by default.

You can use MSVC to compile the code. There's nothing about the code that should be gcc+clang specific (and if it is, that should be fixed).

However that doesn't help for releases as they need to be able to be built from source deterministically (with gitian). Using a closed source, not freely redistributable compiler is out of the question for that.

**Comment by sipsorcery** [comment]
I can confirm that on Windows x64 a bitcoin-qt.exe process built from source on WSL is benefiting from ASLR.

Method used to confirm (note that two separate tools are used VMMap and WinDbg to provide additional confidence):

1. Start bitcoin-qt.exe,
2. Open VMMap and select the bitcoin-qt process,
3. Click on the Image Type and note virtual addresses of certain modules, e.g.
    0x190000 f:\temp\bitcoin-qt.exe
    0x7FFA06190000 c:\windows\system32\kernel32.dll
    0x7FFA038F0000 c:\windows\system32\ws2_32.dll
4. Capture a memory dump of the process using Task Manager->Right Click Process->Create Dump File,
5. Open dump file in windbg,
6. Use lm to list loaded modules and confirm addresses are the same as VMMap,
   00000000`00190000 00000000`01fd4000   bitcoin_qt   (deferred)  
   00007ffa`06190000 00007ffa`0623e000   kernel32   (deferred)    
  00007ffa`038f0000 00007ffa`0395c000   ws2_32     (deferred)    

Now reboot Windows, since ASLR will only reset the module addresses for a process after each OS restart, and repeat the above steps:

VMMap results:
 0x820000 f:\temp\bitcoin-qt.exe
 0x7FF9D1B00000 c:\windows\system32\kernel32.dll
 0x7FF9D18D0000 c:\windows\system32\ws2_32.dll

WinDbg results:
 00000000`00820000 00000000`02664000   bitcoin_qt   (deferred) 
 00007ff9`d1b00000 00007ff9`d1bae000   kernel32   (deferred)   
 00007ff9`d18d0000 00007ff9`d193c000   ws2_32     (deferred)

**Comment by chouquette** [comment]
Hi,
For what it's worth, I submitted a patch that fixes the issue on binutils/ld side: https://sourceware.org/bugzilla/show_bug.cgi?id=19011

(Should you want a patch that applies cleanly over binutils 2.31.1 tarball, there's also one here: https://code.videolan.org/videolan/docker-images/blob/master/vlc-debian-win64/patches/binutils.patch

Hopefully that will be of use :)

**Comment by laanwj** [comment]
@chouquette Thanks!

I think this can be closed, now that we're building on bionic, `HIGH_ENTROPY_VA` is enabled.
See #13764.

**Comment by chouquette** [comment]
I doubt it is fixed, the patch I propose is breaking the binaries, and AFAIK it hasn't been fixed upstream in another way.

Unless your executable has some explicitly exported symbols, the relocation table will be missing, and this will cause the executable to be flagged with `IMAGE_FILE_RELOCS_STRIPPED`, so Windows won't enable ASLR.

**Comment by fanquake** [comment]
There's been some [upstream activity](https://sourceware.org/bugzilla/show_bug.cgi?id=19011#c9) here. binutils have [implemented](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blobdiff;f=ld/ld.texi;h=eb7bcb993383fa57392acd45dda66956c9995f1f;hp=c7016f18452dc1cae3bb2ef69b7c4a8fe716242c;hb=dc9bd8c92af67947db44b3cb428c050259b15cd0;hpb=b26a3d5827edcb942b3af5b921bf317bbc0c8e83) a `--enable-reloc-section`, which would be turned on along side `--dynamicbase` or `--high-entropy-va`.

**Comment by fanquake** [comment]
Now that #18629 and #18702 have been merged. I think we can close this  as "working for now".
