### ISSUE TITLE
Fatal Internal Error

### ISSUE THREAD

**Issue by Panzzy** [bitcoin/bitcoin#8322]
I am unable to open my Bitcoin Core application. I just downloaded it and when it finished installing, the application opened up just fine. After Bitcoin Core was syncing with the network, I got a error message. The application closed out and when I tried opening it up again, it won't. The application first starts up by verifying blocks and once completed, it says "Activating best chain..." then the error message appears saying, "A fatal internal error occurred, see debug.log for details". The application force itself close from there. Please help! 

Thanks!

[debug log.docx](https://github.com/bitcoin/bitcoin/files/355405/debug.log.docx)

**Comment by NicolasDorier** [comment]
put the logs in a txt file

**Comment by Panzzy** [comment]
Ohh got it. It didn't let me before so i had to copy and paste it to word. But now it works. Here it is.

[Debug.txt](https://github.com/bitcoin/bitcoin/files/355450/Debug.txt)

**Comment by MarcoFalke** [comment]
The tail reads:

```
2016-07-09 05:01:09 Corruption: block checksum mismatch
2016-07-09 05:01:09 *** System error while flushing: Database corrupted

**Comment by laanwj** [comment]
The usual recommendation for database corruption issues (we really need a FAQ) is:
- You can work around the immediate issue by rebuilding the database with `-reindex`
- Check your hardware (most corruptions are caused by faulty CPU, memory or disk)
- If there are hardware isues, `-par=1` to set only one script verification thread has been known to mitigate problems. Of course, running software such as bitcoin core on faulty hardware, especially if wallets are involved, is risky
