### ISSUE TITLE
How to set fees start with 0.0001 ?

### ISSUE THREAD

**Issue by JokerCatz** [bitcoin/bitcoin#8326]
Hi , dev team

my node is 0.11.2 , wish to upgrade to last version , but I scared to set low fees make slow confirm

my node fees settings is

    paytxfee=0.0001
    mintxfee=0.0001

if I set it same in last version , fees will be same ?

and I need start with 0.0001 and more then 0.0001 be normal fees , it be possible in last version ? and where is recommend fees settings in normal speed confirm (1~30 min) ?

anyway , Thanx and sorry my poor english : )

**Comment by sipa** [comment]
If you have a long-running bitcoind instance, it is better to not set mintxfee or paytxfee.

If you do not set paytxfee, an estimate of the fees on the network is used to determine the fee amount since 0.12. You can also do this manually by calling `estimatesmartfee blocks`, with blocks the number of blocks you're willing to wait for confirmation. Note that this value may go higher than what you're used to during peaks of high activity.

Also note that the argument to paytxfee is in fees per kilobyte, and not an absolute amount. This means that if you set it to 0.0001, and a transaction is 270 bytes, it will set the fee to 0.000027. This is what you need, as miners select by fee per byte as well, but it can be unintuitive.

You should not ever set mintxfee.

**Comment by MarcoFalke** [comment]
> my node is 0.11.2 , wish to upgrade to last version ,

You can have a look at the release notes for 0.12.0 to find more information about transaction fees: https://github.com/bitcoin/bitcoin/blob/v0.12.0/doc/release-notes.md#wallet-transaction-fees

This is pretty much what @sipa  told you. And you are mostly good with the default setting for smart fees: `-txconfirmtarget=<m> (default: 2)`. Make sure to remove or comment out the `paytxfee` and `mintxfee` option in your conf.

**Comment by JokerCatz** [comment]
okay ... I'll be test it , thanx all : )
