### ISSUE TITLE
New wallet.dat is not always the same size under 0.13.0rc1

### ISSUE THREAD

**Issue by keystrike** [bitcoin/bitcoin#8401]
When I create a new wallet under 0.13.0rc1 sometimes the file size of wallet.dat is 96KiB and sometimes it is 112KiB. Is this expected behavior? I do not see any difference in the log file.

**Comment by pstratem** [comment]
@keystrike wallet.dat is berkeley db file; the internal structure of which is more than a little weird

**Comment by laanwj** [comment]
It's curious, but this IMO is not an issue that merits deeper investigation.
My guess would be: berkeleydb internally uses some kind of hash table, and its growth depends on just how the keys end up in the hash buckets. If it turns out lucky you end up with a smaller file, if not and a bucket overflows, it grows by a size increment.
