### ISSUE TITLE
peeraddr no longer showing onion addresses

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#8409]
In the version message in the debug log, the "them=" used to show the onion address of a connection. Now it is showing just a 127.0.0.1 address and a port number which is not useful and makes banning misbehaviour less reliable (not that banning an onion address is totally reliable).

Can this be changed to show onion addresses again?

**Comment by laanwj** [comment]
For outgoing Tor connections it will (or at least should) show the onion.
For incoming Tor connections it will show 127.0.0.1:X because that's where the connection comes from, after being forwarded locally by the Tor daemon. Anything else would be impossible as Tor does not provide source information for connections.
