### ISSUE TITLE
p2p sends local-scope addresses when IPv4 is behind NAT

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#8616]
Wireshark tells me I am sending my local-scope IPv6 address, when connecting over IPv4 (behind NAT)... :/

Context: #8594

**Comment by laanwj** [comment]
Added privacy tag. Leaking internal addresses behind a LAN is a serious privacy issue, see https://github.com/bitcoin/bitcoin/pull/8594#issuecomment-242767752 .
Aren't local-scope addresses based on the MAC address? Ouch.

**Comment by sipa** [comment]
@luke-jr Is this an RFC4862 address (fe80::/64) ?

**Comment by luke-jr** [comment]
Hmm, no. I don't seem to actually have the address on any of my interfaces.

Begins with fd87. Second-guessing if this is actually IPv6 local, or perhaps some way of encoding a Tor hidden service?

**Comment by sipa** [comment]
Yes, that's an onioncat address - the way Bitcoin P2P encodes onion addresses in IPv6.

**Comment by sipa** [comment]
Closing; feel free to reopen if you see other local addresses being relayed.

**Comment by laanwj** [comment]
Sending an onion address as from-address is a privacy breach, too.

**Comment by sipa** [comment]
Hmm, I believe the logic is that we send the most compatible known local address to peers. That means that you'd send your onion address to non-tor peers if you don't know of any other local reachable non-onion address.

Perhaps that logic should be revisited, and we should never send an address out except to peers that are already connected to through that interface. That is complicated, as it means we need a way to identify incoming onion connections as belonging to tor.

**Comment by laanwj** [comment]
I think it should leave the `addrFrom` address blank in version messages, full stop. There's no need to fill it in at all it if it's no longer needed by peers connected to (e.g. #/8594).

**Comment by sipa** [comment]
@laanwj Perhaps, but that's orthogonal. We also announce our own address using `ADDR` messages.

**Comment by laanwj** [comment]
Which is less privacy-sensitive, at least it's hiding among a crowd there.

**Comment by EthanHeilman** [comment]
Is anyone working on a PR for this? If I'm not stepping on anyone's toes I'd like to put a PR together over the weekend.

**Comment by laanwj** [comment]
@EthanHeilman not aware of anyone working on this

**Comment by laanwj** [comment]
Partially mitigated by #8740.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?

**Comment by vasild** [comment]
To summarize, there are 3 issues here:

1. The problem from OP of sending local addresses to peers was nonexistent. That was never done.
2. Sending our addr in the `VERSION` message, fixed by https://github.com/bitcoin/bitcoin/pull/8740
3. Sending our addr via `ADDR` (or `ADDRv2`) message. I need to look at this more carefully, but a brief look tells me that maybe the problem exists. I mean sending our IPv4 address to a Tor peer or sending our Tor address to an IPv4 peer. At least `CNetAddr::GetReachabilityFrom()` does not explicitly disable that:

https://github.com/bitcoin/bitcoin/blob/c464e67e0b71c397f6b3d3a920d98a1a2a296c7a/src/netaddress.cpp#L773

Maybe this can happen if we can make outbound connections to both Tor and IPv4 but only listen on one of them.

**Comment by vasild** [comment]
https://github.com/bitcoin/bitcoin/pull/27411 should have resolved 3.

**Comment by willcl-ark** [comment]
Closing as fixed based on prior comments from vasild.
