### ISSUE TITLE
Replacing Boost Test Framework

### ISSUE THREAD

**Issue by JeremyRubin** [bitcoin/bitcoin#8670]
The unit tests are pretty slow (especially under wine) which can cause timeouts in travis.

Furthermore, it's another boost dependency we can probably get rid of.

This issue is to discuss what features people would like in a new test framework.

To start a list of features that people might like:
- printing the expression, value, and line number on failure
- checkpointing in case of segfaults
- regex filter tests
- progress meter/output currently running test
- test benchmarking info/ability to regression test performance

Please chime in with anything else that you think should go into it.

**Comment by Christewart** [comment]
It would be nice to have some sort of support for property based testing, as per #8469. Conveniently the framework I integrate in that pull request supports integration with Boost.

**Comment by JeremyRubin** [comment]
@Christewart we're trying to get rid of boost.

**Comment by MarcoFalke** [comment]
There is a bunch of `BOOST_CHECK()`s in the code( where `BOOST_CHECK_EQUAL()`s should be used instead) causing at least one assignment error (#8673). So would it make sense to have `BOOST_CHECK()` fail on non-boolean values, if it is possible at all?

**Comment by JeremyRubin** [comment]
@MarcoFalke I have no clue how to do that; short of a compile time regex (http://cpptruths.blogspot.com/2011/07/compile-time-regex-matcher-using.html).

**Comment by JeremyRubin** [comment]
I also like that GDB can attach itself on a failure. I don't like that it seems to launch a gui gdb needing root to attach on x sessions though.

**Comment by Christewart** [comment]
@JeremyRubin I think it would be worthwhile to building in a property based testing framework into our custom framework if we are hell bent on having building a framework from scratch. I'm not sure if I support completely eliminating the Boost dependency, since the overhead of maintaining the new framework might be more trouble than its worth. 

Would it just be more wise to run our own fork of Boost and fix the performance issues you mentioned above? Could those features you mentioned above be layered on top of Boost?

**Comment by sipa** [comment]
Feature request: a command line option to make the application `abort()` on the first error, allowing the creation of a core dump and inspect afterwards in gdb.

**Comment by laanwj** [comment]
> The unit tests are pretty slow (especially under wine) which can cause timeouts in travis.

Also on FreeBSD: `test_bitcoin takes` 236.803s, whereas on Linux only 40s on older hardware.

It's starting to look like boost::test is optimized specifically for Linux.

**Comment by laanwj** [comment]
NM, I had accidentally disabled optimization for the entire build (issue #3921). New time on FreeBSD is the same (within rounding error) as the Linux time.

**Comment by NicolasDorier** [comment]
A test I added during segwit https://github.com/bitcoin/bitcoin/blob/dd98f045382428f450dc917a3933c9e4e8e1ba99/src/test/transaction_tests.cpp#L415 is very slow. (I think like 30sec)

I am not sure if it is a good idea to remove it though.

**Comment by JeremyRubin** [comment]
This is (probably) because you're creating a ton of threads, I think!

`for (int i=0; i<20; i++)`

There's no reason to do that, try i < 2.

**Comment by NicolasDorier** [comment]
@JeremyRubin the test was testing race conditions.

**Comment by NicolasDorier** [comment]
The problem is that signing so much input takes time. Not so much the number of spawned thread.

**Comment by JeremyRubin** [comment]
Ah ok -- maybe use pregenerated test vectors as is done in a couple other places? Or use the threads to generate the signatures (do they need to be signed in serial order)?

**Comment by NicolasDorier** [comment]
I remember having tried to parallelize signature but that it was not worth it, pregenerated test vectors are better indeed.

Anyway, I think this is a separate problem from this issue. I would like better test framework for sure.

**Comment by kthcode** [comment]
Lean principles addition match subtraction diferential equality ratios

**Comment by BrannonKing** [comment]
I don't think that there is any reason to change to a different unit test framework as long as we have a single Boost dependency remaining. This would be the very last dependency to go. And if it's time for Boost Test to go away, I think you should replace it with an already-existing framework like Catch2 rather than write your own. I don't want to have to learn a new framework to write tests for bitcoin. It feels like a custom test framework is too far outside the direction and responsibility of the bitcoin codebase.

**Comment by MarcoFalke** [comment]
At the very least, we should look into replacing the `BOOST_CHECK` (et al.) macros with our own. None of the `BOOST_` macros are thread-safe. However, Bitcoin Core runs multiple threads (indexers, validation interface, main thread, ...), so we can use those macros in at most one thread. See for example this place https://github.com/bitcoin/bitcoin/pull/13023/files#diff-83ded29db9bfc1c9342adc826ca2b5abR168
