### ISSUE TITLE
Fix documentations of rpc `listsinceblock`

### ISSUE THREAD

**Issue by FrozenPrincess** [bitcoin/bitcoin#8758]
## The second param of listsinceblock

From [issue 8752](https://github.com/bitcoin/bitcoin/issues/8752#issuecomment-247988691)

> The second parameter (target confirmation) is quite strange and should probably be better > documented in the RPC help of listsinceblock (check original comment: #199 (comment))

From the actual docs here is it is:

> target-confirmations:    (numeric, optional) The confirmations required, must be 1 or more

However, that's misleading at best. I've seen at least one project thinking that `target-confirmations` means "filter to only show transactions of n target-confirmations". It's a weird param but I'd document it as

> target-confirmations: (numeric, optional) Return the hash of the block that has target-confirmations of confirmations, for use in a further call to listsinceblock
## Transactions confirmations

Says:

> "confirmations": n,       (numeric) The number of confirmations for the transaction. Available for 'send' and 'receive' category of transactions.

It should also say when it's < 0, it means the transaction conflicted that many blocks ago
## bip125-replaceable

There's an undocumented field of transactions "bip125-replaceable" which I believe has three possibilities "yes" "no" and "unknown"  (under what circumstances it says unknown, should also be documented)

**Comment by laanwj** [comment]
Agree, though I don't think the parameter should even be called target-confirmations if that is what it does.

**Comment by FrozenPrincess** [comment]
I updated the issue to include 2 other minor documentation issues for the same rpc call, as it probably should all be done as one thing.

**Comment by RHavar** [comment]
I don't think this should be closed, #9396 only fixed 1 out of the three issues in the docs.

**Comment by RHavar** [comment]
Another issue with listsinceblock documentation, is that it's  missing documentation for `walletconflicts` (and it should explain exactly what that mean, if exclusively transactions from the wallet that conflicts or any transaction)

**Comment by RHavar** [comment]
There's also missing documentation for the field `replaced_by_txid`. I'm not sure I'm a fan of these "omit empty" style fields that only appear when the data exists. They make them rather hard to discover, especially if the docs aren't comprehensive.

**Comment by ryanofsky** [comment]
> There's also missing documentation for the field `replaced_by_txid`.

`replaced_by_txid` is documented here: https://github.com/bitcoin/bitcoin/blob/7a74f88a26cf251ba36b26f604f1ac9940fd9c92/src/wallet/wallet.h#L280

**Comment by RHavar** [comment]
>replaced_by_txid is documented here: 

That's not exposed to end users when they via the listsinceblock help/docs :D

**Comment by laanwj** [comment]
> I'm not sure I'm a fan of these "omit empty" style fields that only appear when the data exists. 

The alternative is to use a "special value", which is fraught with more risk. E.g. the return value -1 for "no data" in `estimatesmartfee` has been criticized many times, because it's too easy to use as a value. Leaving out the field completely avoids potential confusion.
Of course the documentation needs to be complete.

**Comment by gmaxwell** [comment]
@RHavar  errors are always hard to discover if they're not documented correctly and even then;  hiding the fields is about shaping how the caller fails when they get it wrong.

I think our coding standards should reflect something like: "Avoid returning special values for error conditions, especially for gauge outputs (like numbers of connections, btc amounts, etc.) because the error code can be mistaken for a value even if the error is negative and negative results don't make much sense. For fields which are naturally categorical an in-band error can be more acceptable e.g. something that returns "apple" / "grape" / "cherry"  could also return "error", but is generally preferable to have a named result field and not return it when there is an error, and return an error field instead."

It's always sad if you mishandle an error-- but I'd rather the caller fail cleanly rather than average a -1 into some data or something like that.

**Comment by gmaxwell** [comment]
@RHavar  errors are always hard to discover if they're not documented correctly and even then;  hiding the fields is about shaping how the caller fails when they get it wrong.

I think our coding standards should reflect something like: "Avoid returning special values for error conditions, especially for gauge outputs (like numbers of connections, btc amounts, etc.) because the error code can be mistaken for a value even if the error is negative and negative results don't make much sense. For fields which are naturally categorical an in-band error can be more acceptable e.g. something that returns "apple" / "grape" / "cherry"  could also return "error", but is generally preferable to have a named result field and not return it when there is an error, and return an error field instead."

It's always sad if you mishandle an error-- but I'd rather the caller fail cleanly rather than average a -1 into some data or something like that.

**Comment by jeffrade** [comment]
I believe this issue can be closed.  The fields `target-confirmations`, `confirmations` and `bip125-replaceable` have either been updated or added since this issue was originally opened.  The PRs weren't referencing this issue number, so this issue stayed open.  Below are the commits that have addressed them:

 - [`confirmations`](https://github.com/bitcoin/bitcoin/commit/3f67972654748a2f24e4aa95b6f3df5d4574ed55)
 - [`target-confirmations`](https://github.com/bitcoin/bitcoin/commit/9f8a46f077e2f8b6829faa10212c6707e2402f40#diff-df7d84ff2f53fcb2a0dc15a3a51e55ceR1764)
 - [`bip125-replaceable`](https://github.com/bitcoin/bitcoin/commit/54ee3fcb8f2d21ded2efd236aa0b974050f685ba#diff-df7d84ff2f53fcb2a0dc15a3a51e55ceR1665)
