### ISSUE TITLE
Blockchain stops downloading at exactly 235283 height, even after deleting the dd

### ISSUE THREAD

**Issue by charlesfries** [bitcoin/bitcoin#8907]
Running bitcoind 0.13.0 on Ubuntu 16.04. The debug.log shows nothing out of the ordinary.

**Comment by achow101** [comment]
Are you running out of disk space? Anyways, debug.log please (you might have missed something).

**Comment by MarcoFalke** [comment]
If you manage to reproduce with -debug=net enabled, please upload the debug.log.

**Comment by rebroad** [comment]
@charlesfries In order to determine if this is an issue or not we need to see the debug.log with debug=net enabled. Are you willing to do this? If not, probably better to close this issue. I realise debug=net produces a lot of debug info not relevant to this issue.... Feel free to use https://github.com/rebroad/bitcoin/tree/MoreGranularDebug with debug=block if you just want to enable debug for block download.

**Comment by charlesfries** [comment]
@rebroad Forgive me, I reinstalled Xenial and now it works. User error, my bad.
