### ISSUE TITLE
Console command paths cannot be specified correctly with backslashes

### ISSUE THREAD

**Issue by Derek701** [bitcoin/bitcoin#8912]
Bitcoin Core v0.13.0 on Windows 10 (using Debug window console in GUI)

Console commands with filename arguments cause unexpected behavior when using Windows-style backslashes in paths. For example, `dumpwallet D:\Bitcoin\test.txt` creates `D:\Bitcointest.txt`. Replacing backslashes with slashes, `dumpwallet D:/Bitcoin/test.txt` creates `D:\Bitcoin\test.txt`.

The unexpected result is more confusing because `dumpwallet` does not print the path/filename of the created file to the console (only a blank line).

At least a note for Windows users to specify paths with slashes in the help text would be nice. Also, the help text for `dumpwallet` and `importwallet` does not indicate that the filename argument requires a full path to work correctly in the console (_i.e._, there's no default working directory).

**Comment by laanwj** [comment]
The debug console has a minimal sh-like parser. You can actually use backslashes, but you need to escape them or surround with quotes (preferably single quotes, because there \ will never be interpreted as an escape sequence). E.g. either
```
dumpwallet d:\\Bitcoin\\test.txt
dumpwallet 'D:\Bitcoin\test.txt'
```
Closing in favor of #9195 which is a more general issue for tracking RPC console documentation.
