### ISSUE TITLE
Assertion failed: (nMaxInbound > 0), function AcceptConnection, file net.cpp, line 973.

### ISSUE THREAD

**Issue by paveljanik** [bitcoin/bitcoin#9007]
Current bitcoin-master on testnet, `maxconnections=8` in the config file. Running in VM that doesn't have public IP and is not reachable from the Internet.

Wait until you have 8 peers.

```
telnet localhost 18333
```

It will result in:

```
Assertion failed: (nMaxInbound > 0), function AcceptConnection, file net.cpp, line 973.
```

First found in https://github.com/bitcoin/bitcoin/pull/8996, but can be reproduced on master.

**Comment by sipa** [comment]
Can it also be reproduced in 0.13.1rc2?

**Comment by laanwj** [comment]
Can you try setting maxconnections=9 instead and see if it still happens?

**Comment by paveljanik** [comment]
I think it should be 10, because the assert is >0. Confirmed by testing.

**Comment by paveljanik** [comment]
Extended original report:
```
nMaxConnections = 8
nMaxFeeler = 1
nMaxOutbound = 8
nMaxInbound = -1
Assertion failed: (nMaxInbound > 0), function AcceptConnection, file net.cpp, line 979.
```

**Comment by EthanHeilman** [comment]
The core assumption I made which is being violated is that nMaxConnections is less than 9. 

I'm against just removing this assert since it seems confusing and unexpected to allow a max number integer to be negative. Instead I propose that the code not assume nMaxConnections will always be greater than 9 by scaling nMaxOutbound with nMaxConnections such that nMaxInbound is not negative.

**Comment by laanwj** [comment]
@EthanHeilman I agree with doing that for 0.14, the logic (and input checking! this error should have been flagged in init.cpp not while the node is running with an assert) could definitely be improved, but for 0.13.1 we don't have the time to do a more measured solution.
