### ISSUE TITLE
Run "Parsing JSON is a Minefield" against univalue

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#9028]
Nicolas Seriot recently published [an article](http://seriot.ch/parsing_json.html) comparing various JSON parsers. Some of the problems he found are quite worrying, such as parser crash bugs in common libraries.

We did a lot of fuzzing so I'd hope we find no or few crash bugs. However it would be interesting to run his test suite (raw test data [is available](https://github.com/nst/JSONTestSuite)) against univalue to see how univalue compares or whether it finds any crash-level issues or just pedantic ones.

**Comment by ryanofsky** [comment]
I looked into this, creating a test driver for UniValue that works with the test suite, and fixing a few issues that this uncovered. There were no test cases that caused crashes, but there was:

* A test case that showed UniValue improperly accepting a non-minimal utf8 sequence (`C0 AF`)
* A test case that showed UniValue returning a partial parsing of a json input with an embedded nul byte (`'\0'`)
* Some test cases that failed because of missing features in UniValue: utf16 decoding, support for reading plain number and string values not embedded in objects or arrays.

I created a PR at https://github.com/ryanofsky/bitcoin/pull/1 with a few commits fixing the various issues. Not sending the PR upstream for now, because it's not clear which of the changes might be desirable to keep permanently.

**Comment by laanwj** [comment]
> The second commit extends UniValue::Read() to support reading standalone number/string/bool/null values that aren't arrays or objects. It fixes the following tests:

Slighly off-topic: I like this one. We actually have workarounds in place to do "lonely" JSON value parsing: `ParseNonRFCJSONValue` in https://github.com/bitcoin/bitcoin/blob/master/src/rpc/client.h#L12 . Would be great if upstream just supported it.

**Comment by ryanofsky** [comment]
Created upstream PRs at:

https://github.com/jgarzik/univalue/pull/30
https://github.com/jgarzik/univalue/pull/31
https://github.com/jgarzik/univalue/pull/32
https://github.com/jgarzik/univalue/pull/33

**Comment by ryanofsky** [comment]
Could close this issue, the fixes are upstream.

**Comment by MarcoFalke** [comment]
Pending merge is https://github.com/jgarzik/univalue/pull/33, but indeed no need to keep this open with the label 'good first issue'
