### ISSUE TITLE
"unknown new rules activated (versionbit 28)" message - more info needed

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9080]
This is affecting other users who are also unable to determine what it means:-

http://bitcoin.stackexchange.com/questions/43846/testnet-wallet-fully-sync-block-height-different-to-testnet-blockchain-explorer

There needs to be more information made readily available to the user where they can at least read what this message means or might mean, preferably with how to find more information on what it does mean.

**Comment by MarcoFalke** [comment]
You can read more about what caused the bit 28 message here: https://bitcointalk.org/index.php?topic=1471338.0

In the general case, I am not sure if we can or should improve the user friendliness of the message. It just means what it says: Some new rules (this can even be an empty set of new rules), which are not known to the node which displays the message, are active since the message is displayed.

**Comment by laanwj** [comment]
There just isn't more information available to the node, so no more can be reported to the user. It is assumed the user can use google to find more information about it.
