### ISSUE TITLE
Better venue for development discussion needed

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9149]
https://botbot.me/freenode/bitcoin-core-dev/2016-09-29/?msg=73959763&page=4 (to show an example of a recent meeting)

Currently the IRC group is being used for discussion regarding development, but this doesn't allow for people in all time-zones to participate (e.g. it's 2am in Thailand).

Also the bitcoin-core-dev group is being used to discuss protocol changes, which obviously affects all other Bitcoin variants, so perhaps such topics ought to be moved to non-core specific areas.

Raising this here as I am unaware of a more appropriate venue currently to raise this, as it is currently a core-specific issue (given it's the core specific chat room).

Any suggestions on a better forum/software to use for this? Ideally it ought to be something that allows likes/dislikes (as GitHub already has) to previous suggestions - doesn't rely on everyone being present at the same time - and ideally allows for threaded conversations and sub-topics to occur, yet allowing for an overall agenda to persist, perhaps with options to vote on proposals and keep a tally of votes, as well as the membership/status of participants (GitHub also already does this).

Overall, given the criteria I am inclined to think GitHub may already be the best venue, but I do hope that others can agree that a venue that allows participants from varying timezones and allows inclusion of non-core participants for non-core issues is desirable.

So, this is two issues really - a better venue for bitcoin core discussion, and a better venue for overall bitcoin development discussion.

**Comment by jonasschnelli** [comment]
Again. The place for this is probably the bitcoin-dev mailing list.

The current time-slot has been chosen after asking and arranging with every interested participant finding the best slot that could work for most interested participants. Sure, we can (and probably should) re-evaluate a better, different time-slot every here and there (maybe once every year).
But my feeling tells me, that changing the timeslot will make things difficult for some.

The public IRC meeting is hold in #bitcoin-core-dev (just because it's most convenient there).

IMO there are already various forums to discuss stuff (ex. https://bitcointalk.org).

**Comment by jonasschnelli** [comment]
closing

**Comment by rebroad** [comment]
Bitcoin-dev mailing list seems to be heavily censored. I just got a post
rejected today in fact (regarding BIP9).

**Comment by Leviathn** [comment]
That topic had already been flagged and noted that further discussion on it was to be continued on Bitcoin-Discuss. That is hardly censorship, especially when the original note in question was off-topic, and had largely ignored previous information on the topic (see Sipa's post on soft-forks).

**Comment by venzen** [comment]
@rebroad I'm sure your persistent problem-invention on every non-issue in this landscape is annoying others too, so let me push back a little for the sake of my own inbox and everyone else's:

I happen to live in Thailand and the IRC meeting at 3am (Indochina time) makes participation difficult, yes. However, the minutes/summary of the meeting is always made available at bitcoincore.org. In the final analysis, there is no utilitarian outcome in me synchronously participating in the meeting because the matters being discussed, though interesting, are beyond my capacity as a hobbyist to influence or sway.

The same applies to you, since your repeated failure to make meaningful contribution to this project means you also lack the merit and reputation to influence the course of Core development.

Please put a plug in the constant revisitation of old issues and public questions you should correctly be researching on your own.

**Comment by rebroad** [comment]
@venzen With posts like that you might just acquire the merit and influence you claim you lack :)
