### ISSUE TITLE
inundated with cmpctblocks

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9163]
[debug.log.txt](https://github.com/bitcoin/bitcoin/files/592002/debug.log.txt)

My node is being swamped with cmpctblocks from nodes, when as far as I understood it, only 3 nodes at a time were supposed to be announcing via cmpctblocks. Not only this, but many of the cmpctblocks arrive quite a while after I have received the block from other nodes, so surely my node should be requesting the announcement via cmpctblocks stops, or disconnecting the nodes that continue to announce via cmpctblocks after they've been requested not to.

As a bolt-on question: why is the contents of every cmpctblock received different?

**Comment by MarcoFalke** [comment]
​What version/commit are you running?​ Are there local patches applied?

**Comment by rebroad** [comment]
@MarcoFalke 13.1 with some local patches to improve debug information - is no one else seeing this then?

**Comment by gmaxwell** [comment]
@rebroad I strongly suspect someone was up to shenanigans.  When your issue went up I went to one of my nodes and saw similar results: in some cases I was getting 12 duplicates, the behavior was recent and not reflected in older logs.

I then quickly implemented a bunch of additional logging and restarted and in several days have not seen a _single_ other instance of excessive repeats. (I see usually one, sometimes a couple when they race, never more than four (not three because sometimes a block comes right after changing preferences, and sometimes the tree HB peers come in when we've getdataed from a non-HB peer).

I carefully reviewed both the requesting and responding code in both master and 0.13.1 and am reasonably confident that there is no simple bug in Bitcoin Core that could have caused that behavior. So in the absence of further information I would guess the cause was someone running broken customized things or an ineffectual attempt at an attack.

**Comment by rebroad** [comment]
@gmaxwell thanks for the update. Hmm, odd choice of shenanigans - I have seen this happened quite a bit in the past also. Is it worth classing as misbehaviour? i.e. if a peer annnounces cmpctblocks when it's not been asked to, and when a peer announces with anything other than cmpctblocks when it has been asked to?

**Comment by rebroad** [comment]
Seem to have been fixed by #9199
