### ISSUE TITLE
How I can increase a outbound connections?

### ISSUE THREAD

**Issue by jeong760** [bitcoin/bitcoin#9217]
Dears,

I am operation my own private BTC mining pool so I want ask you following in order to increase it. 
How I can increased a outbound connection on Bitcoin-QT 0.13.1? Because It was fixed as only 8 of outbound connection. 

Regards,
john Ahn

**Comment by jonasschnelli** [comment]
There is no runtime option for this and AFAIK it wouldn't be wise to do so (potentially increase pressure on the already declining number of nodes).
Also, see discussions in https://github.com/bitcoin/bitcoin/pull/6533 and https://github.com/bitcoin/bitcoin/pull/6014

**Comment by TheBlueMatt** [comment]
You probably don't want to do this not just because it's "bad behavior", but because having too many connections results in your upload bandwidth being more heavily utilized when you find a block (resulting in increased packet loss), actually increasing the time it takes for nodes to hear about your block.

You might also consider looking into advanced relay technologies and connecting to highly connected nodes such as the Relay Network (http://bitcoinfibre.org/public-network.html).

**Comment by laanwj** [comment]
Closing, this is intentionally not supported.
