### ISSUE TITLE
60s timeouts during IBD

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9314]
During IBD when many blocks are being UpdateTip()ed it can be very common for many new connections to be made but most of them timeout due to no messages being sent or received during the first 60 seconds. This was made worse recently by 902768099cb92b39f5ff509cd91fdd8970759b8a as now the version message is now sent from the messaging processing thread (and no longer the network connection thread) so the timeouts can occur from the remove peer also.

Possible fixes are 1) to ensure the version message is sent upon connection from the network handling thread instead of the message processing thread which freezes during UpdateTip(), and 2) to change the disconnection logic for the 60s timeout so that it uses a timestamp set within the message processing thread (rather than a timestamp set possibly more than 60 seconds before it even gets a chance to process any messages).

**Comment by theuni** [comment]
This is known and will be fixed with the upcoming async changes.

https://github.com/bitcoin/bitcoin/commit/902768099cb92b39f5ff509cd91fdd8970759b8a didn't change the sending thread for version, it should still (unfortunately) sent on the sockethander thread, since the optimistic send should always succeed.
