### ISSUE TITLE
Incorrect error message when trying to sign with compressed key

### ISSUE THREAD

**Issue by davout** [bitcoin/bitcoin#9437]
### Reproduction
Try to sign a transaction with `signrawtransaction`, but instead of using the uncompressed key as third argument, use a compressed key.

### Expected behaviour
A meaningful error message.

### Actual behaviour
The error message returned will be "Operation not valid with the current stack size".

### What version of bitcoin-core are you using?
3bf06e9bac57b5b5a746677b75e297a7b154bdbd

**Comment by unsystemizer** [comment]
The same error appears in other similar situations (for example, if one tries to send unsigned raw transaction).
There could be some basic checking of inputs based on the length of valid input arguments, so say if input is X instead of the expected Y or Z bytes, a "Maybe you screwed up" message could be displayed. 
I think this would require less effort compared to advanced checking and would help detect a lot of simple problems that happen in the CLI.

**Comment by MeshCollider** [comment]
I think this was fixed by #11288, so can be closed (unless anyone says otherwise)
