### ISSUE TITLE
[GUI] GUI misses some header updates when in IBD

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#9464]
OSX 10.12.2, Qt 5.7.1, master at 2a524b8e8fe69ef487fd8ea1b4f7a03f473ed201.

Running with `bitcoin-qt -reindex-chainstate`, "Number of blocks left" in the modal overlay never updates, and remains as "Unknown. Syncing Headers (446424)...". Even though we've synced > 200'000 blocks.
![modal](https://cloud.githubusercontent.com/assets/863730/21626478/430cc750-d24c-11e6-8d4b-39e55873a57a.png)

**Comment by jonasschnelli** [comment]
Yes. We enforce the text "Syncing Headers..." until we have fetch a header not older then 4h. But maybe the 4h is to low.
@MarcoFalke: are you going to take a look at this?

**Comment by MarcoFalke** [comment]
Not sure this is worth fixing. Due to reindex, you are in IBD and only update the text every 250 ms. If the best known header to the network arrives in less than 250 ms after the last text update, you are going to just miss it.

@fanquake The text should update as soon as block 446425 is known to you.

**Comment by fanquake** [comment]
This also occurs when running with `--reindex`, Number of blocks left is still unknown, however additionally, both Progress increase per hour and Estimated time left until synced remain as "calculating.."
![screen shot](https://cloud.githubusercontent.com/assets/863730/23165050/2a9dbd6a-f875-11e6-8949-aa2d959b937e.png)

**Comment by volkno25** [comment]
![untitled](https://user-images.githubusercontent.com/30658516/28874772-7220e2f8-77bd-11e7-82b8-abdced5c9b73.png)
i have the same problem from windows 7 after the hard fork please help!. i've tried many things. it have been "syncing headers" for days and stopped downloading anymore block. before the problem i had set up the bitcoin abc wallet for bch, which i have removed, please put an end to this. :(

**Comment by MarcoFalke** [comment]
Confirmed that the issue is still present in current master (5180a86c96) and "fixes itself"/ is worked around when the next header is sent to you. C.f. my comment https://github.com/bitcoin/bitcoin/issues/9464#issuecomment-270362394

@fanquake I adjusted the issue title to properly summarize the issue, hope this is ok.
@volkno25 It seems you issue is not related to the GUI missing header updates sometimes, but rather an issue with stuck sync? Please file a separate issue if still reproducible.
