### ISSUE TITLE
Write instructions on offline signing.

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#9492]
The only instructions I'm aware of for offline signing are https://people.xiph.org/~greg/signdemo.txt which is really out of date, doesn't cover watching wallets, or fundrawtransaction.

**Comment by gmaxwell** [comment]
Please assign me.

**Comment by adamjonas** [comment]
Greg's signdemo.txt file is no longer online, but I've put up a copy [here](https://gist.githubusercontent.com/adamjonas/87e903c0f80a4f9970990cc3cb735840/raw/4119ee902fdb47a1a52b91d99433e9293caea8b5/signdemo.txt) for those that would like to reference.

**Comment by pinheadmz** [comment]
https://github.com/bitcoin/bitcoin/blob/master/doc/external-signer.md was added by @Sjors over 2 years ago. I also found some good answers about `signrawtransaction` on stack exchange. There is also https://github.com/bitcoin/bitcoin/blob/master/doc/psbt.md which is about as old. I think PSBT was added to Bitcoin after this issue was opened and although the guides are more geared to multisig, they cover a lot.

@adamjonas do you think those docs are good enough to close this issue? Otherwise I can add something that exemplifies the manual process with `signrawtransaction` etc

**Comment by Sjors** [comment]
I think that with PSBT there's no need to go out of our way to document the legacy `signrawtransaction`.

The external signer docs kind of assume a connected device / service, so not really "offline". The PSBT doc could probably be update to use descriptor wallets rather than `createmultisig`, though creating descriptors by hand is a bit tedious at the moment.

The [multisig tutorial](https://github.com/bitcoin/bitcoin/blob/master/doc/multisig-tutorial.md) is more up to date, uses descriptors as well as PSBT. It doesn't explicitly mention offline use, but it's not incompatible either.

**Comment by Tracachang** [comment]
Hello, I've ever wrote a step by step tutorial on bitcointalk forum about offline signing if it can help: [https://bitcointalk.org/index.php?topic=5392824.msg59740404#msg59740404](url)

It is one year old but it is up to date, screenshots are not online any more but I do still have them on a i2p website if needed.

**Comment by Tracachang** [comment]
> 

Thank you, just let me know how to proceed in case you want me to rewrite the tutorial or need me to add more information. Always happy to help.
