### ISSUE TITLE
Design for a bitcoin wallet

### ISSUE THREAD

**Issue by DATSEC** [bitcoin/bitcoin#9639]
I made a couple of versions of the wallet, if you like I'll do the other parts **free**
If you will be creating I will give the source PSD files :)
https://www.dropbox.com/s/zxclwzflg2d1fkw/1.jpg?dl=0
https://www.dropbox.com/s/su405j2jcsh1s5n/2.jpg?dl=0
https://www.dropbox.com/s/kuyaaucb28nsf2u/3.jpg?dl=0

![](http://i.imgur.com/txwmWJS.jpg)
![](http://i.imgur.com/z3kBxpM.jpg)
![](http://i.imgur.com/RpSGFpS.jpg)

http://imgur.com/a/11sFu

**PSD** https://www.dropbox.com/s/a5drumqp5hr7kie/bitcoin.psd?dl=0

Optional upgrade

![](http://i.imgur.com/MsWIKIz.jpg)

**Comment by MarcoFalke** [comment]
I think it is useful to change the appearance of the gui slightly for every (other) major release. This way we can combat the impression that "nothing has changed" since the last major release.

Though, we need to make sure that the system style is not violated. Otherwise it will make the gui impossible to use for some people. (c.f. https://github.com/bitcoin/bitcoin/pull/8889#issuecomment-251606020)
I really like the flat buttons, but I don't know if this is possible with qt.

Assigned the 0.15 milestone in case someone want to give it a try.

**Comment by jonasschnelli** [comment]
I also link the style. It would certainly be possible with Qt.
But it would be hard to adapt this to work with different (mostly linux) color schemes.

**Comment by DATSEC** [comment]
I can try to adapt it to linux, using standards
functionality I wasn't cheating :)

**Comment by DATSEC** [comment]
In linux it is possible to make flat design using languages such as HTML, CSS and javascript

**Example**
![](https://i.imgur.com/lxt9Z1k.png)

**Comment by jonasschnelli** [comment]
@DATSEC: Thanks for doing this. I think improving the design is something we should do once.
Have a look at the following comment: https://github.com/bitcoin/bitcoin/pull/8371#issuecomment-235840248
Some (Linux, but I guess also possible with Windows) themes do have different color schemes. This would require that your design is flexible to adapt colors according to the used scheme.

I guess the Linux users would not be happy if we would force them to a pre-given scheme (force setting the Bitcoin-Core GUI colors). Also, this could be complex to achieve because I guess there are some internal control colors that need hacks to change.

**Comment by JeremyRubin** [comment]
There is some argument to having the software not (by default) match the host theme. You get better branding awareness that "this is a bitcoin core wallet". E.g., facebook's UI uses an iconic blue banner. Spotify's color theme is distinctively dark with green highlights.

Allowing customization if preferred is maybe fine though?

**Comment by jonasschnelli** [comment]
I kinda agree with @JeremyRubin. I know other may not. A fixed color scheme makes stuff much simpler and yes, the branding capabilities (recognizability) are way better.

There are some things you can't change form within the applications. I think window title and borders, maybe some sorts of alerts. File dialogues. Menus.
And we certainly don't want to go down the path where we custom-create all the UI elements like File-Dialogs, menus, etc.

**Comment by DATSEC** [comment]
@jonasschnelli People don't know what they want, better to do something than to wait for everything to be resolved.
If you can move the interface into HTML, CSS, javascript, I'll help with the code.

**Comment by laanwj** [comment]
Though I personally like @DATSEC white-on-black style, I prefer software that simply blends in with the OS theme:
- This ages much better than something that tries to make it's own interface. If the host OS is updated the application will follow.
- UI metaphors learned are easily transferable from other applications. Fixed elements have fixed colors.
- It allows the user to set their own theme. This is not only aesthetic choice, but also required for e.g. people with bad eyesight that need high-contrast themes

I personally hate most "branded" applications and stay away from them where possible, at least on the desktop.

> I really like the flat buttons, but I don't know if this is possible with qt.

Sure, this could certainly be done as a custom qt theme. There a few altcoins that have taken bitcoin-qt but applied their own custom theme.

**Comment by DATSEC** [comment]
Let's make a new topic for bitcoina under version 0.14 
what do you think?

**Comment by sipa** [comment]
We're already past the feature freeze for the 0.14 release (see #8719), but we can discuss it for 0.15.

**Comment by stefment** [comment]
Hi. This doesent look bad. But something irked me the wrong way. I wondered how it would look like in all white. So i made some modifications in paint and a comparision to current GUI. Im not convinced all white is the right way but i think i like it better. Its a more subtle change which will arguably upset less people - there will always be upset people when you change design :)

Anyway i thought id share the mockup i made for anyone who was interested. Have a nice day.

![image](https://cloud.githubusercontent.com/assets/8888420/22497536/a8ff458a-e852-11e6-95d1-d1bf117cac59.png)

**Comment by laanwj** [comment]
What I think would be more constructive than arguing about colors is a redesign of say, the overview page - not the style, but how things are placed. When I created that tab initially the idea was to add all kinds of accounting overviews there. So it looks kind of awkward with things crammed in the corners. Four years later it's still almost empty and it's completely unclear *what* those things would be.

**Comment by jonasschnelli** [comment]
Agree with @laanwj. Also, lower level multi wallet support seems to be ready soon and someone needs to think about how to handle multiple wallets (probably including creation/locking/unlocking/detach) which maybe could be combine with the overview-screen overhaul.

**Comment by DATSEC** [comment]
I added PSD templates that you could modify if you come up with something unique. 
Later I will add this uniqueness to the main template
https://www.dropbox.com/s/a5drumqp5hr7kie/bitcoin.psd?dl=0
Fonts helvetica, can download on the Internet

**Comment by luke-jr** [comment]
Forcing flat buttons would by definition violate the system style...

**Comment by flack** [comment]
@laanwj You could do what a lot of web apps do, i.e. have simplified widgets of what is available in the separate views with the detailed functionality. For example, you could have a small area called "Send" which just contains the two or three essential fields from the Send view (e.g. Send [Amount] to [Address]), so that the overview is more useful and functionality more discoverable.

You could also go a bit further and show the balances horizontally, and then split the rest of the screen into two columns of transactions where one side shows incoming and the other one outgoing transactions. Above or below you can put the appropriate widgets (e.g. the Send widget described above would belong to the Outgoing column), then the overview page should be pretty full :-)

**Comment by DATSEC** [comment]
Added one of the ideas for the purse
![](http://i.imgur.com/MsWIKIz.jpg)

**Comment by Leviathn** [comment]
@datsec seems this was never followed through on -- is it closeable?

**Comment by MarcoFalke** [comment]
I think that the GUI needs more work and may be made for user friendly. Though, keeping an issue open for this is probably overkill. Pulls are more than welcome.
