### ISSUE TITLE
encrypt public wallet data

### ISSUE THREAD

**Issue by praxeology-guy** [bitcoin/bitcoin#9844]
### Describe the issue
People want to backup their wallet at insecure locations.  bitcoin core currently does not encypt public key/transaction history in the wallet.  People have to use an external program such as 7-zip to encrypt the public key data.

### Expected behaviour
Two options:
1. Create an extra feature where a password is required to even open the public data part of the wallet.  When this feature is activated, password is required to open the wallet on bitcoin client startup. This could be implemented to also decrypt the private keys of the wallet, so that no further password entry is required to spend.  Another decision would be whether the password should be different or the same to temporarily decrypt the private keys.
2. Add an "export encrypted wallet" menu option. User clicks this and a dialog prompts the user for where to save and then a password. 

### Actual behaviour
Bitcoin core does not currently encrypt public data in the wallet.

### What version of bitcoin-core are you using?
0.13.2

**Comment by laanwj** [comment]
IMO it is preferable to simply use an external tool for this. Any disk encryption or file encryption tool will do, and is better supported too. No need to roll every single feature into bitcoin core.

**Comment by praxeology-guy** [comment]
OK, here is a different use case: some may want their wallet on a USB drive, but all other node data stored on disk.  And they want their wallet data on their USB drive fully encrypted, incase they lose it somewhere they don't want people to know their transaction history and balance.  It would be much easier if the client could change the loaded wallet after its been started, by finding the wallet in a file explorer popup... and the file was fully encrypted on USB drive.

I know I'm asking for a lot now...  imo the client should be able to open and close wallets, not just specify wallet file on startup via command line.  Are you trying to make something easy for everyone to use? Or just for software engineers?

**Comment by laanwj** [comment]
Multiwallet support is in the pipeline, although initially all the wallets will need to be in the same database environment (directory).

**Comment by Sjors** [comment]
@praxeology-guy macOS makes encrypting USB drives nearly trivial (stores password in keychain), not sure about other OS's.

**Comment by andronoob** [comment]
>macOS makes encrypting USB drives nearly trivial (stores password in keychain), not sure about other OS's.

BitLocker is not available for "Home" SKUs of Windows.

EFS requires the drive to be formatted into NTFS, and, EFS is well known for its backfires - countless users had lost access to their EFS-encrypted files because they didn't care to backup the private key.

**Comment by laanwj** [comment]
> countless users had lost access to their EFS-encrypted files because they didn't notice the importance of backuping the private key.

This is the same for bitcoin's own wallet encryption. I sometimes get sad at the "help me I've lost my private key can you help recover it" in my mailbox.

**Comment by Fonta1n3** [comment]
I was going to raise another issue but this one is very similar but with a very different motivation:

**Is your feature request related to a problem? Please describe.**

I have built a few apps on top of Bitcoin Core [Fully Noded](https://github.com/Fonta1n3/FullyNoded) and [FullyNoded 2](https://github.com/BlockchainCommons/FullyNoded-2). In the apps users have the ability to connect to a node via a QR code which is essentially a tor v3 hidden service controlling rpc port that conforms to http protocol for rpc auth.

This makes it incredibly easy for users to connect to nodes via QR scanning. This makes it an ideal way to share your node with others.

FullyNoded 2 uses the nodes wallets in a watch-only capacity only so it is not possible to spend from the wallets however if you share your node with someone else they can obviously have full access and see your balances, complete and utter loss of privacy.

**Describe the solution you'd like**
An obvious solution to this would be the ability to utilize `bitcoin-cli encryptwallet` for public keys and private keys so that a user is prompted for a decrytion password for any operation to do with public keys. This way you can share a node with watch-only wallets but maintain privacy via a strong secondary encryption password.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
