### ISSUE TITLE
Fee estimator should be more user-friendly.

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#9914]
Instead of selecting between 2-25 blocks to begin confirming, the user should be able to select something like:

* Confirmation not needed / whenever (target )
* Confirmation within 2 weeks (target 1024 blocks)
* Confirmation within a week (target 512 blocks)
* Next-day confirmation (target 128 blocks)
* Priority confirmation within 24 hours (target 32 blocks)
* Urgent confirmation, ASAP (target 2 blocks)

**Comment by streamofstars** [comment]
I would rather see custom fee window allowing to enter btc fee PER BYTE instead of per kB (or allow to choose). All websites that estimate transaction fee e.g. https://bitcoinfees.21.co/ provide them per byte, not kB. I really do not want to make any stupid calculation mistake when sending my money because my wallet uses different unit than rest of the world.

**Comment by MeshCollider** [comment]
Was this closed by https://github.com/bitcoin/bitcoin/pull/10769?

**Comment by MarcoFalke** [comment]
I assume
